// Bu dosya otomatik olarak oluşturulmuştur. Supabase bağımlılığı kaldırılmıştır.

export interface LocalFlashcard {
  id: string;
  kategori: string;
  on_yuz: string;
  arka_yuz: string;
  zorluk: string;
  aktif: boolean;
}

export const flashcardsData: LocalFlashcard[] = [
  { id: '1', kategori: 'Türkçe', on_yuz: 'Kucuk unlu uyumu nedir?', arka_yuz: 'Dudak ve dil uyumunu kapsar. Duz unlulerden sonra duz gelir.', zorluk: 'zor', aktif: true },
  { id: '2', kategori: 'Matematik', on_yuz: 'Bir ucgenin alani nasil hesaplanir?', arka_yuz: 'Alan = taban x yukseklik / 2', zorluk: 'kolay', aktif: true },
  { id: '3', kategori: 'Tarih', on_yuz: 'Tarihte bilinen ilk Türk devleti hangisidir?', arka_yuz: 'Asya Hun Devleti (Teoman kurucudur).', zorluk: 'kolay', aktif: true },
  { id: '4', kategori: 'Tarih', on_yuz: 'Kendi adına para bastıran ilk Türk hükümdarı?', arka_yuz: 'Baga Tarkan (Türgişler).', zorluk: 'zor', aktif: true },
  { id: '5', kategori: 'Türkçe', on_yuz: 'Sifat tamlamasi nedir?', arka_yuz: 'Bir sifatin bir ismi nitelemesi. Guzel ev gibi.', zorluk: 'kolay', aktif: true },
  { id: '6', kategori: 'Matematik', on_yuz: 'EKOK ne demektir?', arka_yuz: 'En Kucuk Ortak Kat.', zorluk: 'kolay', aktif: true },
  { id: '7', kategori: 'Türkçe', on_yuz: 'Isim tamlamasi nedir?', arka_yuz: 'Tamlayan ve tamlanan ilişkisidir (Kapının kolu).', zorluk: 'kolay', aktif: true },
  { id: '8', kategori: 'Coğrafya', on_yuz: 'Turkiye nin en uzun kiyisi hangi denize aittir?', arka_yuz: 'Ege Denizi ne aittir.', zorluk: 'orta', aktif: true },
  { id: '9', kategori: 'Anayasa', on_yuz: 'Turkiye Cumhuriyeti nin temel nitelikleri nelerdir?', arka_yuz: 'Demokratik, laik, sosyal hukuk devletidir. Anayasa 2. madde.', zorluk: 'orta', aktif: true },
  { id: '10', kategori: 'Tarih', on_yuz: 'Türkiye Cumhuriyeti kaç yılında kuruldu?', arka_yuz: '1923. 29 Ekim 1923\'te Mustafa Kemal Atatürk tarafından ilan edildi.', zorluk: 'kolay', aktif: true },
  { id: '11', kategori: 'Coğrafya', on_yuz: 'Turkiye nin en uzun nehri hangisidir?', arka_yuz: 'Kizilirmak, 1355 km ile en uzun nehirdir.', zorluk: 'orta', aktif: true },
  { id: '12', kategori: 'Anayasa', on_yuz: 'TBMM kac milletvekilinden olusur?', arka_yuz: '600 milletvekili. 2017 referandumuyla 550 den 600 e cikti.', zorluk: 'orta', aktif: true },
  { id: '13', kategori: 'Matematik', on_yuz: 'Ardışık tek sayıların genel formülü?', arka_yuz: '2n-1', zorluk: 'orta', aktif: true },
  { id: '14', kategori: 'Matematik', on_yuz: 'En küçük asal sayı kaçtır?', arka_yuz: '2.', zorluk: 'kolay', aktif: true },
  { id: '15', kategori: 'Anayasa', on_yuz: 'Anayasa degisikligi icin kac oy gerekir?', arka_yuz: 'En az 360 oy ile kabul edilir.', zorluk: 'zor', aktif: true },
  { id: '16', kategori: 'Tarih', on_yuz: 'Ilk yazili kanunlar kime aittir?', arka_yuz: 'Hammurabi Kanunlari. MO 1754 yilinda Babil de hazirlanmistir.', zorluk: 'orta', aktif: true },
  { id: '17', kategori: 'Anayasa', on_yuz: 'İl idaresinin başı kimdir?', arka_yuz: 'Vali.', zorluk: 'kolay', aktif: true },
  { id: '18', kategori: 'Anayasa', on_yuz: 'Cumhurbaskani olmak icin yas siniri nedir?', arka_yuz: '40 yasini doldurmus olmak gerekir.', zorluk: 'orta', aktif: true },
  { id: '19', kategori: 'Güncel', on_yuz: '2024 Avrupa Futbol Şampiyonası nerede yapıldı?', arka_yuz: 'Almanya.', zorluk: 'orta', aktif: true },
  { id: '20', kategori: 'Matematik', on_yuz: 'Pisagor teoremi nedir?', arka_yuz: 'Dik ucgende hipotenüs karesi diger iki kenar karelerinin toplamina esittir.', zorluk: 'orta', aktif: true },
  { id: '21', kategori: 'Türkçe', on_yuz: 'Eylem nedir?', arka_yuz: 'Is olus veya durum bildiren kelimedir. Fiil olarak da adlandirilir.', zorluk: 'kolay', aktif: true },
  { id: '22', kategori: 'Güncel', on_yuz: 'Turkiye OECD ye ne zaman katildi?', arka_yuz: '1961 yilinda kurucu uye olarak katildi.', zorluk: 'orta', aktif: true },
  { id: '23', kategori: 'Coğrafya', on_yuz: 'Türkiye de fön rüzgarlarının en etkili olduğu yer?', arka_yuz: 'Doğu Karadeniz (Rize ve çevresi).', zorluk: 'orta', aktif: true },
  { id: '24', kategori: 'Coğrafya', on_yuz: 'Firat ve Dicle nehirleri nereye dokulur?', arka_yuz: 'Basra Korfezi ne dokulur.', zorluk: 'orta', aktif: true },
  { id: '25', kategori: 'Türkçe', on_yuz: 'Ünsüz benzeşmesi (sertleşme) nedir?', arka_yuz: 'f, s, t, k, ç, ş, h, p harflerinden sonra c, d, g ile başlayan eklerin ç, t, k ye dönüşmesi.', zorluk: 'zor', aktif: true },
  { id: '26', kategori: 'Güncel', on_yuz: 'TUİK ne demektir?', arka_yuz: 'Turkiye Istatistik Kurumu. Ulusal istatistikleri derler ve yayinlar.', zorluk: 'kolay', aktif: true },
  { id: '27', kategori: 'Tarih', on_yuz: 'Lozan Antlaşması nı imzalayan Türk heyeti başkanı kimdir?', arka_yuz: 'İsmet İnönü.', zorluk: 'orta', aktif: true },
  { id: '28', kategori: 'Matematik', on_yuz: 'EKOK ne demektir?', arka_yuz: 'En Kucuk Ortak Kat. Iki sayinin ortak katlari arasindaki en kucugu.', zorluk: 'kolay', aktif: true },
  { id: '29', kategori: 'Anayasa', on_yuz: 'Secim donemi kac yildir?', arka_yuz: '5 yildir. Hem TBMM hem Cumhurbaskanligi secimi ayni anda yapilir.', zorluk: 'kolay', aktif: true },
  { id: '30', kategori: 'Anayasa', on_yuz: 'Sayıştay kimin adına denetim yapar?', arka_yuz: 'TBMM adına.', zorluk: 'zor', aktif: true },
  { id: '31', kategori: 'Tarih', on_yuz: 'Ataturk kac yilinda vefat etti?', arka_yuz: '10 Kasim 1938. Dolmabahce Sarayi nda hayata gozlerini yumdu.', zorluk: 'kolay', aktif: true },
  { id: '32', kategori: 'Güncel', on_yuz: 'Türkiye\'nin başkenti neresidir?', arka_yuz: 'Ankara. 1923 yılında başkent ilan edilmiştir.', zorluk: 'kolay', aktif: true },
  { id: '33', kategori: 'Tarih', on_yuz: 'Sumerler hangi bolgede yasadi?', arka_yuz: 'Mezopotamya. Gunumuz Irak topraklarinda yasadilar.', zorluk: 'orta', aktif: true },
  { id: '34', kategori: 'Coğrafya', on_yuz: 'Türkiye de doğalgaz çıkarılan yerler?', arka_yuz: 'Hamitabat (Kırklareli) ve Çamurlu (Mardin).', zorluk: 'zor', aktif: true },
  { id: '35', kategori: 'Coğrafya', on_yuz: 'Turkiye nin en bati ili hangisidir?', arka_yuz: 'Edirne ilidir.', zorluk: 'kolay', aktif: true },
  { id: '36', kategori: 'Coğrafya', on_yuz: 'Turkiye nin en dogu ili hangisidir?', arka_yuz: 'Igdir ilidir.', zorluk: 'orta', aktif: true },
  { id: '37', kategori: 'Coğrafya', on_yuz: 'Türkiye nin en işlek sınır kapısı?', arka_yuz: 'Kapıkule (Bulgaristan ile).', zorluk: 'orta', aktif: true },
  { id: '38', kategori: 'Matematik', on_yuz: 'Aritmetik dizi nedir?', arka_yuz: 'Her terimin bir oncekinden sabit bir sayi kadar farkli oldugu dizidir.', zorluk: 'orta', aktif: true },
  { id: '39', kategori: 'Tarih', on_yuz: 'Ikinci Dunya Savasi kac yilinda sona erdi?', arka_yuz: '1945. Almanya ve Japonya nin teslim olmasiyla bitti.', zorluk: 'kolay', aktif: true },
  { id: '40', kategori: 'Coğrafya', on_yuz: 'Kışın don olaylarının en az görüldüğü bölge?', arka_yuz: 'Akdeniz.', zorluk: 'kolay', aktif: true },
  { id: '41', kategori: 'Coğrafya', on_yuz: 'Karadeniz in ozelligi nedir?', arka_yuz: 'Tuzluluk orani dusuktur. Bogaz akintilari vardir.', zorluk: 'orta', aktif: true },
  { id: '42', kategori: 'Matematik', on_yuz: 'Geometrik dizi nedir?', arka_yuz: 'Her terimin bir oncekiyle sabit bir oran iliskisi icinde oldugu dizidir.', zorluk: 'orta', aktif: true },
  { id: '43', kategori: 'Güncel', on_yuz: 'Turkiye nin AB uyelik sureci ne zaman basladi?', arka_yuz: '1987 de basvuruldu, 1999 da aday ulke ilan edildi.', zorluk: 'zor', aktif: true },
  { id: '44', kategori: 'Tarih', on_yuz: 'Kadinlara secme ve secilme hakki kac yilinda verildi?', arka_yuz: '1934. Pek cok Avrupa ulkesinden once.', zorluk: 'orta', aktif: true },
  { id: '45', kategori: 'Türkçe', on_yuz: 'Yuklem nedir?', arka_yuz: 'Cumlede oznenin yaptigini veya halini bildiren unsurdur.', zorluk: 'kolay', aktif: true },
  { id: '46', kategori: 'Anayasa', on_yuz: 'İstinaf mahkemesi hangi mahkemeye verilen addır?', arka_yuz: 'Bölge Adliye Mahkemesi.', zorluk: 'zor', aktif: true },
  { id: '47', kategori: 'Tarih', on_yuz: 'Turk Dil Kurumu kac yilinda kuruldu?', arka_yuz: '1932. Ataturk un talimatiyla kuruldu.', zorluk: 'orta', aktif: true },
  { id: '48', kategori: 'Coğrafya', on_yuz: 'Ege Bolgesi nin ekonomik ozelligi nedir?', arka_yuz: 'Tarim ve turizm on plandadir. Zeytinyagi ve uzum uretiminde ilk siradadir.', zorluk: 'orta', aktif: true },
  { id: '49', kategori: 'Anayasa', on_yuz: 'Hukukta emredici kural nedir?', arka_yuz: 'Aksi kararlaştırılamayan, uyulması zorunlu kurallar.', zorluk: 'orta', aktif: true },
  { id: '50', kategori: 'Tarih', on_yuz: 'Osmanli Devleti kac yilinda kuruldu?', arka_yuz: '1299. Osman Bey tarafindan kuruldu.', zorluk: 'kolay', aktif: true },
  { id: '51', kategori: 'Tarih', on_yuz: 'Cok partili hayata gecis kac yilinda oldu?', arka_yuz: '1946. Demokrat Parti kuruldu.', zorluk: 'orta', aktif: true },
  { id: '52', kategori: 'Anayasa', on_yuz: 'Olagan ustu hal kac aydir?', arka_yuz: '6 ayla sinirlidir. Uzatilabilir.', zorluk: 'orta', aktif: true },
  { id: '53', kategori: 'Coğrafya', on_yuz: 'Turkiye kac ile ayrilmistir?', arka_yuz: '81 il. En son eklenen il Duzce dir.', zorluk: 'kolay', aktif: true },
  { id: '54', kategori: 'Tarih', on_yuz: 'İstiklal Marşı nın ilk bestecisi?', arka_yuz: 'Ali Rıfat Çağatay.', zorluk: 'zor', aktif: true },
  { id: '55', kategori: 'Güncel', on_yuz: 'NATO nun son üyesi olan ülke?', arka_yuz: 'İsveç (2024).', zorluk: 'zor', aktif: true },
  { id: '56', kategori: 'Matematik', on_yuz: 'Kareler toplami formulu nedir?', arka_yuz: 'n(n+1)(2n+1)/6', zorluk: 'zor', aktif: true },
  { id: '57', kategori: 'Güncel', on_yuz: 'Turkiye Buyuk Millet Meclisi nerede bulunur?', arka_yuz: 'Ankara da bulunur. 1923 yilindan bu yana Ankara baskenttir.', zorluk: 'kolay', aktif: true },
  { id: '58', kategori: 'Güncel', on_yuz: 'BM kac uyeden olusur?', arka_yuz: '193 uye devlet. 1945 yilinda kuruldu.', zorluk: 'orta', aktif: true },
  { id: '59', kategori: 'Anayasa', on_yuz: 'Temel haklar hangi durumlarda kisitlanabilir?', arka_yuz: 'Ancak kanunla ve anayasada belirtilen sebeplerle kisitlanabilir.', zorluk: 'zor', aktif: true },
  { id: '60', kategori: 'Tarih', on_yuz: 'Karlofca Antlasmasi ne zaman imzalandi?', arka_yuz: '1699. Osmanli nin toprak kaybettigi ilk antlasmadir.', zorluk: 'zor', aktif: true },
  { id: '61', kategori: 'Güncel', on_yuz: 'D-8 nedir?', arka_yuz: 'Gelismekte olan 8 Musluman ulkenin olusturdugu ekonomik is birligi orgutu.', zorluk: 'zor', aktif: true },
  { id: '62', kategori: 'Tarih', on_yuz: 'Kurtulus Savasi nda Dogu Cephesi nde kime karsi savasıldi?', arka_yuz: 'Ermenistan a karsi savasıldi. 1920 de Gumru Antlasmasi imzalandi.', zorluk: 'orta', aktif: true },
  { id: '63', kategori: 'Anayasa', on_yuz: 'Anayasa Mahkemesi kac uyeden olusur?', arka_yuz: '15 asil uye. 3 u TBMM tarafindan secilir.', zorluk: 'zor', aktif: true },
  { id: '64', kategori: 'Coğrafya', on_yuz: 'Akdeniz ikliminin ozelligi nedir?', arka_yuz: 'Yazlar sicak ve kuru, kislar ilik ve yagislidir.', zorluk: 'kolay', aktif: true },
  { id: '65', kategori: 'Anayasa', on_yuz: 'Devlet Denetleme Kurulu (DDK) nereye bağlıdır?', arka_yuz: 'Cumhurbaşkanlığına.', zorluk: 'orta', aktif: true },
  { id: '66', kategori: 'Türkçe', on_yuz: 'Buyuk unlu uyumu nedir?', arka_yuz: 'Kelimedeki unlular ya hep kalin ya da hep ince olmalidir.', zorluk: 'orta', aktif: true },
  { id: '67', kategori: 'Güncel', on_yuz: 'Turkiye nin resmi dini var midir?', arka_yuz: 'Hayir. Anayasaya gore Turkiye laik bir devlettir.', zorluk: 'kolay', aktif: true },
  { id: '68', kategori: 'Coğrafya', on_yuz: 'En fazla rüzgar aşındırması hangi bölgededir?', arka_yuz: 'İç Anadolu Bölgesi.', zorluk: 'orta', aktif: true },
  { id: '69', kategori: 'Türkçe', on_yuz: 'Eklemeli dil ne demektir?', arka_yuz: 'Kelimelere ekler getirilerek yeni kelimeler olusturulan dildir. Turkce eklemeli bir dildir.', zorluk: 'orta', aktif: true },
  { id: '70', kategori: 'Güncel', on_yuz: 'Türkiye nin en önemli ihraç kalemi nedir?', arka_yuz: 'Otomotiv ve yan sanayi.', zorluk: 'orta', aktif: true },
  { id: '71', kategori: 'Coğrafya', on_yuz: 'Tuz Golu hangi bolgededir?', arka_yuz: 'Ic Anadolu Bolgesi nde yer alir.', zorluk: 'orta', aktif: true },
  { id: '72', kategori: 'Coğrafya', on_yuz: 'Türkiye nin en büyük delta ovası?', arka_yuz: 'Çukurova (Seyhan ve Ceyhan).', zorluk: 'orta', aktif: true },
  { id: '73', kategori: 'Coğrafya', on_yuz: 'Turkiye de kac bolge vardir?', arka_yuz: '7 cografya bolgesi vardir.', zorluk: 'kolay', aktif: true },
  { id: '74', kategori: 'Tarih', on_yuz: 'Misak-i Milli kac yilinda kabul edildi?', arka_yuz: '1920. Son Osmanli Mebuslar Meclisi nde kabul edildi.', zorluk: 'zor', aktif: true },
  { id: '75', kategori: 'Tarih', on_yuz: 'Fransiz Ihtilali kac yilinda oldu?', arka_yuz: '1789. Ozgurluk esitlik kardeslik sloganiyla basladi.', zorluk: 'kolay', aktif: true },
  { id: '76', kategori: 'Anayasa', on_yuz: 'Cumhurbaskani kac yilda bir secilir?', arka_yuz: '5 yilda bir secilir. En fazla 2 donem gorev yapabilir.', zorluk: 'kolay', aktif: true },
  { id: '77', kategori: 'Matematik', on_yuz: 'Permutasyon ne demektir?', arka_yuz: 'n elemanli kumeden r tanesinin sirayla dizilme sayisidir.', zorluk: 'orta', aktif: true },
  { id: '78', kategori: 'Türkçe', on_yuz: 'Anlam kayması nedir?', arka_yuz: 'Fiilin bir kipi ifade edip başka bir kipi kastetmesi (Yarın geliyorum).', zorluk: 'zor', aktif: true },
  { id: '79', kategori: 'Tarih', on_yuz: 'Sultan-ı İklim-i Rum unvanı kime verilmiştir?', arka_yuz: 'Yıldırım Bayezid (Niğbolu Savaşı sonrası).', zorluk: 'zor', aktif: true },
  { id: '80', kategori: 'Coğrafya', on_yuz: 'Türkiye nin en büyük tatlı su gölü hangisidir?', arka_yuz: 'Beyşehir Gölü.', zorluk: 'orta', aktif: true },
  { id: '81', kategori: 'Güncel', on_yuz: 'Türkiye nin ilk milli parkı neresidir?', arka_yuz: 'Yozgat Çamlığı.', zorluk: 'orta', aktif: true },
  { id: '82', kategori: 'Anayasa', on_yuz: 'Yasama dokunulmazligi ne demektir?', arka_yuz: 'Milletvekillerinin gorev suresi icinde yargilanamamasidir.', zorluk: 'orta', aktif: true },
  { id: '83', kategori: 'Güncel', on_yuz: 'Türkiye nin otomobili TOGG un fabrikası nerededir?', arka_yuz: 'Bursa - Gemlik.', zorluk: 'kolay', aktif: true },
  { id: '84', kategori: 'Coğrafya', on_yuz: 'Tiftik keçisi en çok nerede yetiştirilir?', arka_yuz: 'Ankara ve çevresi.', zorluk: 'orta', aktif: true },
  { id: '85', kategori: 'Matematik', on_yuz: 'Olasılık her zaman hangi aralıktadır?', arka_yuz: '0 ile 1 arasındadır.', zorluk: 'orta', aktif: true },
  { id: '86', kategori: 'Coğrafya', on_yuz: 'Bakır madeninin çıkarıldığı yerler?', arka_yuz: 'Kastamonu(Küre), Artvin(Murgul), Diyarbakır(Ergani), Elazığ(Maden), Rize(Çayeli).', zorluk: 'zor', aktif: true },
  { id: '87', kategori: 'Güncel', on_yuz: 'Dünyanın en büyük sodalı gölü?', arka_yuz: 'Van Gölü.', zorluk: 'orta', aktif: true },
  { id: '88', kategori: 'Coğrafya', on_yuz: 'Zeytin, fındık, turunçgil gibi bitkiler neye örnektir?', arka_yuz: 'Mikroklima bitki örtüsü.', zorluk: 'zor', aktif: true },
  { id: '89', kategori: 'Anayasa', on_yuz: 'Yüksek Seçim Kurulu (YSK) üye sayısı kaçtır?', arka_yuz: '7 asıl, 4 yedek (Toplam 11).', zorluk: 'zor', aktif: true },
  { id: '90', kategori: 'Anayasa', on_yuz: 'Turkiye Cumhuriyeti Anayasasi kac yilinda yapildi?', arka_yuz: '1982 yilinda yapildi. Halk oylamasiyla kabul edildi.', zorluk: 'orta', aktif: true },
  { id: '91', kategori: 'Güncel', on_yuz: 'G20 nedir?', arka_yuz: 'Dunyanin en buyuk 20 ekonomisini bir araya getiren uluslararasi forum.', zorluk: 'orta', aktif: true },
  { id: '92', kategori: 'Coğrafya', on_yuz: 'Dogu Anadolu Bolgesi nin ozelligi nedir?', arka_yuz: 'En yuksek ve en soguk bolgemizdir. En az yagis alan bolgemizdir.', zorluk: 'orta', aktif: true },
  { id: '93', kategori: 'Tarih', on_yuz: 'Medeni Kanun kac yilinda kabul edildi?', arka_yuz: '1926. Isvicre den alinarak uyarlanmistir.', zorluk: 'orta', aktif: true },
  { id: '94', kategori: 'Güncel', on_yuz: 'Dunya Saglik Orgutu nun kisaltmasi nedir?', arka_yuz: 'WHO. Merkezi Cenevre de bulunur.', zorluk: 'kolay', aktif: true },
  { id: '95', kategori: 'Güncel', on_yuz: 'Turkiye de kac universite vardir?', arka_yuz: '200 den fazla universite bulunmaktadir.', zorluk: 'kolay', aktif: true },
  { id: '96', kategori: 'Coğrafya', on_yuz: 'Türkiye de orman yangınlarının en çok görüldüğü bölge?', arka_yuz: 'Ege ve Akdeniz.', zorluk: 'kolay', aktif: true },
  { id: '97', kategori: 'Matematik', on_yuz: 'Kombinasyon ne demektir?', arka_yuz: 'n elemanli kumeden r tanesinin sira gozetmeksizin secilme sayisidir.', zorluk: 'orta', aktif: true },
  { id: '98', kategori: 'Güncel', on_yuz: 'Şeker hastalığına karşı kullanılan insülini bulan bilim insanı?', arka_yuz: 'Frederick Banting.', zorluk: 'zor', aktif: true },
  { id: '99', kategori: 'Türkçe', on_yuz: 'Zamir nedir?', arka_yuz: 'Ismin yerine kullanilan kelimedir. Ben sen o biz siz onlar gibi.', zorluk: 'kolay', aktif: true },
  { id: '100', kategori: 'Tarih', on_yuz: 'Osmanlı da ilk bakır para hangi dönemde basıldı?', arka_yuz: 'Osman Bey dönemi.', zorluk: 'orta', aktif: true },
  { id: '101', kategori: 'Tarih', on_yuz: 'Sakarya Meydan Savasi kac yilinda yapildi?', arka_yuz: '1921. Mustafa Kemal Baskumandan olarak savasi yonetti.', zorluk: 'orta', aktif: true },
  { id: '102', kategori: 'Güncel', on_yuz: 'İstiklal Madalyası alan son yerleşim yeri?', arka_yuz: 'Şanlıurfa (2016).', zorluk: 'zor', aktif: true },
  { id: '103', kategori: 'Tarih', on_yuz: 'İstiklal Marşı nı mecliste ilk okuyan kişi kimdir?', arka_yuz: 'Hamdullah Suphi Tanrıöver.', zorluk: 'zor', aktif: true },
  { id: '104', kategori: 'Güncel', on_yuz: 'UNESCO 2024 Dünya Miras Listesi ne eklenen yerimiz?', arka_yuz: 'Gordion Antik Kenti (Ankara).', zorluk: 'zor', aktif: true },
  { id: '105', kategori: 'Coğrafya', on_yuz: 'Turkiye nin en kalabalik sehri hangisidir?', arka_yuz: 'Istanbul. 15 milyonun uzerinde nufusuyla en kalabalik sehirdir.', zorluk: 'kolay', aktif: true },
  { id: '106', kategori: 'Matematik', on_yuz: 'Bir tam sayinin kendisiyle carpimindan elde edilen isleme ne denir?', arka_yuz: 'Kare alma. Ornegin 5 in karesi 25 tir.', zorluk: 'kolay', aktif: true },
  { id: '107', kategori: 'Tarih', on_yuz: 'Tanzimat Fermanı hangi padişah döneminde ilan edildi?', arka_yuz: 'Sultan Abdülmecid (1839).', zorluk: 'zor', aktif: true },
  { id: '108', kategori: 'Tarih', on_yuz: 'Ilk Turk matbaasi kimin tarafindan kuruldu?', arka_yuz: 'Ibrahim Muteferrika. 1727 yilinda Istanbul da kuruldu.', zorluk: 'orta', aktif: true },
  { id: '109', kategori: 'Anayasa', on_yuz: 'Kamu Denetçiliği Kurumu nereye bağlıdır?', arka_yuz: 'TBMM Başkanlığına.', zorluk: 'zor', aktif: true },
  { id: '110', kategori: 'Coğrafya', on_yuz: 'Turkiye de en fazla yagis hangi bolgede duser?', arka_yuz: 'Karadeniz Bolgesi. Yillik 2000 mm nin uzerinde yagis alir.', zorluk: 'orta', aktif: true },
  { id: '111', kategori: 'Tarih', on_yuz: 'Harf devrimi kac yilinda yapildi?', arka_yuz: '1928. Latin alfabesine gecildi.', zorluk: 'kolay', aktif: true },
  { id: '112', kategori: 'Tarih', on_yuz: 'Buyuk Taarruz kac yilinda basladi?', arka_yuz: '26 Agustos 1922. Yunan kuvvetleri yenilgiye ugratildi.', zorluk: 'orta', aktif: true },
  { id: '113', kategori: 'Tarih', on_yuz: 'TBMM yi tanıyan ilk Müslüman devlet?', arka_yuz: 'Afganistan.', zorluk: 'zor', aktif: true },
  { id: '114', kategori: 'Tarih', on_yuz: 'Istanbul kac yilinda fethediildi?', arka_yuz: '1453. Fatih Sultan Mehmet tarafindan fethediildi.', zorluk: 'kolay', aktif: true },
  { id: '115', kategori: 'Türkçe', on_yuz: 'Özne nedir?', arka_yuz: 'Yüklemin bildirdiği işi yapan veya durumu üzerine alan öge.', zorluk: 'kolay', aktif: true },
  { id: '116', kategori: 'Türkçe', on_yuz: 'Zarf nedir?', arka_yuz: 'Eylemi veya sifati niteleyen kelimedir. Nasil nerede ne zaman sorusu.', zorluk: 'orta', aktif: true },
  { id: '117', kategori: 'Matematik', on_yuz: 'Asal sayi nedir?', arka_yuz: '1 ve kendisiyle bolunen sayi. 2 tek cift asal sayidir.', zorluk: 'kolay', aktif: true },
  { id: '118', kategori: 'Coğrafya', on_yuz: 'Demir-Çelik fabrikalarının Karabük te kurulma sebebi?', arka_yuz: 'Enerji kaynağına (taş kömürü) yakınlık.', zorluk: 'zor', aktif: true },
  { id: '119', kategori: 'Tarih', on_yuz: 'Osmanlı nın ilk Şeyhülislamı kimdir?', arka_yuz: 'Molla Fenari.', zorluk: 'zor', aktif: true },
  { id: '120', kategori: 'Türkçe', on_yuz: 'Nesne nedir?', arka_yuz: 'Eylemin etkisini uzerinde tasiyan cumledir. Kimi neyi sorulariyla bulunur.', zorluk: 'orta', aktif: true },
  { id: '121', kategori: 'Coğrafya', on_yuz: 'Türkiye\'nin en uzun nehri hangisidir?', arka_yuz: 'Kızılırmak Nehri, 1355 km uzunluğuyla Türkiye\'nin en uzun nehridir.', zorluk: 'orta', aktif: true },
  { id: '122', kategori: 'Tarih', on_yuz: 'Amasya Görüşmeleri ni İstanbul hükümeti adına kim yürüttü?', arka_yuz: 'Salih Paşa.', zorluk: 'zor', aktif: true },
  { id: '123', kategori: 'Tarih', on_yuz: 'Vaka-i Hayriye (Hayırlı Olay) nedir?', arka_yuz: '1826 yılında Yeniçeri Ocağı nın kaldırılmasıdır.', zorluk: 'orta', aktif: true },
  { id: '124', kategori: 'Tarih', on_yuz: 'Yerleşik hayata geçen ilk Türk devleti hangisidir?', arka_yuz: 'Uygurlar.', zorluk: 'orta', aktif: true },
  { id: '125', kategori: 'Güncel', on_yuz: 'Kuzey Kutbu nu keşfeden ilk kişi?', arka_yuz: 'Robert Peary.', zorluk: 'zor', aktif: true },
  { id: '126', kategori: 'Türkçe', on_yuz: 'Edat nedir?', arka_yuz: 'Tek basina anlami olmayan, cümle içinde anlam kazanan kelime.', zorluk: 'orta', aktif: true },
  { id: '127', kategori: 'Güncel', on_yuz: 'KPSS nin acilimi nedir?', arka_yuz: 'Kamu Personeli Secme Sinavi. OSYM tarafindan duzenlenir.', zorluk: 'kolay', aktif: true },
  { id: '128', kategori: 'Türkçe', on_yuz: 'Ses uyumu nedir?', arka_yuz: 'Kelimedeki seslerin belirli kurallara gore uyum icinde olmasi.', zorluk: 'orta', aktif: true },
  { id: '129', kategori: 'Güncel', on_yuz: 'Merkez Bankasi nin gorevleri nelerdir?', arka_yuz: 'Para politikasi yonetimi doviz rezerv yonetimi ve finansal istikrar.', zorluk: 'orta', aktif: true },
  { id: '130', kategori: 'Güncel', on_yuz: 'Turkiye NATO ya ne zaman katildi?', arka_yuz: '1952 yilinda.', zorluk: 'orta', aktif: true },
  { id: '131', kategori: 'Güncel', on_yuz: 'Türkiye nin ilk astronotu kimdir?', arka_yuz: 'Alper Gezeravcı.', zorluk: 'kolay', aktif: true },
  { id: '132', kategori: 'Türkçe', on_yuz: 'Cümle ögelerinde vurgu nerededir?', arka_yuz: 'Yüklemden hemen önceki ögededir.', zorluk: 'orta', aktif: true },
  { id: '133', kategori: 'Matematik', on_yuz: 'Olasilik nasil hesaplanir?', arka_yuz: 'Istenen sonuc sayisi bolu Toplam sonuc sayisi.', zorluk: 'kolay', aktif: true },
  { id: '134', kategori: 'Türkçe', on_yuz: 'Yazımı karıştırılan \'her şey\' nasıl yazılır?', arka_yuz: 'Ayrı yazılır.', zorluk: 'kolay', aktif: true },
  { id: '135', kategori: 'Anayasa', on_yuz: 'Bir siyasi partinin grup kurması için gereken vekil sayısı?', arka_yuz: '20.', zorluk: 'orta', aktif: true },
  { id: '136', kategori: 'Güncel', on_yuz: 'Türkiye nin ilk yerli haberleşme uydusu hangisidir?', arka_yuz: 'Türksat 6A.', zorluk: 'orta', aktif: true },
  { id: '137', kategori: 'Güncel', on_yuz: 'Turkiye nin en onemli tarim urunleri nelerdir?', arka_yuz: 'Bugday arpa misir findik uzum zeytin ve pamuk on siralardadir.', zorluk: 'orta', aktif: true },
  { id: '138', kategori: 'Tarih', on_yuz: 'Ilk Turk devleti hangisidir?', arka_yuz: 'Buyuk Hun Imparatorlugu. MO 3. yuzyilda kurulmustur.', zorluk: 'orta', aktif: true },
  { id: '139', kategori: 'Güncel', on_yuz: 'Turkiye nin para birimi nedir?', arka_yuz: 'Turk Lirasi (TL). Merkez Bankasi para politikasini yonetir.', zorluk: 'kolay', aktif: true },
  { id: '140', kategori: 'Anayasa', on_yuz: 'Turkiye de oy kullanma yasi kactir?', arka_yuz: '18 yas. 2010 anayasa degisikligiyle 18 e indirildi.', zorluk: 'kolay', aktif: true },
  { id: '141', kategori: 'Güncel', on_yuz: 'Cumhurbaşkanlığı Forsunda kaç yıldız vardır?', arka_yuz: '16 yıldız.', zorluk: 'orta', aktif: true },
  { id: '142', kategori: 'Güncel', on_yuz: 'Modern hemşireliğin kurucusu kimdir?', arka_yuz: 'Florence Nightingale.', zorluk: 'zor', aktif: true },
  { id: '143', kategori: 'Tarih', on_yuz: 'Kurtulus Savasi hangi tarihte basladi?', arka_yuz: '19 Mayis 1919. Mustafa Kemal Ataturk Samsun a cikti.', zorluk: 'orta', aktif: true },
  { id: '144', kategori: 'Güncel', on_yuz: 'Dünya nın yedi harikasından biri olan Babil in Asma Bahçeleri nerededir?', arka_yuz: 'Irak.', zorluk: 'orta', aktif: true },
  { id: '145', kategori: 'Anayasa', on_yuz: 'Anayasa Mahkemesi ne zaman kuruldu?', arka_yuz: '1961 Anayasasi ile kuruldu.', zorluk: 'orta', aktif: true },
  { id: '146', kategori: 'Coğrafya', on_yuz: 'Turkiye nin yuzolcumu ne kadardir?', arka_yuz: '783.562 km2. Dunyada 37. buyuk ulkedir.', zorluk: 'orta', aktif: true },
  { id: '147', kategori: 'Güncel', on_yuz: 'Yerkürenin dış katmanına ne ad verilir?', arka_yuz: 'Litosfer (Taş küre).', zorluk: 'orta', aktif: true },
  { id: '148', kategori: 'Tarih', on_yuz: 'Halifelik kac yilinda kaldirildi?', arka_yuz: '1924. Turk Buyuk Millet Meclisi karariyla kaldirildi.', zorluk: 'orta', aktif: true },
  { id: '149', kategori: 'Anayasa', on_yuz: 'Anayasa Mahkemesi kac uyeden olusur?', arka_yuz: '15 asil uye. 3 si TBMM tarafindan secilir.', zorluk: 'zor', aktif: true },
  { id: '150', kategori: 'Güncel', on_yuz: 'Güneşe en yakın gezegen hangisidir?', arka_yuz: 'Merkür.', zorluk: 'kolay', aktif: true },
  { id: '151', kategori: 'Anayasa', on_yuz: 'Turkiye de oy kullanma yasi kactir?', arka_yuz: '18 yas.', zorluk: 'kolay', aktif: true },
  { id: '152', kategori: 'Coğrafya', on_yuz: 'Türkiye nin en genç volkanik arazisi nerededir?', arka_yuz: 'Manisa - Kula Tepeleri.', zorluk: 'zor', aktif: true },
  { id: '153', kategori: 'Türkçe', on_yuz: 'Ozne nedir?', arka_yuz: 'Cumlede yapi veya olusu gerceklestiren unsurdur. Kim veya ne sorusuyla bulunur.', zorluk: 'kolay', aktif: true },
  { id: '154', kategori: 'Tarih', on_yuz: 'Ankara Savasi kac yilinda yapildi?', arka_yuz: '1402. Yildirim Bayezid Timur a yenildi.', zorluk: 'orta', aktif: true },
  { id: '155', kategori: 'Güncel', on_yuz: 'Dünyanın en uzun asma köprüsü?', arka_yuz: '1915 Çanakkale Köprüsü.', zorluk: 'kolay', aktif: true },
  { id: '156', kategori: 'Coğrafya', on_yuz: 'Yıl boyunca gece-gündüz süresinin eşit olduğu tarih?', arka_yuz: '21 Mart - 23 Eylül (Ekinoks).', zorluk: 'kolay', aktif: true },
  { id: '157', kategori: 'Tarih', on_yuz: 'Mısırda kurulan ilk Türk-İslam devleti?', arka_yuz: 'Tolunoğulları.', zorluk: 'orta', aktif: true },
  { id: '158', kategori: 'Güncel', on_yuz: 'Türkiye nin ilk nükleer santrali nerede kuruluyor?', arka_yuz: 'Mersin - Akkuyu.', zorluk: 'kolay', aktif: true },
  { id: '159', kategori: 'Tarih', on_yuz: 'Osmanlı da ilk altın para hangi dönemde basıldı?', arka_yuz: 'Fatih Sultan Mehmet dönemi.', zorluk: 'orta', aktif: true },
  { id: '160', kategori: 'Tarih', on_yuz: 'Osmanli da ilk resmi gazete hangisidir?', arka_yuz: 'Takvim-i Vekayi (1831).', zorluk: 'orta', aktif: true },
  { id: '161', kategori: 'Coğrafya', on_yuz: 'Dünya bor rezervlerinin yaklaşık %73 üne sahip ülke?', arka_yuz: 'Türkiye.', zorluk: 'kolay', aktif: true },
  { id: '162', kategori: 'Tarih', on_yuz: 'Iskan politikasi nedir?', arka_yuz: 'Osmanli nin fethedilen Rumeli topraklarina Turkmenleri yerlestirme siyasetidir.', zorluk: 'orta', aktif: true },
  { id: '163', kategori: 'Tarih', on_yuz: 'Süveyş Kanalı hangi padişah döneminde açıldı?', arka_yuz: 'Sultan Abdülaziz.', zorluk: 'zor', aktif: true },
  { id: '164', kategori: 'Matematik', on_yuz: 'Faktöriyelde 0! değeri kaçtır?', arka_yuz: '1.', zorluk: 'orta', aktif: true },
  { id: '165', kategori: 'Tarih', on_yuz: 'Osmanlı da \'Şairlerin Sultanı\' unvanlı padişah kimdir?', arka_yuz: 'Kanuni Sultan Süleyman (Muhibbi mahlasıyla).', zorluk: 'zor', aktif: true },
  { id: '166', kategori: 'Tarih', on_yuz: 'Anadolu nun kapılarını Türklere açan savaş hangisidir?', arka_yuz: '1071 Malazgirt Meydan Muharebesi.', zorluk: 'kolay', aktif: true },
  { id: '167', kategori: 'Tarih', on_yuz: 'Yurt tutan savaş olarak bilinen savaş hangisidir?', arka_yuz: '1176 Miryokefalon Savaşı.', zorluk: 'orta', aktif: true },
  { id: '168', kategori: 'Tarih', on_yuz: 'Mustafa Kemal in nüfusa kayıtlı olduğu il?', arka_yuz: 'Gaziantep.', zorluk: 'zor', aktif: true },
  { id: '169', kategori: 'Güncel', on_yuz: 'İstiklal Madalyası alan ilk ilimiz?', arka_yuz: 'Kahramanmaraş (1925).', zorluk: 'zor', aktif: true },
  { id: '170', kategori: 'Tarih', on_yuz: 'Türk adıyla kurulan ilk devlet hangisidir?', arka_yuz: 'Kök Türk Devleti.', zorluk: 'kolay', aktif: true },
  { id: '171', kategori: 'Matematik', on_yuz: 'Bir ucgenin ic acilari toplamı kac derecedir?', arka_yuz: '180 derece. Bu kural tum ucgenler icin gecerlidir.', zorluk: 'kolay', aktif: true },
  { id: '172', kategori: 'Türkçe', on_yuz: 'Baglac nedir?', arka_yuz: 'Kelime veya cumleleri birbirine baglayan kelimedir. Ve ile ama gibi.', zorluk: 'kolay', aktif: true },
  { id: '173', kategori: 'Matematik', on_yuz: '0 in faktöriyeli kactir?', arka_yuz: '1. Tanim geregi 0! = 1 kabul edilir.', zorluk: 'orta', aktif: true },
  { id: '174', kategori: 'Anayasa', on_yuz: 'Yargı yetkisi kimin adına kullanılır?', arka_yuz: 'Türk Milleti adına bağımsız ve tarafsız mahkemelerce.', zorluk: 'kolay', aktif: true },
  { id: '175', kategori: 'Matematik', on_yuz: 'Asal sayılar içinde çift olan tek sayı kaçtır?', arka_yuz: '2.', zorluk: 'kolay', aktif: true },
  { id: '176', kategori: 'Tarih', on_yuz: 'İslamiyet öncesi Türk devletlerinde meclise ne ad verilir?', arka_yuz: 'Kurultay (Toy veya Kengeş).', zorluk: 'orta', aktif: true },
  { id: '177', kategori: 'Tarih', on_yuz: 'Dünyanın ilk burslu öğrencilik sistemini başlatan devlet?', arka_yuz: 'Karahanlılar.', zorluk: 'zor', aktif: true },
  { id: '178', kategori: 'Anayasa', on_yuz: 'Hâkimler ve Savcılar Kurulu (HSK) kaç üyeden oluşur?', arka_yuz: '13 üye.', zorluk: 'zor', aktif: true },
  { id: '179', kategori: 'Coğrafya', on_yuz: 'Türkiye nin en büyük yüz ölçümüne sahip gölü hangisidir?', arka_yuz: 'Van Gölü (Karma yapılı, sodalı).', zorluk: 'kolay', aktif: true },
  { id: '180', kategori: 'Tarih', on_yuz: 'Kuvayi Milliye den duzenli orduya gecis hangi savas sonrasidir?', arka_yuz: 'Gediz Taarruzu ndaki basarisizliktan sonra.', zorluk: 'zor', aktif: true },
  { id: '181', kategori: 'Matematik', on_yuz: 'Bir çemberin çevre formülü nedir?', arka_yuz: '2 x pi x r', zorluk: 'kolay', aktif: true },
  { id: '182', kategori: 'Anayasa', on_yuz: 'Milletvekilliği hangi durumda kendiliğinden düşer?', arka_yuz: 'Cumhurbaşkanı seçilme veya bakan olma.', zorluk: 'orta', aktif: true },
  { id: '183', kategori: 'Coğrafya', on_yuz: 'Hangi dağımızda buzullara rastlanmaz?', arka_yuz: 'Yıldız Dağları (Yükseltisi az olduğu için).', zorluk: 'zor', aktif: true },
  { id: '184', kategori: 'Güncel', on_yuz: 'İstiklal Marşı nın bestecisi kimdir?', arka_yuz: 'Osman Zeki Üngör.', zorluk: 'orta', aktif: true },
  { id: '185', kategori: 'Anayasa', on_yuz: 'Siyasi partilerin mali denetimini kim yapar?', arka_yuz: 'Anayasa Mahkemesi (Sayıştay yardımıyla).', zorluk: 'zor', aktif: true },
  { id: '186', kategori: 'Coğrafya', on_yuz: 'Türkiye de kıyı turizminin en geç açıldığı bölge?', arka_yuz: 'Karadeniz (Bulutluluk oranı yüksek olduğu için).', zorluk: 'orta', aktif: true },
  { id: '187', kategori: 'Matematik', on_yuz: 'EBOB ne demektir?', arka_yuz: 'En Buyuk Ortak Bolen. Iki sayinin ortak bolenleri arasindaki en buyugu.', zorluk: 'kolay', aktif: true },
  { id: '188', kategori: 'Tarih', on_yuz: 'Ankara nın başkent olma tarihi?', arka_yuz: '13 Ekim 1923.', zorluk: 'orta', aktif: true },
  { id: '189', kategori: 'Tarih', on_yuz: 'Birinci Dunya Savasi kac yilinda basladi?', arka_yuz: '1914. Saraybosna suikastiyla basladi.', zorluk: 'kolay', aktif: true },
  { id: '190', kategori: 'Güncel', on_yuz: 'ECO nedir?', arka_yuz: 'Ekonomik Is Birligi Teskilati. Turkiye Iran ve Pakistan tarafindan kuruldu.', zorluk: 'zor', aktif: true },
  { id: '191', kategori: 'Güncel', on_yuz: 'Kızıl Gezegen olarak bilinen gezegen hangisidir?', arka_yuz: 'Mars.', zorluk: 'kolay', aktif: true },
  { id: '192', kategori: 'Türkçe', on_yuz: 'Fiilimsi nedir?', arka_yuz: 'Fiil kökünden türeyip isim, sıfat veya zarf görevinde kullanılan kelime.', zorluk: 'orta', aktif: true },
  { id: '193', kategori: 'Anayasa', on_yuz: 'Anayasanin kacinci maddesi temel haklari duzenler?', arka_yuz: '12. madde. Temel haklar ve ozgurlukler bolumunde yer alir.', zorluk: 'zor', aktif: true },
  { id: '194', kategori: 'Matematik', on_yuz: 'Tam kare sayılar nedir?', arka_yuz: 'Bir tam sayının karesi olan sayılar (1, 4, 9, 16...).', zorluk: 'kolay', aktif: true },
  { id: '195', kategori: 'Anayasa', on_yuz: 'Yüksek Mahkemeler hangileridir?', arka_yuz: 'Anayasa Mahkemesi, Yargıtay, Danıştay, Uyuşmazlık Mahkemesi.', zorluk: 'orta', aktif: true },
  { id: '196', kategori: 'Güncel', on_yuz: 'Nobel Kimya Ödülü nü kazanan ilk Türk bilim insanı?', arka_yuz: 'Aziz Sancar.', zorluk: 'kolay', aktif: true },
  { id: '197', kategori: 'Tarih', on_yuz: 'Tanzimat Fermani kac yilinda ilan edildi?', arka_yuz: '1839. Sultan Abdulmecid doneminde ilan edilmistir.', zorluk: 'orta', aktif: true },
  { id: '198', kategori: 'Coğrafya', on_yuz: 'Turkiye nin en buyuk golu hangisidir?', arka_yuz: 'Van Golu. Dogu Anadolu da yer alir.', zorluk: 'kolay', aktif: true },
  { id: '199', kategori: 'Türkçe', on_yuz: 'Kucuk unlu uyumu nedir?', arka_yuz: 'Dudak ve dil uyumu (düz-yuvarlak).', zorluk: 'zor', aktif: true },
  { id: '200', kategori: 'Tarih', on_yuz: 'Mustafa Kemal e \'Gazi\' unvani hangi savas sonunda verildi?', arka_yuz: 'Sakarya Meydan Muharebesi.', zorluk: 'orta', aktif: true },
  { id: '201', kategori: 'Anayasa', on_yuz: 'Turkiye nin yonetim sekli nedir?', arka_yuz: 'Cumhuriyet. Devletin sekli degistirilemez madde ile guvence altindadir.', zorluk: 'kolay', aktif: true },
  { id: '202', kategori: 'Güncel', on_yuz: 'Türksoy un merkezi nerededir?', arka_yuz: 'Ankara.', zorluk: 'orta', aktif: true },
  { id: '203', kategori: 'Türkçe', on_yuz: 'Kişileştirme (Teşhis) nedir?', arka_yuz: 'İnsan dışı varlıklara insani özellikler verilmesi.', zorluk: 'orta', aktif: true },
  { id: '204', kategori: 'Matematik', on_yuz: 'Cemberin alani formulu nedir?', arka_yuz: 'Alan = pi x r karesi.', zorluk: 'kolay', aktif: true },
  { id: '205', kategori: 'Coğrafya', on_yuz: 'Marmara Denizi hangi bogazlarla baglantilidir?', arka_yuz: 'Canakkale Bogazi ve Istanbul Bogazi ile baglantilidir.', zorluk: 'orta', aktif: true },
  { id: '206', kategori: 'Güncel', on_yuz: 'OSYM nin acilimi nedir?', arka_yuz: 'Olcme Secme ve Yerlestirme Merkezi.', zorluk: 'kolay', aktif: true },
  { id: '207', kategori: 'Anayasa', on_yuz: 'Cumhurbaşkanlığı kararnamesi ne zaman yürürlüğe girer?', arka_yuz: 'Resmi Gazete de yayımlandığı gün.', zorluk: 'orta', aktif: true },
  { id: '208', kategori: 'Türkçe', on_yuz: 'Baglac nedir?', arka_yuz: 'Kelime veya cumleleri birbirine baglayan kelimedir.', zorluk: 'kolay', aktif: true },
  { id: '209', kategori: 'Güncel', on_yuz: 'TUSAŞ tarafından geliştirilen milli muharip uçağımızın adı?', arka_yuz: 'KAAN.', zorluk: 'kolay', aktif: true },
  { id: '210', kategori: 'Coğrafya', on_yuz: 'Hangi platomuzda karstik aşınma en fazladır?', arka_yuz: 'Teke ve Taşeli Platoları.', zorluk: 'zor', aktif: true },
  { id: '211', kategori: 'Tarih', on_yuz: 'Sivas Kongresi nde çıkarılan gazete?', arka_yuz: 'İrade-i Milliye.', zorluk: 'zor', aktif: true },
  { id: '212', kategori: 'Güncel', on_yuz: 'Avrupa nın en yüksek binası unvanına sahip yapı?', arka_yuz: 'Merkez Bankası Kulesi (İstanbul).', zorluk: 'zor', aktif: true },
  { id: '213', kategori: 'Güncel', on_yuz: 'Ayşe Tatile Çıksın parolası hangi olayla özdeşleşmiştir?', arka_yuz: 'Kıbrıs Barış Harekatı.', zorluk: 'orta', aktif: true },
{ id: '236', kategori: 'Güncel', on_yuz: 'ASELSAN\'ın geliştirdiği KARAT sistemi ne işe yarar?', arka_yuz: 'Kızılötesi arama ve takip teknolojisiyle çalışır.', zorluk: 'zor', aktif: true },
  { id: '237', kategori: 'Güncel', on_yuz: 'YILDIRIMHAN balistik füzesinin menzili ne kadardır?', arka_yuz: '6.000 km menziliyle Türkiye\'nin en uzun menzilli füzesidir.', zorluk: 'orta', aktif: true },
  { id: '238', kategori: 'Güncel', on_yuz: '2026 Dünya Spor Başkenti hangi şehirdir?', arka_yuz: 'Bakü, Azerbaycan.', zorluk: 'orta', aktif: true },
  { id: '239', kategori: 'Güncel', on_yuz: 'Türkiye 2027-2031 yılları arasında hangi organizasyona ev sahipliği yapacak?', arka_yuz: 'Formula 1 yarışlarına.', zorluk: 'orta', aktif: true },
  { id: '240', kategori: 'Güncel', on_yuz: 'Kayseri Pastırması kaçıncı AB coğrafi işaret tescilli Türk ürünüdür?', arka_yuz: 'Türkiye\'nin 46. tescilli ürünüdür (Mart 2026).', zorluk: 'zor', aktif: true },
  { id: '241', kategori: 'Güncel', on_yuz: 'Cittaslow (Sakin Şehir) hareketi ilk kez hangi ülkede ortaya çıktı?', arka_yuz: 'İtalya.', zorluk: 'orta', aktif: true },
  { id: '242', kategori: 'Güncel', on_yuz: 'Türkiye\'de Cittaslow unvanına sahip ilk ve tek ada hangisidir?', arka_yuz: 'Gökçeada.', zorluk: 'orta', aktif: true },
  { id: '243', kategori: 'Güncel', on_yuz: 'Türk edebiyatının ilk psikolojik romanı hangisidir ve yazarı kimdir?', arka_yuz: 'Eylül — Mehmet Rauf.', zorluk: 'orta', aktif: true },
  { id: '244', kategori: 'Güncel', on_yuz: 'Türk edebiyatının ilk köy romanı hangisidir ve yazarı kimdir?', arka_yuz: 'Karabibik — Nabizade Nazım.', zorluk: 'orta', aktif: true },
  { id: '245', kategori: 'Güncel', on_yuz: '"Modern Türkiye\'nin Doğuşu" kitabının yazarı kimdir?', arka_yuz: 'Bernard Lewis.', zorluk: 'zor', aktif: true },
  { id: '246', kategori: 'Güncel', on_yuz: 'Troposfer atmosferin kaçta kaçını barındırır?', arka_yuz: 'Atmosferin %75\'ini barındırır. Yaşamın sürdüğü en alt katmandır.', zorluk: 'orta', aktif: true },
  { id: '247', kategori: 'Güncel', on_yuz: 'Güneş Sistemi\'nin en büyük uydusu hangisidir ve hangi gezegene aittir?', arka_yuz: 'Ganymede, Jüpiter\'in uydusudur.', zorluk: 'orta', aktif: true },
  { id: '248', kategori: 'Güncel', on_yuz: 'Rıza Kayaalp\'in 2026 Avrupa Şampiyonası\'ndaki toplam şampiyonluk sayısı kaçtır?', arka_yuz: '13 Avrupa şampiyonluğu.', zorluk: 'zor', aktif: true },
  { id: '249', kategori: 'Güncel', on_yuz: '"Gölge etme başka ihsan istemem" sözü kime aittir?', arka_yuz: 'Diyojen.', zorluk: 'orta', aktif: true },
  { id: '250', kategori: 'Tarih', on_yuz: 'Atatürk\'ün yurt gezilerinde kullandığı tren ne olarak bilinir?', arka_yuz: 'Beyaz Tren.', zorluk: 'orta', aktif: true },
  { id: '251', kategori: 'Tarih', on_yuz: 'Karanfil Devrimi hangi ülkede ve kaç yılında yaşandı?', arka_yuz: 'Portekiz, 1974.', zorluk: 'orta', aktif: true },
  { id: '252', kategori: 'Güncel', on_yuz: 'Mimar Sinan\'ın adı hangi gezegendeki bir kratere verilmiştir?', arka_yuz: 'Merkür gezegenindeki bir kratere.', zorluk: 'zor', aktif: true },
  { id: '253', kategori: 'Güncel', on_yuz: 'Güneş Sistemi\'nde kendi ekseni etrafında en yavaş dönen gezegen hangisidir?', arka_yuz: 'Venüs.', zorluk: 'orta', aktif: true },
  { id: '254', kategori: 'Güncel', on_yuz: 'Venüs hangi yönde döner?', arka_yuz: 'Doğudan batıya döner (diğer gezegenlerin tersine).', zorluk: 'zor', aktif: true },
  { id: '255', kategori: 'Tarih', on_yuz: 'Matrakçı Nasuh hangi sporun en bilinen ismidir?', arka_yuz: '"Matrak" sporunun. Aynı zamanda tarihçi ve matematikçidir.', zorluk: 'zor', aktif: true },
  { id: '256', kategori: 'Güncel', on_yuz: 'Kübizmin kurucusu kimdir?', arka_yuz: 'Pablo Picasso.', zorluk: 'kolay', aktif: true },
  { id: '257', kategori: 'Güncel', on_yuz: 'Hantavirüs nasıl bulaşır?', arka_yuz: 'Kemirgenler aracılığıyla insanlara bulaşan bir RNA virüsüdür.', zorluk: 'orta', aktif: true },
  { id: '258', kategori: 'Güncel', on_yuz: 'Uluslararası Sıfır Atık Forumu 2026\'da nerede yapılacak?', arka_yuz: 'İstanbul (5-7 Haziran 2026).', zorluk: 'orta', aktif: true },
  { id: '259', kategori: 'Coğrafya', on_yuz: 'Dünyanın en büyük ikinci adası hangisidir?', arka_yuz: 'Yeni Gine Adası (Grönland\'dan sonra).', zorluk: 'orta', aktif: true },
  { id: '260', kategori: 'Güncel', on_yuz: 'Güneş Sistemi\'nin en büyük gezegeni hangisidir?', arka_yuz: 'Jüpiter.', zorluk: 'kolay', aktif: true },
  { id: '261', kategori: 'Güncel', on_yuz: 'Modern astronominin kurucusu kimdir?', arka_yuz: 'Kopernik.', zorluk: 'kolay', aktif: true },
  { id: '262', kategori: 'Coğrafya', on_yuz: 'Dünyanın en uzun sıradağları hangileridir?', arka_yuz: 'And Dağları (Güney Amerika).', zorluk: 'kolay', aktif: true },
  { id: '263', kategori: 'Güncel', on_yuz: 'Türkiye\'nin ilk insansız Ay görevi ne olarak adlandırılmaktadır?', arka_yuz: 'AYAP-1.', zorluk: 'orta', aktif: true },
  { id: '264', kategori: 'Güncel', on_yuz: '2026 UEFA Avrupa Ligi finali hangi stadyumda oynandı?', arka_yuz: 'İstanbul Beşiktaş Park Stadyumu.', zorluk: 'orta', aktif: true },
  { id: '265', kategori: 'Güncel', on_yuz: '98. Akademi Ödülleri\'nde En İyi Film ödülünü hangi film kazandı?', arka_yuz: '"One Battle After Another".', zorluk: 'zor', aktif: true },
{ id: '266', kategori: 'Güncel', on_yuz: 'Bağdat 2026 yılı için ne olarak seçildi?', arka_yuz: 'İslam Dünyası Kültür Başkenti.', zorluk: 'orta', aktif: true },
  { id: '267', kategori: 'Güncel', on_yuz: '7. Dünya Göçebe Oyunları nerede düzenlenecek?', arka_yuz: 'Bişkek (Kırgızistan).', zorluk: 'orta', aktif: true },
  { id: '268', kategori: 'Güncel', on_yuz: '2026 Avrupa Yeşil Başkenti hangi şehirdir?', arka_yuz: 'Guimarães (Portekiz).', zorluk: 'zor', aktif: true },
  { id: '269', kategori: 'Güncel', on_yuz: 'BM Genel Sekreteri Antonio Guterres\'e 2026\'da hangi ödül verildi?', arka_yuz: 'Atatürk Uluslararası Barış Ödülü.', zorluk: 'zor', aktif: true },
  { id: '270', kategori: 'Güncel', on_yuz: 'Interpol\'ün merkezi nerededir?', arka_yuz: 'Lyon, Fransa.', zorluk: 'orta', aktif: true },
  { id: '271', kategori: 'Güncel', on_yuz: 'Uluslararası Adalet Divanı nerede bulunur?', arka_yuz: 'Lahey, Hollanda.', zorluk: 'orta', aktif: true },
  { id: '272', kategori: 'Coğrafya', on_yuz: 'Güney Afrika\'nın kaç başkenti vardır ve hangileridir?', arka_yuz: '3 başkenti vardır: Pretoria, Cape Town ve Bloemfontein.', zorluk: 'zor', aktif: true },
  { id: '273', kategori: 'Coğrafya', on_yuz: 'BAE\'nin siyasi başkenti neresidir?', arka_yuz: 'Abu Dabi.', zorluk: 'orta', aktif: true },
  { id: '274', kategori: 'Coğrafya', on_yuz: 'Kazakistan\'ın başkenti neresidir?', arka_yuz: 'Astana.', zorluk: 'kolay', aktif: true },
  { id: '275', kategori: 'Coğrafya', on_yuz: 'İran\'ın resmi adı nedir?', arka_yuz: 'İran İslam Cumhuriyeti.', zorluk: 'kolay', aktif: true },
  { id: '276', kategori: 'Coğrafya', on_yuz: 'İran\'ın kaç komşusu vardır ve hangileridir?', arka_yuz: '7 komşusu vardır: Türkiye, Irak, Azerbaycan, Ermenistan, Türkmenistan, Afganistan ve Pakistan.', zorluk: 'zor', aktif: true },
  { id: '277', kategori: 'Coğrafya', on_yuz: 'Hürmüz Boğazı neden önemlidir?', arka_yuz: 'Dünya petrol taşımacılığı için kritik öneme sahiptir.', zorluk: 'orta', aktif: true },
  { id: '278', kategori: 'Coğrafya', on_yuz: 'En kalabalık Müslüman nüfusa sahip ülke hangisidir?', arka_yuz: 'Endonezya.', zorluk: 'kolay', aktif: true },
  { id: '279', kategori: 'Coğrafya', on_yuz: 'En büyük petrol rezervlerine sahip ülke hangisidir?', arka_yuz: 'Venezuela.', zorluk: 'orta', aktif: true },
  { id: '280', kategori: 'Güncel', on_yuz: '"İlyada" ve "Odysseia" destanlarının yazarı kimdir?', arka_yuz: 'Homeros.', zorluk: 'kolay', aktif: true },
  { id: '281', kategori: 'Güncel', on_yuz: 'Periyodik tablonun temelini atan bilim insanı kimdir?', arka_yuz: 'Dimitri Mendeleyev.', zorluk: 'orta', aktif: true },
  { id: '282', kategori: 'Güncel', on_yuz: '"Düşünen Adam" heykelinin sanatçısı kimdir?', arka_yuz: 'Auguste Rodin.', zorluk: 'kolay', aktif: true },
  { id: '283', kategori: 'Güncel', on_yuz: 'Satrancın atası kabul edilen eski oyunun adı nedir?', arka_yuz: 'Çaturanga.', zorluk: 'zor', aktif: true },
  { id: '284', kategori: 'Güncel', on_yuz: 'İlker Çatak\'ın "Sarı Mektuplar" filmi hangi festivalde Altın Ayı kazandı?', arka_yuz: 'Berlin Uluslararası Film Festivali.', zorluk: 'zor', aktif: true },
  { id: '285', kategori: 'Güncel', on_yuz: 'Aspirinin hammaddesi olan salisilik asit nereden elde edilir?', arka_yuz: 'Söğüt ağacından.', zorluk: 'orta', aktif: true },
  { id: '286', kategori: 'Güncel', on_yuz: 'İnsan vücudunun yaklaşık yüzde kaçı oksijenden oluşur?', arka_yuz: '%65.', zorluk: 'orta', aktif: true },
  { id: '287', kategori: 'Güncel', on_yuz: 'Güneş ışığı Dünya\'ya kaç dakikada ulaşır?', arka_yuz: 'Yaklaşık 8 dakikada.', zorluk: 'orta', aktif: true },
  { id: '288', kategori: 'Güncel', on_yuz: 'Sera etkisi nedeniyle Güneş Sistemi\'nin en sıcak gezegeni hangisidir?', arka_yuz: 'Venüs.', zorluk: 'orta', aktif: true },
  { id: '289', kategori: 'Güncel', on_yuz: 'İnsan vücudundaki en küçük kemik hangisidir?', arka_yuz: 'Üzengi kemiği (orta kulakta, yaklaşık 3 mm).', zorluk: 'orta', aktif: true },
  { id: '290', kategori: 'Güncel', on_yuz: '1997\'de satrançta insanı yenen ilk bilgisayar hangisidir?', arka_yuz: 'Deep Blue.', zorluk: 'orta', aktif: true },
  { id: '291', kategori: 'Güncel', on_yuz: 'Hicri takvim hangi ay ile başlar?', arka_yuz: 'Muharrem ayı.', zorluk: 'kolay', aktif: true },
  { id: '292', kategori: 'Güncel', on_yuz: '2026 yılını "Uluslararası Mera ve Çobanlar Yılı" ilan eden kuruluş hangisidir?', arka_yuz: 'Birleşmiş Milletler (BM).', zorluk: 'zor', aktif: true },
  { id: '293', kategori: 'Güncel', on_yuz: '"Dünya Türk Dili Aileleri Günü" hangi tarihte kutlanır?', arka_yuz: '15 Aralık.', zorluk: 'zor', aktif: true },
  { id: '294', kategori: 'Güncel', on_yuz: '2026 G20 Liderler Zirvesi nerede düzenlenecek?', arka_yuz: 'Miami, Florida, ABD.', zorluk: 'orta', aktif: true },
  { id: '295', kategori: 'Güncel', on_yuz: '2026 Kış Olimpiyatları hangi şehirlerde düzenlenecek?', arka_yuz: 'Milano ve Cortina d\'Ampezzo (İtalya).', zorluk: 'orta', aktif: true },
  { id: '296', kategori: 'Güncel', on_yuz: 'TRT Genç ne zaman yayın hayatına başladı?', arka_yuz: 'Ocak 2026.', zorluk: 'orta', aktif: true },
  { id: '297', kategori: 'Güncel', on_yuz: 'Göbeklitepe\'den daha eski olabileceği değerlendirilen ve 2025\'in en önemli arkeolojik keşfi seçilen yer neresidir?', arka_yuz: 'Karahantepe.', zorluk: 'zor', aktif: true },
  { id: '298', kategori: 'Coğrafya', on_yuz: 'Grönland hangi devlete bağlıdır?', arka_yuz: 'İç işlerinde özerk; dış ilişkiler ve savunmada Danimarka Krallığı\'na bağlıdır.', zorluk: 'orta', aktif: true },
  { id: '299', kategori: 'Güncel', on_yuz: '2026 Türk Dünyası Kültür Başkenti hangi şehirdir?', arka_yuz: 'Andican (Özbekistan).', zorluk: 'zor', aktif: true },
  { id: '300', kategori: 'Güncel', on_yuz: 'Airbus A-380 kullanan ilk Türk kadın pilot kimdir?', arka_yuz: 'Safiye Ademoğlu Türkyılmaz.', zorluk: 'zor', aktif: true },
  { id: '301', kategori: 'Güncel', on_yuz: 'Efes Antik Kenti\'nin öne çıkan yapıları hangileridir?', arka_yuz: 'Celsus Kütüphanesi ve Artemis Tapınağı (Dünyanın Yedi Harikası\'ndan biri).', zorluk: 'orta', aktif: true },
  { id: '302', kategori: 'Güncel', on_yuz: 'Patara Antik Kenti\'nin önemi nedir?', arka_yuz: 'Antik dünyanın ilk meclis binasına sahiptir; Likya Birliği\'nin başkentidir.', zorluk: 'zor', aktif: true },
  { id: '303', kategori: 'Tarih', on_yuz: 'Gaziantep\'e "Gazi" unvanını veren kuruluş hangisidir?', arka_yuz: 'TBMM.', zorluk: 'orta', aktif: true },
  { id: '304', kategori: 'Güncel', on_yuz: 'Thomas Hobbes hangi sözüyle bilinir?', arka_yuz: '"Homo homini lupus" (İnsan insanın kurdudur).', zorluk: 'orta', aktif: true },
  { id: '305', kategori: 'Güncel', on_yuz: '2026 yılı İçişleri Bakanlığı tarafından ne yılı ilan edildi?', arka_yuz: '"Sokak çeteleriyle mücadele yılı."', zorluk: 'zor', aktif: true },
{ id: '306', kategori: 'Coğrafya', on_yuz: 'Dünyada en fazla bağımsız ülkeye sahip kıta hangisidir?', arka_yuz: 'Afrika — 54 bağımsız ülke.', zorluk: 'kolay', aktif: true },
  { id: '307', kategori: 'Güncel', on_yuz: 'Mimari Barok tarzın özellikleri nelerdir?', arka_yuz: 'Abartılı hareket, zengin süslemeler, dramatik ışık-gölge kullanımı. 17. yüzyıl Avrupa\'sında yaygınlaştı.', zorluk: 'orta', aktif: true },
  { id: '308', kategori: 'Güncel', on_yuz: 'Batı müziğindeki nota sistemini kim geliştirdi?', arka_yuz: 'İtalyan keşiş Guido d\'Arezzo, 11. yüzyılda.', zorluk: 'zor', aktif: true },
  { id: '309', kategori: 'Güncel', on_yuz: 'Dünyanın ilk sinema filmi kabul edilen eser hangisidir ve kim tarafından çekilmiştir?', arka_yuz: '"Roundhay Bahçe Sahnesi" — Louis Le Prince (1888).', zorluk: 'zor', aktif: true },
  { id: '310', kategori: 'Tarih', on_yuz: 'Rönesans hangi şehirde başladı?', arka_yuz: 'İtalya\'nın Floransa kentinde, 14. yüzyılda.', zorluk: 'kolay', aktif: true },
  { id: '311', kategori: 'Güncel', on_yuz: 'Taoizm\'in kurucusu kimdir?', arka_yuz: 'Lao Tzu.', zorluk: 'orta', aktif: true },
  { id: '312', kategori: 'Güncel', on_yuz: 'Özgürlük Heykeli ABD\'ye kim tarafından hediye edilmiştir?', arka_yuz: 'Fransa tarafından. 350 ayrı parça halinde taşınarak yeniden birleştirilmiştir.', zorluk: 'kolay', aktif: true },
  { id: '313', kategori: 'Güncel', on_yuz: '2025 FIFA Kıtalararası Kupa\'yı hangi takım kazandı?', arka_yuz: 'Paris Saint Germain (PSG).', zorluk: 'orta', aktif: true },
  { id: '314', kategori: 'Güncel', on_yuz: '2025 BM İklim Değişikliği Konferansı (COP30) nerede düzenlendi?', arka_yuz: 'Brezilya\'nın Belém kentinde (10-21 Kasım 2025).', zorluk: 'orta', aktif: true },
  { id: '315', kategori: 'Güncel', on_yuz: '"En İyi Turizm Köyleri 2025" listesinde Türkiye\'den kaç köy yer aldı?', arka_yuz: '4 köy: Muğla Akyaka, Antalya Kale Üçağız, Mardin Anıtlı, İzmir Barbaros.', zorluk: 'zor', aktif: true },
  { id: '316', kategori: 'Güncel', on_yuz: 'Euromonitor\'ün "Dünyanın En İyi 10 Turizm Destinasyonu" listesinde Türkiye\'den hangi şehir yer aldı ve kaçıncı sıradadır?', arka_yuz: 'Antalya, 5. sırada. Los Angeles ve Dubai\'yi geride bıraktı.', zorluk: 'zor', aktif: true },
  { id: '317', kategori: 'Güncel', on_yuz: 'Türkiye\'nin ilk "UNESCO Edebiyat Şehri" hangi şehirdir?', arka_yuz: 'Kahramanmaraş (2025).', zorluk: 'zor', aktif: true },
  { id: '318', kategori: 'Güncel', on_yuz: 'Antalya\'nın hangi ilçesi "cittaslow" (sakin şehir) unvanı aldı?', arka_yuz: 'Demre ilçesi.', zorluk: 'zor', aktif: true },
  { id: '319', kategori: 'Güncel', on_yuz: 'İngiltere\'nin Türkiye\'den aldığı savaş uçağı anlaşması nedir?', arka_yuz: '20 adet Eurofighter Typhoon savaş uçağı alımı (2025).', zorluk: 'zor', aktif: true },];
