export interface GuncelBilgi {
  id: string;
  kategori: string;
  on_yuz: string;
  arka_yuz: string;
  zorluk: string;
  aktif: boolean;
}

export const guncelBilgilerData: GuncelBilgi[] = [
  // ── BİLİM / NOBEL ÖDÜLLERİ ──────────────────────────────
  { id: "gb001", kategori: "Bilim", on_yuz: "2025 Nobel Kimya Ödülü", arka_yuz: "Susumu Kitagawa, Richard Robson ve Omar Yaghi, \"metal-organik çerçevelerin geliştirilmesi\" çalışmasıyla kazandı.", zorluk: "orta", aktif: true },
  { id: "gb002", kategori: "Bilim", on_yuz: "2025 Nobel Fizik Ödülü", arka_yuz: "John Clarke, Michel Devoret ve John Martinis, elektrik devrelerinde makroskopik kuantum mekanik tünelleme keşfiyle kazandı.", zorluk: "zor", aktif: true },
  { id: "gb003", kategori: "Bilim", on_yuz: "2025 Nobel Tıp Ödülü", arka_yuz: "Mary Brunkow, Fred Ramsdell ve Shimon Sakaguchi, \"periferik bağışıklık toleransı\" keşifleriyle kazandı.", zorluk: "orta", aktif: true },
  { id: "gb004", kategori: "Bilim", on_yuz: "Türkiye'nin son Nobel sahibi kimdir?", arka_yuz: "2015 yılında Kimya dalında ödül alan Prof. Dr. Aziz Sancar'dır (DNA onarım mekanizmaları).", zorluk: "kolay", aktif: true },
  { id: "gb005", kategori: "Bilim", on_yuz: "Nobel Edebiyat Ödülü'nü kazanan ilk Türk yazar", arka_yuz: "2006 yılında Nobel Edebiyat Ödülü'nü kazanan ilk Türk yazar Orhan Pamuk'tur.", zorluk: "kolay", aktif: true },
  { id: "gb006", kategori: "Bilim", on_yuz: "Cahit Arf kimdir?", arka_yuz: "10 TL banknotun arkasında resmi bulunan, kendi adıyla anılan matematiksel teoremleri olan Türk matematikçidir.", zorluk: "orta", aktif: true },

  // ── TÜRKİYE GÜNDEMİ ─────────────────────────────────────
  { id: "gb007", kategori: "Türkiye Gündemi", on_yuz: "Emniyet Genel Atama Dönemi 2026", arka_yuz: "İçişleri Bakanı Mustafa Çiftçi, 19.096 personelin (1.528 amir, 17.568 polis memuru) görev yerini değiştirdi.", zorluk: "orta", aktif: true },
  { id: "gb008", kategori: "Türkiye Gündemi", on_yuz: "HSK 2026 Ana Kararnamesi", arka_yuz: "Ankara Cumhuriyet Başsavcılığı'na Aykut Çelik atandı.", zorluk: "zor", aktif: true },
  { id: "gb009", kategori: "Türkiye Gündemi", on_yuz: "Anayasa Mahkemesi Başkanı kimdir?", arka_yuz: "Kadir Özkaya, AYM Başkanı olarak görevini sürdürmektedir.", zorluk: "kolay", aktif: true },
  { id: "gb010", kategori: "Türkiye Gündemi", on_yuz: "TCMB Başkanı kimdir?", arka_yuz: "Dr. Fatih Karahan, Türkiye Cumhuriyet Merkez Bankası Başkanı olarak görev yapmaktadır.", zorluk: "kolay", aktif: true },
  { id: "gb011", kategori: "Türkiye Gündemi", on_yuz: "2026 NATO Zirvesi nerede yapılacak?", arka_yuz: "7-8 Temmuz 2026'da Ankara'da (Cumhurbaşkanlığı Külliyesi) yapılacak. Türkiye, 2004 İstanbul Zirvesi'nden sonra ikinci kez ev sahipliği yapıyor.", zorluk: "orta", aktif: true },

  // ── EKONOMİ ─────────────────────────────────────────────
  { id: "gb012", kategori: "Ekonomi", on_yuz: "TCMB'nin 2026 enflasyon tahmini", arka_yuz: "TCMB, 2026 yıl sonu enflasyon tahminini %18'den %26'ya yükseltti.", zorluk: "orta", aktif: true },
  { id: "gb013", kategori: "Ekonomi", on_yuz: "TCMB politika faizi (Haziran 2026)", arka_yuz: "Haziran 2026 itibarıyla TCMB politika faizi %37 seviyesinde sabit tutuluyor.", zorluk: "orta", aktif: true },
  { id: "gb014", kategori: "Ekonomi", on_yuz: "2026 G20 Dönem Başkanı hangi ülke?", arka_yuz: "ABD, G20 dönem başkanlığını yürütüyor; zirve Aralık 2026'da Miami'de yapılacak.", zorluk: "orta", aktif: true },

  // ── OTOMOTİV / SAVUNMA SANAYİİ ──────────────────────────
  { id: "gb015", kategori: "Otomotiv/Teknoloji", on_yuz: "TOGG T10F nedir?", arka_yuz: "Togg'un ikinci modeli, fastback sedan T10F, 15 Eylül 2025'te Türkiye ve Avrupa'da aynı anda satışa sunuldu (WLTP'ye göre 623 km menzil).", zorluk: "kolay", aktif: true },
  { id: "gb016", kategori: "Otomotiv/Teknoloji", on_yuz: "Türkiye'nin ilk yerli otomobili", arka_yuz: "TOGG (Türkiye'nin Otomobili Girişim Grubu); ilk üretilen modeli T10X'tir.", zorluk: "kolay", aktif: true },
  { id: "gb017", kategori: "Otomotiv/Teknoloji", on_yuz: "Türkiye'nin ilk astronotu kimdir?", arka_yuz: "Alper Gezeravcı, Axiom-3 misyonuyla ISS'e gitti. Uzayda söylediği ilk söz: \"İstikbal göklerdedir.\"", zorluk: "kolay", aktif: true },
  { id: "gb018", kategori: "Otomotiv/Teknoloji", on_yuz: "Türkiye'nin ilk yerli haberleşme uydusu", arka_yuz: "SpaceX roketiyle fırlatılan TÜRKSAT 6A'dır.", zorluk: "orta", aktif: true },
  { id: "gb019", kategori: "Otomotiv/Teknoloji", on_yuz: "Türkiye'nin ilk yerli gözlem uydusu", arka_yuz: "Yüksek çözünürlüklü yerli gözlem uydumuz İMECE'dir.", zorluk: "orta", aktif: true },
  { id: "gb020", kategori: "Otomotiv/Teknoloji", on_yuz: "TCG Anadolu nedir?", arka_yuz: "Türkiye'nin ilk yerli amfibi hücum gemisi; İHA/SİHA'ların iniş yapabildiği \"dünyanın ilk SİHA gemisi\" olarak bilinir.", zorluk: "orta", aktif: true },
  { id: "gb021", kategori: "Otomotiv/Teknoloji", on_yuz: "KAAN nedir?", arka_yuz: "Türkiye'nin 5. nesil yerli savaş uçağı; ilk uçuşunu başarıyla gerçekleştirdi.", zorluk: "kolay", aktif: true },
  { id: "gb022", kategori: "Otomotiv/Teknoloji", on_yuz: "Bayraktar Kızılelma nedir?", arka_yuz: "Baykar tarafından geliştirilen, Türkiye'nin ilk jet motorlu insansız savaş uçağıdır.", zorluk: "kolay", aktif: true },
  { id: "gb023", kategori: "Otomotiv/Teknoloji", on_yuz: "HÜRJET nedir?", arka_yuz: "TUSAŞ tarafından geliştirilen, Türkiye'nin ilk insanlı süpersonik jet eğitim uçağıdır.", zorluk: "orta", aktif: true },
  { id: "gb024", kategori: "Otomotiv/Teknoloji", on_yuz: "TEKNOFEST nedir?", arka_yuz: "Dünyanın en büyük havacılık, uzay ve teknoloji festivali olarak Türkiye'de düzenlenmektedir.", zorluk: "kolay", aktif: true },
  { id: "gb025", kategori: "Otomotiv/Teknoloji", on_yuz: "Türkiye'nin en yüksek barajı", arka_yuz: "Artvin Çoruh Nehri üzerinde inşa edilen Yusufeli Barajı'dır.", zorluk: "orta", aktif: true },
  { id: "gb026", kategori: "Otomotiv/Teknoloji", on_yuz: "GAP'ın en büyük barajı", arka_yuz: "Gövde hacmi bakımından Türkiye'nin en büyük barajı olan Atatürk Barajı'dır.", zorluk: "kolay", aktif: true },
  { id: "gb027", kategori: "Otomotiv/Teknoloji", on_yuz: "Avrupa'nın en uzun çift tüplü karayolu tüneli", arka_yuz: "Trabzon ile Gümüşhane'yi birbirine bağlayan Yeni Zigana Tüneli'dir.", zorluk: "zor", aktif: true },

  // ── SPOR ────────────────────────────────────────────────
  { id: "gb028", kategori: "Spor", on_yuz: "Türkiye 2026 Dünya Kupası'na kaç yıl aradan sonra katıldı?", arka_yuz: "A Milli Futbol Takımı, 2002'deki dünya üçüncülüğünden 24 yıl sonra ilk kez 2026 FIFA Dünya Kupası'na katıldı.", zorluk: "kolay", aktif: true },
  { id: "gb029", kategori: "Spor", on_yuz: "2026 Dünya Kupası formatı", arka_yuz: "Tarihte ilk kez 48 takımla ve ABD-Kanada-Meksika ortak ev sahipliğinde düzenleniyor; toplam 104 maç oynanacak.", zorluk: "orta", aktif: true },
  { id: "gb030", kategori: "Spor", on_yuz: "Türkiye'nin 2026 Dünya Kupası grubu", arka_yuz: "D Grubu'nda Türkiye, ABD, Avustralya ve Paraguay ile eşleşti.", zorluk: "kolay", aktif: true },
  { id: "gb031", kategori: "Spor", on_yuz: "2024 Paris Olimpiyatları - atıcılık madalyası", arka_yuz: "Yusuf Dikeç ve Şevval İlayda Tarhan, Türkiye'ye olimpiyat tarihinde atıcılıkta ilk madalyayı (gümüş) kazandırdı.", zorluk: "orta", aktif: true },
  { id: "gb032", kategori: "Spor", on_yuz: "Mete Gazoz kimdir?", arka_yuz: "Milli okçu, Tokyo ve Paris olimpiyatlarında madalya kazanan sporcularımızdandır.", zorluk: "kolay", aktif: true },
  { id: "gb033", kategori: "Spor", on_yuz: "\"Filenin Sultanları\" kimdir?", arka_yuz: "A Milli Kadın Voleybol Takımı'nın, dünya ve Avrupa şampiyonluklarının ardından kazandığı unvandır.", zorluk: "kolay", aktif: true },
  { id: "gb034", kategori: "Spor", on_yuz: "Dünyanın en eski spor organizasyonu", arka_yuz: "Edirne'de düzenlenen Kırkpınar Yağlı Güreşleri'dir.", zorluk: "orta", aktif: true },

  // ── EDEBİYAT / SANAT / KÜLTÜR ───────────────────────────
  { id: "gb035", kategori: "Edebiyat/Sanat", on_yuz: "\"Yüzyılın Tarihçisi\" kimdir?", arka_yuz: "2016'da vefat eden, Osmanlı tarihi üzerine dünyaca tanınan tarihçimiz Halil İnalcık'tır.", zorluk: "zor", aktif: true },
  { id: "gb036", kategori: "Edebiyat/Sanat", on_yuz: "İlk realist roman kabul edilen eser", arka_yuz: "Araba Sevdası, Recaizade Mahmut Ekrem tarafından yazılmıştır.", zorluk: "orta", aktif: true },
  { id: "gb037", kategori: "Edebiyat/Sanat", on_yuz: "Dede Korkut'un yeni nüshası", arka_yuz: "Kazakistan'da bulunan üçüncü nüshaya \"Türkistan (Bursa) Nüshası\" adı verilmiştir.", zorluk: "zor", aktif: true },
  { id: "gb038", kategori: "Edebiyat/Sanat", on_yuz: "Kutadgu Bilig ne anlama gelir?", arka_yuz: "Yusuf Has Hacib tarafından yazılan eserin anlamı \"Mutluluk Veren Bilgi\"dir.", zorluk: "orta", aktif: true },
  { id: "gb039", kategori: "Edebiyat/Sanat", on_yuz: "Düşünen Adam heykelinin sanatçısı", arka_yuz: "Fransız heykeltıraş Auguste Rodin'e aittir.", zorluk: "kolay", aktif: true },
  { id: "gb040", kategori: "Edebiyat/Sanat", on_yuz: "Guernica tablosunun ressamı", arka_yuz: "İspanyol İç Savaşı'nı anlatan, kübizmin öncüsü Pablo Picasso'nun eseridir.", zorluk: "kolay", aktif: true },
  { id: "gb041", kategori: "Edebiyat/Sanat", on_yuz: "İlahi Komedya'nın yazarı", arka_yuz: "İtalyan edebiyatının babası kabul edilen Dante Alighieri'nin eseridir.", zorluk: "orta", aktif: true },
  { id: "gb042", kategori: "Edebiyat/Sanat", on_yuz: "Savaş ve Barış / Anna Karenina'nın yazarı", arka_yuz: "Rus yazar Lev Tolstoy'a aittir.", zorluk: "kolay", aktif: true },
  { id: "gb043", kategori: "Edebiyat/Sanat", on_yuz: "Kaplumbağa Terbiyecisi tablosunun ressamı", arka_yuz: "Türk müzeciliğinin kurucusu olan Osman Hamdi Bey'in tablosudur.", zorluk: "kolay", aktif: true },
  { id: "gb044", kategori: "Edebiyat/Sanat", on_yuz: "Mona Lisa / Son Akşam Yemeği'nin ressamı", arka_yuz: "Rönesans dâhisi Leonardo da Vinci'ye aittir.", zorluk: "kolay", aktif: true },
  { id: "gb045", kategori: "Edebiyat/Sanat", on_yuz: "Sinekli Bakkal / Ateşten Gömlek'in yazarı", arka_yuz: "Kurtuluş Savaşı dönemini anlatan Halide Edib Adıvar'ın romanlarıdır.", zorluk: "orta", aktif: true },

  // ── DÜNYA GÜNDEMİ ────────────────────────────────────────
  { id: "gb046", kategori: "Dünya Gündemi", on_yuz: "AI Act (Yapay Zeka Yasası) nedir?", arka_yuz: "Avrupa Birliği tarafından kabul edilen, yapay zeka alanında dünyadaki ilk kapsamlı yasal düzenlemedir.", zorluk: "orta", aktif: true },
  { id: "gb047", kategori: "Dünya Gündemi", on_yuz: "İlk ticari uzay yürüyüşü", arka_yuz: "SpaceX'in Polaris Dawn göreviyle siviller tarafından gerçekleştirildi.", zorluk: "zor", aktif: true },
  { id: "gb048", kategori: "Dünya Gündemi", on_yuz: "BM Genel Sekreteri kimdir?", arka_yuz: "Portekizli diplomat Antonio Guterres, görevine devam etmektedir.", zorluk: "kolay", aktif: true },
  { id: "gb049", kategori: "Dünya Gündemi", on_yuz: "NATO Genel Sekreteri kimdir?", arka_yuz: "Hollanda eski Başbakanı Mark Rutte, Jens Stoltenberg'den görevi devralmıştır.", zorluk: "orta", aktif: true },
  { id: "gb050", kategori: "Dünya Gündemi", on_yuz: "AB Komisyonu Başkanı kimdir?", arka_yuz: "Ursula von der Leyen, ikinci kez bu göreve seçilmiştir.", zorluk: "orta", aktif: true },
  { id: "gb051", kategori: "Dünya Gündemi", on_yuz: "ECB Başkanı kimdir?", arka_yuz: "Christine Lagarde, Avrupa Merkez Bankası'nın ilk kadın başkanıdır.", zorluk: "orta", aktif: true },

  // ── TÜRKİYE - İLKLER VE TARİH ────────────────────────────
  { id: "gb052", kategori: "Türkiye İlkleri", on_yuz: "Türkiye'nin en son ili", arka_yuz: "1999 yılında il yapılan 81. ilimiz Düzce'dir.", zorluk: "kolay", aktif: true },
  { id: "gb053", kategori: "Türkiye İlkleri", on_yuz: "Türkiye'nin en son büyükşehiri", arka_yuz: "2012 yılındaki kanunla büyükşehir statüsü kazanan 30. ilimiz Ordu'dur.", zorluk: "orta", aktif: true },
  { id: "gb054", kategori: "Türkiye İlkleri", on_yuz: "Nüfusu en az olan ilimiz", arka_yuz: "TÜİK verilerine göre Türkiye'nin nüfus bakımından en küçük ili Bayburt'tur.", zorluk: "kolay", aktif: true },
  { id: "gb055", kategori: "Türkiye İlkleri", on_yuz: "İstiklal Madalyası alan ilk il", arka_yuz: "1925 yılında bu madalyayı alan ilk il Kahramanmaraş'tır.", zorluk: "orta", aktif: true },
  { id: "gb056", kategori: "Türkiye İlkleri", on_yuz: "\"Gazi\" unvanı alan ilk şehir", arka_yuz: "1921 yılında bu unvanı alan Gaziantep'tir.", zorluk: "kolay", aktif: true },
  { id: "gb057", kategori: "Türkiye İlkleri", on_yuz: "\"Şanlı\" unvanı alan şehir", arka_yuz: "1984 yılında bu unvanı alan Şanlıurfa'dır.", zorluk: "kolay", aktif: true },
  { id: "gb058", kategori: "Türkiye İlkleri", on_yuz: "\"Kahraman\" unvanı alan şehir", arka_yuz: "1973 yılında bu unvanı alan Kahramanmaraş'tır.", zorluk: "kolay", aktif: true },
  { id: "gb059", kategori: "Türkiye İlkleri", on_yuz: "Türkiye'nin ilk Cittaslow'u (Sakin Şehir)", arka_yuz: "İzmir'in Seferihisar ilçesidir.", zorluk: "orta", aktif: true },
  { id: "gb060", kategori: "Türkiye İlkleri", on_yuz: "Türkiye'nin ilk sakin adası", arka_yuz: "Çanakkale'ye bağlı Gökçeada'dır.", zorluk: "orta", aktif: true },
  { id: "gb061", kategori: "Türkiye İlkleri", on_yuz: "UNESCO Dünya Miras Listesi'ndeki 20. varlığımız", arka_yuz: "Ankara'da yer alan Gordion Antik Kenti'dir.", zorluk: "zor", aktif: true },
  { id: "gb062", kategori: "Türkiye İlkleri", on_yuz: "Türkiye'nin ilk UNESCO kültür mirası", arka_yuz: "1985 yılında listeye giren Divriği Ulu Camii ve Darüşşifası'dır.", zorluk: "orta", aktif: true },
  { id: "gb063", kategori: "Türkiye İlkleri", on_yuz: "Türkiye'nin ilk biyosfer rezerv alanı", arka_yuz: "Artvin'de bulunan Macahel (Camili) Havzası'dır.", zorluk: "zor", aktif: true },
  { id: "gb064", kategori: "Türkiye İlkleri", on_yuz: "Cumhuriyet'in ilk Başbakanı", arka_yuz: "İsmet İnönü'dür.", zorluk: "kolay", aktif: true },
  { id: "gb065", kategori: "Türkiye İlkleri", on_yuz: "Cumhuriyet'in ilk Meclis Başkanı", arka_yuz: "Fethi Okyar'dır.", zorluk: "orta", aktif: true },
  { id: "gb066", kategori: "Türkiye İlkleri", on_yuz: "Cumhuriyet döneminin ilk kadın bakanı", arka_yuz: "Prof. Dr. Türkan Akyol'dur.", zorluk: "orta", aktif: true },
  { id: "gb067", kategori: "Türkiye İlkleri", on_yuz: "Türkiye'nin ilk kadın başbakanı", arka_yuz: "Tansu Çiller'dir.", zorluk: "kolay", aktif: true },
  { id: "gb068", kategori: "Türkiye İlkleri", on_yuz: "Türkiye'nin ilk kadın valisi", arka_yuz: "Muğla ve Aydın valiliği yapmış olan Lale Aytaman'dır.", zorluk: "orta", aktif: true },
  { id: "gb069", kategori: "Türkiye İlkleri", on_yuz: "Türkiye'nin ilk kadın doktoru", arka_yuz: "Safiye Ali'dir.", zorluk: "orta", aktif: true },
  { id: "gb070", kategori: "Türkiye İlkleri", on_yuz: "Türkiye'nin ilk kadın pilotu", arka_yuz: "Sabiha Gökçen'dir; ilk kadın jet pilotu ise Leman Bozkurt Altınçekiç'tir.", zorluk: "kolay", aktif: true },

  // ── COĞRAFYA - GÜNCEL "EN"LER ────────────────────────────
  { id: "gb071", kategori: "Coğrafya", on_yuz: "Dünyanın en büyük adası", arka_yuz: "Danimarka'ya bağlı özerk bölge Grönland'dır.", zorluk: "kolay", aktif: true },
  { id: "gb072", kategori: "Coğrafya", on_yuz: "Türkiye'nin en büyük gölü", arka_yuz: "Tektonik-volkanik set oluşumlu Van Gölü'dür.", zorluk: "kolay", aktif: true },
  { id: "gb073", kategori: "Coğrafya", on_yuz: "Türkiye'nin en büyük tatlı su gölü", arka_yuz: "Göller Yöresi'nde bulunan Beyşehir Gölü'dür.", zorluk: "orta", aktif: true },
  { id: "gb074", kategori: "Coğrafya", on_yuz: "Türkiye'nin en büyük adası", arka_yuz: "Çanakkale sınırlarında yer alan Gökçeada'dır.", zorluk: "kolay", aktif: true },
  { id: "gb075", kategori: "Coğrafya", on_yuz: "Dünyanın en uzun orta açıklıklı asma köprüsü", arka_yuz: "Çanakkale Boğazı üzerine inşa edilen 1915 Çanakkale Köprüsü'dür (2023 m orta açıklık).", zorluk: "orta", aktif: true },
  { id: "gb076", kategori: "Coğrafya", on_yuz: "Türkiye'nin en yüksek zirvesi", arka_yuz: "5137 metre yüksekliğindeki Ağrı Dağı'dır.", zorluk: "kolay", aktif: true },
  { id: "gb077", kategori: "Coğrafya", on_yuz: "Türkiye'nin en uzun iç akarsuyu", arka_yuz: "Sınırlarımız içinde doğup yine sınırlarımız içinde denize dökülen Kızılırmak'tır.", zorluk: "kolay", aktif: true },
  { id: "gb078", kategori: "Coğrafya", on_yuz: "Türkiye'nin en fazla yağış alan yeri", arka_yuz: "Doğu Karadeniz Bölümü'nde bulunan Rize'dir.", zorluk: "kolay", aktif: true },

  // ── EKLENTİ 2: HAZİRAN 2026 GÜNCEL GELİŞMELER ────────────
  { id: "gb079", kategori: "Dünya Gündemi", on_yuz: "COP31 İklim Zirvesi nerede yapılacak?", arka_yuz: "Türkiye, Kasım 2026'da Antalya'da COP31'e (31. BM İklim Değişikliği Konferansı) ev sahipliği ve dönem başkanlığı yapacak.", zorluk: "orta", aktif: true },
  { id: "gb080", kategori: "Dünya Gündemi", on_yuz: "COP31 Liderler Zirvesi nerede yapılacak?", arka_yuz: "COP31 kapsamındaki Dünya Liderler Zirvesi, Cumhurbaşkanı'nın ev sahipliğinde İstanbul'da gerçekleştirilecek.", zorluk: "orta", aktif: true },
  { id: "gb081", kategori: "Türkiye Gündemi", on_yuz: "Halkalı-İstanbul Havalimanı Metro Hattı (M11)", arka_yuz: "Hattın son kesimi olan 22 km'lik Halkalı-Arnavutköy bölümü 19 Haziran 2026'da hizmete açıldı.", zorluk: "orta", aktif: true },
  { id: "gb082", kategori: "Türkiye Gündemi", on_yuz: "Türkiye'nin en uzun metro hattı", arka_yuz: "Halkalı-Arnavutköy kesiminin açılmasıyla Gayrettepe-İstanbul Havalimanı-Halkalı hattı toplam 69 km'ye ulaşarak Türkiye'nin en uzun metro hattı oldu.", zorluk: "orta", aktif: true },
  { id: "gb083", kategori: "Türkiye Gündemi", on_yuz: "Yenilenen Ankara Havalimanı", arka_yuz: "1933 yılında yapılan ve uzun yıllar askeri havalimanı olarak kullanılan Ankara Havalimanı yenilendi; pisti 3000 metreye uzatıldı, 44 uçak eş zamanlı park kapasitesine kavuştu.", zorluk: "zor", aktif: true },
  { id: "gb084", kategori: "Türkiye Gündemi", on_yuz: "NATO Parlamenter Zirvesi 2026", arka_yuz: "28-29 Haziran 2026'da İstanbul'da yapılacak; ardından 7-8 Temmuz'da NATO Liderler Zirvesi Türkiye'de gerçekleşecek.", zorluk: "orta", aktif: true },
  { id: "gb085", kategori: "Otomotiv/Teknoloji", on_yuz: "SİPER nedir?", arka_yuz: "Türkiye'nin yerli geliştirilen uzun menzilli hava ve füze savunma sistemidir.", zorluk: "orta", aktif: true },
  { id: "gb086", kategori: "Otomotiv/Teknoloji", on_yuz: "ALTAY nedir?", arka_yuz: "Türkiye'nin yerli ana muharebe tankıdır; Türk Silahlı Kuvvetleri'ne teslimatları başlamıştır.", zorluk: "kolay", aktif: true },
  { id: "gb087", kategori: "Otomotiv/Teknoloji", on_yuz: "ATMACA nedir?", arka_yuz: "Türkiye'nin yerli geliştirilen gemi savar (anti-gemi) güdümlü füzesidir.", zorluk: "orta", aktif: true },

  // ── EKLENTİ 3: DÜNYA GÜNDEMİ (HAZİRAN 2026) ──────────────
  { id: "gb088", kategori: "Dünya Gündemi", on_yuz: "İslamabad Mutabakat Anlaşması nedir?", arka_yuz: "18 Haziran 2026'da ABD Başkanı Donald Trump ile İran Cumhurbaşkanı Mesud Pezeşkiyan arasında dijital olarak imzalanan, Orta Doğu'daki çatışmaları sona erdiren anlaşmadır. Pakistan ve Katar arabuluculuk yaptı.", zorluk: "zor", aktif: true },
  { id: "gb089", kategori: "Dünya Gündemi", on_yuz: "İslamabad Mutabakatı'nın temel maddeleri", arka_yuz: "Anlaşma kapsamında İran, Hürmüz Boğazı'nı yeniden açtı; ABD ise İran'a uyguladığı deniz ablukasını kaldırdı. Nükleer program ve yaptırımlar konusunda taraflar 60 gün içinde nihai anlaşmayı müzakere edecek.", zorluk: "zor", aktif: true },
  { id: "gb090", kategori: "Dünya Gündemi", on_yuz: "Yeni FED (ABD Merkez Bankası) Başkanı kimdir?", arka_yuz: "Kevin Warsh, ABD Merkez Bankası'nın (Federal Reserve) yeni başkanı olarak göreve başlamıştır.", zorluk: "orta", aktif: true },

  // ── EKLENTİ 4: EĞİTİM GÜNDEMİ (2026) ──────────────────────
  { id: "gb091", kategori: "Türkiye Gündemi", on_yuz: "2026 LGS sınav tarihi neden değişti?", arka_yuz: "Milli Eğitim Bakanı Yusuf Tekin, A Milli Takımı'nın 2026 Dünya Kupası'ndaki Avustralya maçıyla çakışmaması için LGS sınavını 14 Haziran'dan 13 Haziran 2026 Cumartesi'ye aldı.", zorluk: "kolay", aktif: true },
  { id: "gb092", kategori: "Türkiye Gündemi", on_yuz: "Milli Eğitim Bakanı kimdir?", arka_yuz: "Yusuf Tekin, Milli Eğitim Bakanı olarak görev yapmaktadır.", zorluk: "kolay", aktif: true },
  { id: "gb093", kategori: "Türkiye Gündemi", on_yuz: "Türkiye Yüzyılı Maarif Modeli nedir?", arka_yuz: "MEB'in yeni müfredat reformudur; LGS ve YKS'de \"beceri temelli\" yeni soru modeli, 2026/2027'yi etkilemeden ilk kez 2028 yılında uygulanacaktır.", zorluk: "orta", aktif: true },
  { id: "gb094", kategori: "Türkiye Gündemi", on_yuz: "2026 LGS ve YKS'de yapısal değişiklik var mı?", arka_yuz: "Hayır; MEB'e göre sınav oturumları, süreler ve puanlama sistemi 2026'da aynı şekilde devam ediyor, kökten değişiklik 2028'e ertelendi.", zorluk: "orta", aktif: true },

  // ── EKLENTİ 5: ÖDÜLLER, ULUSLARARASI ÖRGÜTLER, EK BİLGİLER ──
  { id: "gb095", kategori: "Otomotiv/Teknoloji", on_yuz: "Türkiye'nin ikinci astronotu kimdir?", arka_yuz: "Tuva Cihangir Atasever, 8 Haziran 2024'te Virgin Galactic'in VSS Unity aracıyla yörünge altı araştırma uçuşu gerçekleştirdi.", zorluk: "orta", aktif: true },
  { id: "gb096", kategori: "Edebiyat/Sanat", on_yuz: "76. Berlin Film Festivali Altın Ayı ödülü", arka_yuz: "İlker Çatak'ın yönettiği \"Sarı Zarflar\" (Yellow Letters) filmi, 2026'da festivalin en büyük ödülü olan Altın Ayı'yı kazandı.", zorluk: "orta", aktif: true },
  { id: "gb097", kategori: "Edebiyat/Sanat", on_yuz: "76. Berlin Film Festivali Gümüş Ayı (Jüri Büyük Ödülü)", arka_yuz: "Emin Alper'in yönettiği \"Kurtuluş\" (Salvation) filmi, 2026'da Gümüş Ayı Jüri Büyük Ödülü'nü kazandı.", zorluk: "orta", aktif: true },
  { id: "gb098", kategori: "Dünya Gündemi", on_yuz: "NATO'nun en yeni üyesi hangi ülke?", arka_yuz: "İsveç, 2024 yılında NATO'ya 32. üye olarak katılmıştır.", zorluk: "kolay", aktif: true },
  { id: "gb099", kategori: "Dünya Gündemi", on_yuz: "Şanghay İşbirliği Örgütü'nün (ŞİÖ) en yeni tam üyesi", arka_yuz: "Belarus, 2024'te ŞİÖ'ye tam üye olarak kabul edilmiştir.", zorluk: "orta", aktif: true },
  { id: "gb100", kategori: "Dünya Gündemi", on_yuz: "BRICS'e 2024'te katılan ülkeler", arka_yuz: "Mısır, Etiyopya, İran ve Birleşik Arap Emirlikleri, 2024'te BRICS topluluğuna resmen katılmıştır.", zorluk: "orta", aktif: true },
  { id: "gb101", kategori: "Edebiyat/Sanat", on_yuz: "2024 Eurovision Şarkı Yarışması birincisi", arka_yuz: "İsviçre adına yarışan Nemo, \"The Code\" şarkısıyla birinci oldu.", zorluk: "kolay", aktif: true },
  { id: "gb102", kategori: "Spor", on_yuz: "2026 Kış Olimpiyatları nerede yapılacak?", arka_yuz: "İtalya'nın Milano ve Cortina d'Ampezzo şehirlerinde ortaklaşa düzenlenecektir.", zorluk: "kolay", aktif: true },
  { id: "gb103", kategori: "Spor", on_yuz: "2026 Akdeniz Oyunları nerede yapılacak?", arka_yuz: "20. Akdeniz Oyunları'na İtalya'nın Taranto şehri ev sahipliği yapacaktır.", zorluk: "orta", aktif: true },
  { id: "gb104", kategori: "Bilim", on_yuz: "2024 Nobel Edebiyat Ödülü", arka_yuz: "Güney Koreli yazar Han Kang kazandı.", zorluk: "kolay", aktif: true },
  { id: "gb105", kategori: "Bilim", on_yuz: "2024 Nobel Barış Ödülü", arka_yuz: "Nükleer silahsızlanma çabalarından dolayı Japon organizasyon Nihon Hidankyo'ya verildi.", zorluk: "orta", aktif: true },
  { id: "gb106", kategori: "Bilim", on_yuz: "2024 Nobel Ekonomi Ödülü", arka_yuz: "Kurumların refah üzerindeki etkilerini inceleyen Türk asıllı bilim insanı Daron Acemoğlu, Simon Johnson ve James A. Robinson'a verildi.", zorluk: "orta", aktif: true },
  { id: "gb107", kategori: "Edebiyat/Sanat", on_yuz: "2024 Oscar En İyi Film Ödülü", arka_yuz: "Christopher Nolan'ın yönettiği \"Oppenheimer\" filmi kazandı.", zorluk: "kolay", aktif: true },
  { id: "gb108", kategori: "Edebiyat/Sanat", on_yuz: "2024 Oscar En İyi Yönetmen Ödülü", arka_yuz: "\"Oppenheimer\" filmiyle Christopher Nolan kazandı.", zorluk: "kolay", aktif: true },
  { id: "gb109", kategori: "Edebiyat/Sanat", on_yuz: "2024 Pritzker Mimarlık Ödülü", arka_yuz: "\"Mimarlığın Nobel'i\" kabul edilen ödülü Japon mimar Riken Yamamoto kazandı.", zorluk: "zor", aktif: true },
  { id: "gb110", kategori: "Dünya Gündemi", on_yuz: "Birleşmiş Milletler'in merkezi nerededir?", arka_yuz: "ABD'nin New York şehrindedir.", zorluk: "kolay", aktif: true },
  { id: "gb111", kategori: "Dünya Gündemi", on_yuz: "NATO'nun genel merkezi nerededir?", arka_yuz: "Belçika'nın başkenti Brüksel'dedir.", zorluk: "kolay", aktif: true },
  { id: "gb112", kategori: "Dünya Gündemi", on_yuz: "UNESCO'nun merkezi nerededir?", arka_yuz: "Fransa'nın başkenti Paris'tedir.", zorluk: "kolay", aktif: true },
  { id: "gb113", kategori: "Dünya Gündemi", on_yuz: "Dünya Sağlık Örgütü'nün (WHO) merkezi nerededir?", arka_yuz: "İsviçre'nin Cenevre kentindedir.", zorluk: "kolay", aktif: true },
  { id: "gb114", kategori: "Dünya Gündemi", on_yuz: "Uluslararası Adalet Divanı nerededir?", arka_yuz: "Hollanda'nın Lahey kentindedir.", zorluk: "orta", aktif: true },
  { id: "gb115", kategori: "Dünya Gündemi", on_yuz: "İslam İşbirliği Teşkilatı'nın (İİT) merkezi nerededir?", arka_yuz: "Suudi Arabistan'ın Cidde şehrindedir.", zorluk: "orta", aktif: true },
  { id: "gb116", kategori: "Dünya Gündemi", on_yuz: "Avrupa Merkez Bankası'nın (ECB) merkezi nerededir?", arka_yuz: "Almanya'nın Frankfurt kentindedir.", zorluk: "orta", aktif: true },
  { id: "gb117", kategori: "Dünya Gündemi", on_yuz: "Interpol'ün merkezi nerededir?", arka_yuz: "Fransa'nın Lyon şehrindedir.", zorluk: "orta", aktif: true },
  { id: "gb118", kategori: "Spor", on_yuz: "Uluslararası Olimpiyat Komitesi'nin (IOC) merkezi nerededir?", arka_yuz: "İsviçre'nin Lozan kentindedir.", zorluk: "orta", aktif: true },
  { id: "gb119", kategori: "Ekonomi", on_yuz: "IMF ve Dünya Bankası'nın merkezleri nerededir?", arka_yuz: "İkisinin de genel merkezi ABD'nin Washington D.C. şehrindedir.", zorluk: "kolay", aktif: true },
  { id: "gb120", kategori: "Edebiyat/Sanat", on_yuz: "İstiklal Marşı'nın şairi kimdir?", arka_yuz: "Mehmet Akif Ersoy'dur; aldığı ödülü Darülmesai vakfına bağışlamıştır.", zorluk: "kolay", aktif: true },
  { id: "gb121", kategori: "Edebiyat/Sanat", on_yuz: "\"Tutunamayanlar\" romanının yazarı", arka_yuz: "Türk edebiyatında postmodernizmin ilk örneklerinden olan eser Oğuz Atay'a aittir.", zorluk: "orta", aktif: true },
  { id: "gb122", kategori: "Edebiyat/Sanat", on_yuz: "\"Devlet Ana\" ve \"Yorgun Savaşçı\" romanlarının yazarı", arka_yuz: "Kemal Tahir'e aittir.", zorluk: "orta", aktif: true },
  { id: "gb123", kategori: "Edebiyat/Sanat", on_yuz: "\"Kuyucaklı Yusuf\" romanının yazarı", arka_yuz: "Sabahattin Ali'ye aittir.", zorluk: "kolay", aktif: true },
  { id: "gb124", kategori: "Türkiye İlkleri", on_yuz: "Şerife Bacı kimdir?", arka_yuz: "Kurtuluş Savaşı'nda İnebolu'dan Kastamonu'ya cephane taşırken donarak şehit olan milli mücadele kahramanıdır.", zorluk: "orta", aktif: true },
  { id: "gb125", kategori: "Türkiye İlkleri", on_yuz: "Yörük Ali Efe kimdir?", arka_yuz: "Batı Anadolu'da Yunan işgaline karşı ilk düzenli halk direnişini başlatan Kuva-yi Milliye reisidir.", zorluk: "orta", aktif: true },
  { id: "gb126", kategori: "Türkiye İlkleri", on_yuz: "Türkiye'nin ilk kadın muhtarı kimdir?", arka_yuz: "Aydın'ın Çine ilçesine bağlı Demircidere köyünde seçilen Gül Esin'dir.", zorluk: "zor", aktif: true },
  { id: "gb127", kategori: "Coğrafya", on_yuz: "\"Tarihin Sıfır Noktası\" olarak bilinen yer", arka_yuz: "Şanlıurfa'da bulunan, insanlık tarihinin bilinen en eski kült yapılar topluluğu Göbeklitepe'dir.", zorluk: "kolay", aktif: true },
  { id: "gb128", kategori: "Otomotiv/Teknoloji", on_yuz: "Akkuyu Nükleer Güç Santrali", arka_yuz: "Mersin'de inşaatı süren, Türkiye'nin ilk nükleer güç santralidir.", zorluk: "kolay", aktif: true },
  { id: "gb129", kategori: "Otomotiv/Teknoloji", on_yuz: "Sakarya Gaz Sahası nedir?", arka_yuz: "Karadeniz'de bulunan, Türkiye tarihinin en büyük deniz altı doğal gaz keşif bölgesidir.", zorluk: "orta", aktif: true },
  { id: "gb130", kategori: "Otomotiv/Teknoloji", on_yuz: "PARDUS nedir?", arka_yuz: "TÜBİTAK bünyesinde geliştirilen, yerli ve milli işletim sistemidir.", zorluk: "kolay", aktif: true },
  { id: "gb131", kategori: "Otomotiv/Teknoloji", on_yuz: "Doğu Anadolu Gözlemevi (DAG) nerededir?", arka_yuz: "Erzurum'da yer alır; Avrupa'nın en büyük aynalı teleskoplarından birine sahiptir.", zorluk: "orta", aktif: true },
  { id: "gb132", kategori: "Otomotiv/Teknoloji", on_yuz: "Karapınar Güneş Enerjisi Santrali", arka_yuz: "Konya'da kurulan, Avrupa'nın tek alana kurulu en büyük güneş enerjisi santrallerinden biridir.", zorluk: "orta", aktif: true },
  { id: "gb133", kategori: "Otomotiv/Teknoloji", on_yuz: "GÖKBEY nedir?", arka_yuz: "Türkiye'nin özgün tasarımlı, genel maksat milli helikopteridir.", zorluk: "kolay", aktif: true },
  { id: "gb134", kategori: "Otomotiv/Teknoloji", on_yuz: "TEI-TS1400 nedir?", arka_yuz: "TUSAŞ Motor Sanayii (TEI) tarafından geliştirilen Türkiye'nin ilk yerli helikopter motorudur.", zorluk: "zor", aktif: true },
  { id: "gb135", kategori: "Otomotiv/Teknoloji", on_yuz: "Abdülhamid Han nedir?", arka_yuz: "Türkiye'nin filosuna katılan 7. nesil derin deniz sondaj gemisidir (diğerleri: Fatih, Yavuz, Kanuni).", zorluk: "zor", aktif: true },
  { id: "gb136", kategori: "Coğrafya", on_yuz: "Dünyanın en derin noktası", arka_yuz: "Pasifik Okyanusu'nda yer alan, derinliği yaklaşık 11.000 metreyi bulan Mariana Çukuru'dur.", zorluk: "kolay", aktif: true },
  { id: "gb137", kategori: "Dünya Gündemi", on_yuz: "2026 NATO Liderler Zirvesi nerede yapılacak?", arka_yuz: "7-8 Temmuz 2026 tarihlerinde Türkiye'nin başkenti Ankara'da, Cumhurbaşkanlığı Külliyesi'nde (Beştepe) gerçekleştirilecek. 36. NATO zirvesidir.", zorluk: "orta", aktif: true },
  { id: "gb138", kategori: "Dünya Gündemi", on_yuz: "Türkiye'de kaçıncı NATO Liderler Zirvesi yapılıyor?", arka_yuz: "2004 İstanbul zirvesinin ardından Türkiye'de düzenlenecek ikinci NATO Liderler Zirvesidir.", zorluk: "zor", aktif: true },
  { id: "gb139", kategori: "Dünya Gündemi", on_yuz: "NATO Parlamenter Zirvesi 2026 nerede?", arka_yuz: "28-29 Haziran 2026 tarihlerinde İstanbul'da gerçekleştirildi.", zorluk: "orta", aktif: true },
  { id: "gb140", kategori: "Spor", on_yuz: "2026 FIFA Dünya Kupası'na kaç takım katılıyor?", arka_yuz: "İlk kez 48 takımla düzenleniyor; önceki turnuvada 32 takım vardı. Takımlar 12 dörtlü gruba ayrıldı.", zorluk: "kolay", aktif: true },
  { id: "gb141", kategori: "Spor", on_yuz: "2026 FIFA Dünya Kupası ev sahibi ülkeler hangileri?", arka_yuz: "ABD (11 şehir), Meksika (3 şehir) ve Kanada (2 şehir); üç ülkenin ortaklaşa ev sahipliği yaptığı ilk Dünya Kupasıdır.", zorluk: "orta", aktif: true },
  { id: "gb142", kategori: "Spor", on_yuz: "2026 FIFA Dünya Kupası ne zaman başladı ve ne zaman bitiyor?", arka_yuz: "11 Haziran - 19 Temmuz 2026 tarihleri arasında oynanıyor; toplam 104 maç oynanan en uzun Dünya Kupası formatıdır.", zorluk: "orta", aktif: true },
  { id: "gb143", kategori: "Spor", on_yuz: "Türkiye 2026 Dünya Kupası'na nasıl katıldı?", arka_yuz: "24 yıl aradan sonra (son katılım 2002) FIFA Dünya Kupası finallerine katıldı; ancak grup aşamasını geçemeyerek turnuvaya veda etti.", zorluk: "orta", aktif: true },
  { id: "gb144", kategori: "Türkiye Gündemi", on_yuz: "2026 Mülki İdare Amirleri Atama Kararnamesi", arka_yuz: "İçişleri Bakanı Mustafa Çiftçi imzasıyla 430 mülki idare amirinin görev yeri değiştirildi; 208 Kaymakamdan Kaymakamlığa, 82'si Kaymakamlıktan Vali Yardımcılığına atandı.", zorluk: "zor", aktif: true },
  { id: "gb145", kategori: "Türkiye Gündemi", on_yuz: "Adalet Bakanı kimdir? (2026)", arka_yuz: "Akın Gürlek, Adalet Bakanı olarak görev yapmaktadır.", zorluk: "orta", aktif: true },
  { id: "gb146", kategori: "Türkiye Gündemi", on_yuz: "Türkiye-Suudi Arabistan Yenilenebilir Enerji Anlaşması", arka_yuz: "Haziran 2026'da TBMM tarafından onaylanan bu anlaşmayla iki ülke arasında yenilenebilir enerji santrali projeleri için hükümetlerarası işbirliği çerçevesi kuruldu.", zorluk: "orta", aktif: true },
  { id: "gb147", kategori: "Türkiye Gündemi", on_yuz: "TBMM 2026 yaz tatili uzatıldı mı?", arka_yuz: "Evet. 1 Temmuz'da tatile girmesi gereken TBMM, Genel Kurul kararıyla çalışmalarına devam etmeye karar verdi.", zorluk: "orta", aktif: true },
  { id: "gb148", kategori: "Spor", on_yuz: "2026 FIFA Dünya Kupası'nın savunma şampiyonu kimdir?", arka_yuz: "2022 Katar Dünya Kupası'nı kazanarak üçüncü şampiyonluğunu elde eden Arjantin.", zorluk: "kolay", aktif: true },
  { id: "gb149", kategori: "Spor", on_yuz: "Dünya Kupasını en çok kazanan ülke hangisidir?", arka_yuz: "5 şampiyonlukla Brezilya; ardından 4'er şampiyonlukla Almanya ve İtalya gelmektedir.", zorluk: "kolay", aktif: true },
  { id: "gb150", kategori: "Spor", on_yuz: "2026 Dünya Kupası grup kurasının yapıldığı şehir", arka_yuz: "Grup kuraları, 5 Aralık 2025'te ABD'nin başkenti Washington'da çekildi.", zorluk: "zor", aktif: true },

  // ── EKLENTİ 6: 2026 ULUSLARARASI ETKİNLİK TAKVİMİ ─────────
  { id: "gb151", kategori: "Dünya Gündemi", on_yuz: "2026 G7 Zirvesi nerede yapıldı?", arka_yuz: "Fransa'nın Evian-les-Bains kentinde 15-17 Haziran 2026 tarihlerinde düzenlendi; 52. G7 zirvesidir. Ev sahibi Fransa Cumhurbaşkanı Emmanuel Macron'du.", zorluk: "orta", aktif: true },
  { id: "gb152", kategori: "Türkiye Gündemi", on_yuz: "TEKNOFEST 2026 nerede düzenlenecek?", arka_yuz: "30 Eylül - 4 Ekim 2026 tarihlerinde Şanlıurfa GAP Havalimanı'nda düzenlenecek. Bir önceki TEKNOFEST İstanbul'da yapılmıştı.", zorluk: "kolay", aktif: true },
  { id: "gb153", kategori: "Spor", on_yuz: "2026 UEFA Avrupa Ligi Finali nerede oynandı?", arka_yuz: "20 Mayıs 2026'da İstanbul'daki Beşiktaş Park stadyumunda oynandı.", zorluk: "orta", aktif: true },
  { id: "gb154", kategori: "Spor", on_yuz: "2026 UEFA Şampiyonlar Ligi Finali nerede oynanacak?", arka_yuz: "Macaristan'ın başkenti Budapeşte'de oynanacak.", zorluk: "orta", aktif: true },
  { id: "gb155", kategori: "Edebiyat/Sanat", on_yuz: "Eurovision Şarkı Yarışması 2026 nerede yapılacak?", arka_yuz: "Avusturya'nın başkenti Viyana'da düzenlenecek.", zorluk: "kolay", aktif: true },
  { id: "gb156", kategori: "Spor", on_yuz: "2026 Dünya Göçebe Oyunları'na kim ev sahipliği yapacak?", arka_yuz: "Geleneksel göçebe sporlarının yaşatıldığı bu organizasyona Kırgızistan ev sahipliği yapacak.", zorluk: "orta", aktif: true },
  { id: "gb157", kategori: "Ekonomi", on_yuz: "2026 Dünya Ekonomik Forumu nerede toplanacak?", arka_yuz: "Her yıl olduğu gibi İsviçre'nin Davos kentinde gerçekleştirilecek.", zorluk: "kolay", aktif: true },
  { id: "gb158", kategori: "Spor", on_yuz: "2026 Asya Oyunları nerede yapılacak?", arka_yuz: "Japonya'nın Aichi-Nagoya bölgesinde gerçekleştirilecek.", zorluk: "orta", aktif: true },

  // ── EKLENTİ 7: MEB MÜFREDAT TERİM DEĞİŞİKLİKLERİ (2026) ───
  { id: "gb159", kategori: "Türkiye Gündemi", on_yuz: "Yeni müfredatta \"Kurtuluş Savaşı\" yerine hangi kavram kullanılıyor?", arka_yuz: "\"Milli Mücadele\" kavramı kullanılıyor. MEB Bakanı Yusuf Tekin, Cumhuriyet öncesinde de Osmanlı Devleti'nin var olduğunu gerekçe göstererek bu değişikliği açıkladı.", zorluk: "orta", aktif: true },
  { id: "gb160", kategori: "Türkiye Gündemi", on_yuz: "Yeni müfredatta \"Bizans\" terimi neyle değiştirildi?", arka_yuz: "\"Doğu Roma\" ifadesiyle değiştirildi.", zorluk: "kolay", aktif: true },
  { id: "gb161", kategori: "Türkiye Gündemi", on_yuz: "Yeni müfredatta \"ormanlarımız\" ifadesi neyle değiştirildi?", arka_yuz: "\"Yeşil Vatan\" ifadesiyle değiştirildi.", zorluk: "orta", aktif: true },
  { id: "gb162", kategori: "Türkiye Gündemi", on_yuz: "Yeni müfredatta Türkiye'nin deniz yetki alanları nasıl adlandırılıyor?", arka_yuz: "\"Mavi Vatan\" olarak adlandırılıyor.", zorluk: "kolay", aktif: true },
  { id: "gb163", kategori: "Türkiye Gündemi", on_yuz: "Yeni müfredatta \"Ermeni Meselesi\" başlığı neyle değiştirildi?", arka_yuz: "\"Asılsız Ermeni İddiaları\" şeklinde değiştirildi.", zorluk: "orta", aktif: true },
  { id: "gb164", kategori: "Türkiye Gündemi", on_yuz: "Yeni müfredatta \"Haçlı Seferleri\" ifadesi neyle değiştirildi?", arka_yuz: "\"Haçlı Saldırıları\" ifadesiyle değiştirildi.", zorluk: "orta", aktif: true },
  { id: "gb165", kategori: "Türkiye Gündemi", on_yuz: "Yeni müfredatta \"Orta Asya\" terimi yerine ne kullanılıyor?", arka_yuz: "\"Türkistan\" ifadesi kullanılıyor.", zorluk: "orta", aktif: true },
  { id: "gb166", kategori: "Türkiye Gündemi", on_yuz: "Yeni müfredatta \"Coğrafi Keşifler\" dönemi nasıl adlandırılıyor?", arka_yuz: "\"Sömürgecilik\" (sömürgeciliğin başlangıcı) olarak adlandırılıyor.", zorluk: "zor", aktif: true },
  { id: "gb167", kategori: "Türkiye Gündemi", on_yuz: "Müfredat içerik yükü ne oranda azaltıldı?", arka_yuz: "Bakan Yusuf Tekin'e göre müfredat içeriği yaklaşık %35 oranında sadeleştirildi.", zorluk: "orta", aktif: true },

  // ── EKLENTİ 8: ULUSLARARASI ÖRGÜT MERKEZLERİ (EK) ─────────
  { id: "gb168", kategori: "Dünya Gündemi", on_yuz: "WTO ve ILO'nun ortak merkezi neresidir?", arka_yuz: "İsviçre'nin Cenevre kentidir (WHO ile aynı şehir).", zorluk: "orta", aktif: true },
  { id: "gb169", kategori: "Dünya Gündemi", on_yuz: "OECD'nin merkezi neresidir?", arka_yuz: "Fransa'nın Paris kentidir (UNESCO ile aynı şehir).", zorluk: "orta", aktif: true },
  { id: "gb170", kategori: "Dünya Gündemi", on_yuz: "FAO'nun (Gıda ve Tarım Örgütü) merkezi neresidir?", arka_yuz: "İtalya'nın Roma kentidir.", zorluk: "orta", aktif: true },
  { id: "gb171", kategori: "Türkiye Gündemi", on_yuz: "Türk Devletleri Teşkilatı, D-8 ve KEİ'nin ortak merkezi neresidir?", arka_yuz: "Üçünün de genel merkezi İstanbul'dur.", zorluk: "orta", aktif: true },
  { id: "gb172", kategori: "Dünya Gündemi", on_yuz: "Şanghay İşbirliği Örgütü'nün merkezi neresidir?", arka_yuz: "Çin'in başkenti Pekin'dir.", zorluk: "orta", aktif: true },
  { id: "gb173", kategori: "Dünya Gündemi", on_yuz: "Ekonomik İşbirliği Teşkilatı'nın (EİT) merkezi neresidir?", arka_yuz: "İran'ın başkenti Tahran'dır.", zorluk: "zor", aktif: true },
  { id: "gb174", kategori: "Dünya Gündemi", on_yuz: "Arap Birliği'nin merkezi neresidir?", arka_yuz: "Mısır'ın başkenti Kahire'dir.", zorluk: "kolay", aktif: true },
  { id: "gb175", kategori: "Dünya Gündemi", on_yuz: "Afrika Birliği'nin merkezi neresidir?", arka_yuz: "Etiyopya'nın başkenti Addis Ababa'dır.", zorluk: "orta", aktif: true },

  // ── EKLENTİ 9: TARİHE YÖN VEREN MUCİTLER VE İLKLER ────────
  { id: "gb176", kategori: "Bilim", on_yuz: "Telgrafı kim icat etmiştir?", arka_yuz: "İngiliz mucitler William Cooke ve Charles Wheatstone.", zorluk: "orta", aktif: true },
  { id: "gb177", kategori: "Bilim", on_yuz: "Mors alfabesini kim geliştirmiştir?", arka_yuz: "Samuel Morse.", zorluk: "kolay", aktif: true },
  { id: "gb178", kategori: "Bilim", on_yuz: "Telefonu kim icat etmiştir?", arka_yuz: "Graham Bell.", zorluk: "kolay", aktif: true },
  { id: "gb179", kategori: "Bilim", on_yuz: "Cep telefonunu kim icat etmiştir?", arka_yuz: "Martin Cooper, Motorola şirketinde çalışırken icat etmiştir.", zorluk: "orta", aktif: true },
  { id: "gb180", kategori: "Bilim", on_yuz: "Radyoyu kim icat etmiştir?", arka_yuz: "Guglielmo Marconi.", zorluk: "kolay", aktif: true },
  { id: "gb181", kategori: "Bilim", on_yuz: "İzafiyet Teorisi'ni kim geliştirmiştir?", arka_yuz: "Albert Einstein.", zorluk: "kolay", aktif: true },
  { id: "gb182", kategori: "Bilim", on_yuz: "İlk antibiyotik olan penisilini kim keşfetmiştir?", arka_yuz: "Alexander Fleming.", zorluk: "kolay", aktif: true },
  { id: "gb183", kategori: "Bilim", on_yuz: "Çocuk felci (polio) aşısını kim geliştirmiştir?", arka_yuz: "Jonas Salk.", zorluk: "orta", aktif: true },
  { id: "gb184", kategori: "Bilim", on_yuz: "Röntgen ışınlarını (X-Ray) kim keşfetmiştir?", arka_yuz: "Wilhelm Conrad Röntgen.", zorluk: "orta", aktif: true },
  { id: "gb185", kategori: "Bilim", on_yuz: "Richter Ölçeği'ni kim geliştirmiştir?", arka_yuz: "Charles Francis Richter.", zorluk: "orta", aktif: true },
  { id: "gb186", kategori: "Türkiye İlkleri", on_yuz: "İlk dünya haritasını kim çizmiştir?", arka_yuz: "Osmanlı denizci ve haritacı Piri Reis.", zorluk: "kolay", aktif: true },
  { id: "gb187", kategori: "Bilim", on_yuz: "İlk elektronik genel amaçlı bilgisayar hangisidir?", arka_yuz: "ENIAC'tır.", zorluk: "orta", aktif: true },
  { id: "gb188", kategori: "Türkiye İlkleri", on_yuz: "Osmanlı'nın ilk denizaltısı hangisidir?", arka_yuz: "İbrahim Efendi tarafından tasarlanan Tahtelbahir'dir.", zorluk: "zor", aktif: true },
  { id: "gb189", kategori: "Bilim", on_yuz: "Televizyonu kim icat etmiştir?", arka_yuz: "John Logie Baird.", zorluk: "kolay", aktif: true },
  { id: "gb190", kategori: "Bilim", on_yuz: "Matbaayı kim icat etmiştir?", arka_yuz: "Johann Gutenberg.", zorluk: "kolay", aktif: true },

  // ── EKLENTİ 10: UNESCO YARATICI ŞEHİRLER AĞI (TR, 2026) ───
  { id: "gb191", kategori: "Türkiye İlkleri", on_yuz: "UNESCO Yaratıcı Şehirler Ağı'na giren ilk Türk şehri hangisidir?", arka_yuz: "Gaziantep, 2015 yılında Gastronomi dalında ağa kabul edilen ilk Türk şehridir. Ardından Hatay (Gastronomi, 2017), İstanbul (Tasarım, 2017) ve Kütahya (Zanaat ve Halk Sanatları, 2017) katılmıştır.", zorluk: "orta", aktif: true },
  { id: "gb192", kategori: "Türkiye İlkleri", on_yuz: "UNESCO Yaratıcı Şehirler Ağı'na en son kabul edilen Türk şehri hangisidir?", arka_yuz: "Kahramanmaraş, 2025 yılında Edebiyat dalında ağa kabul edildi.", zorluk: "zor", aktif: true },

  // ── EKLENTİ 11: 2026 OSCAR ÖDÜLLERİ (98. AKADEMİ ÖDÜLLERİ) ─
  { id: "gb193", kategori: "Edebiyat/Sanat", on_yuz: "2026 Oscar Ödülleri'nde En İyi Film hangisi oldu?", arka_yuz: "Paul Thomas Anderson'ın yönettiği \"One Battle After Another\" (Savaş Üstüne Savaş), toplam 6 dalda ödül kazanarak En İyi Film oldu.", zorluk: "orta", aktif: true },
  { id: "gb194", kategori: "Edebiyat/Sanat", on_yuz: "2026 Oscar En İyi Yönetmen ödülünü kim kazandı?", arka_yuz: "Paul Thomas Anderson, \"One Battle After Another\" filmiyle kazandı.", zorluk: "orta", aktif: true },
  { id: "gb195", kategori: "Edebiyat/Sanat", on_yuz: "2026 Oscar En İyi Erkek/Kadın Oyuncu ödüllerini kimler kazandı?", arka_yuz: "Michael B. Jordan (\"Sinners\") En İyi Erkek Oyuncu, Jessie Buckley (\"Hamnet\") En İyi Kadın Oyuncu ödülünü kazandı.", zorluk: "orta", aktif: true },

  // ── EKLENTİ 12: UZAY GÜNDEMİ ───────────────────────────────
  { id: "gb196", kategori: "Otomotiv/Teknoloji", on_yuz: "NASA'nın Artemis II göreviyle Ay'a gidecek ilk kadın astronot kimdir?", arka_yuz: "Christina Koch.", zorluk: "orta", aktif: true },
// ── EKLENTİ 13: ULUSLARARASI KURULUŞLAR VE BAŞKANLIKLAR (PDF'TEN) ──
  { id: "gb197", kategori: "Dünya Gündemi", on_yuz: "2026 AB Dönem Başkanlıkları", arka_yuz: "Kıbrıs (Ocak-Haziran) ve İrlanda (Temmuz-Aralık, 1 Temmuz 2026'da devraldı). Litvanya'nın sırası 2027'nin ilk yarısında.", zorluk: "orta", aktif: true },
  { id: "gb198", kategori: "Dünya Gündemi", on_yuz: "2025 AB Dönem Başkanlıkları", arka_yuz: "Polonya (Ocak-Haziran) ve Danimarka (Temmuz-Aralık).", zorluk: "orta", aktif: true },
  { id: "gb199", kategori: "Dünya Gündemi", on_yuz: "Türk Devletleri Teşkilatı (TDT) 2025 Zirvesi ev sahibi", arka_yuz: "Macaristan ev sahipliği yaptı.", zorluk: "orta", aktif: true },
  { id: "gb200", kategori: "Dünya Gündemi", on_yuz: "BM 80. Genel Kurul Başkanı (2025-2026) kimdir?", arka_yuz: "Philemon Yang (Kamerun).", zorluk: "zor", aktif: true },
  { id: "gb201", kategori: "Dünya Gündemi", on_yuz: "Uluslararası Ceza Mahkemesi (UCM) Başkanı kimdir?", arka_yuz: "Tomoko Akane, 2024'te seçildi.", zorluk: "zor", aktif: true },
  { id: "gb202", kategori: "Dünya Gündemi", on_yuz: "İslam İşbirliği Teşkilatı (İİT) 15. Zirvesi nerede yapıldı?", arka_yuz: "Gambiya'nın başkenti Banjul'da yapıldı.", zorluk: "orta", aktif: true },
  { id: "gb203", kategori: "Dünya Gündemi", on_yuz: "Şanghay İşbirliği Örgütü (ŞİÖ) 2024 Zirvesi nerede yapıldı?", arka_yuz: "Kazakistan'ın başkenti Astana'da yapıldı.", zorluk: "orta", aktif: true },
  { id: "gb204", kategori: "Dünya Gündemi", on_yuz: "Avrupa Konseyi Genel Sekreteri kimdir?", arka_yuz: "Alain Berset (İsviçre), 2024'te seçildi.", zorluk: "orta", aktif: true },
  { id: "gb205", kategori: "Dünya Gündemi", on_yuz: "Uluslararası Adalet Divanı Başkanı kimdir?", arka_yuz: "Nawaf Salam (Lübnan).", zorluk: "orta", aktif: true },
  { id: "gb206", kategori: "Dünya Gündemi", on_yuz: "Dünya Sağlık Örgütü (DSÖ) Genel Direktörü kimdir?", arka_yuz: "Tedros Adhanom Ghebreyesus.", zorluk: "kolay", aktif: true },
  { id: "gb207", kategori: "Dünya Gündemi", on_yuz: "Interpol Başkanı kimdir?", arka_yuz: "Lucas Philippe (Fransa), 27 Kasım 2025'te seçildi. Önceki başkan Ahmed Naser Al-Raisi (BAE) idi.", zorluk: "orta", aktif: true },
  { id: "gb208", kategori: "Ekonomi", on_yuz: "OPEC Genel Sekreteri kimdir?", arka_yuz: "Heysem el-Gays.", zorluk: "orta", aktif: true },
  { id: "gb209", kategori: "Dünya Gündemi", on_yuz: "APEC 2025 Zirvesi'ne kim ev sahipliği yaptı?", arka_yuz: "Güney Kore.", zorluk: "orta", aktif: true },
  { id: "gb210", kategori: "Dünya Gündemi", on_yuz: "ASEAN 2025 Dönem Başkanı hangi ülkedir?", arka_yuz: "Malezya.", zorluk: "orta", aktif: true },
  { id: "gb211", kategori: "Ekonomi", on_yuz: "Dünya Bankası Başkanı kimdir?", arka_yuz: "Ajay Banga.", zorluk: "orta", aktif: true },
  { id: "gb212", kategori: "Ekonomi", on_yuz: "IMF Başkanı kimdir?", arka_yuz: "Kristalina Georgieva.", zorluk: "kolay", aktif: true },
  { id: "gb213", kategori: "Ekonomi", on_yuz: "Dünya Ticaret Örgütü (WTO) Genel Direktörü kimdir?", arka_yuz: "Ngozi Okonjo-Iweala.", zorluk: "orta", aktif: true },
  { id: "gb214", kategori: "Dünya Gündemi", on_yuz: "BM Mülteciler Yüksek Komiserliği (UNHCR) merkezi neresidir?", arka_yuz: "Cenevre.", zorluk: "orta", aktif: true },
  { id: "gb215", kategori: "Dünya Gündemi", on_yuz: "Gıda ve Tarım Örgütü (FAO) merkezi neresidir?", arka_yuz: "Roma.", zorluk: "orta", aktif: true },
  { id: "gb216", kategori: "Dünya Gündemi", on_yuz: "Avrupa Birliği'nin en son üyesi hangi ülkedir?", arka_yuz: "Hırvatistan (Brexit sonrası 27 üye kaldı, Hırvatistan son katılan ülkedir).", zorluk: "orta", aktif: true },
  { id: "gb217", kategori: "Dünya Gündemi", on_yuz: "Euro Bölgesi'ne en son katılan ülke (2023) hangisidir?", arka_yuz: "Hırvatistan.", zorluk: "orta", aktif: true },
  { id: "gb218", kategori: "Dünya Gündemi", on_yuz: "Avrupa Parlamentosu hangi şehirlerde bulunur?", arka_yuz: "Strazburg ve Brüksel.", zorluk: "orta", aktif: true },
  { id: "gb219", kategori: "Türkiye Gündemi", on_yuz: "D-8 nedir?", arka_yuz: "Türkiye'nin kurucu üyesi olduğu, 8 İslam ülkesini kapsayan ekonomik işbirliği örgütüdür.", zorluk: "orta", aktif: true },
  { id: "gb220", kategori: "Dünya Gündemi", on_yuz: "2025 BRICS Dönem Başkanı hangi ülkedir?", arka_yuz: "Brezilya.", zorluk: "orta", aktif: true },
  { id: "gb221", kategori: "Dünya Gündemi", on_yuz: "G7 ülkeleri hangileridir?", arka_yuz: "ABD, Almanya, İngiltere, Fransa, İtalya, Kanada, Japonya.", zorluk: "kolay", aktif: true },
  { id: "gb222", kategori: "Dünya Gündemi", on_yuz: "G20'ye en son tam üye olarak kabul edilen birlik hangisidir?", arka_yuz: "Afrika Birliği.", zorluk: "orta", aktif: true },
  { id: "gb223", kategori: "Türkiye Gündemi", on_yuz: "Türk Devletleri Teşkilatı'nın gözlemci üyeleri kimlerdir?", arka_yuz: "Macaristan, KKTC ve Türkmenistan.", zorluk: "orta", aktif: true },

  // ── EKLENTİ 14: TÜRKİYE GÜNDEMİ - SAVUNMA VE PROJELER (PDF) ──
  { id: "gb224", kategori: "Otomotiv/Teknoloji", on_yuz: "TCG Derya nedir?", arka_yuz: "Türkiye'nin denize indirdiği en büyük ikinci gemisi; Denizde İkmal Muharebe Destek Gemisi'dir.", zorluk: "orta", aktif: true },
  { id: "gb225", kategori: "Otomotiv/Teknoloji", on_yuz: "TCG Piri Reis nedir?", arka_yuz: "Türkiye'nin Havadan Bağımsız Tahrik Sistemine sahip ilk denizaltısıdır.", zorluk: "orta", aktif: true },
  { id: "gb226", kategori: "Otomotiv/Teknoloji", on_yuz: "Türkiye'nin ilk milli denizaltısı (MİLDEN) hangi aşamadadır?", arka_yuz: "Tasarım aşaması tamamlandı, inşası devam ediyor.", zorluk: "zor", aktif: true },
  { id: "gb227", kategori: "Coğrafya", on_yuz: "Türkiye'nin en yüksek viyadüğü hangisidir?", arka_yuz: "Konya-Karaman arasındaki Eğiste Hadimi Viyadüğü'dür.", zorluk: "zor", aktif: true },
  { id: "gb228", kategori: "Türkiye Gündemi", on_yuz: "Sakin Şehir (Cittaslow) ağına 2024'te katılan ilçelerimiz hangileridir?", arka_yuz: "Safranbolu ve Daday.", zorluk: "orta", aktif: true },
  { id: "gb229", kategori: "Türkiye Gündemi", on_yuz: "Türkiye'nin milli hava savunma sistemi ailesi nelerdir?", arka_yuz: "Siper (uzun menzil), Hisar (orta menzil), Sungur (kısa menzil).", zorluk: "orta", aktif: true },
  { id: "gb230", kategori: "Otomotiv/Teknoloji", on_yuz: "Türkiye'nin denize dolgu yapılarak inşa edilen ilk havalimanı hangisidir?", arka_yuz: "Ordu-Giresun Havalimanı.", zorluk: "orta", aktif: true },
  { id: "gb231", kategori: "Otomotiv/Teknoloji", on_yuz: "Türkiye'nin denize dolgu yapılarak inşa edilen ikinci havalimanı hangisidir?", arka_yuz: "Rize-Artvin Havalimanı.", zorluk: "orta", aktif: true },
  { id: "gb232", kategori: "Türkiye İlkleri", on_yuz: "2020'de tekrar cami olan, İstanbul'un fethinin simgesi eser hangisidir?", arka_yuz: "Ayasofya-i Kebir Câmi-i Şerifi.", zorluk: "kolay", aktif: true },
  { id: "gb233", kategori: "Otomotiv/Teknoloji", on_yuz: "Türkiye'nin uzaydaki aktif haberleşme uyduları hangileridir?", arka_yuz: "Türksat 3A, 4A, 4B, 5A, 5B ve 6A.", zorluk: "orta", aktif: true },
  { id: "gb234", kategori: "Türkiye Gündemi", on_yuz: "Türkiye'nin siber güvenlik tatbikatının adı nedir?", arka_yuz: "Yıldız.", zorluk: "orta", aktif: true },
  { id: "gb235", kategori: "Türkiye İlkleri", on_yuz: "Türkiye'nin otomobili (TOGG) üretim kampüsü nerededir?", arka_yuz: "Bursa (Gemlik).", zorluk: "kolay", aktif: true },

  // ── EKLENTİ 15: KÜLTÜR, SANAT VE ÖDÜLLER (PDF) ──
  { id: "gb236", kategori: "Edebiyat/Sanat", on_yuz: "2025 UNESCO Anma Programı hangi esere ayrıldı?", arka_yuz: "Kaşgarlı Mahmud'un Divanü Lügati't-Türk eserinin 950. yılına.", zorluk: "zor", aktif: true },
  { id: "gb237", kategori: "Edebiyat/Sanat", on_yuz: "2024 UNESCO Anma Programı kimlere ayrıldı?", arka_yuz: "Ali Kuşçu ve Fuat Sezgin'e.", zorluk: "zor", aktif: true },
  { id: "gb238", kategori: "Edebiyat/Sanat", on_yuz: "2025 ve 2026 Dünya Kitap Başkentleri hangileridir?", arka_yuz: "2025: Riyad (Suudi Arabistan), 2026: Rabat (Fas).", zorluk: "orta", aktif: true },
  { id: "gb239", kategori: "Türkiye Gündemi", on_yuz: "2026 Türk Dünyası Kültür Başkenti neresidir?", arka_yuz: "Andican (Özbekistan). 2027'de bu unvan Kayseri'ye geçecek.", zorluk: "orta", aktif: true },
  { id: "gb240", kategori: "Edebiyat/Sanat", on_yuz: "2025 ve 2026 Avrupa Kültür Başkentleri hangileridir?", arka_yuz: "2025: Chemnitz (Almanya) ve Nova Gorica (Slovenya). 2026: Oulu (Finlandiya) ve Trencin (Slovakya).", zorluk: "orta", aktif: true },
  { id: "gb241", kategori: "Bilim", on_yuz: "2025 Nobel Edebiyat Ödülü'nü kim kazandı?", arka_yuz: "László Krasznahorkai (Macaristan).", zorluk: "orta", aktif: true },
  { id: "gb242", kategori: "Bilim", on_yuz: "2025 Nobel Barış Ödülü'nü kim kazandı?", arka_yuz: "María Corina Machado (Venezuela).", zorluk: "orta", aktif: true },
  { id: "gb243", kategori: "Bilim", on_yuz: "2025 Nobel Ekonomi Ödülü'nü kimler kazandı?", arka_yuz: "Joel Mokyr, Philippe Aghion ve Peter Howitt.", zorluk: "orta", aktif: true },
  { id: "gb244", kategori: "Edebiyat/Sanat", on_yuz: "97. Oscar Ödülleri'nde (2025) Türkiye'nin adayı kimdi?", arka_yuz: "Zeki Demirkubuz, \"Hayat\" filmiyle.", zorluk: "zor", aktif: true },
  { id: "gb245", kategori: "Edebiyat/Sanat", on_yuz: "98. Oscar Ödülleri'nde (2026) Türkiye'nin adayı kimdi?", arka_yuz: "Murat Fıratoğlu, \"Hemme'nin Öldüğü Günlerden Biri\" filmiyle.", zorluk: "zor", aktif: true },
  { id: "gb246", kategori: "Edebiyat/Sanat", on_yuz: "78. Cannes Film Festivali (2025) Altın Palmiye'sini kim kazandı?", arka_yuz: "Jafar Panahi (İran), \"It Was Just an Accident\" filmiyle.", zorluk: "orta", aktif: true },
  { id: "gb247", kategori: "Edebiyat/Sanat", on_yuz: "79. Cannes Film Festivali (2026) Altın Palmiye'sini kim kazandı?", arka_yuz: "Cristian Mungiu (Romanya), \"Fjord\" filmiyle; ödülü 2. kez kazandı.", zorluk: "orta", aktif: true },
  { id: "gb248", kategori: "Edebiyat/Sanat", on_yuz: "Cumhurbaşkanlığı Kültür Sanat Büyük Ödülü'nü (2024 Vefa Ödülü) kim aldı?", arka_yuz: "Yönetmen Halit Refiğ, 25 Aralık 2024'te düzenlenen törenle.", zorluk: "zor", aktif: true },
  { id: "gb249", kategori: "Türkiye Gündemi", on_yuz: "TEKNOFEST 2024 nerede yapıldı?", arka_yuz: "Adana'da düzenlendi.", zorluk: "orta", aktif: true },
  { id: "gb250", kategori: "Dünya Gündemi", on_yuz: "Expo 2025, 2027 ve 2030 ev sahipleri hangileridir?", arka_yuz: "2025: Osaka (Japonya), 2027: Belgrad (Sırbistan), 2030: Riyad (Suudi Arabistan).", zorluk: "orta", aktif: true },
  { id: "gb251", kategori: "Dünya Gündemi", on_yuz: "2024 Dünya Göçebe Oyunları'na kim ev sahipliği yaptı?", arka_yuz: "Kazakistan (Astana).", zorluk: "orta", aktif: true },

  // ── EKLENTİ 16: SPOR DÜNYASI (PDF) ──
  { id: "gb252", kategori: "Spor", on_yuz: "EURO 2024 şampiyonu hangi ülkedir?", arka_yuz: "İspanya.", zorluk: "kolay", aktif: true },
  { id: "gb253", kategori: "Spor", on_yuz: "EURO 2028 ve EURO 2032 ev sahipleri kimlerdir?", arka_yuz: "2028: Birleşik Krallık ve İrlanda Cumhuriyeti (ortak). 2032: Türkiye ve İtalya (ortak).", zorluk: "orta", aktif: true },
  { id: "gb254", kategori: "Spor", on_yuz: "2024 Paris Olimpiyatları'nda Türkiye kaç madalya kazandı?", arka_yuz: "3 Gümüş, 5 Bronz olmak üzere toplam 8 madalyayla tamamladı.", zorluk: "orta", aktif: true },
  { id: "gb255", kategori: "Spor", on_yuz: "2028 ve 2032 Yaz Olimpiyatları nerede yapılacak?", arka_yuz: "2028: Los Angeles (ABD). 2032: Brisbane (Avustralya).", zorluk: "orta", aktif: true },
  { id: "gb256", kategori: "Spor", on_yuz: "2025 UEFA Şampiyonlar Ligi Finali nerede oynandı?", arka_yuz: "Almanya'nın Münih şehrindeki Allianz Arena'da oynandı.", zorluk: "orta", aktif: true },
  { id: "gb257", kategori: "Spor", on_yuz: "2027 UEFA Konferans Ligi Finali'ne kim ev sahipliği yapacak?", arka_yuz: "Ankara (yeni stadyum).", zorluk: "orta", aktif: true },
  { id: "gb258", kategori: "Spor", on_yuz: "2024 ve 2025 THY EuroLeague şampiyonları kimlerdir?", arka_yuz: "2024: Panathinaikos. 2025: Fenerbahçe Beko (2. kez, finalde Monaco'yu yendi).", zorluk: "orta", aktif: true },
  { id: "gb259", kategori: "Spor", on_yuz: "2024, 2025 ve 2026 FIBA Kadınlar EuroLeague şampiyonları kimlerdir?", arka_yuz: "2024: Fenerbahçe Alagöz Holding. 2025: ZVVZ USK Praha (Çekya). 2026: Fenerbahçe Opet (3. kez, finalde Galatasaray'ı yendi).", zorluk: "orta", aktif: true },
  { id: "gb260", kategori: "Spor", on_yuz: "Buse Naz Çakıroğlu kimdir?", arka_yuz: "Avrupa şampiyonalarında üst üste 3 kez altın madalya kazanan ilk Türk kadın boksördür.", zorluk: "orta", aktif: true },
  { id: "gb261", kategori: "Spor", on_yuz: "A Milli Kadın Voleybol Takımı 2024 Paris Olimpiyatları'nda kaçıncı oldu?", arka_yuz: "4. oldu.", zorluk: "orta", aktif: true },
  { id: "gb262", kategori: "Spor", on_yuz: "Şahika Ercümen kimdir?", arka_yuz: "Serbest dalış dünya rekorlarına yenilerini eklemeye devam eden milli sporcumuzdur.", zorluk: "orta", aktif: true },
  { id: "gb263", kategori: "Spor", on_yuz: "2025 Kış Üniversite Oyunları (Universiade) nerede yapıldı?", arka_yuz: "İtalya'nın Torino şehrinde yapıldı.", zorluk: "orta", aktif: true },
  { id: "gb264", kategori: "Spor", on_yuz: "2025 FIFA Kulüpler Dünya Kupası hangi formatta düzenlendi?", arka_yuz: "ABD'de, 32 takımlı genişletilmiş yeni formatıyla düzenlendi.", zorluk: "orta", aktif: true },
  { id: "gb265", kategori: "Spor", on_yuz: "2026 Avrupa Erkekler Hentbol Şampiyonası'na kimler ev sahipliği yapacak?", arka_yuz: "Danimarka, İsveç ve Norveç.", zorluk: "orta", aktif: true },
  { id: "gb266", kategori: "Spor", on_yuz: "2025 Dünya Atletizm Şampiyonası nerede yapıldı?", arka_yuz: "Tokyo (Japonya).", zorluk: "kolay", aktif: true },

  // ── EKLENTİ 17: COĞRAFYA, TARIM VE ÇEVRE (PDF) ──
  { id: "gb267", kategori: "Coğrafya", on_yuz: "Dünyanın en derin gölü hangisidir?", arka_yuz: "Rusya'daki Baykal Gölü'dür.", zorluk: "kolay", aktif: true },
  { id: "gb268", kategori: "Coğrafya", on_yuz: "Salda Gölü neden \"Türkiye'nin Maldivleri\" olarak bilinir?", arka_yuz: "Burdur'da bulunan bu gölün beyaz kumsalları ve turkuaz suyu nedeniyle bu isimle anılır.", zorluk: "kolay", aktif: true },
  { id: "gb269", kategori: "Coğrafya", on_yuz: "Dünyanın en yüksek şelalesi hangisidir?", arka_yuz: "Venezuela'daki Angel Şelalesi'dir.", zorluk: "orta", aktif: true },
  { id: "gb270", kategori: "Coğrafya", on_yuz: "Dünyanın en uzun nehri hangisidir?", arka_yuz: "Nil Nehri'dir.", zorluk: "kolay", aktif: true },
  { id: "gb271", kategori: "Coğrafya", on_yuz: "Türkiye'de en çok orman alanına sahip il hangisidir?", arka_yuz: "Antalya.", zorluk: "orta", aktif: true },
  { id: "gb272", kategori: "Coğrafya", on_yuz: "Türkiye'de rüzgar enerjisi kapasitesi en yüksek il hangisidir?", arka_yuz: "İzmir.", zorluk: "orta", aktif: true },
  { id: "gb273", kategori: "Coğrafya", on_yuz: "Türkiye'de jeotermal enerji kapasitesi en yüksek bölge neresidir?", arka_yuz: "Ege Bölgesi (özellikle Denizli-Sarayköy ve Aydın-Germencik).", zorluk: "orta", aktif: true },
  { id: "gb274", kategori: "Coğrafya", on_yuz: "Karadeniz'de keşfedilen doğalgazın karaya çıkarıldığı tesis hangisidir?", arka_yuz: "Zonguldak-Çaycuma'daki Filyos Doğalgaz İşleme Tesisi'dir.", zorluk: "orta", aktif: true },
  { id: "gb275", kategori: "Coğrafya", on_yuz: "Türkiye'nin dünyada rezerv birinciliğine sahip olduğu maden hangisidir?", arka_yuz: "Bor.", zorluk: "kolay", aktif: true },
  { id: "gb276", kategori: "Türkiye Gündemi", on_yuz: "Gabar Dağı Petrol Keşfi nedir?", arka_yuz: "Şırnak bölgesinde keşfedilen, Türkiye'nin günlük petrol üretimini rekor seviyelere çıkaran Şehit Aybüke Yalçın ve Şehit Esma Çevik petrol sahalarıdır.", zorluk: "orta", aktif: true },
  { id: "gb277", kategori: "Türkiye Gündemi", on_yuz: "Türkiye'nin Avrupa Birliği'nden tescil alan ilk ürünü hangisidir?", arka_yuz: "Antep Baklavası.", zorluk: "kolay", aktif: true },
  { id: "gb278", kategori: "Türkiye Gündemi", on_yuz: "Türkiye'nin AB'den tescil alan ilk zeytinyağı hangisidir?", arka_yuz: "Milas Zeytinyağı.", zorluk: "orta", aktif: true },
  { id: "gb279", kategori: "Türkiye Gündemi", on_yuz: "Türkiye'nin AB'den tescil alan ilk peyniri hangisidir?", arka_yuz: "Ezine Peyniri (Edremit Körfezi Yeşil Çizik Zeytini ile birlikte son yıllardaki tesciller arasındadır).", zorluk: "orta", aktif: true },
  { id: "gb280", kategori: "Türkiye Gündemi", on_yuz: "Türkiye'nin AB tescilli ürün sayısı kaça ulaştı?", arka_yuz: "Kasım 2025 itibarıyla 40'a ulaştı; 2026 hedefi 60.", zorluk: "orta", aktif: true },
  { id: "gb281", kategori: "Coğrafya", on_yuz: "Türkiye'de çay tarımının başkenti neresidir?", arka_yuz: "Rize.", zorluk: "kolay", aktif: true },
  { id: "gb282", kategori: "Coğrafya", on_yuz: "Türkiye'de fındık üretiminde lider il hangisidir?", arka_yuz: "Ordu.", zorluk: "kolay", aktif: true },
  { id: "gb283", kategori: "Coğrafya", on_yuz: "Türkiye'de incir üretiminde lider il hangisidir?", arka_yuz: "Aydın.", zorluk: "kolay", aktif: true },
  { id: "gb284", kategori: "Coğrafya", on_yuz: "Türkiye'de kayısı üretiminde lider il hangisidir?", arka_yuz: "Malatya (aynı zamanda AB tescillidir).", zorluk: "kolay", aktif: true },
  { id: "gb285", kategori: "Coğrafya", on_yuz: "GAP (Güneydoğu Anadolu Projesi) nedir?", arka_yuz: "Türkiye'nin enerji ve sulama odaklı en büyük entegre bölgesel kalkınma projesidir.", zorluk: "kolay", aktif: true },
  { id: "gb286", kategori: "Coğrafya", on_yuz: "GAP kapsamındaki iller hangileridir?", arka_yuz: "Adıyaman, Batman, Diyarbakır, Gaziantep, Kilis, Mardin, Siirt, Şanlıurfa, Şırnak.", zorluk: "orta", aktif: true },
  { id: "gb287", kategori: "Coğrafya", on_yuz: "ZBK Kapsamındaki iller hangileridir?", arka_yuz: "Zonguldak, Bartın, Karabük.", zorluk: "orta", aktif: true },
  { id: "gb288", kategori: "Coğrafya", on_yuz: "Yeşilırmak Havzası Gelişim Projesi (YHGP) illeri hangileridir?", arka_yuz: "Amasya, Çorum, Samsun, Tokat.", zorluk: "zor", aktif: true },
  { id: "gb289", kategori: "Coğrafya", on_yuz: "Türkiye'de tiftik keçisi yetiştiriciliğinde lider il hangisidir?", arka_yuz: "Ankara.", zorluk: "orta", aktif: true },
  { id: "gb290", kategori: "Coğrafya", on_yuz: "Türkiye'de ipek böcekçiliğinde lider il hangisidir?", arka_yuz: "Diyarbakır.", zorluk: "zor", aktif: true },
  { id: "gb291", kategori: "Coğrafya", on_yuz: "Türkiye'de sığır sayısında lider il hangisidir?", arka_yuz: "Konya.", zorluk: "orta", aktif: true },
  { id: "gb292", kategori: "Coğrafya", on_yuz: "Türkiye'nin en büyük alüminyum (boksit) tesisleri nerededir?", arka_yuz: "Seydişehir (Konya).", zorluk: "zor", aktif: true },
  { id: "gb293", kategori: "Coğrafya", on_yuz: "Türkiye'nin tek fosfat çıkarılan ve işlenen yeri neresidir?", arka_yuz: "Mazıdağı (Mardin).", zorluk: "zor", aktif: true },
  { id: "gb294", kategori: "Coğrafya", on_yuz: "Dünyanın en büyük lityum rezervine sahip ülkesi hangisidir?", arka_yuz: "Bolivya.", zorluk: "orta", aktif: true },
  { id: "gb295", kategori: "Coğrafya", on_yuz: "Dünyanın en küçük ülkesi hangisidir?", arka_yuz: "Vatikan.", zorluk: "kolay", aktif: true },
  { id: "gb296", kategori: "Coğrafya", on_yuz: "Dünyanın en uzun sıradağları hangisidir?", arka_yuz: "And Dağları.", zorluk: "orta", aktif: true },
  { id: "gb297", kategori: "Coğrafya", on_yuz: "Türkiye'nin en doğusu ile en batısı arasındaki zaman farkı ne kadardır?", arka_yuz: "76 dakikadır.", zorluk: "orta", aktif: true },
  { id: "gb298", kategori: "Coğrafya", on_yuz: "Türkiye'de en fazla sınır kapısına sahip il hangisidir?", arka_yuz: "Edirne.", zorluk: "orta", aktif: true },
  { id: "gb299", kategori: "Coğrafya", on_yuz: "Türkiye'nin en kısa ve en uzun kara sınırı olan komşuları hangileridir?", arka_yuz: "En kısa: Nahçıvan (Azerbaycan). En uzun: Suriye.", zorluk: "orta", aktif: true },
  { id: "gb300", kategori: "Coğrafya", on_yuz: "Türkiye'de en çok komşusu olan il hangisidir?", arka_yuz: "Iğdır (Ermenistan, Nahçıvan/Azerbaycan, İran).", zorluk: "orta", aktif: true },

  // ── EKLENTİ 18: ANAYASA, YÜKSEK YARGI VE YÖNETİM (PDF) ──
  { id: "gb301", kategori: "Anayasa", on_yuz: "Yargıtay Başkanı kimdir?", arka_yuz: "Ömer Kerkez, 2024'te seçildi.", zorluk: "orta", aktif: true },
  { id: "gb302", kategori: "Anayasa", on_yuz: "Danıştay Başkanı kimdir?", arka_yuz: "Zeki Yiğit, 2024'te yeniden seçildi.", zorluk: "orta", aktif: true },
  { id: "gb303", kategori: "Anayasa", on_yuz: "Yüksek Seçim Kurulu (YSK) Başkanı kimdir?", arka_yuz: "Görev süresi Ocak 2026'da dolan Ahmet Yener'in yerine 6 Mayıs 2026'da Serdar Mutta seçildi.", zorluk: "zor", aktif: true },
  { id: "gb304", kategori: "Anayasa", on_yuz: "Sayıştay Başkanı kimdir?", arka_yuz: "Metin Yener.", zorluk: "orta", aktif: true },
  { id: "gb305", kategori: "Anayasa", on_yuz: "Hâkimler ve Savcılar Kurulu (HSK) Başkanı kimdir?", arka_yuz: "Adalet Bakanı kurulun doğal başkanıdır; 11 Şubat 2026'da Yılmaz Tunç'un yerine Akın Gürlek atandı.", zorluk: "orta", aktif: true },
  { id: "gb306", kategori: "Anayasa", on_yuz: "Türkiye İnsan Hakları ve Eşitlik Kurumu (TİHEK) Başkanı kimdir?", arka_yuz: "Vasip Şahin, 30 Nisan 2026'da atandı; arada Fahrettin Altun da bu görevi yürütmüştü.", zorluk: "zor", aktif: true },
  { id: "gb307", kategori: "Anayasa", on_yuz: "Kamu Başdenetçisi (Ombudsman) kimdir?", arka_yuz: "Mehmet Akarca (eski Yargıtay Başkanı), 5 Aralık 2024'te Şeref Malkoç'tan devraldı.", zorluk: "orta", aktif: true },
  { id: "gb308", kategori: "Anayasa", on_yuz: "TBMM Başkanı kimdir?", arka_yuz: "Numan Kurtulmuş (28. Dönem).", zorluk: "kolay", aktif: true },
  { id: "gb309", kategori: "Anayasa", on_yuz: "Türkiye'de Cumhurbaşkanı seçilme yaşı kaçtır?", arka_yuz: "40.", zorluk: "kolay", aktif: true },
  { id: "gb310", kategori: "Anayasa", on_yuz: "Türkiye'de milletvekili seçilme ve oy kullanma yaşı kaçtır?", arka_yuz: "Milletvekili seçilme yaşı 18 (2017 değişikliği), oy kullanma yaşı da 18'dir (1995 değişikliği).", zorluk: "kolay", aktif: true },
  { id: "gb311", kategori: "Anayasa", on_yuz: "Cumhurbaşkanının görev süresi ve seçilme sınırı nedir?", arka_yuz: "5 yıldır. Bir kişi kural olarak en fazla 2 kez Cumhurbaşkanı seçilebilir.", zorluk: "kolay", aktif: true },
  { id: "gb312", kategori: "Anayasa", on_yuz: "Olağanüstü Hal (OHAL) Cumhurbaşkanı tarafından en fazla ne kadar süre ilan edilebilir?", arka_yuz: "En fazla 6 ay.", zorluk: "orta", aktif: true },
  { id: "gb313", kategori: "Anayasa", on_yuz: "Tüzükler Türk hukuk sisteminden ne zaman kaldırıldı?", arka_yuz: "2017 Anayasa değişikliği ile hukuk sistemimizden tamamen kaldırılmıştır.", zorluk: "orta", aktif: true },
  { id: "gb314", kategori: "Anayasa", on_yuz: "Bakanlıkların kurulması ve kaldırılması nasıl düzenlenir?", arka_yuz: "2017 Anayasa değişikliği sonrası \"Cumhurbaşkanlığı Kararnamesi\" ile düzenlenir.", zorluk: "orta", aktif: true },
  { id: "gb315", kategori: "Anayasa", on_yuz: "Anayasa Mahkemesi (AYM) üye sayısı ve görev süresi nedir?", arka_yuz: "15 üyeden oluşur; üyelerin görev süresi 12 yıldır.", zorluk: "orta", aktif: true },
  { id: "gb316", kategori: "Anayasa", on_yuz: "HSK (Hâkimler ve Savcılar Kurulu) üye sayısı kaçtır?", arka_yuz: "13.", zorluk: "orta", aktif: true },
  { id: "gb317", kategori: "Anayasa", on_yuz: "Yüksek Seçim Kurulu (YSK) üye sayısı kaçtır?", arka_yuz: "7 asıl, 4 yedek olmak üzere toplam 11 üyeden oluşur.", zorluk: "orta", aktif: true },
  { id: "gb318", kategori: "Anayasa", on_yuz: "Türkiye'de seçim barajı yüzde kaçtır?", arka_yuz: "%7 (2022 değişikliği ile %10'dan düşürüldü).", zorluk: "orta", aktif: true },
  { id: "gb319", kategori: "Anayasa", on_yuz: "Belediye, büyükşehir belediyesi ve köy kurulabilmesi için gereken nüfus şartları nelerdir?", arka_yuz: "Belediye: en az 5.000. Büyükşehir belediyesi: en az 750.000. Köy: 150-2.000 arası nüfus.", zorluk: "orta", aktif: true },
  { id: "gb320", kategori: "Anayasa", on_yuz: "Siyasi partilerin mali denetimini hangi kurum yapar?", arka_yuz: "Anayasa Mahkemesi yapar; bu denetimde Sayıştay'dan yardım alır.", zorluk: "orta", aktif: true },
  { id: "gb321", kategori: "Anayasa", on_yuz: "Cumhurbaşkanlığı makamının boşalması durumunda kim vekalet eder?", arka_yuz: "Yenisi seçilene kadar Cumhurbaşkanı Yardımcısı vekalet eder.", zorluk: "orta", aktif: true },

  // ── EKLENTİ 19: UZAY, BİLİM VE TIP (PDF) ──
  { id: "gb322", kategori: "Bilim", on_yuz: "Dünyanın ilk sıtma aşısı hangisidir?", arka_yuz: "Dünya Sağlık Örgütü tarafından onaylanan Mosquirix'tir.", zorluk: "orta", aktif: true },
  { id: "gb323", kategori: "Bilim", on_yuz: "CRISPR-Cas9 teknolojisi nedir?", arka_yuz: "\"DNA makası\" olarak da bilinen, Nobel Kimya ödülü kazandıran devrim niteliğindeki gen düzenleme teknolojisidir.", zorluk: "orta", aktif: true },
  { id: "gb324", kategori: "Bilim", on_yuz: "James Webb Uzay Teleskobu nedir?", arka_yuz: "Hubble'ın yerini alan, evrenin en eski galaksilerini fotoğraflayan NASA/ESA/CSA ortak teleskobudur.", zorluk: "kolay", aktif: true },
  { id: "gb325", kategori: "Bilim", on_yuz: "Artemis Projesi nedir?", arka_yuz: "NASA'nın insanlığı (ve ilk kadını) tekrar Ay'a götürme misyonudur.", zorluk: "kolay", aktif: true },
  { id: "gb326", kategori: "Bilim", on_yuz: "Perseverance ve Ingenuity nedir?", arka_yuz: "NASA'nın Mars'a gönderdiği keşif aracı (Perseverance) ve onunla birlikte uçan ilk uzay helikopteridir (Ingenuity).", zorluk: "orta", aktif: true },
  { id: "gb327", kategori: "Bilim", on_yuz: "Tarihte çekilen ilk kara delik fotoğrafı hangi galaksiye aittir?", arka_yuz: "M87 (Messier 87) galaksisine ait. İkinci fotoğraf Samanyolu'nun merkezindeki Sagittarius A*'dır.", zorluk: "zor", aktif: true },
  { id: "gb328", kategori: "Bilim", on_yuz: "Uluslararası Uzay İstasyonu'nu (ISS) hangi ülkeler kurdu?", arka_yuz: "ABD, Rusya, Avrupa, Japonya ve Kanada uzay ajanslarının ortaklığıyla kuruldu.", zorluk: "orta", aktif: true },
  { id: "gb329", kategori: "Bilim", on_yuz: "İnsanları özel bir şirket olarak ilk kez uzaya taşıyan araç hangisidir?", arka_yuz: "SpaceX'in Crew Dragon kapsülü.", zorluk: "orta", aktif: true },
  { id: "gb330", kategori: "Bilim", on_yuz: "Dünyanın bilinen en büyük hayvanı hangisidir?", arka_yuz: "Mavi balina.", zorluk: "kolay", aktif: true },
  { id: "gb331", kategori: "Bilim", on_yuz: "Dünyanın en büyük çiçeği hangisidir?", arka_yuz: "Rafflesia Arnoldii, kötü kokusu nedeniyle \"ceset çiçeği\" olarak da bilinir.", zorluk: "orta", aktif: true },
  { id: "gb332", kategori: "Bilim", on_yuz: "Güneş'e en yakın gezegen hangisidir?", arka_yuz: "Merkür.", zorluk: "kolay", aktif: true },
  { id: "gb333", kategori: "Bilim", on_yuz: "Plüton neden gezegenlikten çıkarıldı?", arka_yuz: "2006 yılında Uluslararası Astronomi Birliği (IAU) tarafından \"Cüce Gezegen\" sınıfına dahil edildi.", zorluk: "orta", aktif: true },
  { id: "gb334", kategori: "Bilim", on_yuz: "Nobel Ödülleri nerede dağıtılır?", arka_yuz: "Fizik, Kimya, Tıp, Edebiyat ve Ekonomi ödülleri Stockholm'de (İsveç); Barış Ödülü ise Oslo'da (Norveç) verilir.", zorluk: "orta", aktif: true },
  { id: "gb335", kategori: "Bilim", on_yuz: "Hulusi Behçet kimdir?", arka_yuz: "Kendi adıyla anılan \"Behçet Hastalığı\"nı tanımlayan Türk hekimdir.", zorluk: "orta", aktif: true },
  { id: "gb336", kategori: "Bilim", on_yuz: "Gazi Yaşargil kimdir?", arka_yuz: "Dünya Nörolojik Cerrahlar Kongresi tarafından \"Yüzyılın Beyin Cerrahı\" unvanına layık görülen Türk doktordur.", zorluk: "orta", aktif: true },
  { id: "gb337", kategori: "Bilim", on_yuz: "Özlem Türeci ve Uğur Şahin kimdir?", arka_yuz: "mRNA tabanlı ilk onaylanmış COVID-19 aşısını geliştiren, BioNTech'in kurucusu Türk asıllı bilim insanlarıdır.", zorluk: "kolay", aktif: true },
  { id: "gb338", kategori: "Bilim", on_yuz: "Dünyanın en büyük parçacık fiziği laboratuvarı hangisidir?", arka_yuz: "İsviçre-Fransa sınırındaki CERN.", zorluk: "orta", aktif: true },
  { id: "gb339", kategori: "Bilim", on_yuz: "JUICE nedir?", arka_yuz: "Jüpiter'in buzlu uydularını inceleyecek Avrupa uzay aracıdır.", zorluk: "zor", aktif: true },

  // ── EKLENTİ 20: TARİHİ İLKLER VE ULUSLARARASI ANLAŞMALAR (PDF) ──
  { id: "gb340", kategori: "Tarih", on_yuz: "BM Güvenlik Konseyi'nin daimi (veto yetkili) üyeleri kimlerdir?", arka_yuz: "ABD, Rusya, Çin, İngiltere, Fransa.", zorluk: "kolay", aktif: true },
  { id: "gb341", kategori: "Dünya Gündemi", on_yuz: "Avrupa Birliği'nden ayrılan ilk ve tek ülke hangisidir?", arka_yuz: "İngiltere (Brexit süreciyle 2020'de fiilen ayrıldı).", zorluk: "kolay", aktif: true },
  { id: "gb342", kategori: "Dünya Gündemi", on_yuz: "Avrupa İnsan Hakları Mahkemesi (AİHM) merkezi neresidir?", arka_yuz: "Strazburg (Fransa).", zorluk: "orta", aktif: true },
  { id: "gb343", kategori: "Dünya Gündemi", on_yuz: "Birleşmiş Milletler'in resmi dilleri hangileridir?", arka_yuz: "İngilizce, Fransızca, Rusça, İspanyolca, Çince ve Arapça.", zorluk: "orta", aktif: true },
  { id: "gb344", kategori: "Türkiye Gündemi", on_yuz: "KKTC hangi kurumlara gözlemci üyedir?", arka_yuz: "Türk Devletleri Teşkilatı (TDT) ve İslam İşbirliği Teşkilatı (İİT).", zorluk: "orta", aktif: true },
  { id: "gb345", kategori: "Türkiye İlkleri", on_yuz: "Türkiye'nin ilk kadın büyükelçisi kimdir?", arka_yuz: "Filiz Dinçmen.", zorluk: "orta", aktif: true },
  { id: "gb346", kategori: "Türkiye İlkleri", on_yuz: "Türkiye'nin ilk kadın tiyatro oyuncusu kimdir?", arka_yuz: "Afife Jale.", zorluk: "orta", aktif: true },
  { id: "gb347", kategori: "Türkiye İlkleri", on_yuz: "Türkiye Cumhuriyeti'nin ilk Diyanet İşleri Başkanı kimdir?", arka_yuz: "Rıfat Börekçi.", zorluk: "orta", aktif: true },
  { id: "gb348", kategori: "Türkiye İlkleri", on_yuz: "Türkiye Cumhuriyeti'nin ilk Genelkurmay Başkanı kimdir?", arka_yuz: "Fevzi Çakmak.", zorluk: "orta", aktif: true },
  { id: "gb349", kategori: "Tarih", on_yuz: "TBMM'yi tanıyan ilk Müslüman devlet hangisidir?", arka_yuz: "Afganistan (Dostluk Antlaşması).", zorluk: "orta", aktif: true },
  { id: "gb350", kategori: "Tarih", on_yuz: "TBMM'yi tanıyan ilk Avrupa (Batılı) devlet hangisidir?", arka_yuz: "Sovyet Rusya (Moskova Antlaşması).", zorluk: "orta", aktif: true },
  { id: "gb351", kategori: "Tarih", on_yuz: "TBMM'yi tanıyan ilk itilaf devleti hangisidir?", arka_yuz: "Fransa (Ankara Antlaşması).", zorluk: "orta", aktif: true },
  { id: "gb352", kategori: "Tarih", on_yuz: "Osmanlı'da çıkarılan ilk resmi ve ilk özel gazete hangileridir?", arka_yuz: "İlk resmi gazete: Takvim-i Vekayi. İlk özel gazete: Tercüman-ı Ahval (Şinasi ve Agah Efendi).", zorluk: "orta", aktif: true },
  { id: "gb353", kategori: "Tarih", on_yuz: "Türk tarihindeki ilk yazılı eserler hangileridir?", arka_yuz: "Orhun Abideleri (Göktürk Kitabeleri).", zorluk: "kolay", aktif: true },
  { id: "gb354", kategori: "Tarih", on_yuz: "Tarihte bilinen ilk yazılı antlaşma hangisidir?", arka_yuz: "Hititler ile Mısır arasında imzalanan Kadeş Antlaşması'dır.", zorluk: "kolay", aktif: true },

  // ── EKLENTİ 21: ATATÜRK DÖNEMİ VE İNKILAPLAR (PDF) ──
  { id: "gb355", kategori: "Tarih", on_yuz: "Mustafa Kemal Atatürk hangi ile nüfusa kayıtlıdır?", arka_yuz: "Gaziantep.", zorluk: "orta", aktif: true },
  { id: "gb356", kategori: "Tarih", on_yuz: "Atatürk'ün \"Yarım kalan bir projem\" dediği, sonradan kurulan kurum hangisidir?", arka_yuz: "Türkkuşu.", zorluk: "zor", aktif: true },
  { id: "gb357", kategori: "Tarih", on_yuz: "Atatürk'ün katıldığı son askeri tatbikat hangisidir?", arka_yuz: "Trakya Manevraları.", zorluk: "zor", aktif: true },
  { id: "gb358", kategori: "Tarih", on_yuz: "Cumhuriyet'in ilanından sonra kurulan ilk muhalefet partisi hangisidir?", arka_yuz: "Terakkiperver Cumhuriyet Fırkası.", zorluk: "orta", aktif: true },
  { id: "gb359", kategori: "Tarih", on_yuz: "Türkiye Cumhuriyeti'nin ilk özel bankası hangisidir?", arka_yuz: "İş Bankası.", zorluk: "orta", aktif: true },
  { id: "gb360", kategori: "Tarih", on_yuz: "Medeni Kanun'un kabulünde Türkiye hangi ülkeyi örnek aldı?", arka_yuz: "İsviçre.", zorluk: "kolay", aktif: true },
  { id: "gb361", kategori: "Tarih", on_yuz: "Harf İnkılabı hangi yıl yapıldı?", arka_yuz: "1928.", zorluk: "kolay", aktif: true },
  { id: "gb362", kategori: "Tarih", on_yuz: "Soyadı Kanunu hangi yıl kabul edildi?", arka_yuz: "1934.", zorluk: "kolay", aktif: true },
  { id: "gb363", kategori: "Tarih", on_yuz: "Kadınlara seçme ve seçilme hakkı hangi sırayla verildi?", arka_yuz: "Belediye (1930), Muhtar (1933), Vekil/Milletvekili (1934).", zorluk: "orta", aktif: true },
  { id: "gb364", kategori: "Tarih", on_yuz: "Montrö Boğazlar Sözleşmesi hangi yıl imzalandı?", arka_yuz: "1936.", zorluk: "orta", aktif: true },
  { id: "gb365", kategori: "Tarih", on_yuz: "Balkan Antantı üyesi ülkeler hangileridir?", arka_yuz: "Türkiye, Yunanistan, Yugoslavya, Romanya.", zorluk: "orta", aktif: true },
  { id: "gb366", kategori: "Tarih", on_yuz: "Sadabat Paktı üyesi ülkeler hangileridir?", arka_yuz: "Türkiye, İran, Irak, Afganistan.", zorluk: "orta", aktif: true },
  { id: "gb367", kategori: "Tarih", on_yuz: "Temsil Heyeti'nin ilk siyasi başarısı nedir?", arka_yuz: "Damat Ferit Paşa hükümetinin istifa etmesi.", zorluk: "zor", aktif: true },
  { id: "gb368", kategori: "Tarih", on_yuz: "TBMM'nin çıkardığı ilk kanun nedir?", arka_yuz: "Ağnam (hayvanlardan alınan) vergisinin artırılması.", zorluk: "zor", aktif: true },
  { id: "gb369", kategori: "Tarih", on_yuz: "Mustafa Kemal'e \"Gazi\" unvanı ve \"Mareşal\" rütbesi hangi savaş sonrası verildi?", arka_yuz: "Sakarya Meydan Muharebesi sonrası.", zorluk: "orta", aktif: true },
  { id: "gb370", kategori: "Tarih", on_yuz: "Düzenli ordunun ilk askeri başarısı hangisidir?", arka_yuz: "I. İnönü Muharebesi.", zorluk: "orta", aktif: true },
  { id: "gb371", kategori: "Tarih", on_yuz: "İstiklal Marşı'nın günümüzdeki bestecisi kimdir?", arka_yuz: "Osman Zeki Üngör.", zorluk: "orta", aktif: true },
  { id: "gb372", kategori: "Tarih", on_yuz: "Hatay anavatana hangi yıl katıldı?", arka_yuz: "1939.", zorluk: "kolay", aktif: true },
  { id: "gb373", kategori: "Tarih", on_yuz: "Çok partili hayata kesintisiz geçiş hangi yıl gerçekleşti?", arka_yuz: "1946.", zorluk: "kolay", aktif: true },
  { id: "gb374", kategori: "Tarih", on_yuz: "Köy Enstitüleri hangi yıl ve kimler tarafından kuruldu?", arka_yuz: "1940 yılında Hasan Ali Yücel ve İsmail Hakkı Tonguç tarafından kuruldu.", zorluk: "orta", aktif: true },
  { id: "gb375", kategori: "Türkiye İlkleri", on_yuz: "TEMA Vakfı'nın kurucusu kimdir?", arka_yuz: "Hayrettin Karaca (Toprak Dede).", zorluk: "kolay", aktif: true },
  { id: "gb376", kategori: "Tarih", on_yuz: "Nutuk hangi yılları kapsar?", arka_yuz: "1919-1927.", zorluk: "kolay", aktif: true },
  { id: "gb377", kategori: "Tarih", on_yuz: "Atatürk'ün \"Benim Gazetem\" dediği gazete hangisidir?", arka_yuz: "İrade-i Milliye.", zorluk: "orta", aktif: true },
  { id: "gb378", kategori: "Tarih", on_yuz: "İstiklal Marşı ilk kez hangi gazete ve dergide yayımlandı?", arka_yuz: "Gazete: Hakimiyet-i Milliye. Dergi: Sebilürreşad.", zorluk: "orta", aktif: true },
  { id: "gb379", kategori: "Edebiyat/Sanat", on_yuz: "İlk yerli tiyatro eseri ve ilk yerli roman hangileridir?", arka_yuz: "İlk yerli tiyatro eseri: Şair Evlenmesi (Şinasi). İlk yerli roman: Taaşşuk-ı Talat ve Fitnat (Şemsettin Sami).", zorluk: "orta", aktif: true },

  // ── EKLENTİ 22: SANAT, EDEBİYAT VE ARKEOLOJİ (PDF) ──
  { id: "gb380", kategori: "Tarih", on_yuz: "İstiklal Marşı kime ithaf edilmiştir?", arka_yuz: "Kahraman Türk Ordusu'na.", zorluk: "orta", aktif: true },
  { id: "gb381", kategori: "Tarih", on_yuz: "Mehmet Akif Ersoy, İstiklal Marşı'nı nerede yazdı?", arka_yuz: "Taceddin Dergahı'nda.", zorluk: "orta", aktif: true },
  { id: "gb382", kategori: "Tarih", on_yuz: "İstiklal Marşı yarışmasını hangi kurum düzenledi?", arka_yuz: "Maarif Vekaleti (Milli Eğitim Bakanlığı).", zorluk: "orta", aktif: true },
  { id: "gb383", kategori: "Edebiyat/Sanat", on_yuz: "Türkiye'nin ilk kadın ressamlarından biri kimdir?", arka_yuz: "Mihri Müşfik Hanım.", zorluk: "zor", aktif: true },
  { id: "gb384", kategori: "Edebiyat/Sanat", on_yuz: "Mimar Sinan'ın çıraklık, kalfalık ve ustalık eserleri hangileridir?", arka_yuz: "Çıraklık eseri: Şehzade Camii. Kalfalık eseri: Süleymaniye Camii. Ustalık eseri: Selimiye Camii.", zorluk: "orta", aktif: true },
  { id: "gb385", kategori: "Edebiyat/Sanat", on_yuz: "UNESCO listesindeki Divriği Ulu Camii'ni hangi beylik yaptırmıştır?", arka_yuz: "Mengücekliler.", zorluk: "orta", aktif: true },
  { id: "gb386", kategori: "Tarih", on_yuz: "Arslantepe Höyüğü hangi ilimizdedir?", arka_yuz: "Malatya.", zorluk: "orta", aktif: true },
  { id: "gb387", kategori: "Tarih", on_yuz: "Çatalhöyük hangi ilimizdedir?", arka_yuz: "Konya.", zorluk: "kolay", aktif: true },
  { id: "gb388", kategori: "Tarih", on_yuz: "Ani Harabeleri hangi ilimizdedir?", arka_yuz: "Kars.", zorluk: "kolay", aktif: true },
  { id: "gb389", kategori: "Tarih", on_yuz: "Truva Antik Kenti hangi ilimizdedir?", arka_yuz: "Çanakkale.", zorluk: "kolay", aktif: true },
  { id: "gb390", kategori: "Tarih", on_yuz: "Nemrut Dağı Milli Parkı hangi ilimizdedir?", arka_yuz: "Adıyaman.", zorluk: "kolay", aktif: true },

  // ── EKLENTİ 23: TARİHİ KURUMLAR VE İLKLER (PDF) ──
  { id: "gb391", kategori: "Tarih", on_yuz: "Dünyanın ilk metrosu nerede açıldı?", arka_yuz: "Londra.", zorluk: "kolay", aktif: true },
  { id: "gb392", kategori: "Türkiye İlkleri", on_yuz: "Türkiye'nin ilk metrosu (Tünel) hangisidir?", arka_yuz: "İstanbul'da Karaköy-Beyoğlu arasında 1875'te açıldı.", zorluk: "orta", aktif: true },
  { id: "gb393", kategori: "Otomotiv/Teknoloji", on_yuz: "Türkiye'nin diğer milli sondaj gemileri hangileridir?", arka_yuz: "Fatih'in yanı sıra Yavuz, Kanuni ve Abdülhamid Han.", zorluk: "orta", aktif: true },
  { id: "gb394", kategori: "Otomotiv/Teknoloji", on_yuz: "Türkiye'nin sismik araştırma gemileri hangileridir?", arka_yuz: "Barbaros Hayreddin Paşa ve MTA Oruç Reis.", zorluk: "orta", aktif: true },
  { id: "gb395", kategori: "Türkiye Gündemi", on_yuz: "TİKA hangi bakanlığa bağlıdır?", arka_yuz: "Kültür ve Turizm Bakanlığı'na bağlıdır.", zorluk: "orta", aktif: true },
  { id: "gb396", kategori: "Türkiye Gündemi", on_yuz: "AFAD hangi bakanlığa bağlıdır?", arka_yuz: "İçişleri Bakanlığı'na bağlıdır.", zorluk: "orta", aktif: true },
  { id: "gb397", kategori: "Tarih", on_yuz: "Anadolu Ajansı'nın kurucuları kimlerdir?", arka_yuz: "Yunus Nadi ve Halide Edip Adıvar, Milli Mücadele'nin sesini duyurmak için Atatürk'ün talimatıyla kurdu.", zorluk: "orta", aktif: true },
  { id: "gb398", kategori: "Tarih", on_yuz: "Hilal-i Ahmer ve Hilal-i Ahdar Cemiyetleri günümüzde hangi isimlerle anılır?", arka_yuz: "Hilal-i Ahmer: Türk Kızılayı. Hilal-i Ahdar: Yeşilay.", zorluk: "orta", aktif: true },
  { id: "gb399", kategori: "Tarih", on_yuz: "Darülaceze (Düşkünler Evi) kimin döneminde açıldı?", arka_yuz: "II. Abdülhamid döneminde.", zorluk: "orta", aktif: true },
  { id: "gb400", kategori: "Tarih", on_yuz: "Darüşşafaka'nın kuruluş amacı nedir?", arka_yuz: "Yetim ve öksüz çocukların eğitimini sağlamak.", zorluk: "orta", aktif: true },
  { id: "gb401", kategori: "Tarih", on_yuz: "Osmanlı'nın ilk kağıt parası ve ilk madeni parası hangileridir?", arka_yuz: "İlk kağıt para: Kaime (Abdülmecit dönemi). İlk madeni para: Akçe (Osman Bey dönemi).", zorluk: "orta", aktif: true },
  { id: "gb402", kategori: "Tarih", on_yuz: "Osmanlı'nın ilk düzenli ordusu hangisidir?", arka_yuz: "Yaya ve Müsellem (Orhan Bey dönemi).", zorluk: "orta", aktif: true },
  { id: "gb403", kategori: "Tarih", on_yuz: "Türklerde ilk düzenli ordu (onluk sistem) kim tarafından kuruldu?", arka_yuz: "Mete Han (Asya Hun Devleti).", zorluk: "orta", aktif: true },
  { id: "gb404", kategori: "Tarih", on_yuz: "Cengiz Han'a itaat eden ilk Türk boyu hangisidir?", arka_yuz: "Kırgızlar.", zorluk: "zor", aktif: true },
  { id: "gb405", kategori: "Tarih", on_yuz: "Cengiz Han'a itaat eden ilk Müslüman Türk boyu hangisidir?", arka_yuz: "Karluklar (Karahanlıların da kurucu unsurudur).", zorluk: "zor", aktif: true },
  { id: "gb406", kategori: "Tarih", on_yuz: "İslamiyet'i kabul eden ilk Türk devleti hangisidir?", arka_yuz: "İtil (Volga) Bulgarları.", zorluk: "orta", aktif: true },
  { id: "gb407", kategori: "Tarih", on_yuz: "Orta Asya'da İslamiyet'i kabul eden ilk Türk devleti hangisidir?", arka_yuz: "Karahanlılar.", zorluk: "orta", aktif: true },
  { id: "gb408", kategori: "Tarih", on_yuz: "Malazgirt Savaşı'nda taraf değiştirerek Selçuklu saflarına geçen Türk boyları hangileridir?", arka_yuz: "Peçenekler ve Uzlar (Oğuzlar).", zorluk: "orta", aktif: true },
  { id: "gb409", kategori: "Tarih", on_yuz: "Anadolu'da kurulan ilk Türk beyliği hangisidir?", arka_yuz: "Saltuklular (Erzurum ve çevresi).", zorluk: "orta", aktif: true },
  { id: "gb410", kategori: "Tarih", on_yuz: "Anadolu Selçuklu Devleti'nin en parlak dönemi hangisidir?", arka_yuz: "Alaeddin Keykubat Dönemi.", zorluk: "orta", aktif: true },
  { id: "gb411", kategori: "Tarih", on_yuz: "İlk denizci Türk beyliği hangisidir?", arka_yuz: "Çaka Beyliği (İzmir).", zorluk: "orta", aktif: true },
  { id: "gb412", kategori: "Tarih", on_yuz: "Hicaz Bölgesi'ne (Mekke ve Medine'ye) egemen olan ilk Türk-İslam devleti hangisidir?", arka_yuz: "Akşitler (İhşidiler).", zorluk: "zor", aktif: true },

  // ── EKLENTİ 24: DOĞA TAKVİMİ VE DİĞER (PDF) ──
  { id: "gb413", kategori: "Türkiye İlkleri", on_yuz: "Türkiye'nin ilk milli parkı hangisidir?", arka_yuz: "Yozgat Çamlığı.", zorluk: "orta", aktif: true },
  { id: "gb414", kategori: "Türkiye İlkleri", on_yuz: "Türkiye'nin ilk tabiatı koruma alanı hangisidir?", arka_yuz: "Hacıosman Ormanı (Samsun).", zorluk: "zor", aktif: true },
  { id: "gb415", kategori: "Coğrafya", on_yuz: "Türkiye'de en çok göç veren ve en çok göç alan bölgeler hangileridir?", arka_yuz: "En çok göç veren: Karadeniz Bölgesi. En çok göç alan: Marmara Bölgesi.", zorluk: "orta", aktif: true },
  { id: "gb416", kategori: "Coğrafya", on_yuz: "Güneş enerjisinden elektrik üretimi potansiyeli en yüksek ve en düşük bölgelerimiz hangileridir?", arka_yuz: "En yüksek: Güneydoğu Anadolu. En düşük: Karadeniz (bulutluluk oranı en yüksek bölge).", zorluk: "orta", aktif: true },
  { id: "gb417", kategori: "Coğrafya", on_yuz: "\"Siyah Altın\" olarak bilinen ve Zonguldak ile özdeşleşen enerji kaynağı nedir?", arka_yuz: "Taş Kömürü.", zorluk: "kolay", aktif: true },