export interface KonuNotu {
  id: string;
  kategori: string;
  on_yuz: string;
  arka_yuz: string;
  zorluk: string;
  aktif: boolean;
}

export const konuTarihData: KonuNotu[] = [
  { id: 'tarih-1-1', kategori: 'İslamiyet Öncesi Türk Tarihi & İlk Devletler', on_yuz: 'İslamiyet\'i kabul eden ilk Türk devleti', arka_yuz: 'İtil Bulgarları', zorluk: 'orta', aktif: true },
  { id: 'tarih-1-2', kategori: 'İslamiyet Öncesi Türk Tarihi & İlk Devletler', on_yuz: 'İslamiyet\'i kabul eden ilk Türk topluluğu', arka_yuz: 'Karluklar', zorluk: 'orta', aktif: true },
  { id: 'tarih-1-3', kategori: 'İslamiyet Öncesi Türk Tarihi & İlk Devletler', on_yuz: 'Parayı kullanan ilk Türk devleti', arka_yuz: 'Göktürkler', zorluk: 'orta', aktif: true },
  { id: 'tarih-1-4', kategori: 'İslamiyet Öncesi Türk Tarihi & İlk Devletler', on_yuz: 'Kendi adına para bastıran ilk Türk devleti ve hükümdarı', arka_yuz: 'Türgişler - Baga Tarkan', zorluk: 'orta', aktif: true },
  { id: 'tarih-1-5', kategori: 'İslamiyet Öncesi Türk Tarihi & İlk Devletler', on_yuz: 'Çin kaynaklarında "Türk" kelimesinin anlamı', arka_yuz: 'Miğfer', zorluk: 'orta', aktif: true },
  { id: 'tarih-1-6', kategori: 'İslamiyet Öncesi Türk Tarihi & İlk Devletler', on_yuz: 'İslamiyet\'in yayılmasını engelleyen devletler', arka_yuz: 'Hazarlar - Türgişler', zorluk: 'orta', aktif: true },
  { id: 'tarih-1-7', kategori: 'İslamiyet Öncesi Türk Tarihi & İlk Devletler', on_yuz: 'Kendilerini Avrupa Hun Devleti\'nin varisi olarak gören devlet', arka_yuz: 'Macarlar', zorluk: 'orta', aktif: true },
  { id: 'tarih-1-8', kategori: 'İslamiyet Öncesi Türk Tarihi & İlk Devletler', on_yuz: '"Çar" unvanını kullanan ilk Türk devleti', arka_yuz: 'Tuna Bulgarları', zorluk: 'orta', aktif: true },
  { id: 'tarih-1-9', kategori: 'İslamiyet Öncesi Türk Tarihi & İlk Devletler', on_yuz: '"Tanrının Kırbacı", "Cesur Kavimlerin Efendisi" olarak bilinen Türk hükümdarı', arka_yuz: 'Atilla', zorluk: 'orta', aktif: true },
  { id: 'tarih-1-10', kategori: 'İslamiyet Öncesi Türk Tarihi & İlk Devletler', on_yuz: 'Asya Hun Devleti\'nden sonra Orta Asya\'ya hükmeden devlet', arka_yuz: 'Avarlar', zorluk: 'orta', aktif: true },
  { id: 'tarih-1-11', kategori: 'İslamiyet Öncesi Türk Tarihi & İlk Devletler', on_yuz: 'Cengiz Han\'a itaat eden ilk Müslüman Türk topluluğu', arka_yuz: 'Karluklar', zorluk: 'orta', aktif: true },
  { id: 'tarih-1-12', kategori: 'İslamiyet Öncesi Türk Tarihi & İlk Devletler', on_yuz: 'Yerleşik yaşama geçen ilk Türk devleti', arka_yuz: 'Uygurlar', zorluk: 'orta', aktif: true },
  { id: 'tarih-1-13', kategori: 'İslamiyet Öncesi Türk Tarihi & İlk Devletler', on_yuz: 'Çin eserlerinden kurtulup devlet kuran Türk devleti', arka_yuz: 'Kutluk Devleti', zorluk: 'orta', aktif: true },
  { id: 'tarih-1-14', kategori: 'İslamiyet Öncesi Türk Tarihi & İlk Devletler', on_yuz: 'Orhun Abideleri hangi ülkede yer almaktadır', arka_yuz: 'Moğolistan', zorluk: 'orta', aktif: true },
  { id: 'tarih-1-15', kategori: 'İslamiyet Öncesi Türk Tarihi & İlk Devletler', on_yuz: 'Toplumsal hiyerarşi küçükten büyüğe', arka_yuz: 'Oguş - Urug - Boy - Bodun - İl', zorluk: 'orta', aktif: true },
  { id: 'tarih-1-16', kategori: 'İslamiyet Öncesi Türk Tarihi & İlk Devletler', on_yuz: 'İslamiyet\'i kabul etmeyen tek Moğol devleti', arka_yuz: 'Kubilay Hanlığı', zorluk: 'orta', aktif: true },
  { id: 'tarih-2-1', kategori: 'Türk-İslam Tarihi & Anadolu Selçuklu', on_yuz: 'Türk-İslam tarihini başlatan savaş', arka_yuz: 'Talas Savaşı', zorluk: 'orta', aktif: true },
  { id: 'tarih-2-2', kategori: 'Türk-İslam Tarihi & Anadolu Selçuklu', on_yuz: 'İlk cami-medrese-kervansaray-posta teşkilatı örneklerini veren devlet', arka_yuz: 'Karahanlılar', zorluk: 'orta', aktif: true },
  { id: 'tarih-2-3', kategori: 'Türk-İslam Tarihi & Anadolu Selçuklu', on_yuz: 'İslamiyet\'i koruyan ilk hükümdar', arka_yuz: 'Gazneli Mahmut', zorluk: 'orta', aktif: true },
  { id: 'tarih-2-4', kategori: 'Türk-İslam Tarihi & Anadolu Selçuklu', on_yuz: 'Gazneliler döneminde yaşayan ünlü bilim adamı', arka_yuz: 'Biruni', zorluk: 'orta', aktif: true },
  { id: 'tarih-2-5', kategori: 'Türk-İslam Tarihi & Anadolu Selçuklu', on_yuz: 'Gaznelilerin yıkılmasını kolaylaştıran savaş', arka_yuz: 'Dandanakan Savaşı', zorluk: 'orta', aktif: true },
  { id: 'tarih-2-6', kategori: 'Türk-İslam Tarihi & Anadolu Selçuklu', on_yuz: '"Doğu\'nun ve Batı\'nın Sultanı" unvanı verilen hükümdar', arka_yuz: 'Tuğrul Bey', zorluk: 'orta', aktif: true },
  { id: 'tarih-2-7', kategori: 'Türk-İslam Tarihi & Anadolu Selçuklu', on_yuz: '"Ebu\'l Fetih" unvanı verilen hükümdar', arka_yuz: 'Alparslan', zorluk: 'orta', aktif: true },
  { id: 'tarih-2-8', kategori: 'Türk-İslam Tarihi & Anadolu Selçuklu', on_yuz: 'İlk Bizans-Büyük Selçuklu savaşı', arka_yuz: 'Pasinler Savaşı', zorluk: 'orta', aktif: true },
  { id: 'tarih-2-9', kategori: 'Türk-İslam Tarihi & Anadolu Selçuklu', on_yuz: 'Malazgirt Savaşı\'nın diğer adları', arka_yuz: 'Yurtaçan - Yurtkuran Savaşı', zorluk: 'orta', aktif: true },
  { id: 'tarih-2-10', kategori: 'Türk-İslam Tarihi & Anadolu Selçuklu', on_yuz: 'İlk kurulan Türk beyliği', arka_yuz: 'Saltuklular', zorluk: 'orta', aktif: true },
  { id: 'tarih-2-11', kategori: 'Türk-İslam Tarihi & Anadolu Selçuklu', on_yuz: 'En güçlü olan beylik', arka_yuz: 'Danişmentliler', zorluk: 'orta', aktif: true },
  { id: 'tarih-2-12', kategori: 'Türk-İslam Tarihi & Anadolu Selçuklu', on_yuz: 'Denizcilikle uğraşan beylik', arka_yuz: 'Çaka Beyliği', zorluk: 'orta', aktif: true },
  { id: 'tarih-2-13', kategori: 'Türk-İslam Tarihi & Anadolu Selçuklu', on_yuz: 'Ali Kuşçu hangi devletlerde yaşamıştır', arka_yuz: 'Timur - Akkoyunlu - Osmanlı', zorluk: 'orta', aktif: true },
  { id: 'tarih-2-14', kategori: 'Türk-İslam Tarihi & Anadolu Selçuklu', on_yuz: 'Azerbaycan\'ın Türkleşmesini sağlayan devlet', arka_yuz: 'Karakoyunlular', zorluk: 'orta', aktif: true },
  { id: 'tarih-2-15', kategori: 'Türk-İslam Tarihi & Anadolu Selçuklu', on_yuz: 'Kutsal bölgelere hakim olan ilk Türk-İslam devleti', arka_yuz: 'Akşitler', zorluk: 'orta', aktif: true },
  { id: 'tarih-2-16', kategori: 'Türk-İslam Tarihi & Anadolu Selçuklu', on_yuz: 'Kudüs\'ü Haçlılardan kurtaran devlet', arka_yuz: 'Eyyubiler', zorluk: 'orta', aktif: true },
  { id: 'tarih-2-17', kategori: 'Türk-İslam Tarihi & Anadolu Selçuklu', on_yuz: 'Maristan adı verilen hastaneleri yapan devlet', arka_yuz: 'Tolunoğulları', zorluk: 'orta', aktif: true },
  { id: 'tarih-2-18', kategori: 'Türk-İslam Tarihi & Anadolu Selçuklu', on_yuz: 'Bimaristan adı verilen hastaneleri yapan devlet', arka_yuz: 'Karahanlılar', zorluk: 'orta', aktif: true },
  { id: 'tarih-2-19', kategori: 'Türk-İslam Tarihi & Anadolu Selçuklu', on_yuz: 'İslamiyet\'i kabul eden ilk Moğol devleti', arka_yuz: 'Altın Orda Devleti', zorluk: 'orta', aktif: true },
  { id: 'tarih-2-20', kategori: 'Türk-İslam Tarihi & Anadolu Selçuklu', on_yuz: 'Timur\'un yıkması ile Rusların güneye inmesi kolaylaşan devlet', arka_yuz: 'Altın Orda Devleti', zorluk: 'orta', aktif: true },
  { id: 'tarih-2-21', kategori: 'Türk-İslam Tarihi & Anadolu Selçuklu', on_yuz: 'Yıkılmasıyla Anadolu Moğol istilasına açık hale gelen devlet', arka_yuz: 'Harzemşahlar', zorluk: 'orta', aktif: true },
  { id: 'tarih-2-22', kategori: 'Türk-İslam Tarihi & Anadolu Selçuklu', on_yuz: 'Anadolu\'daki ilk dini isyan', arka_yuz: 'Baba İshak İsyanı', zorluk: 'orta', aktif: true },
  { id: 'tarih-2-23', kategori: 'Türk-İslam Tarihi & Anadolu Selçuklu', on_yuz: 'Anadolu Selçuklu Devleti\'nin en parlak dönemi', arka_yuz: 'I. Alaaddin Keykubat', zorluk: 'orta', aktif: true },
  { id: 'tarih-2-24', kategori: 'Türk-İslam Tarihi & Anadolu Selçuklu', on_yuz: 'Büyük Selçuklu Devleti\'nin en parlak dönemi', arka_yuz: 'Melikşah', zorluk: 'orta', aktif: true },
  { id: 'tarih-2-25', kategori: 'Türk-İslam Tarihi & Anadolu Selçuklu', on_yuz: 'Büyük Selçuklu Devleti\'nin son hükümdarı', arka_yuz: 'Sultan Sencer', zorluk: 'orta', aktif: true },
  { id: 'tarih-2-26', kategori: 'Türk-İslam Tarihi & Anadolu Selçuklu', on_yuz: 'Büyük Selçuklu\'nun yıkılmasını hızlandıran savaş', arka_yuz: 'Katvan Savaşı', zorluk: 'orta', aktif: true },
  { id: 'tarih-2-27', kategori: 'Türk-İslam Tarihi & Anadolu Selçuklu', on_yuz: 'Anadolu Selçuklu\'nun yıkılmasını hızlandıran savaş', arka_yuz: 'Kösedağ Savaşı', zorluk: 'orta', aktif: true },
  { id: 'tarih-2-28', kategori: 'Türk-İslam Tarihi & Anadolu Selçuklu', on_yuz: 'Malazgirt ve Kösedağ savaşlarının ortak özelliği', arka_yuz: 'Beyliklerin kurulmasına yol açmıştır', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-1', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Osmanlı\'da ilk verginin adı', arka_yuz: 'Bac Vergisi', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-2', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Aşiretten Beyliğe geçiş dönemi padişahı', arka_yuz: 'Osman Bey', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-3', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Beylikten Devlete geçiş dönemi padişahı', arka_yuz: 'Orhan Bey', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-4', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Osmanlı\'ya katılan ilk beylik', arka_yuz: 'Karesioğulları', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-5', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'İlk vezir kimdir', arka_yuz: 'Alaaddin Paşa', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-6', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'İlk medrese nerede, kimin döneminde açıldı', arka_yuz: 'Orhan Bey - İznik', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-7', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'İlk müderris kimdir', arka_yuz: 'Davud-i Kayseri', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-8', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'İlk kadı kimdir', arka_yuz: 'Dursun Fakih', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-9', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Savaş alanında ölen tek Osmanlı padişahı', arka_yuz: 'I. Murat', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-10', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Türk Bayrağı\'nın şekillendiği savaş', arka_yuz: 'I. Kosova Savaşı', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-11', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'İlk Osmanlı-Haçlı savaşı', arka_yuz: 'Sırpsındığı Savaşı', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-12', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Edirne\'nin başkent oluşunu sağlayan savaş', arka_yuz: 'Sazlıdere Savaşı', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-13', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'İlk defterdar-kazasker-sadrazam ataması hangi padişah döneminde', arka_yuz: 'I. Murat', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-14', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Rumeli Beylerbeyliğini kuran padişah', arka_yuz: 'I. Murat', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-15', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Anadolu Beylerbeyliğini kuran padişah', arka_yuz: 'Yıldırım Bayezid', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-16', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Anadolu Hisarı\'nı yaptıran padişah', arka_yuz: 'Yıldırım Bayezid', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-17', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Rumeli Hisarı\'nı yaptıran padişah', arka_yuz: 'Fatih Sultan Mehmet', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-18', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'I. Bayezid\'in "Yıldırım" unvanını aldığı savaş', arka_yuz: 'Frenkyazısı Savaşı', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-19', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'I. Bayezid\'in "Sultan-ı İklim-i Rum" unvanını aldığı savaş', arka_yuz: 'Niğbolu Savaşı', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-20', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Niğbolu ganimetiyle yaptırılan cami', arka_yuz: 'Bursa Ulu Camii', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-21', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Osmanlı\'yı Fetret Devri\'ne sokan savaş', arka_yuz: 'Ankara Savaşı (1402)', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-22', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Fetret Devri\'nde taht mücadelesi veren şehzadeler', arka_yuz: 'İsa - Musa - Mehmet - Süleyman', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-23', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Fetret Devri\'nde İstanbul\'u kuşatan şehzade', arka_yuz: 'Musa Çelebi', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-24', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Osmanlı\'nın ikinci kurucusu', arka_yuz: 'Çelebi Mehmet', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-25', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'İlk dini ve sosyal içerikli isyan', arka_yuz: 'Şeyh Bedrettin İsyanı', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-26', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'İlk Osmanlı-Venedik savaşı', arka_yuz: 'Çalıbey Savaşı', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-27', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'İlk şeyhülislam ataması yapan padişah', arka_yuz: 'II. Murat', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-28', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'İstanbul\'u kuşatan padişah ve şehzadeler', arka_yuz: 'Yıldırım Bayezid - Şehzade Musa - II. Murat - II. Mehmet', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-29', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Fatih\'in alamadığı karada ve denizdeki iki yer', arka_yuz: 'Belgrad - Rodos', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-30', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Karadeniz\'in Türk gölü olmasını sağlayan bölge', arka_yuz: 'Kırım', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-31', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Fatih döneminde ticari ayrıcalık verilen devlet', arka_yuz: 'Venedik', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-32', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Kendi portresini yaptıran ilk Osmanlı padişahı', arka_yuz: 'Fatih Sultan Mehmet', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-33', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'İstanbul\'un fethinin dünya tarihi açısından üç önemi', arka_yuz: 'Rönesans - Coğrafi Keşifler - Feodalitenin zayıflaması', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-34', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Osmanlı\'da yükselme içinde duraklama dönemi', arka_yuz: 'II. Bayezid', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-35', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'II. Bayezid\'in reddettiği iki ünlü bilim insanı', arka_yuz: 'Kristof Kolomb - Leonardo Da Vinci', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-36', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'İlk avarız vergisini toplayan padişah', arka_yuz: 'II. Bayezid', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-37', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: '8 yıla 80 yıllık iş sığdıran padişah', arka_yuz: 'Yavuz Sultan Selim', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-38', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Osmanlı\'ya katılan son beylik', arka_yuz: 'Dulkadiroğulları', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-39', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Yavuz döneminde Avrupa\'da yaşanan önemli gelişme', arka_yuz: 'Reform Hareketleri', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-40', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'İlk Celali İsyanı olan Bozoklu Celal İsyanı nerede çıktı', arka_yuz: 'Tokat', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-41', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Osmanlı\'nın Orta Avrupa\'da söz sahibi olmasını sağlayan bölge', arka_yuz: 'Belgrad', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-42', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Avusturya üzerinde üstünlük sağlanan antlaşma', arka_yuz: 'İbrahim Paşa (İstanbul) Antlaşması', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-43', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'İlk Osmanlı-İran antlaşması', arka_yuz: 'Amasya Antlaşması', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-44', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'ABD Temsilciler Meclisi\'nde portresi olan padişah', arka_yuz: 'Kanuni Sultan Süleyman', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-45', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Kanuni\'nin idam ettirdiği ünlü denizci', arka_yuz: 'Piri Reis', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-46', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: '"Donanma Günü" olarak kutlanan gelişme', arka_yuz: 'Preveze Deniz Savaşı', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-47', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Akdeniz\'in Türk gölü olması hangi padişah döneminde', arka_yuz: 'Kanuni Sultan Süleyman', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-48', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Barbaros\'un katılımıyla Osmanlı mülkü sayılan ülke', arka_yuz: 'Cezayir', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-49', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Kanuni\'nin son seferi', arka_yuz: 'Zigetvar', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-50', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Savaşa gitmeyen ilk Osmanlı padişahı', arka_yuz: 'II. Selim', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-51', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'İnebahtı\'da kolunu kaybeden ünlü romancı', arka_yuz: 'Cervantes', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-52', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Sokullu\'nun 3 önemli projesi', arka_yuz: 'Don-Volga Kanalı - Süveyş Kanalı - Marmara Projesi', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-53', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Sokullu\'nun sadrazamlık yaptığı padişahlar', arka_yuz: 'Kanuni - II. Selim - III. Murat', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-54', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Takiyüddin Mehmet ilk rasathaneyi kimin döneminde yaptırdı', arka_yuz: 'III. Murat', zorluk: 'orta', aktif: true },
  { id: 'tarih-3-55', kategori: 'Osmanlı Devleti Kuruluş & Yükseliş Dönemi', on_yuz: 'Doğu ve Batı\'da en geniş sınırlara ulaşılan antlaşmalar', arka_yuz: 'Ferhat Paşa - Bucaş Antlaşmaları', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-1', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: '"Eğri Fatih" olarak bilinen padişah', arka_yuz: 'III. Mehmet', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-2', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Avusturya üzerindeki üstünlüğün başladığı ve bittiği antlaşmalar', arka_yuz: 'İbrahim Paşa - Zitvatorok Antlaşması', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-3', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Sancağa çıkma geleneğini kaldıran padişah', arka_yuz: 'III. Mehmet', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-4', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Ekber ve Erşed uygulamasını getiren padişah', arka_yuz: 'I. Ahmet', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-5', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: '"Mavi Camii" olarak bilinen cami', arka_yuz: 'Sultan Ahmet Camii', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-6', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: '"Anadolu\'nun El-Hamrası" olarak bilinen yapı', arka_yuz: 'Divriği Ulu Camii', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-7', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Doğu\'da ilk toprak kaybının yaşandığı antlaşma', arka_yuz: 'Nasuh Paşa Antlaşması', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-8', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'II. Osman\'ın Yeniçerileri kaldırma fikrini oluşturan kuşatma', arka_yuz: 'Hotin Kuşatması', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-9', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Günümüz Türkiye-İran sınırını belirleyen antlaşma', arka_yuz: 'Kasr-ı Şirin Antlaşması', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-10', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Kanatlı uçuşu gerçekleştiren tarihi kişilik', arka_yuz: 'Hezarfen Ahmet Çelebi', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-11', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Batı\'da en geniş sınırlara ulaşılan antlaşma', arka_yuz: 'Bucaş Antlaşması', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-12', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Vakayı Vakvakiye kimin döneminde yaşandı', arka_yuz: 'IV. Mehmet', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-13', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Osmanlı\'da en küçük yaşta tahta geçen padişah', arka_yuz: 'IV. Mehmet', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-14', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Viyana\'yı kuşatıp başarısız olan sadrazam', arka_yuz: 'Merzifonlu Kara Mustafa Paşa', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-15', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Batı\'da geniş çaplı ilk toprak kaybının yaşandığı antlaşma', arka_yuz: 'Karlofça Antlaşması', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-16', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Duraklama döneminde Osmanlı\'ya karşı Kutsal İttifak\'taki devletler', arka_yuz: 'Venedik - Avusturya - Rusya - Lehistan - Malta', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-17', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'III. Mustafa\'nın tahttan indirilip yerine III. Ahmet\'in getirildiği olay', arka_yuz: 'Edirne Olayı', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-18', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Osmanlı\'nın kaybettiği toprakları geri alma ümidinin doğduğu antlaşma', arka_yuz: 'Prut Antlaşması', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-19', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Osmanlı\'nın kaybettiği toprakları geri alma ümidinin bittiği antlaşma', arka_yuz: 'Pasarofça Antlaşması', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-20', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Pasarofça Antlaşması ile beraber başlayan dönem', arka_yuz: 'Lale Devri', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-21', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Lale Devri\'ni bitiren olay', arka_yuz: 'Patrona Halil İsyanı', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-22', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Bir isyanla tahta gelen ve bir isyanla tahttan indirilen padişah', arka_yuz: 'III. Ahmet', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-23', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Lale Devri\'nde ıslahat yapılan alanlar', arka_yuz: 'Din - Askeri - Yönetim - Hukuk', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-24', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Osmanlı\'nın Batı\'da kazançlı çıktığı son antlaşma', arka_yuz: 'Belgrad Antlaşması', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-25', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Belgrad Antlaşması\'nda arabulucu devlet', arka_yuz: 'Fransa', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-26', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Osmanlı\'nın denge siyasetini ilk defa uyguladığı yer', arka_yuz: 'Fransa\'nın Mısır\'ı İşgali', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-27', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Napolyon\'u Akka önlerinde durduran komutan', arka_yuz: 'Cezzar Ahmet Paşa', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-28', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Osmanlı\'ya karşı ayaklanan ilk millet', arka_yuz: 'Sırplar', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-29', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Osmanlı\'dan bağımsızlık kazanarak ayrılan ilk millet', arka_yuz: 'Rumlar (Yunanlılar)', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-30', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Osmanlı\'nın Kuzey Afrika\'daki ilk toprak kaybı', arka_yuz: 'Cezayir', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-31', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Boğazlar meselesinin başladığı antlaşma', arka_yuz: 'Hünkar İskelesi Antlaşması', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-32', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Mısır sorununun başlamasına neden olan antlaşma', arka_yuz: 'Kütahya Antlaşması', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-33', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Osmanlı\'nın İngiltere\'nin yarı sömürgesi olduğu antlaşma', arka_yuz: 'Balta Limanı Ticaret Antlaşması', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-34', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Kırım Savaşı\'nda ilk defa borç alınan ülke', arka_yuz: 'İngiltere', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-35', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Osmanlı donanmasının yakıldığı yerler sırasıyla', arka_yuz: 'İnebahtı - Çeşme - Navarin - Sinop', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-36', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Osmanlı\'nın Avrupa devleti sayıldığı antlaşma', arka_yuz: 'Paris Antlaşması (1856)', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-37', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Telgraf hattının döşendiği savaş', arka_yuz: 'Kırım Savaşı', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-38', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Namık Kemal\'in "Vatan Yahut Silistre" oyununu anlattığı savaş', arka_yuz: 'Kırım Savaşı', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-39', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: '93 Harbi\'nde Doğu\'daki önemli kadın kahraman', arka_yuz: 'Nene Hatun', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-40', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: '93 Harbi\'nde "Plevne Kahramanı"', arka_yuz: 'Gazi Osman Paşa', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-41', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Meclis tarafından onaylanmayan iki antlaşma', arka_yuz: 'Ayastefanos - Sevr', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-42', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Sırbistan\'ın bağımsız olma aşamaları', arka_yuz: 'Bükreş - Edirne - Berlin Antlaşmaları', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-43', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Mustafa Kemal\'in katılamadığı savaş (yaşı küçük)', arka_yuz: 'Dömeke Meydan Savaşı', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-44', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'İlk karantina uygulamasını getiren padişah', arka_yuz: 'II. Mahmut', zorluk: 'orta', aktif: true },
  { id: 'tarih-4-45', kategori: 'Osmanlı Duraklama & Gerileme Dönemi', on_yuz: 'Tanzimat ve Islahat Fermanlarını yayımlayan padişah', arka_yuz: 'Abdülmecid', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-1', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Kendi heykelini yaptıran ilk Osmanlı padişahı', arka_yuz: 'Abdülaziz', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-2', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Mustafa Kemal\'in "Milletin Sarayı" dediği saray', arka_yuz: 'Dolmabahçe Sarayı', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-3', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Maarifperver olarak bilinen padişah', arka_yuz: 'II. Abdülhamid', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-4', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Abdülmecid\'i devirip Abdülaziz\'i tahta çıkarmayı hedefleyen darbe', arka_yuz: 'Kuleli Olayı', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-5', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'II. Abdülhamid\'i indirip yerine V. Murat\'ı çıkarmayı hedefleyen darbe', arka_yuz: 'Çırağan Baskını', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-6', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Ertuğrul Fırkateyni hangi ülkeye gönderildi', arka_yuz: 'Japonya', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-7', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Osmanlı\'nın katıldığı ilk olimpiyatlar', arka_yuz: 'Stockholm Olimpiyatları', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-8', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Osmanlı\'da rejime karşı çıkarılan ilk isyan', arka_yuz: '31 Mart İsyanı', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-9', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Mustafa Kemal\'in tarih sahnesine ilk çıkışı', arka_yuz: '31 Mart İsyanı (Hareket Ordusu)', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-10', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'I. Meşrutiyeti ilan ettiren grup', arka_yuz: 'Genç Osmanlılar', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-11', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'II. Meşrutiyeti ilan ettiren grup', arka_yuz: 'İttihat ve Terakki', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-12', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Meclis kararıyla tahttan indirilen ilk ve ikinci padişahlar', arka_yuz: 'II. Abdülhamid - Vahdettin', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-13', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Trablusgarp Savaşı\'nda Mustafa Kemal\'in lakabı', arka_yuz: 'Gazeteci Şerif', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-14', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Dünya tarihinde ilk defa savaş uçağının kullanıldığı savaş', arka_yuz: 'Trablusgarp Savaşı', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-15', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Üçlü Antlaşma\'nın (Ouchy) imzalandığı ülke', arka_yuz: 'İsviçre', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-16', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'I. Balkan Savaşı\'nda Osmanlı\'ya saldıran devletler', arka_yuz: 'Sırbistan - Karadağ - Yunanistan - Bulgaristan', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-17', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'I. Balkan Savaşı\'ndan sonra yaşanan hükümet darbesi', arka_yuz: 'Babıali Baskını', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-18', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Babıali Baskını ile indirilen ve getirilen hükümetler', arka_yuz: 'Kamil Paşa indirildi - Mahmut Şevket Paşa getirildi', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-19', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'I. Balkan Savaşı\'nı bitiren antlaşma', arka_yuz: 'Londra Antlaşması', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-20', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'II. Balkan Savaşı\'na neden olan devlet', arka_yuz: 'Bulgaristan (çok toprak kazandığı için)', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-21', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'I. Balkan\'da olmayıp II. Balkan\'da olan devlet', arka_yuz: 'Romanya', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-22', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'I. Dünya Savaşı\'nda en karlı çıkan devletler', arka_yuz: 'İngiltere - Fransa - Japonya', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-23', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'I. Dünya Savaşı\'nda ilk çekilen ve en son katılan devletler', arka_yuz: 'Japonya - Yunanistan', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-24', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Açılan ilk cephe', arka_yuz: 'Kafkasya Cephesi', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-25', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'En çok toprak kaybının yaşandığı cephe', arka_yuz: 'Suriye - Filistin Cephesi', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-26', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: '"Ben size savaşmayı değil, ölmeyi emrediyorum." sözünün söylendiği mevzi', arka_yuz: 'Conkbayırı', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-27', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Toprak kazanan tek cephe', arka_yuz: 'Kafkasya Cephesi', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-28', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: '18 Mart Kahramanı', arka_yuz: 'Cevat Çobanlı', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-29', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Wilson İlkelerinde kurulması öngörülen devlet', arka_yuz: 'Polonya', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-30', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Yenen ve yenilen devletler arasında barış görüşmeleri konferansı', arka_yuz: 'Paris Barış Konferansı', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-31', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Osmanlı\'da ilk işgal edilen toprak', arka_yuz: 'Musul', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-32', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Anadolu\'da ilk işgal edilen toprak', arka_yuz: 'Hatay', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-33', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'İtilaf devletleri arasında ilk görüş ayrılığının olduğu yer', arka_yuz: 'Paris Barış Konferansı', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-34', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'İzmir\'in işgalinin haksız olduğunu belirten rapor', arka_yuz: 'Amiral Bristol Raporu', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-35', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Kurulan ilk cemiyet', arka_yuz: 'Kars İslam Şurası', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-36', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Kuvayı Milliye teriminin geçtiği rapor', arka_yuz: 'Dr. Esad Işık Raporu', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-37', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Amacına ulaşan zararlı cemiyetler', arka_yuz: 'Alyans İsrailit - Maccabi', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-38', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Mustafa Kemal\'in Fethi Okar ile çıkarttığı gazete', arka_yuz: 'Minber', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-39', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Milli Mücadele\'nin gerekçesi ve yönteminin belirlendiği gelişme', arka_yuz: 'Amasya Genelgesi', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-40', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Milli egemenlik ve milli bağımsızlıktan ilk bahseden yer', arka_yuz: 'Amasya Genelgesi', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-41', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Milli sınırdan ilk bahsedilen yer', arka_yuz: 'Erzurum Kongresi', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-42', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Temsil Heyetinin kurulma kararı alındığı, kurulduğu ve sayısının arttığı gelişmeler', arka_yuz: 'Amasya Genelgesi - Erzurum Kongresi - Sivas Kongresi', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-43', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Manda ve himayenin ilk reddedildiği yer', arka_yuz: 'Erzurum Kongresi', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-44', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Manda ve himayenin kesin reddedildiği yer', arka_yuz: 'Sivas Kongresi', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-45', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Sivas Kongresi\'nde Batı Cephesi\'ne atanan komutan', arka_yuz: 'Ali Fuat Cebesoy', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-46', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Damat Ferit\'in istifası üzerine göreve getirilen sadrazam', arka_yuz: 'Ali Rıza Paşa', zorluk: 'orta', aktif: true },
  { id: 'tarih-5-47', kategori: 'Osmanlı Son Dönemi & I. Dünya Savaşı', on_yuz: 'Temsil Heyetinin varlığının tanındığı ilk gelişme', arka_yuz: 'Amasya Görüşmeleri', zorluk: 'orta', aktif: true },
  { id: 'tarih-6-1', kategori: 'Kurtuluş Savaşı Cepheleri & TBMM Dönemi', on_yuz: 'Son Osmanlı Mebusan Meclisi\'nde kabul edilen karar', arka_yuz: 'Misak-ı Milli', zorluk: 'orta', aktif: true },
  { id: 'tarih-6-2', kategori: 'Kurtuluş Savaşı Cepheleri & TBMM Dönemi', on_yuz: 'Misak-ı Milli\'nin ilanından sonra işgal edilen şehir', arka_yuz: 'İstanbul', zorluk: 'orta', aktif: true },
  { id: 'tarih-6-3', kategori: 'Kurtuluş Savaşı Cepheleri & TBMM Dönemi', on_yuz: 'TBMM\'ye karşı çıkan isyanların genel amacı', arka_yuz: 'TBMM\'yi ortadan kaldırmak', zorluk: 'orta', aktif: true },
  { id: 'tarih-6-4', kategori: 'Kurtuluş Savaşı Cepheleri & TBMM Dönemi', on_yuz: 'TBMM\'ye karşı çıkan ilk isyan', arka_yuz: 'Anzavur İsyanı', zorluk: 'orta', aktif: true },
  { id: 'tarih-6-5', kategori: 'Kurtuluş Savaşı Cepheleri & TBMM Dönemi', on_yuz: 'TBMM\'ye karşı çıkan en uzun süreli isyan', arka_yuz: 'Çerkez Ethem İsyanı', zorluk: 'orta', aktif: true },
  { id: 'tarih-6-6', kategori: 'Kurtuluş Savaşı Cepheleri & TBMM Dönemi', on_yuz: 'TBMM\'ye karşı çıkan en geniş kapsamlı isyan', arka_yuz: 'Koçgiri İsyanı', zorluk: 'orta', aktif: true },
  { id: 'tarih-6-7', kategori: 'Kurtuluş Savaşı Cepheleri & TBMM Dönemi', on_yuz: 'Düzenli ordunun kazandığı ilk savaş', arka_yuz: 'I. İnönü Savaşı', zorluk: 'orta', aktif: true },
  { id: 'tarih-6-8', kategori: 'Kurtuluş Savaşı Cepheleri & TBMM Dönemi', on_yuz: 'Düzenli ordunun kaybettiği ilk ve tek savaş', arka_yuz: 'Kütahya-Eskişehir Savaşları', zorluk: 'orta', aktif: true },
  { id: 'tarih-6-9', kategori: 'Kurtuluş Savaşı Cepheleri & TBMM Dönemi', on_yuz: 'TBMM\'nin uluslararası alanda ilk siyasi başarısı', arka_yuz: 'Gümrü Antlaşması', zorluk: 'orta', aktif: true },
  { id: 'tarih-6-10', kategori: 'Kurtuluş Savaşı Cepheleri & TBMM Dönemi', on_yuz: 'TBMM\'yi resmi olarak tanıyan ilk devlet', arka_yuz: 'Ermenistan', zorluk: 'orta', aktif: true },
  { id: 'tarih-6-11', kategori: 'Kurtuluş Savaşı Cepheleri & TBMM Dönemi', on_yuz: 'Doğu Cephesi\'nin kapanmasını sağlayan antlaşma', arka_yuz: 'Gümrü Antlaşması', zorluk: 'orta', aktif: true },
  { id: 'tarih-6-12', kategori: 'Kurtuluş Savaşı Cepheleri & TBMM Dönemi', on_yuz: 'Sovyet Rusya ile imzalanan ilk antlaşma', arka_yuz: 'Moskova Antlaşması', zorluk: 'orta', aktif: true },
  { id: 'tarih-6-13', kategori: 'Kurtuluş Savaşı Cepheleri & TBMM Dönemi', on_yuz: 'Misak-ı Milli\'yi tanıyan ilk büyük devlet', arka_yuz: 'Sovyet Rusya', zorluk: 'orta', aktif: true },
  { id: 'tarih-6-14', kategori: 'Kurtuluş Savaşı Cepheleri & TBMM Dönemi', on_yuz: 'İstiklal Marşı\'nın kabul edildiği savaş sonrası', arka_yuz: 'I. İnönü Savaşı', zorluk: 'orta', aktif: true },
  { id: 'tarih-6-15', kategori: 'Kurtuluş Savaşı Cepheleri & TBMM Dönemi', on_yuz: 'Londra Konferansı\'na TBMM\'nin çağrıldığı dönem', arka_yuz: 'I. İnönü Savaşı sonrası', zorluk: 'orta', aktif: true },
  { id: 'tarih-6-16', kategori: 'Kurtuluş Savaşı Cepheleri & TBMM Dönemi', on_yuz: 'Afganistan ile dostluk antlaşmasının imzalandığı dönem', arka_yuz: 'I. İnönü Savaşı sonrası', zorluk: 'orta', aktif: true },
  { id: 'tarih-6-17', kategori: 'Kurtuluş Savaşı Cepheleri & TBMM Dönemi', on_yuz: 'Teşkilat-ı Esasiye Kanunu\'nun kabul edildiği yıl', arka_yuz: '1921', zorluk: 'orta', aktif: true },
  { id: 'tarih-6-18', kategori: 'Kurtuluş Savaşı Cepheleri & TBMM Dönemi', on_yuz: 'Başkomutanlık Kanunu hangi savaş öncesinde çıkarıldı', arka_yuz: 'Sakarya Meydan Muharebesi', zorluk: 'orta', aktif: true },
  { id: 'tarih-6-19', kategori: 'Kurtuluş Savaşı Cepheleri & TBMM Dönemi', on_yuz: 'Mustafa Kemal\'e mareşallik ve gazilik verilen savaş', arka_yuz: 'Sakarya Meydan Muharebesi', zorluk: 'orta', aktif: true },
  { id: 'tarih-6-20', kategori: 'Kurtuluş Savaşı Cepheleri & TBMM Dönemi', on_yuz: '"Hattı müdafaa yoktur, sathı müdafaa vardır." sözü hangi savaşta söylendi', arka_yuz: 'Sakarya Meydan Muharebesi', zorluk: 'orta', aktif: true },
  { id: 'tarih-6-21', kategori: 'Kurtuluş Savaşı Cepheleri & TBMM Dönemi', on_yuz: 'Türk ordusunun taarruza geçtiği son savunma savaşı', arka_yuz: 'Büyük Taarruz', zorluk: 'orta', aktif: true },
  { id: 'tarih-6-22', kategori: 'Kurtuluş Savaşı Cepheleri & TBMM Dönemi', on_yuz: 'Kurtuluş Savaşı\'nın son muharebesi', arka_yuz: 'Başkomutanlık Meydan Muharebesi (Dumlupınar)', zorluk: 'orta', aktif: true },
  { id: 'tarih-6-23', kategori: 'Kurtuluş Savaşı Cepheleri & TBMM Dönemi', on_yuz: 'Kurtuluş Savaşı\'nın askeri safhasını bitiren antlaşma', arka_yuz: 'Mudanya Ateşkes Antlaşması', zorluk: 'orta', aktif: true },
  { id: 'tarih-6-24', kategori: 'Kurtuluş Savaşı Cepheleri & TBMM Dönemi', on_yuz: 'İstanbul, Boğazlar ve Doğu Trakya\'nın savaşılmadan alınmasını sağlayan antlaşma', arka_yuz: 'Mudanya Ateşkes Antlaşması', zorluk: 'orta', aktif: true },
  { id: 'tarih-6-25', kategori: 'Kurtuluş Savaşı Cepheleri & TBMM Dönemi', on_yuz: 'Lozan Konferansı\'na TBMM adına baş delege', arka_yuz: 'İsmet Paşa', zorluk: 'orta', aktif: true },
  { id: 'tarih-6-26', kategori: 'Kurtuluş Savaşı Cepheleri & TBMM Dönemi', on_yuz: 'Lozan görüşmeleri sırasında kaldırılan kurum', arka_yuz: 'Saltanat', zorluk: 'orta', aktif: true },
  { id: 'tarih-6-27', kategori: 'Kurtuluş Savaşı Cepheleri & TBMM Dönemi', on_yuz: 'Yeni Türk Devleti\'nin uluslararası alanda tanınmasını sağlayan antlaşma', arka_yuz: 'Lozan Antlaşması', zorluk: 'orta', aktif: true },
  { id: 'tarih-6-28', kategori: 'Kurtuluş Savaşı Cepheleri & TBMM Dönemi', on_yuz: 'Lozan\'da çözülemeyen ve sonraya bırakılan konu', arka_yuz: 'Musul Sorunu', zorluk: 'orta', aktif: true },
  { id: 'tarih-6-29', kategori: 'Kurtuluş Savaşı Cepheleri & TBMM Dönemi', on_yuz: 'Lozan\'da Türkiye\'nin istediği gibi çözülemeyen konu', arka_yuz: 'Boğazlar Meselesi', zorluk: 'orta', aktif: true },
  { id: 'tarih-6-30', kategori: 'Kurtuluş Savaşı Cepheleri & TBMM Dönemi', on_yuz: 'Cumhuriyetin ilan tarihi', arka_yuz: '29 Ekim 1923', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-1', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Cumhuriyetin ilanından sonra kurulan ilk muhalefet partisi', arka_yuz: 'Terakkiperver Cumhuriyet Fırkası', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-2', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Çok partili hayata geçişte kurulan ikinci muhalefet partisi', arka_yuz: 'Serbest Cumhuriyet Fırkası', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-3', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Cumhuriyet dönemindeki ilk çok partili hayat denemesi', arka_yuz: 'Terakkiperver Cumhuriyet Fırkası', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-4', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Şeyh Sait İsyanı hangi dönemde çıkmıştır', arka_yuz: 'Cumhuriyet Dönemi', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-5', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Takrir-i Sükun Kanunu hangi isyan sonrası çıkarıldı', arka_yuz: 'Şeyh Sait İsyanı', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-6', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'İzmir Suikastı girişimi hangi yıl', arka_yuz: '1926', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-7', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Kabotaj Kanunu hangi yıl kabul edildi', arka_yuz: '1926', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-8', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Medeni Kanun hangi ülkeden alınmıştır', arka_yuz: 'İsviçre', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-9', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Ceza Kanunu hangi ülkeden alınmıştır', arka_yuz: 'İtalya', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-10', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Ticaret Kanunu hangi ülkeden alınmıştır', arka_yuz: 'Almanya', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-11', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'İlk nüfus sayımı hangi yıl yapıldı', arka_yuz: '1927', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-12', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Harf İnkılabı hangi yıl yapıldı', arka_yuz: '1928', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-13', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Millet Mektepleri hangi amaçla açılmıştır', arka_yuz: 'Yeni harfleri öğretmek', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-14', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Kadınlara belediye seçimlerinde hak verildiği yıl', arka_yuz: '1930', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-15', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Kadınlara muhtarlık seçimlerinde hak verildiği yıl', arka_yuz: '1933', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-16', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Kadınlara milletvekili seçme ve seçilme hakkı verildiği yıl', arka_yuz: '1934', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-17', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Soyadı Kanunu hangi yıl çıkarıldı', arka_yuz: '1934', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-18', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Atatürk soyadının verildiği tarih', arka_yuz: '24 Kasım 1934', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-19', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'İlk Türk Tarih Kongresi hangi yıl yapıldı', arka_yuz: '1932', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-20', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Atatürk\'ün ölüm tarihi', arka_yuz: '10 Kasım 1938', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-21', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'II. Dünya Savaşı sırasında Türkiye\'nin cumhurbaşkanı', arka_yuz: 'İsmet İnönü', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-22', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Türkiye\'nin II. Dünya Savaşı\'na fiilen katılma kararı aldığı tarih', arka_yuz: '23 Şubat 1945', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-23', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Türkiye\'nin NATO\'ya üye olduğu yıl', arka_yuz: '1952', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-24', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'NATO\'ya girişte etkili olan savaş', arka_yuz: 'Kore Savaşı', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-25', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Çok partili hayata geçildikten sonra iktidara gelen ilk parti', arka_yuz: 'Demokrat Parti', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-26', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Demokrat Parti\'nin iktidara geldiği yıl', arka_yuz: '1950', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-27', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Türkiye\'nin ilk kadın başbakanı', arka_yuz: 'Tansu Çiller', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-28', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Türkiye Cumhuriyeti\'nin ilk başbakanı', arka_yuz: 'İsmet İnönü', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-29', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Cumhuriyet döneminin ilk cumhurbaşkanı', arka_yuz: 'Mustafa Kemal Atatürk', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-30', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Türkiye\'nin Avrupa Konseyi\'ne üye olduğu yıl', arka_yuz: '1949', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-31', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Birleşmiş Milletler\'in kuruluş tarihi', arka_yuz: '1945', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-32', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Türkiye\'nin BM\'ye katıldığı yıl', arka_yuz: '1945', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-33', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Avrupa Ekonomik Topluluğu\'nu (AET) kuran antlaşma', arka_yuz: 'Roma Antlaşması', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-34', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Türkiye\'nin AB\'ye tam üyelik başvurusu yaptığı yıl', arka_yuz: '1987', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-35', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Türkiye\'nin AB aday ülke ilan edildiği zirve', arka_yuz: 'Helsinki Zirvesi (1999)', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-36', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Türkiye\'nin ilk yerli otomobili', arka_yuz: 'Devrim', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-37', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'GAP\'ın açılımı', arka_yuz: 'Güneydoğu Anadolu Projesi', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-38', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Türkiye\'nin ilk yerli haberleşme uydusu', arka_yuz: 'TÜRKSAT 6A', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-39', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Türkiye\'nin ilk milli savaş gemisi projesi', arka_yuz: 'MİLGEM', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-40', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Türkiye\'nin ilk milli tank projesi', arka_yuz: 'ALTAY', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-41', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Türk Devletleri Teşkilatı\'nın eski adı', arka_yuz: 'Türk Konseyi', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-42', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Türk Devletleri Teşkilatı\'nın merkezi', arka_yuz: 'İstanbul', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-43', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Türkiye\'nin ilk nükleer santrali', arka_yuz: 'Akkuyu Nükleer Güç Santrali', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-44', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'İlk Türk Nobel ödüllü yazar', arka_yuz: 'Orhan Pamuk', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-45', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'İlk Türk Nobel ödüllü bilim insanı', arka_yuz: 'Aziz Sancar', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-46', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'UNESCO Dünya Miras Listesi\'ne giren ilk Türk varlığı', arka_yuz: 'Divriği Ulu Camii ve Darüşşifası', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-47', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Türkiye\'nin ilk milli insansız savaş uçağı', arka_yuz: 'Bayraktar KIZILELMA', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-48', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'TBMM\'nin açılış tarihi', arka_yuz: '23 Nisan 1920', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-49', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'İlk anayasa', arka_yuz: 'Teşkilat-ı Esasiye Kanunu (1921)', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-50', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Cumhuriyet döneminin ilk anayasası', arka_yuz: '1924 Anayasası', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-51', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Halifeliğin kaldırıldığı tarih', arka_yuz: '3 Mart 1924', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-52', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Tevhid-i Tedrisat Kanunu\'nun kabul tarihi', arka_yuz: '3 Mart 1924', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-53', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Şeriye ve Evkaf Vekâleti\'nin kaldırıldığı tarih', arka_yuz: '3 Mart 1924', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-54', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Aşar vergisinin kaldırıldığı yıl', arka_yuz: '1925', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-55', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Milletler Cemiyeti\'ne giriş yılı', arka_yuz: '1932', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-56', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Balkan Antantı\'nın imzalandığı yıl', arka_yuz: '1934', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-57', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Sadabat Paktı\'nın imzalandığı yıl', arka_yuz: '1937', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-58', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Hatay\'ın anavatana katıldığı yıl', arka_yuz: '1939', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-59', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Montrö Boğazlar Sözleşmesi\'nin imzalandığı yıl', arka_yuz: '1936', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-60', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Atatürk\'ün son başbakanı', arka_yuz: 'Celal Bayar', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-61', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Türkiye\'nin ilk muhalefet partisi', arka_yuz: 'Terakkiperver Cumhuriyet Fırkası (Vecihi Hürkuş da katılmıştır)', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-62', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Türkiye\'nin ilk yerli uçağını yapan kişi', arka_yuz: 'Vecihi Hürkuş', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-63', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'İlk Türk kadın savaş pilotu', arka_yuz: 'Sabiha Gökçen', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-64', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Türk Tarih Kurumu\'nun kuruluş yılı', arka_yuz: '1931', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-65', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Türk Dil Kurumu\'nun kuruluş yılı', arka_yuz: '1932', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-66', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Soyadı Kanunu ile Mustafa Kemal\'e verilen soyadı', arka_yuz: 'Atatürk', zorluk: 'orta', aktif: true },
  { id: 'tarih-7-67', kategori: 'Atatürk Dönemi İnkılapları & Cumhuriyet', on_yuz: 'Atatürk\'ün naaşı ilk olarak defnedildiği yer', arka_yuz: 'Etnografya Müzesi', zorluk: 'orta', aktif: true },
  { id: 'tarih-8-1', kategori: 'Çağdaş Türk Tarihi & Güncel Olaylar', on_yuz: 'Bilge Kral olarak bilinen kişi', arka_yuz: 'Aliya İzzetbegoviç', zorluk: 'orta', aktif: true },
  { id: 'tarih-8-2', kategori: 'Çağdaş Türk Tarihi & Güncel Olaylar', on_yuz: 'Arap Baharı ilk olarak hangi ülkede çıktı', arka_yuz: 'Tunus', zorluk: 'orta', aktif: true },
  { id: 'tarih-8-3', kategori: 'Çağdaş Türk Tarihi & Güncel Olaylar', on_yuz: 'Arap Baharı\'nın diğer adları', arka_yuz: 'Twitter Devrimi, Facebook Devrimi, Yasemin Devrimi', zorluk: 'orta', aktif: true },
  { id: 'tarih-8-4', kategori: 'Çağdaş Türk Tarihi & Güncel Olaylar', on_yuz: 'En genç profesör lakaplı kişi', arka_yuz: 'Oktay Sinanoğlu', zorluk: 'orta', aktif: true },
  { id: 'tarih-8-5', kategori: 'Çağdaş Türk Tarihi & Güncel Olaylar', on_yuz: 'Yüzyılın Beyin Cerrahı', arka_yuz: 'Gazi Yaşargil', zorluk: 'orta', aktif: true },
  { id: 'tarih-8-6', kategori: 'Çağdaş Türk Tarihi & Güncel Olaylar', on_yuz: 'Nobel Kimya Ödülü\'nü alan Türk', arka_yuz: 'Aziz Sancar', zorluk: 'orta', aktif: true },
  { id: 'tarih-8-7', kategori: 'Çağdaş Türk Tarihi & Güncel Olaylar', on_yuz: 'Nobel Edebiyat Ödülü\'nü alan Türk', arka_yuz: 'Orhan Pamuk', zorluk: 'orta', aktif: true },
  { id: 'tarih-8-8', kategori: 'Çağdaş Türk Tarihi & Güncel Olaylar', on_yuz: 'Cep Herkülü olarak bilinen sporcu', arka_yuz: 'Naim Süleymanoğlu', zorluk: 'orta', aktif: true },
  { id: 'tarih-8-9', kategori: 'Çağdaş Türk Tarihi & Güncel Olaylar', on_yuz: 'NATO\'ya üye olan son devlet', arka_yuz: 'Kuzey Makedonya', zorluk: 'orta', aktif: true },
  { id: 'tarih-8-10', kategori: 'Çağdaş Türk Tarihi & Güncel Olaylar', on_yuz: 'BM\'ye üye olan son devlet', arka_yuz: 'Güney Sudan', zorluk: 'orta', aktif: true },
  { id: 'tarih-8-11', kategori: 'Çağdaş Türk Tarihi & Güncel Olaylar', on_yuz: 'AB\'ye üye olan son devlet', arka_yuz: 'Hırvatistan', zorluk: 'orta', aktif: true },
  { id: 'tarih-8-12', kategori: 'Çağdaş Türk Tarihi & Güncel Olaylar', on_yuz: 'AB\'den ayrılan devlet', arka_yuz: 'İngiltere', zorluk: 'orta', aktif: true },
  { id: 'tarih-8-13', kategori: 'Çağdaş Türk Tarihi & Güncel Olaylar', on_yuz: 'OPEC\'ten ayrılan devlet', arka_yuz: 'Katar', zorluk: 'orta', aktif: true },
  { id: 'tarih-8-14', kategori: 'Çağdaş Türk Tarihi & Güncel Olaylar', on_yuz: 'Türk-Ermeni meselesini yumuşatma diplomasisi', arka_yuz: 'Peynir Diplomasisi', zorluk: 'orta', aktif: true },
  { id: 'tarih-8-15', kategori: 'Çağdaş Türk Tarihi & Güncel Olaylar', on_yuz: '"Türk" kelimesini kullandığı için cezalandırılan kişi', arka_yuz: 'Dr. Sadık Ahmet', zorluk: 'orta', aktif: true },
  { id: 'tarih-8-16', kategori: 'Çağdaş Türk Tarihi & Güncel Olaylar', on_yuz: 'Dünyanın en çok satan albümü kime aittir', arka_yuz: 'Madonna', zorluk: 'orta', aktif: true },
  { id: 'tarih-8-17', kategori: 'Çağdaş Türk Tarihi & Güncel Olaylar', on_yuz: 'Dünyanın en çok satılan kitabı', arka_yuz: 'Harry Potter', zorluk: 'orta', aktif: true },
  { id: 'tarih-8-18', kategori: 'Çağdaş Türk Tarihi & Güncel Olaylar', on_yuz: 'Klonlanan ilk hayvan', arka_yuz: 'Koyun (Dolly)', zorluk: 'orta', aktif: true },
  { id: 'tarih-8-19', kategori: 'Çağdaş Türk Tarihi & Güncel Olaylar', on_yuz: 'Çernobil faciasının yaşandığı ülke', arka_yuz: 'Ukrayna', zorluk: 'orta', aktif: true },
  { id: 'tarih-8-20', kategori: 'Çağdaş Türk Tarihi & Güncel Olaylar', on_yuz: 'Arap Baharı\'ndan etkilenmeyen ülke', arka_yuz: 'Fas', zorluk: 'orta', aktif: true },
  { id: 'tarih-8-21', kategori: 'Çağdaş Türk Tarihi & Güncel Olaylar', on_yuz: 'Halkı tarafından linç edilerek öldürülen devlet başkanı', arka_yuz: 'Muammer Kaddafi', zorluk: 'orta', aktif: true },
  { id: 'tarih-8-22', kategori: 'Çağdaş Türk Tarihi & Güncel Olaylar', on_yuz: 'İsrail işgaline karşı Filistin\'de başlatılan ayaklanmanın adı', arka_yuz: 'İntifada', zorluk: 'orta', aktif: true },
  { id: 'tarih-8-23', kategori: 'Çağdaş Türk Tarihi & Güncel Olaylar', on_yuz: 'ABD\'nin 1991\'de Irak\'a yaptığı operasyonun adı', arka_yuz: 'Çöl Fırtınası Operasyonu', zorluk: 'orta', aktif: true },
  { id: 'tarih-8-24', kategori: 'Çağdaş Türk Tarihi & Güncel Olaylar', on_yuz: 'Kosova\'nın bağımsızlığını tanıyan ilk devlet', arka_yuz: 'Kostarika', zorluk: 'orta', aktif: true },
  { id: 'tarih-8-25', kategori: 'Çağdaş Türk Tarihi & Güncel Olaylar', on_yuz: 'Türkiye\'nin AB ile yaptığı ilk antlaşma', arka_yuz: '1963 Ankara Antlaşması', zorluk: 'orta', aktif: true },
  { id: 'tarih-8-26', kategori: 'Çağdaş Türk Tarihi & Güncel Olaylar', on_yuz: 'Dağlık Karabağ sorunu hangi iki ülke arasında', arka_yuz: 'Ermenistan - Azerbaycan', zorluk: 'orta', aktif: true },
  { id: 'tarih-8-27', kategori: 'Çağdaş Türk Tarihi & Güncel Olaylar', on_yuz: '2019\'da başkenti değişen Orta Asya ülkesi', arka_yuz: 'Kazakistan', zorluk: 'orta', aktif: true },
  { id: 'tarih-8-28', kategori: 'Çağdaş Türk Tarihi & Güncel Olaylar', on_yuz: 'Dünyaca ünlü Kırgız yazar', arka_yuz: 'Cengiz Aytmatov', zorluk: 'orta', aktif: true },
  { id: 'tarih-8-29', kategori: 'Çağdaş Türk Tarihi & Güncel Olaylar', on_yuz: 'SSCB\'den ayrılan ilk devlet', arka_yuz: 'Gürcistan', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-1', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Yıldız Savaşları projesi hangi ülkeye aitti', arka_yuz: 'ABD', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-2', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Dünya Vatandaşı ödülünü alan Rus yarbay', arka_yuz: 'Stanislav Petrov', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-3', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Suikast sonucu öldürülen başbakan', arka_yuz: 'Nihat Erim', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-4', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Yüce Divan\'a sevk edilen başbakan', arka_yuz: 'Mesut Yılmaz', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-5', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'İdam edilen başbakan', arka_yuz: 'Adnan Menderes', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-6', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Türkiye\'nin Kıbrıs\'a yaptığı operasyonun adı', arka_yuz: 'Atilla Harekatı', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-7', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Uzaya çıkan ilk insan', arka_yuz: 'Yuri Gagarin', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-8', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Ay\'a ayak basan ilk insan', arka_yuz: 'Neil Armstrong', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-9', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Uzaya çıkan ilk kadın', arka_yuz: 'Valentina Tereşkova', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-10', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Kıbrıs Rumlarının kurduğu örgüt', arka_yuz: 'EOKA', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-11', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Kıbrıs Türklerinin kurduğu örgüt', arka_yuz: 'Türk Mukavemet Teşkilatı (TMT) - Volkan', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-12', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'İran\'ın İsrail aracılığıyla ABD\'den silah almasına verilen ad', arka_yuz: 'İrangate Olayı', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-13', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Küba olayında ABD ile SSCB arasındaki telefon hattı', arka_yuz: 'Kırmızı Telefon Hattı', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-14', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'SALT-II Antlaşması\'nın onaylanamama nedeni', arka_yuz: 'SSCB\'nin Afganistan\'ı işgali', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-15', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Avrupa Konseyi\'nin merkezi', arka_yuz: 'Strazburg', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-16', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'UNESCO\'nun merkezi', arka_yuz: 'Paris', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-17', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Avrupa İnsan Hakları Mahkemesi\'nin merkezi', arka_yuz: 'Strazburg', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-18', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'NATO\'nun merkezi', arka_yuz: 'Brüksel', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-19', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Birleşmiş Milletler\'in merkezi', arka_yuz: 'New York', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-20', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Avrupa Birliği\'nin para birimi', arka_yuz: 'Euro', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-21', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Avrupa Birliği\'nin bayrağındaki yıldız sayısı', arka_yuz: '12', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-22', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Avrupa Birliği\'nin marşı', arka_yuz: 'Neşeye Övgü (Ode to Joy)', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-23', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Berlin Duvarı hangi yıl yıkıldı', arka_yuz: '1989', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-24', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'SSCB hangi yıl dağıldı', arka_yuz: '1991', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-25', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Soğuk Savaş\'ın sembol duvarı', arka_yuz: 'Berlin Duvarı', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-26', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Körfez Savaşı hangi yıl başladı', arka_yuz: '1991', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-27', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Avrupa Birliği\'ni bugünkü adıyla kuran antlaşma', arka_yuz: 'Maastricht Antlaşması', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-28', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Avrupa Kömür ve Çelik Topluluğu kaç ülke tarafından kurulmuştur', arka_yuz: '6', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-29', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Schengen Antlaşması\'nın amacı', arka_yuz: 'Serbest dolaşım', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-30', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Dünyanın en büyük uluslararası örgütü', arka_yuz: 'Birleşmiş Milletler', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-31', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'BM\'nin kurucu antlaşmasının adı', arka_yuz: 'BM Şartı', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-32', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'BM Güvenlik Konseyi\'nin daimi üye sayısı', arka_yuz: '5', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-33', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'BM Güvenlik Konseyi\'nde veto hakkı bulunanlar', arka_yuz: 'Daimi Üyeler', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-34', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Dünyanın en büyük ekonomisine sahip ülkesi', arka_yuz: 'ABD', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-35', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Yüzölçümü bakımından en büyük ülke', arka_yuz: 'Rusya', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-36', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Nüfus bakımından en kalabalık ülke', arka_yuz: 'Hindistan', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-37', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Dünyanın en uzun nehri', arka_yuz: 'Nil Nehri', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-38', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Dünyanın en yüksek dağı', arka_yuz: 'Everest', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-39', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Dünyanın en büyük okyanusu', arka_yuz: 'Büyük Okyanus (Pasifik)', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-40', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Küreselleşmenin hız kazandığı dönem', arka_yuz: '21. yüzyılın sonları', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-41', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'İnternetin yaygınlaşmasıyla ortaya çıkan toplum modeli', arka_yuz: 'Bilgi Toplumu', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-42', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'İlk yapay uydu', arka_yuz: 'Sputnik-1', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-43', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'İlk cep telefonunu geliştiren şirket', arka_yuz: 'Motorola', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-44', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Dünya Sağlık Örgütü\'nün kısa adı', arka_yuz: 'WHO', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-45', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'UNICEF\'in açılımı', arka_yuz: 'Birleşmiş Milletler Çocuklara Yardım Fonu', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-46', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Uluslararası Para Fonu\'nun kısa adı', arka_yuz: 'IMF', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-47', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Dünya Bankası\'nın merkezi', arka_yuz: 'Washington D.C.', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-48', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'OPEC\'in açılımı', arka_yuz: 'Petrol İhraç Eden Ülkeler Örgütü', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-49', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Türk Devletleri Teşkilatı\'nın ilk genel sekreteri', arka_yuz: 'Halil Akıncı', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-50', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Türk Devletleri Teşkilatı\'nın gözlemci üyesi Avrupa ülkesi', arka_yuz: 'Macaristan', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-51', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'AGİT\'in merkezi', arka_yuz: 'Viyana', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-52', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Dünya Ticaret Örgütü\'nün kısa adı', arka_yuz: 'DTÖ (WTO)', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-53', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Dünya Ticaret Örgütü\'nün merkezi', arka_yuz: 'Cenevre', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-54', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Uluslararası Adalet Divanı\'nın merkezi', arka_yuz: 'Lahey', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-55', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Avrupa Parlamentosu seçimleri kaç yılda bir yapılır', arka_yuz: '5 yılda bir', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-56', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Avrupa Birliği\'ni yürüten organ', arka_yuz: 'Avrupa Komisyonu', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-57', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Avrupa Birliği\'nin yasama organı', arka_yuz: 'Avrupa Parlamentosu', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-58', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Dünya Çevre Günü hangi tarihte kutlanır', arka_yuz: '5 Haziran', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-59', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Birleşmiş Milletler Günü hangi tarihte kutlanır', arka_yuz: '24 Ekim', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-60', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Avrupa Günü hangi tarihte kutlanır', arka_yuz: '9 Mayıs', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-61', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Dünya Barış Günü hangi tarihte kutlanır', arka_yuz: '21 Eylül', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-62', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Nobel Barış Ödülü hangi ülkede verilir', arka_yuz: 'Norveç', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-63', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Nobel Ödülleri hangi ülkenin vasiyetiyle ortaya çıkmıştır', arka_yuz: 'İsveç', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-64', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'İlk Türk astronot', arka_yuz: 'Alper Gezeravcı', zorluk: 'orta', aktif: true },
  { id: 'tarih-9-65', kategori: 'Dünya Tarihi & Uluslararası Örgütler', on_yuz: 'Uluslararası Uzay İstasyonu\'na çıkan ilk Türk', arka_yuz: 'Alper Gezeravcı', zorluk: 'orta', aktif: true },
];
