export interface Soru {
  id: number;
  metin: string;
  secenekler: string[];
  dogruCevap: string;
  aciklama: string;
}

export const DENEME1_BASLIK = 'Deneme 1';
export const DENEME1_KONU = 'Paylar ve Pay Benzeri Menkul Kıymetler';

export const DENEME1: Soru[] = [
  { id: 1, metin: "Bir şirketin finansal tablolarında zarar bulunmaması veya yapılacak sermaye azaltım tutarının mevcut zarardan yüksek olması durumunda, sermaye azaltımına paralel olarak alınan sermaye artırım kararının asgari miktarı ne olmalıdır?", secenekler: ["Zarar tutarı kadar", "Sermaye azaltım tutarı kadar", "Aradaki fark kadar", "Şirketin ödenmiş sermayesi kadar", "Kurulun belirleyeceği tutar kadar"], dogruCevap: "Aradaki fark kadar", aciklama: "Azaltım zarardan büyükse, fark kadar artırım zorunludur." },
  { id: 2, metin: "Halka açık şirketlerin bedelli sermaye artışlarında, ihraç edilecek payların halka arz edilmeksizin satışı hangi yöntemlerle gerçekleştirilebilir?", secenekler: ["Sadece tahsisli satış", "Sadece nitelikli yatırımcıya satış", "Tahsisli satış ve nitelikli yatırımcıya satış", "Yönetim kurulunun belirleyeceği her yöntem", "Sadece mevcut ortaklara satış"], dogruCevap: "Tahsisli satış ve nitelikli yatırımcıya satış", aciklama: "Bedelli artırımlarda bu iki yöntem kullanılabilir." },
  { id: 3, metin: "Kayıtlı sermaye sistemindeki halka açık şirketlerin bedelli sermaye artırımlarında, artırılan sermayeyi oluşturan paylardan satılamayanlar için alım taahhütnamesi sunma yükümlülüğü hakkında ne söylenebilir?", secenekler: ["Zorunlu değildir, isteğe bağlıdır", "Esas sermaye sistemi için zorunludur", "Her durumda zorunludur", "Borsa fiyatı düşük şirketler için zorunludur", "Rüçhan hakkı kısıtlanmışsa zorunludur"], dogruCevap: "Zorunlu değildir, isteğe bağlıdır", aciklama: "Kayıtlı sermaye sisteminde taahhütname zorunluluğu yoktur." },
  { id: 4, metin: "Katılma intifa senetleri (KİS) ihracında, şirketlerin ihraç edebileceği toplam KİS miktarı, ödenmiş sermayelerinin en fazla yüzde kaçını aşamaz?", secenekler: ["%25", "%40", "%50", "%75", "%100"], dogruCevap: "%50", aciklama: "KİS tutarı çıkarılmış sermayenin yarısını geçemez." },
  { id: 5, metin: "Sermaye Piyasası Kanunu'na göre, bir şirkette oy haklarının yarısından fazlasına tek başına veya birlikte hareket eden kişilerle sahip olmak, yönetim kontrolü açısından ne ifade eder?", secenekler: ["Azınlık pay sahibi", "Önemli etkiye sahip ortak", "Halka arz sonrası satış kısıtlaması yoktur", "İmtiyazlı pay sahibi", "Yönetim kontrolünü elinde bulunduran ortak"], dogruCevap: "Yönetim kontrolünü elinde bulunduran ortak", aciklama: "%50+ oy hakkı yönetim kontrolü demektir." },
  { id: 6, metin: "Bir payın ikincil piyasada gerçeğe uygun fiyatlanabilmesi için sermaye piyasası düzenlemeleri açısından temel şart nedir?", secenekler: ["Fiyatı etkileyen tüm bilgilerin tam ve zamanında piyasaya duyurulması", "Piyasa yapıcıların aktif olması", "Şirketin yüksek kar açıklaması", "Sadece mali tabloların yayınlanması", "Yatırımcı sayısının yeterli olması"], dogruCevap: "Fiyatı etkileyen tüm bilgilerin tam ve zamanında piyasaya duyurulması", aciklama: "Bilginin tam ve zamanında yayılması doğru fiyatlamanın temelidir." },
  { id: 7, metin: "Primli paylarla ilgili aşağıdakilerden hangisi doğrudur?", secenekler: ["Nominal değerinin altında ihraç edilen paylar", "Nominal değeriyle ihraç edilen paylar", "Kar payı garantili paylar", "Nominal değerinin üzerinde ihraç edilen paylar", "Ek oy hakkı tanıyan paylar"], dogruCevap: "Nominal değerinin üzerinde ihraç edilen paylar", aciklama: "Primli pay, itibari değerin üstünde satılan paydır." },
  { id: 8, metin: "Bir payın sermaye piyasası aracı sayılabilmesi için temel koşullar nelerdir?", secenekler: ["SPK ön onayı", "Bilanço büyüklüğünün sınırın üstünde olması", "Borsada işlem görmesi veya halka açık sayılması nedeniyle Kanun'a tabi olması", "Esas sözleşmede hüküm bulunması", "Nama yazılı olması"], dogruCevap: "Borsada işlem görmesi veya halka açık sayılması nedeniyle Kanun'a tabi olması", aciklama: "SPKn kapsamında olmak esastır." },
  { id: 9, metin: "Savunma veya tarım sektöründeki bazı şirketlerin ilk halka arz öncesinde, gelirlerinin yüzde kaçını ilgili sektörden elde etmesi gerekir?", secenekler: ["%50", "%60", "%70", "%75", "%80"], dogruCevap: "%75", aciklama: "İlgili sektör geliri en az %75 olmalıdır." },
  { id: 10, metin: "Sermaye azaltımı ile eş zamanlı veya azaltımı takip eden iki yıl içinde yapılacak sermaye artırımlarında risk bildirim formunun işlevi nedir?", secenekler: ["Kimlik doğrulama", "Riskleri açıklayıp yatırımcının onayını almak", "Kar payı beklentisini kaydetmek", "Fon kullanım yerini belirlemek", "Yatırım deneyimini ölçmek"], dogruCevap: "Riskleri açıklayıp yatırımcının onayını almak", aciklama: "Risk bildirim formu bilgilendirme ve onay amaçlıdır." },
  { id: 11, metin: "İlk kez halka arz edilecek şirketlerde %10 ve üzeri paya sahip ortaklar için satış yasağı süresi nedir?", secenekler: ["90 gün", "180 gün", "6 ay", "1 yıl", "2 yıl"], dogruCevap: "1 yıl", aciklama: "Bu ortaklar 1 yıl boyunca halka arz fiyatının altında satış yapamaz." },
  { id: 12, metin: "Aşağıdakilerden hangisi pay sahiplerinin mali hakları arasında yer almaz?", secenekler: ["Kar payı hakkı", "Bedelsiz pay hakkı", "Tasfiye bakiyesi hakkı", "Genel kurulu toplantıya çağırma hakkı", "Geri alma hakkı"], dogruCevap: "Genel kurulu toplantıya çağırma hakkı", aciklama: "Bu hak idari haklar arasındadır, mali değil." },
  { id: 13, metin: "Satışa hazır bekletilen paylardan bir yıl içinde satılamayanlar için ne olur?", secenekler: ["İkinci yıl tekrar satışa sunulur", "İptal olur", "Ortaklara bedelsiz dağıtılır", "Hazineye devredilir", "Borsada satılır"], dogruCevap: "İptal olur", aciklama: "Bir yıl içinde satılamayan paylar iptal edilir." },
  { id: 14, metin: "Satışa hazır bekletilen paylar için Kurul ücreti hesaplanırken hangi oran kullanılır?", secenekler: ["Halka arz fiyatının %10'u", "%15", "%20", "%25", "%30"], dogruCevap: "%25", aciklama: "Kurul ücreti halka arz fiyatının %25'i üzerinden hesaplanır." },
  { id: 15, metin: "Aşağıdakilerden hangisi şirketin dava hakları arasında sayılmaz?", secenekler: ["Butlan davası", "İptal davası", "Sorumluluk davaları", "Haksız rekabet davası", "Hakimiyet ilişkilerine ait davalar"], dogruCevap: "Haksız rekabet davası", aciklama: "Haksız rekabet davası şirketin dava haklarından biri değildir." },
  { id: 16, metin: "Fiyat istikrarı işlemlerinde, şirket dışındaki kişilerce sağlanan fon miktarı için ne söylenebilir?", secenekler: ["Halka arz gelirinin %20'sini geçemez", "%25'ini geçemez", "%30'unu geçemez", "%50'sini geçemez", "Herhangi bir sınır yoktur"], dogruCevap: "Herhangi bir sınır yoktur", aciklama: "Şirket dışı fonlarda sınırlama yoktur." },
  { id: 17, metin: "Girişim Sermayesi Pazarı'nda işlem görecek şirketlerin pay satış süresi kaç iş günüdür?", secenekler: ["1", "2", "3", "4", "5"], dogruCevap: "2", aciklama: "Bu pazarda satış süresi 2 iş günüdür." },
  { id: 18, metin: "Rüçhan hakkı kullanımı, izahnamenin ilanını takip eden kaç gün içinde başlatılmalıdır?", secenekler: ["5 gün", "7 gün", "10 gün", "15 gün", "20 gün"], dogruCevap: "10 gün", aciklama: "Rüçhan hakkı kullanımı 10 gün içinde başlar." },
  { id: 19, metin: "Payların kaydileştirilmesiyle ilgili hangisi yanlıştır?", secenekler: ["2005'te başlandı", "2012'de tamamlandı", "MKK'de elektronik ortamda izlenir", "Fiziki hisse senetleri hâlâ geçerlidir", "Yeni halka arzlarda zorunludur"], dogruCevap: "Fiziki hisse senetleri hâlâ geçerlidir", aciklama: "Kaydileştirme sonrası fiziki senetler geçerliliğini yitirmiştir." },
  { id: 20, metin: "Aşağıdakilerden hangisi sermayeye eklenebilecek iç kaynaklardan biri değildir?", secenekler: ["Ara dönem karları", "Olağanüstü yedekler", "Yasal yedekler", "Geçmiş yıl karları", "Emisyon primleri"], dogruCevap: "Ara dönem karları", aciklama: "Ara dönem karları iç kaynak sayılmaz." },
  { id: 21, metin: "Kurucu ve intifa paylarıyla ilgili hangisi yanlıştır?", secenekler: ["Emre yazılı olabilir", "Hamile yazılı olabilir", "Tasfiye bakiyesine katılma hakkı verilebilir", "Rüçhan hakkı verilebilir", "Oy hakkı verilir"], dogruCevap: "Oy hakkı verilir", aciklama: "Kurucu ve intifa payları oy hakkı vermez." },
  { id: 22, metin: "Halka açık şirketlerin ikincil halka arzında hangisi doğrudur?", secenekler: ["Sadece mevcut paylar satılabilir", "Hem mevcut paylar hem yeni paylar satılabilir", "Sadece sermaye artırımıyla yeni pay satılabilir", "Rüçhan hakkı kısıtlanamaz", "Sadece yurt dışında yapılabilir"], dogruCevap: "Hem mevcut paylar hem yeni paylar satılabilir", aciklama: "İkincil halka arzda her iki yöntem de kullanılabilir." },
  { id: 23, metin: "Aşağıdakilerden hangisi pay sahiplerinin idari haklarından değildir?", secenekler: ["Genel kurulu toplantıya çağırma", "Genel kurula katılma", "Oy hakkı", "Tasfiye bakiyesine katılma", "Bilgi alma ve inceleme"], dogruCevap: "Tasfiye bakiyesine katılma", aciklama: "Bu hak mali haklardandır." },
  { id: 24, metin: "Katılma intifa senetleri (KİS) ile ilgili hangisi yanlıştır?", secenekler: ["Net kardan pay alma hakkı verir", "Tasfiye bakiyesine katılma hakkı verir", "Rüçhan hakkı verir", "Oy hakkı verir", "Pay benzeri menkul kıymettir"], dogruCevap: "Oy hakkı verir", aciklama: "KİS oy hakkı vermez." },
  { id: 25, metin: "İlk kez halka arz edilecek şirketlerin ödenmiş sermayelerinde, başvuru tarihinden önceki kaç yıl içinde değer artış fonları bulunmamalıdır?", secenekler: ["1 yıl", "2 yıl", "3 yıl", "4 yıl", "5 yıl"], dogruCevap: "2 yıl", aciklama: "Son 2 yılda bu tür fonlar olmamalıdır." },
];