import { DenemeSorusu } from './deneme1';

export const deneme3Baslik = "Osmanlı Devleti Kuruluş ve Yükselme Dönemi";

export const deneme3: DenemeSorusu[] = [
  {
    id: 1,
    soru: "Aşağıdakilerden hangisi Osman Bey döneminde beyliğin ekonomik bağımsızlığını ve hukuki egemenliğini ortaya koyan \"ilk vergi\" ve atanan \"ilk kadı\" eşleştirmesi doğru verilmiştir?",
    secenekler: ["A) Çiftbozan - Davud-i Kayseri", "B) Bac Vergisi - Dursun Fakih", "C) Öşür - Kadı Gıyaseddin", "D) Cizye - Alaaddin Paşa", "E) Avarız - Ebu's-Suud Efendi"],
    cevap: 1,
    aciklama: "Osmanlı Devleti'nde alınan ilk vergi \"Bac\" (çarşı/pazar) vergisidir. Osman Bey döneminde atanan ilk kadı ise Dursun Fakih'tir.",
  },
  {
    id: 2,
    soru: "Orhan Bey Dönemi'nde açılan \"ilk Osmanlı medresesi\" ve bu medreseye atanan \"ilk Osmanlı müderrisi\" aşağıdakilerin hangisinde doğru eşleştirilmiştir?",
    secenekler: ["A) İznik Medresesi - Davud-i Kayseri", "B) Bursa Medresesi - Dursun Fakih", "C) Sahn-ı Seman Medresesi - Ali Kuşçu", "D) Süleymaniye Medresesi - Molla Fenari", "E) Edirne Medresesi - Kadızade-i Rumi"],
    cevap: 0,
    aciklama: "Orhan Bey, İznik'i fethettikten sonra orada Osmanlı'nın ilk medresesi olan İznik Medresesi'ni (Süleyman Paşa Medresesi) açmış ve başına ilk müderris olarak Davud-i Kayseri'yi atamıştır.",
  },
  {
    id: 3,
    soru: "Orhan Bey Dönemi'nde Osmanlı Devleti'ne katılan, bu sayede hem Osmanlı'nın Rumeli'ye geçişini kolaylaştıran hem de devletin ilk donanma gücünü oluşturan beylik aşağıdakilerden hangisidir?",
    secenekler: ["A) Germiyanoğulları", "B) Karesioğulları", "C) Hamitoğulları", "D) Candaroğulları", "E) Dulkadiroğulları"],
    cevap: 1,
    aciklama: "Karesioğulları Beyliği'nin Orhan Bey döneminde Osmanlı topraklarına katılmasıyla Osmanlı ilk kez denizcilik faaliyetlerine başlamış, hazır bir donanmaya sahip olmuş ve Rumeli'ye geçiş (Çimpe Kalesi) kolaylaşmıştır.",
  },
  {
    id: 4,
    soru: "I. Rumeli Beylerbeyliği'nin kurulması\nII. İlk defterdar, kazasker ve sadrazam atamalarının yapılması\nIII. Sınırların genişlemesine bağlı olarak ilk kez \"Devşirme\" ve \"Yeniçeri\" sisteminin temellerinin atılması\nYukarıdaki kurumsallaşma ve teşkilatlanma hamlelerinden hangileri \"I. Murat\" döneminde gerçekleştirilmiştir?",
    secenekler: ["A) Yalnız I", "B) Yalnız II", "C) I ve II", "D) II ve III", "E) I, II ve III"],
    cevap: 4,
    aciklama: "I. Murat dönemi tam bir devletleşme dönemidir. Sınırların genişlemesiyle Rumeli Beylerbeyliği kurulmuş, defterdar, kazasker ve sadrazamlık makamları ihdas edilmiş ve Kapıkulu Ocağı (Devşirme/Yeniçeri) kurulmuştur.",
  },
  {
    id: 5,
    soru: "Osmanlı Devleti'nin Haçlı ittifaklarına karşı kazandığı, savaş alanında ilk kez bir Osmanlı padişahının (I. Murat) şehit düştüğü ve Türk bayrağının şeklinin ortaya çıkmasına zemin hazırlayan savaş aşağıdakilerden hangisidir?",
    secenekler: ["A) Sırpsındığı Savaşı", "B) Niğbolu Savaşı", "C) I. Kosova Savaşı", "D) Varna Savaşı", "E) II. Kosova Savaşı"],
    cevap: 2,
    aciklama: "1389 yılındaki I. Kosova Savaşı'nda Osmanlı, Haçlıları mağlup etmiştir. Savaş sahasını gezen I. Murat, Sırp asilzadesi Miloş Obiliç tarafından şehit edilmiştir. Ayrıca yerdeki kanların üzerine yansıyan hilal ve yıldız silueti Türk bayrağının doğuşuna kaynaklık etmiştir.",
  },
  {
    id: 6,
    soru: "Yıldırım Bayezid'in 1396 Niğbolu Savaşı sonrasında aldığı unvan ve yaptırdığı meşhur mimari eser aşağıdakilerin hangisinde doğru verilmiştir?",
    secenekler: ["A) Ebü'l-Feth - Rumeli Hisarı", "B) Sultan-ı İklim-i Rum - Bursa Ulu Camii", "C) Hadimü'l-Haremeyn - Edirne Selimiye Camii", "D) Hünkar - Anadolu Hisarı", "E) Gazi - Yıldırım Külliyesi"],
    cevap: 1,
    aciklama: "Yıldırım Bayezid, Niğbolu Savaşı'nda Haçlıları yenince Halife tarafından kendisine \"Sultan-ı İklim-i Rum\" (Anadolu Diyarının Sultanı) unvanı verilmiştir. Bu savaştan elde ettiği ganimetlerle de Bursa Ulu Camii'ni inşa ettirmiştir.",
  },
  {
    id: 7,
    soru: "Aşağıdakilerden hangisi Fetret Devri'nde taht mücadelesine girişen şehzadelerden biri olduğu halde, bu süreçte tek başına İstanbul'u kuşatan ilk şehzade olarak tarihe geçmiştir?",
    secenekler: ["A) İsa Çelebi", "B) Mustafa Çelebi", "C) Musa Çelebi", "D) Süleyman Çelebi", "E) Mehmet Çelebi"],
    cevap: 2,
    aciklama: "Fetret Devri'nde İsa, Musa, Süleyman ve Mehmet Çelebi arasında amansız bir mücadele yaşanmıştır. Bu süreçte Bizans'ın şehzadeleri birbirine kışkırtmasına tepki olarak Musa Çelebi, İstanbul'u kuşatan ilk şehzade olmuştur.",
  },
  {
    id: 8,
    soru: "Aşağıdakilerden hangisi I. Mehmet Dönemi'nde yaşanan \"ilk dini-sosyal nitelikli isyan\" ile Venediklilerle yapılan \"ilk deniz savaşı\" eşleştirmesini doğru göstermektedir?",
    secenekler: ["A) Şeyh Bedrettin İsyanı - Çalıbey Savaşı", "B) Baba İshak İsyanı - Koyunhisar Savaşı", "C) Bozoklu Celal İsyanı - İnebahtı Savaşı", "D) Şahkulu İsyanı - Preveze Savaşı", "E) Buçuktepe İsyanı - Çeşme Savaşı"],
    cevap: 0,
    aciklama: "Çelebi Mehmet döneminde sosyal patlama niteliğindeki ilk dini-sosyal isyan olan Şeyh Bedrettin İsyanı çıkmış; denizlerde ise Venediklilerle ilk deniz savaşı olan Çalıbey Savaşı yapılmış ve Osmanlı bu savaşı kaybetmiştir.",
  },
  {
    id: 9,
    soru: "Osmanlı tarihinde ilk kez \"Şeyhülislamlık\" makamını kurarak bu göreve Molla Fenari'yi atayan padişah aşağıdakilerden hangisidir?",
    secenekler: ["A) Orhan Bey", "B) I. Murat", "C) II. Murat", "D) Fatih Sultan Mehmet", "E) II. Bayezid"],
    cevap: 2,
    aciklama: "Osmanlı tarihinde ilk kez din işlerini organize etmesi amacıyla II. Murat döneminde Şeyhülislamlık makamı kurulmuş ve ilk şeyhülislam olarak ünlü fıkıh alimi Molla Fenari atanmıştır.",
  },
  {
    id: 10,
    soru: "Aşağıdaki padişah/şehzade çiftlerinden hangileri İstanbul'u kuşattığı halde fethi gerçekleştiremeyen isimler arasında yer alır?",
    secenekler: ["A) Yıldırım Bayezid - II. Murat", "B) I. Murat - Çelebi Mehmet", "C) Osman Bey - Orhan Bey", "D) II. Bayezid - Yavuz Sultan Selim", "E) Kanuni Sultan Süleyman - II. Selim"],
    cevap: 0,
    aciklama: "Fatih'ten önce İstanbul'u kuşatanlar arasında Yıldırım Bayezid (4 kez), Şehzade Musa Çelebi ve II. Murat yer almaktadır. Dolayısıyla \"Yıldırım Bayezid - II. Murat\" ikilisi doğru seçenektir.",
  },
  {
    id: 11,
    soru: "Fatih Sultan Mehmet'in \"karada ve denizde\" kuşatıp da alamadığı, daha sonra Kanuni Sultan Süleyman döneminde Osmanlı topraklarına katılan yerler sırasıyla hangisinde doğru verilmiştir?",
    secenekler: ["A) Belgrad - Rodos", "B) Viyana - Girit", "C) Uyvar - Kıbrıs", "D) Budin - Malta", "E) Niğbolu - Mora"],
    cevap: 0,
    aciklama: "Fatih Sultan Mehmet, karada Belgrad'ı, denizde ise Rodos adasını kuşatmış ancak alamamıştır. Bu iki stratejik nokta daha sonra Kanuni Sultan Süleyman tarafından fethedilmiştir.",
  },
  {
    id: 12,
    soru: "Fatih Sultan Mehmet döneminde gerçekleştirilen aşağıdaki fetihlerden hangisiyle \"Karadeniz bir Türk gölü\" haline gelmiştir?",
    secenekler: ["A) Amasra'nın alınması", "B) Sinop'un ele geçirilmesi", "C) Trabzon İmparatorluğu'na son verilmesi", "D) Kırım'ın fethedilmesi", "E) Kefe'nin alınması"],
    cevap: 3,
    aciklama: "Fatih döneminde Amasra, Sinop ve Trabzon alınarak Karadeniz kıyıları güvenliğe alınmış; en son Cenevizlilerden Kırım'ın fethiyle Karadeniz kesin olarak bir Türk gölü haline gelmiştir.",
  },
  {
    id: 13,
    soru: "Osmanlı Devleti'ni uluslararası arenada zor durumda bırakan ve II. Bayezid Dönemi'nin sönük geçmesine neden olan iç gelişme aşağıdakilerden hangisidir?",
    secenekler: ["A) Şahkulu İsyanı", "B) Cem Sultan Olayı", "C) Düzmece Mustafa İsyanı", "D) Şehzade Bayezid İsyanı", "E) Bozoklu Celal İsyanı"],
    cevap: 1,
    aciklama: "Fatih'in ölümüyle oğulları II. Bayezid ve Cem Sultan arasında taht kavgası çıkmıştır. Cem Sultan'ın sırasıyla Rodos Şövalyelerine ve Papalık'a sığınmasıyla bu iç sorun, Osmanlı'nın elini kolunu bağlayan büyük bir dış soruna dönüşmüştür.",
  },
  {
    id: 14,
    soru: "I. Kristof Kolomb'un Atlantik seferi projesini reddetmesi\nII. Leonardo da Vinci'nin Haliç üzerine köprü yapma teklifini geri çevirmesi\nIII. İstanbul'da meydana gelen büyük deprem (Küçük Kıyamet) sonrasında ilk kez \"Avarız\" vergisini toplamaya başlaması\nYukarıdaki gelişmelerden hangileri \"II. Bayezid\" döneminde yaşanmıştır?",
    secenekler: ["A) Yalnız I", "B) Yalnız II", "C) I ve II", "D) II ve III", "E) I, II ve III"],
    cevap: 4,
    aciklama: "II. Bayezid Dönemi sanılanın aksine çok ilginç olaylara sahne olmuştur: Kristof Kolomb ve Leonardo da Vinci'nin teklifleri geri çevrilmiş; 1509 yılındaki büyük İstanbul depreminden (Küçük Kıyamet) sonra yaraları sarmak için ilk kez halktan Avarız vergisi toplanmıştır.",
  },
  {
    id: 15,
    soru: "Osmanlı tahtında sadece 8 yıl kalmasına rağmen \"80 yıllık iş sığdıran\" Yavuz Sultan Selim döneminde, Dulkadiroğulları Beyliği'ne son verilerek Anadolu Türk siyasi birliğinin kesin olarak sağlanmasını sağlayan savaş aşağıdakilerden hangisidir?",
    secenekler: ["A) Çaldıran Savaşı", "B) Turnadağ Savaşı", "C) Ridaniye Savaşı", "D) Mercidabık Savaşı", "E) Otlukbeli Savaşı"],
    cevap: 1,
    aciklama: "Yavuz Sultan Selim, 1515 Turnadağ Savaşı ile Dulkadiroğulları Beyliği'ne son vermiş, böylece Anadolu Türk siyasi birliği kesin olarak ve tamamen sağlanmıştır.",
  },
  {
    id: 16,
    soru: "1533 İstanbul (İbrahim Paşa) Antlaşması'nın hangi maddesi Osmanlı Devleti'nin Avusturya karşısında mutlak üstünlük sağladığının kanıtıdır?",
    secenekler: [
      "A) Avusturya'nın Osmanlı'ya yıllık vergi ödemesi",
      "B) Macaristan topraklarının Osmanlı korumasına bırakılması",
      "C) Avusturya Arşidükü'nün (kralının) protokolde Osmanlı sadrazamına denk sayılması",
      "D) Antlaşmanın süresinin Avusturya kralının kararına bırakılması",
      "E) Sınır kalelerinin her iki devlet tarafından ortak korunması",
    ],
    cevap: 2,
    aciklama: "1533 İstanbul (İbrahim Paşa) Antlaşması'na göre Avusturya Arşidükü (kralı), protokol bakımından Osmanlı padişahına değil, onun bir alt makamı olan sadrazama (veziriazama) denk sayılmıştır. Bu durum Osmanlı'nın diplomatik üstünlüğünün kanıtıdır.",
  },
  {
    id: 17,
    soru: "Kanuni Sultan Süleyman döneminde Safevi Devleti (İran) üzerine düzenlenen Doğu seferleri sonucunda imzalanan, \"Osmanlı ile İran arasındaki ilk resmi antlaşma\" özelliği taşıyan gelişme hangisidir?",
    secenekler: ["A) Nasuh Paşa Antlaşması", "B) Amasya Antlaşması", "C) Kasr-ı Şirin Antlaşması", "D) Ferhat Paşa Antlaşması", "E) Serav Antlaşması"],
    cevap: 1,
    aciklama: "Kanuni döneminde İran (Safevi) üzerine Irakeyn gibi büyük seferler yapılmış ve sonucunda 1555 yılında Osmanlı ile İran arasındaki ilk resmi antlaşma olan Amasya Antlaşması imzalanmıştır.",
  },
  {
    id: 18,
    soru: "Barbaros Hayrettin Paşa'nın Osmanlı hizmetine girmesiyle doğrudan Osmanlı'ya bağlanan Kuzey Afrika toprağı ve Akdeniz'i Türk gölü haline getiren büyük deniz zaferi sırasıyla hangisidir?",
    secenekler: ["A) Trablusgarp - Cerbe Deniz Savaşı", "B) Cezayir - Preveze Deniz Savaşı", "C) Tunus - İnebahtı Deniz Savaşı", "D) Mısır - Çalıbey Savaşı", "E) Fas - Navarin Savaşı"],
    cevap: 1,
    aciklama: "Cezayir hükümdarı olan Barbaros Hayrettin Paşa'nın Osmanlı hizmetine girip sadrazam/kaptan-ı derya olmasıyla Cezayir savaşsız Osmanlı'ya katılmıştır. 1538 Preveze Deniz Zaferi ile de Akdeniz bir Türk gölü haline gelmiştir.",
  },
  {
    id: 19,
    soru: "II. Selim döneminde Haçlı müttefikleri karşısında alınan ilk büyük deniz yenilgisi olan ve Cervantes'in de kolunu kaybettiği deniz savaşı aşağıdakilerden hangisidir?",
    secenekler: ["A) Preveze Deniz Savaşı", "B) İnebahtı Deniz Savaşı", "C) Navarin Faciası", "D) Çeşme Baskını", "E) Sinop Baskını"],
    cevap: 1,
    aciklama: "II. Selim döneminde donanmamızın yakıldığı yerlerden ilki olan İnebahtı Deniz Savaşı'nda (1571) müttefik Haçlı ordusu Osmanlı donanmasını yakmıştır. Bu savaşta ünlü İspanyol yazar Cervantes de savaşmış ve sol kolunu kaybetmiştir.",
  },
  {
    id: 20,
    soru: "Kanuni Sultan Süleyman, II. Selim ve III. Murat dönemlerinde sadrazamlık yapan, Don-Volga ve Süveyş Kanalı gibi vizyoner projelerle tarihe geçen devlet adamı aşağıdakilerden hangisidir?",
    secenekler: ["A) Pargalı İbrahim Paşa", "B) Sokullu Mehmet Paşa", "C) Köprülü Mehmet Paşa", "D) Tarhuncu Ahmed Paşa", "E) Merzifonlu Kara Mustafa Paşa"],
    cevap: 1,
    aciklama: "Kanuni Sultan Süleyman, II. Selim ve III. Murat olmak üzere 3 padişaha sadrazamlık yapan, Don-Volga ve Süveyş kanalları gibi döneminin çok ötesinde projeler hazırlayan dahi devlet adamı Sokullu Mehmet Paşa'dır.",
  },
];
