import { DenemeSorusu } from './deneme1';

export const deneme9Baslik = "Atatürk İlke ve İnkılapları & Dış Politika";

export const deneme9: DenemeSorusu[] = [
  {
    id: 1,
    soru: "Cumhuriyetin ilan edilmesinin ardından kurulan \"Türkiye Cumhuriyeti'nin ilk muhalefet partisi\" aşağıdakilerden hangisidir?",
    secenekler: ["A) Terakkiperver Cumhuriyet Fırkası", "B) Serbest Cumhuriyet Fırkası", "C) Demokrat Parti", "D) Halk Fırkası", "E) Vatan Partisi"],
    cevap: 0,
    aciklama: "Cumhuriyetin ilanından sonra kurulan ilk muhalefet partisi Terakkiperver Cumhuriyet Fırkası'dır. (Halk Fırkası ise ilk iktidar partisidir).",
  },
  {
    id: 2,
    soru: "Çok partili hayata geçişin ilk denemesi olan Terakkiperver Cumhuriyet Fırkası'nın kapatılmasına yol açan ve Cumhuriyet döneminde \"rejime karşı çıkan ilk büyük isyan\" aşağıdakilerden hangisidir?",
    secenekler: ["A) Menemen Olayı", "B) Şeyh Sait İsyanı", "C) 31 Mart Vakası", "D) Koçgiri İsyanı", "E) Anzavur İsyanı"],
    cevap: 1,
    aciklama: "Çok partili yaşama geçişi kesintiye uğratan, rejime ve laik düzene karşı çıkan ilk büyük isyan 1925 yılındaki Şeyh Sait İsyanı'dır. Bu isyan sonrasında Terakkiperver Cumhuriyet Fırkası kapatılmıştır.",
  },
  {
    id: 3,
    soru: "Şeyh Sait İsyanı'nın ardından ülkede huzur ve güvenliği sağlamak, inkılapların yapılmasını kolaylaştırmak amacıyla çıkarılan olağanüstü hal kanunu aşağıdakilerden hangisidir?",
    secenekler: ["A) Hıyanet-i Vataniye Kanunu", "B) Takrir-i Sükun Kanunu", "C) Nisab-ı Müzakere Kanunu", "D) Kabotaj Kanunu", "E) Başkomutanlık Kanunu"],
    cevap: 1,
    aciklama: "Şeyh Sait İsyanı'nın yarattığı karışıklığı dindirmek ve hükümete geniş yetkiler vermek amacıyla çıkarılan olağanüstü hal yasası Takrir-i Sükun Kanunu'dur (1925-1929).",
  },
  {
    id: 4,
    soru: "Mustafa Kemal'e karşı planlanan ve onun \"Benim naçiz vücudum bir gün elbet toprak olacaktır fakat Türkiye Cumhuriyeti ilelebet payidar kalacaktır\" sözünü söylemesine vesile olan suikast girişimi hangi şehirde gerçekleştirilmek istenmiştir?",
    secenekler: ["A) Ankara", "B) İstanbul", "C) İzmir", "D) Samsun", "E) Amasya"],
    cevap: 2,
    aciklama: "Eski İttihatçıların organize ettiği İzmir Suikastı Girişimi (1926), Giritli Şevki'nin ihbarı üzerine başlamadan önlenmiştir. Mustafa Kemal o ünlü sözünü bu olay üzerine İzmir'de söylemiştir.",
  },
  {
    id: 5,
    soru: "1 Temmuz 1926 tarihinde kabul edilen, Türk karasularında gemi işletme ve limanlar arasında yük/yolcu taşıma hakkını sadece Türk denizcilerine veren yasa aşağıdakilerden hangisidir?",
    secenekler: ["A) Teşvik-i Sanayi Kanunu", "B) Kabotaj Kanunu", "C) Men-i İsrafat Kanunu", "D) Düyun-ı Umumiye Kanunu", "E) Aşar Kanunu"],
    cevap: 1,
    aciklama: "1926 yılında yürürlüğe giren Kabotaj Kanunu ile Türk karasularında ticaret ve denizcilik hakkı sadece Türk vatandaşlarına tanınmıştır. Bu yasa doğrudan Milliyetçilik ilkesiyle ilgilidir.",
  },
  {
    id: 6,
    soru: "1926 yılında yürürlüğe giren ve kadın-erkek eşitliğini sosyal ve hukuki alanda sağlayan Türk Medeni Kanunu aşağıdaki ülkelerin hangisinden örnek alınarak hazırlanmıştır?",
    secenekler: ["A) Almanya", "B) İtalya", "C) İsviçre", "D) Fransa", "E) Belçika"],
    cevap: 2,
    aciklama: "1926 tarihli Türk Medeni Kanunu, döneminin en modern, en demokratik ve pratik çözümler sunan yasası olan İsviçre Medeni Kanunu'ndan uyarlanarak hazırlanmıştır.",
  },
  {
    id: 7,
    soru: "Türkiye Cumhuriyeti'nde \"ilk nüfus sayımı\" hangi yıl gerçekleştirilmiştir?",
    secenekler: ["A) 1923", "B) 1927", "C) 1930", "D) 1934", "E) 1938"],
    cevap: 1,
    aciklama: "Cumhuriyet tarihinin modern yöntemlerle gerçekleştirilen ilk nüfus sayımı 1927 yılında yapılmıştır.",
  },
  {
    id: 8,
    soru: "Yeni Türk Devleti'nde okuma-yazma oranını artırmak ve halka yeni harfleri öğretmek amacıyla açılan eğitim kurumları aşağıdakilerden hangisidir?",
    secenekler: ["A) Millet Mektepleri", "B) Köy Enstitüleri", "C) Darülfünun", "D) Medreseler", "E) Maarif Kongresi Kurumları"],
    cevap: 0,
    aciklama: "1 Kasım 1928'de Harf İnkılabı'nın kabul edilmesinin ardından, yeni Türk harflerini okuma-yazma çağını geçmiş yetişkin halka öğretmek amacıyla Millet Mektepleri açılmıştır.",
  },
  {
    id: 9,
    soru: "Atatürk Dönemi'nde Türk kadınına verilen siyasi hakların (Belediye seçimlerine katılma, Muhtarlık ve Milletvekilliği seçme/seçilme hakları) kronolojik sıralaması aşağıdakilerden hangisinde doğru verilmiştir?",
    secenekler: ["A) 1930 - 1933 - 1934", "B) 1933 - 1930 - 1934", "C) 1934 - 1933 - 1930", "D) 1930 - 1934 - 1933", "E) 1934 - 1930 - 1933"],
    cevap: 0,
    aciklama: "Kadınların kazandığı siyasi hakların tarihsel kronolojisi şöyledir: 1930 Belediye seçimleri → 1933 Muhtarlık seçimleri → 1934 Milletvekili seçimleri.",
  },
  {
    id: 10,
    soru: "TBMM tarafından 24 Kasım 1934 tarihinde kabul edilen bir kanunla Mustafa Kemal'e \"Atatürk\" soyadı verilmiştir. Bu kanuna göre \"Atatürk\" soyadının kullanım hakkı ile ilgili aşağıdakilerden hangisi doğrudur?",
    secenekler: [
      "A) Sadece erkek kardeşleri tarafından kullanılabilir",
      "B) Başka hiç kimse tarafından kullanılamaz ve tescil edilemez",
      "C) Yalnızca meclis başkanının izniyle akrabalarına verilebilir",
      "D) Yabancı devlet adamlarına onursal olarak verilebilir",
      "E) Sadece askeri rütbeye sahip generallerce taşınabilir",
    ],
    cevap: 1,
    aciklama: "1934 yılında Soyadı Kanunu çıktıktan sonra meclis tarafından Mustafa Kemal'e Atatürk soyadı verilmiştir. Özel bir kanunla, bu soyadının başka hiç kimse tarafından (akrabaları dahil) kullanılamayacağı hükme bağlanmıştır.",
  },
  {
    id: 11,
    soru: "Atatürk'ün vefat tarihi ve saati aşağıdakilerin hangisinde doğru olarak verilmiştir?",
    secenekler: ["A) 29 Ekim 1923 - 08.30", "B) 10 Kasım 1938 - 09.05", "C) 10 Kasım 1938 - 19.00", "D) 23 Nisan 1920 - 09.05", "E) 10 Kasım 1939 - 09.05"],
    cevap: 1,
    aciklama: "Türkiye Cumhuriyeti'nin kurucusu Gazi Mustafa Kemal Atatürk, 10 Kasım 1938 günü saat 09.05'te Dolmabahçe Sarayı'nda hayata gözlerini yummuştur.",
  },
  {
    id: 12,
    soru: "Atatürk Dönemi Türk Dış Politikası'nda Türkiye'nin uluslararası alandaki barışçı politikasının bir sonucu olarak 1932 yılında üye olduğu küresel barış örgütü aşağıdakilerden hangisidir?",
    secenekler: ["A) Birleşmiş Milletler", "B) Milletler Cemiyeti (Cemiyet-i Akvam)", "C) NATO", "D) Sadabat Paktı", "E) Balkan Antantı"],
    cevap: 1,
    aciklama: "Türkiye, uluslararası iş birliğine önem verdiğini göstermek amacıyla davet üzerine 1932 yılında Milletler Cemiyeti'ne (Cemiyet-i Akvam) katılmıştır.",
  },
  {
    id: 13,
    soru: "Almanya ve İtalya'nın saldırgan politikalarına karşı batı sınırını güvence altına almak amacıyla Türkiye, Yunanistan, Yugoslavya ve Romanya arasında 1934 yılında imzalanan bölgesel ittifak aşağıdakilerden hangisidir?",
    secenekler: ["A) Sadabat Paktı", "B) Balkan Antantı", "C) Montrö Boğazlar Sözleşmesi", "D) Briand-Kellogg Paktı", "E) Akdeniz Paktı"],
    cevap: 1,
    aciklama: "Türkiye, Yunanistan, Yugoslavya ve Romanya arasında batı sınırlarını koruma amacıyla 1934 yılında Atina'da Balkan Antantı imzalanmıştır.",
  },
  {
    id: 14,
    soru: "İtalya'nın Habeşistan'ı işgal etmesi üzerine Türkiye'nin doğu sınırlarını güvence altına almak amacıyla Türkiye, İran, Irak ve Afganistan arasında 1937 yılında imzalanan pakt aşağıdakilerden hangisidir?",
    secenekler: ["A) Sadabat Paktı", "B) Balkan Antantı", "C) Bağdat Paktı", "D) Locarno Antlaşması", "E) Saadabad Sözleşmesi"],
    cevap: 0,
    aciklama: "Türkiye, İran, Irak ve Afganistan arasında Tahran'daki Sadabat Sarayı'nda doğu sınırlarını korumak için 1937 yılında Sadabat Paktı imzalanmıştır.",
  },
  {
    id: 15,
    soru: "Lozan'da Boğazlar üzerinde kurulan uluslararası komisyonun kaldırılarak Boğazların egemenliğinin ve savunmasının \"tamamen Türkiye'ye\" bırakılmasını sağlayan antlaşma hangisidir?",
    secenekler: ["A) Hünkar İskelesi Antlaşması", "B) Londra Boğazlar Sözleşmesi", "C) Montrö Boğazlar Sözleşmesi (1936)", "D) Lozan Barış Antlaşması", "E) Mudanya Mütarekesi"],
    cevap: 2,
    aciklama: "20 Temmuz 1936 tarihinde imzalanan Montrö Boğazlar Sözleşmesi ile Boğazlar Komisyonu lağvedilmiş, egemenlik hakları tamamen Türkiye'ye geçmiştir.",
  },
  {
    id: 16,
    soru: "Fransa'nın Suriye üzerindeki mandasını kaldırmasının ardından başlayan diplomatik süreç sonucunda, 1939 yılında Türkiye sınırlarına katılan ve Mustafa Kemal'in \"Şahsi meselem\" olarak nitelendirdiği toprak parçası aşağıdakilerden hangisidir?",
    secenekler: ["A) Kıbrıs", "B) Hatay (Sancak)", "C) Musul", "D) Batum", "E) Selanik"],
    cevap: 1,
    aciklama: "Atatürk'ün sağlığında büyük mücadele verdiği, \"şahsi meselem\" dediği Hatay, vefatından sonra 1939 yılında anavatana katılmıştır.",
  },
  {
    id: 17,
    soru: "Atatürk döneminin \"son başbakanı\" olarak görev yapan ve daha sonraki yıllarda Türkiye'nin 3. Cumhurbaşkanı olacak devlet adamı aşağıdakilerden hangisidir?",
    secenekler: ["A) İsmet İnönü", "B) Celal Bayar", "C) Fethi Okyar", "D) Adnan Menderes", "E) Refik Saydam"],
    cevap: 1,
    aciklama: "Atatürk döneminin son başbakanı Celal Bayar'dır. Atatürk'ün vefat ettiği sırada başbakanlık görevini o yürütmekteydi.",
  },
  {
    id: 18,
    soru: "Cumhuriyet döneminde açılan ilk muhalefet partisi olan Terakkiperver Cumhuriyet Fırkası'nın kurucuları arasında yer alıp istiklal madalyasına sahip olan \"ilk genel başkanı\" aşağıdakilerden hangisidir?",
    secenekler: ["A) Kazım Karabekir", "B) Ali Fuat Cebesoy", "C) Rauf Orbay", "D) Refet Bele", "E) Adnan Adıvar"],
    cevap: 0,
    aciklama: "Terakkiperver Cumhuriyet Fırkası'nın kurucu genel başkanı, Kurtuluş Savaşı'nın Doğu Cephesi kahramanı olan Kazım Karabekir'dir.",
  },
  {
    id: 19,
    soru: "Atatürk'ün naaşı, Anıtkabir yapılana kadar (1938-1953 yılları arasında) geçici olarak aşağıdaki yerlerin hangisinde muhafaza edilmiştir?",
    secenekler: ["A) Dolmabahçe Sarayı", "B) Ankara Etnoğrafya Müzesi", "C) Birinci Meclis Binası", "D) Topkapı Sarayı", "E) Çankaya Köşkü"],
    cevap: 1,
    aciklama: "Atatürk'ün naaşı, 1938'deki cenaze töreninin ardından geçici kabir olarak belirlenen Ankara Etnografya Müzesi'nde muhafaza edilmiş, 1953'te Anıtkabir'e nakledilmiştir.",
  },
  {
    id: 20,
    soru: "I. Aşar vergisinin kaldırılması (1925)\nII. Kabotaj Kanunu'nun çıkarılması (1926)\nIII. Miladi Takvimin kabul edilmesi (1926)\nYukarıda verilen inkılapların ilişkili olduğu Atatürk ilkeleri (Halkçılık - Milliyetçilik - İnkılapçılık) sırasıyla aşağıdakilerin hangisinde doğru eşleştirilmiştir?",
    secenekler: ["A) Halkçılık - Milliyetçilik - İnkılapçılık", "B) Milliyetçilik - Halkçılık - Devletçilik", "C) Cumhuriyetçilik - Milliyetçilik - Halkçılık", "D) Halkçılık - Laiklik - Milliyetçilik", "E) Devletçilik - Laiklik - İnkılapçılık"],
    cevap: 0,
    aciklama: "Köylünün sırtındaki büyük yük olan Aşar vergisinin kaldırılması Halkçılık; denizlerde bağımsızlığı sağlayan Kabotaj Kanunu Milliyetçilik; batı dünyasıyla uyumu hedefleyen Miladi Takvim ise İnkılapçılık ilkesiyle doğrudan ilgilidir.",
  },
];
