import { DenemeSorusu } from './deneme1';

export const deneme6Baslik = "XX. Yüzyıl Başlarında Osmanlı Devleti";

export const deneme6: DenemeSorusu[] = [
  {
    id: 1,
    soru: "Dünya tarihinde ilk kez \"savaş uçağının\" kullanıldığı ve Mustafa Kemal'in \"Gazeteci Şerif\" lakabıyla yerel halkı teşkilatlandırarak İtalyanlara karşı mücadele ettiği savaş aşağıdakilerden hangisidir?",
    secenekler: ["A) I. Balkan Savaşı", "B) Trablusgarp Savaşı", "C) II. Balkan Savaşı", "D) I. Dünya Savaşı", "E) Dömeke Meydan Savaşı"],
    cevap: 1,
    aciklama: "1911-1912 Trablusgarp Savaşı, dünya tarihinde ilk kez İtalyanlar tarafından savaş uçağının kullanıldığı savaştır. Mustafa Kemal bu savaşa gizlice katılmış, yerel halkı teşkilatlandırmak amacıyla \"Gazeteci Şerif\" takma adını kullanmıştır.",
  },
  {
    id: 2,
    soru: "Osmanlı Devleti, İtalya ile imzaladığı aşağıdaki antlaşmalardan hangisiyle Trablusgarp ve Bingazi'yi İtalya'ya bırakarak Kuzey Afrika'daki son toprak parçasını da kaybetmiştir?",
    secenekler: ["A) Londra Antlaşması", "B) Paris Antlaşması", "C) Uşi Antlaşması", "D) Atina Antlaşması", "E) İstanbul Antlaşması"],
    cevap: 2,
    aciklama: "Osmanlı Devleti, Balkan Savaşları'nın başlaması üzerine İtalya ile barış yapmak zorunda kalmış ve 1912 Uşi Antlaşması'nı imzalayarak Trablusgarp ile Bingazi'yi İtalya'ya bırakmıştır.",
  },
  {
    id: 3,
    soru: "I. Balkan Savaşı'nda Osmanlı Devleti'ne karşı birleşerek savaş açan Balkan devletleri aşağıdakilerin hangisinde bir arada verilmiştir?",
    secenekler: ["A) Sırbistan - Karadağ - Yunanistan - Bulgaristan", "B) Romanya - Sırbistan - Karadağ - Yunanistan", "C) Bulgaristan - Romanya - Sırbistan - Arnavutluk", "D) Yunanistan - Bulgaristan - Karadağ - Romanya", "E) Sırbistan - Karadağ - Romanya - Arnavutluk"],
    cevap: 0,
    aciklama: "I. Balkan Savaşı'nda Osmanlı Devleti'ne karşı ittifak kurup saldıran devletler Sırbistan, Karadağ, Yunanistan ve Bulgaristan'dır.",
  },
  {
    id: 4,
    soru: "İttihat ve Terakki Cemiyeti'nin, yenilgiden sorumlu tuttukları Kamil Paşa hükümetini silah zoruyla devirip yerine Mahmut Şevket Paşa hükümetini getirdiği \"Osmanlı tarihindeki ilk hükümet darbesi\" aşağıdakilerden hangisidir?",
    secenekler: ["A) 31 Mart Vakası", "B) Çırağan Baskını", "C) Kuleli Vakası", "D) Babıali Baskını", "E) Edirne Olayı"],
    cevap: 3,
    aciklama: "I. Balkan Savaşı'ndaki büyük yenilgi ve toprak kayıpları üzerine İttihat ve Terakki Cemiyeti, 1913 yılında Babıali Baskını adıyla bir hükümet darbesi gerçekleştirerek yönetimi tamamen ele geçirmiştir.",
  },
  {
    id: 5,
    soru: "I. Balkan Savaşı'nda yer almadığı halde, Bulgaristan'ın çok fazla toprak kazanmasına tepki olarak açılan II. Balkan Savaşı'na diğer Balkan devletleriyle birleşerek katılan devlet aşağıdakilerden hangisidir?",
    secenekler: ["A) Sırbistan", "B) Yunanistan", "C) Karadağ", "D) Romanya", "E) Arnavutluk"],
    cevap: 3,
    aciklama: "I. Balkan Savaşı'nda yer almayan ancak II. Balkan Savaşı'nda Bulgaristan'ın zayıflığından yararlanarak savaşa dahil olan ve Dobruca bölgesini geri almak isteyen devlet Romanya'dır.",
  },
  {
    id: 6,
    soru: "I. Balkan Savaşı'nı bitiren ve Osmanlı Devleti'nin Midye-Enez hattının batısındaki tüm Balkan topraklarını kaybetmesine neden olan antlaşma aşağıdakilerden hangisidir?",
    secenekler: ["A) Londra Antlaşması", "B) Uşi Antlaşması", "C) Atina Antlaşması", "D) İstanbul Antlaşması", "E) Bükreş Antlaşması"],
    cevap: 0,
    aciklama: "I. Balkan Savaşı, büyük güçlerin arabuluculuğunda imzalanan 1913 Londra Antlaşması ile sona ermiştir. Bu antlaşmayla Osmanlı Devleti, Midye-Enez çizgisinin batısında kalan Edirne dahil tüm Rumeli ve Balkan topraklarını kaybetmiştir.",
  },
  {
    id: 7,
    soru: "I. Dünya Savaşı'nda \"en karlı çıkan devletler\" ile savaştan \"ilk çekilen\" ve \"en son katılan\" devletler sırasıyla aşağıdakilerin hangisinde doğru verilmiştir?",
    secenekler: ["A) İngiltere-Fransa / Japonya / Yunanistan", "B) ABD-İngiltere / Rusya / İtalya", "C) İngiltere-Fransa / Rusya / Bulgaristan", "D) ABD-Fransa / İtalya / Yunanistan", "E) İngiltere-Almanya / Japonya / Romanya"],
    cevap: 0,
    aciklama: "I. Dünya Savaşı'ndan en karlı çıkan devletler İngiltere ve Fransa'dır. Savaştan ilk çekilen devlet Japonya, savaşa en son katılan devlet ise Yunanistan'dır.",
  },
  {
    id: 8,
    soru: "Osmanlı Devleti'nin I. Dünya Savaşı'nda açtığı \"ilk taarruz cephesi\" aşağıdakilerden hangisidir?",
    secenekler: ["A) Çanakkale Cephesi", "B) Kafkasya Cephesi", "C) Suriye-Filistin Cephesi", "D) Irak-Basra Cephesi", "E) Kanal Cephesi"],
    cevap: 1,
    aciklama: "Osmanlı Devleti'nin I. Dünya Savaşı'na girmesiyle açtığı ilk taarruz cephesi Kafkasya Cephesi'dir (Sarıkamış Harekatı). İkinci taarruz cephesi ise Kanal Cephesi'dir.",
  },
  {
    id: 9,
    soru: "Osmanlı Devleti'nin müttefiklerine (Almanya, Avusturya-Macaristan vb.) yardım etmek amacıyla sınırları dışında savaştığı cepheler aşağıdakilerin hangisinde doğru verilmiştir?",
    secenekler: ["A) Kafkasya - Kanal - Hicaz", "B) Galiçya - Romanya - Makedonya", "C) Irak - Suriye - Çanakkale", "D) Galiçya - Kafkasya - Yemen", "E) Makedonya - Hicaz - Filistin"],
    cevap: 1,
    aciklama: "Osmanlı Devleti'nin kendi sınırları dışında, tamamen müttefiklerine yardım etmek amacıyla asker gönderdiği cepheler Galiçya, Romanya ve Makedonya cepheleridir.",
  },
  {
    id: 10,
    soru: "Mustafa Kemal'in I. Dünya Savaşı'nda savaştığı cephelerin kronolojik sırası aşağıdakilerden hangisinde doğru verilmiştir?",
    secenekler: ["A) Çanakkale - Kafkasya - Suriye-Filistin", "B) Kafkasya - Çanakkale - Suriye-Filistin", "C) Suriye-Filistin - Çanakkale - Kafkasya", "D) Çanakkale - Suriye-Filistin - Kafkasya", "E) Kafkasya - Suriye-Filistin - Çanakkale"],
    cevap: 0,
    aciklama: "Mustafa Kemal'in I. Dünya Savaşı boyunca görev aldığı cephelerin kronolojik sırası: Çanakkale (1915) → Kafkasya (1916) → Suriye-Filistin (1917-1918) cepheleridir.",
  },
  {
    id: 11,
    soru: "Osmanlı Devleti'nin I. Dünya Savaşı'nda \"en çok toprak kaybı\" yaşadığı cephe aşağıdakilerden hangisidir?",
    secenekler: ["A) Kafkasya Cephesi", "B) Çanakkale Cephesi", "C) Suriye-Filistin Cephesi", "D) Hicaz-Yemen Cephesi", "E) Irak Cephesi"],
    cevap: 2,
    aciklama: "Osmanlı Devleti, I. Dünya Savaşı'nda en geniş alana yayılan ve en ağır geri çekilmelerin yaşandığı Suriye-Filistin Cephesi'nde en fazla toprak kaybını yaşamıştır.",
  },
  {
    id: 12,
    soru: "Mustafa Kemal'in Çanakkale Cephesi'nde tarihe geçen \"Ben size taarruzu değil, ölmeyi emrediyorum!\" sözünü söylediği meşhur mevzi aşağıdakilerden hangisidir?",
    secenekler: ["A) Arıburnu", "B) Anafartalar", "C) Conkbayırı", "D) Kilitbahir", "E) Seddülbahir"],
    cevap: 2,
    aciklama: "Mustafa Kemal, Çanakkale Savaşları sırasında cephanesi biten ve geri çekilen askerlere dur emri vererek Conkbayırı mevkisinde tarih yazan bu sözü söylemiştir.",
  },
  {
    id: 13,
    soru: "I. Dünya Savaşı'nda müttefiklerin Osmanlı Devleti'ni savaş dışı bırakmak, İstanbul'u ele geçirmek ve zor durumdaki Çarlık Rusyası'na yardım götürmek amacıyla açtığı cephe aşağıdakilerden hangisidir?",
    secenekler: ["A) Irak Cephesi", "B) Çanakkale Cephesi", "C) Suriye-Filistin Cephesi", "D) Kanal Cephesi", "E) Galiçya Cephesi"],
    cevap: 1,
    aciklama: "İtilaf Devletleri, Çarlık Rusyası'na boğazlar üzerinden askeri ve ekonomik yardım ulaştırmak, Osmanlı'yı başkentini alarak savaş dışı bırakmak amacıyla Çanakkale Cephesi'ni açmışlardır.",
  },
  {
    id: 14,
    soru: "Osmanlı Devleti'nin I. Dünya Savaşı'nda toprak kazanmayı başardığı \"tek cephe\" aşağıdakilerden hangisidir?",
    secenekler: ["A) Çanakkale Cephesi", "B) Kafkasya Cephesi", "C) Suriye-Filistin Cephesi", "D) Kanal Cephesi", "E) Galiçya Cephesi"],
    cevap: 1,
    aciklama: "Osmanlı Devleti, Bolşevik İhtilali sonrası Rusya'nın Brest-Litovsk Antlaşması'yla savaştan çekilmesi üzerine Kafkasya Cephesi'nde kaybettiği Kars, Ardahan ve Batum'u (Elviye-i Selase) geri almıştır. Bu yönüyle toprak kazanılan tek cephedir.",
  },
  {
    id: 15,
    soru: "Çanakkale Savaşları'nda boğazı cansiperane savunarak tarihe \"18 Mart Kahramanı\" unvanıyla geçen Osmanlı komutanı kimdir?",
    secenekler: ["A) Cevat Çobanlı", "B) Esat Paşa", "C) Fahreddin Paşa", "D) Halil Kut Paşa", "E) Kazım Karabekir"],
    cevap: 0,
    aciklama: "18 Mart 1915'te Çanakkale Boğazı'nı denizden geçmeye çalışan İtilaf donanmasını Çanakkale Müstahkem Mevki Komutanı olarak büyük bir stratejiyle durduran Cevat Çobanlı, tarihe \"18 Mart Kahramanı\" olarak geçmiştir.",
  },
  {
    id: 16,
    soru: "ABD Başkanı Woodrow Wilson'ın yayımladığı ilkeler doğrultusunda I. Dünya Savaşı'nın ardından \"yeniden kurulması öngörülen\" Avrupa devleti aşağıdakilerden hangisidir?",
    secenekler: ["A) Çekoslovakya", "B) Polonya", "C) Macaristan", "D) Yugoslavya", "E) Ukrayna"],
    cevap: 1,
    aciklama: "Wilson İlkeleri'nde yer alan \"Polonya'nın bağımsız bir devlet olarak yeniden kurulması\" maddesi doğrultusunda, savaşın ardından Avrupa'da Polonya devleti yeniden tarih sahnesine çıkmıştır.",
  },
  {
    id: 17,
    soru: "I. Dünya Savaşı'nda yenen devletler ile yenilen devletler arasında yapılacak olan barış antlaşmalarının taslaklarını ve şartlarını hazırlamak amacıyla toplanan uluslararası konferans aşağıdakilerden hangisidir?",
    secenekler: ["A) Londra Konferansı", "B) San Remo Konferansı", "C) Paris Barış Konferansı", "D) Berlin Konferansı", "E) Lozan Konferansı"],
    cevap: 2,
    aciklama: "18 Ocak 1919'da toplanan Paris Barış Konferansı, I. Dünya Savaşı'ndan yenik çıkan devletlerle imzalanacak barış antlaşmalarının şartlarını belirlemek üzere toplanmıştır.",
  },
  {
    id: 18,
    soru: "I. Dünya Savaşı'nın ardından imzalanan Mondros Mütarekesi (30 Ekim 1918) sonrasında \"Osmanlı topraklarında ilk işgal edilen yer\" aşağıdakilerden hangisidir?",
    secenekler: ["A) Hatay", "B) İzmir", "C) Musul", "D) Antep", "E) Maraş"],
    cevap: 2,
    aciklama: "Mondros Mütarekesi imzalandıktan hemen sonra, mütarekenin hukuksuz işgallere zemin hazırlayan meşhur 7. maddesine dayanılarak Osmanlı topraklarında ilk işgal edilen yer Musul olmuştur (İngiltere tarafından).",
  },
  {
    id: 19,
    soru: "Mondros Mütarekesi sonrasında \"Anadolu sınırları içerisinde ilk işgal edilen toprak\" aşağıdakilerden hangisidir?",
    secenekler: ["A) Musul", "B) Hatay", "C) İzmir", "D) Adana", "E) Samsun"],
    cevap: 1,
    aciklama: "Mondros sonrasında Musul genel Osmanlı toprağı olarak ilk işgal edilen yerken; Anadolu sınırları içerisinde ilk işgal edilen yer Hatay (Dörtyol) olmuştur (Fransızlar tarafından).",
  },
  {
    id: 20,
    soru: "Aşağıdaki gelişmelerden hangisi, İtilaf Devletleri arasında yaşanan \"ilk ciddi görüş ayrılığının\" ortaya çıktığı yerdir?",
    secenekler: ["A) Londra Konferansı", "B) Paris Barış Konferansı", "C) San Remo Konferansı", "D) Mondros Mütarekesi", "E) Mudanya Mütarekesi"],
    cevap: 1,
    aciklama: "Gizli antlaşmalarda İtalya'ya vadedilen İzmir ve çevresi, İngiltere'nin Akdeniz'de güçlü bir İtalya istememesi sebebiyle Paris Barış Konferansı'nda İtalya'dan alınarak Yunanistan'a verilmiştir. Bu durum İtilaf Devletleri arasındaki ilk ciddi görüş ayrılığıdır.",
  },
];
