import { DenemeSorusu } from './deneme1';

export const denemeTurkce2Baslik = "Noktalama İşaretleri ve Sözcükte Yapı (Kökler, Ekler, Gövdeler)";

export const denemeTurkce2: DenemeSorusu[] = [
  {
    id: 1,
    soru: "\"Roman ( ) hikâye ( ) şiir kitaplarını üst rafa ( ) gazete ( ) dergi gibi yayınları da alt rafa yerleştirdi ( )\" Bu cümlede boş bırakılan yerlere sırasıyla hangi noktalama işaretleri getirilmelidir?",
    secenekler: ["A) ( , ) ( , ) ( ; ) ( , ) ( . )", "B) ( , ) ( ; ) ( , ) ( , ) ( . )", "C) ( ; ) ( , ) ( ; ) ( , ) ( . )", "D) ( , ) ( , ) ( , ) ( ; ) ( . )", "E) ( ; ) ( ; ) ( , ) ( , ) ( . )"],
    cevap: 0,
    aciklama: "Virgül aynı takım/türdeki kelimeleri ayırır (Roman, hikâye, şiir kitapları). Noktalı virgül ise virgüllerle ayrılmış tür veya takımları birbirinden ayırır (; gazete, dergi...). Cümle bittiği için nokta konur.",
  },
  {
    id: 2,
    soru: "Aşağıdaki cümlelerin hangisinde virgül ( , ) kullanılmaz?",
    secenekler: [
      "A) Sıralı cümleleri birbirinden ayırmak için",
      "B) Uzun cümlelerde yüklemden uzak düşmüş olan özneyi belirtmek için",
      "C) Metin içinde art arda gelen zarf-fiil eki almış kelimelerden sonra",
      "D) Şart ekini (-se / -sa) almış sözcüklerden hemen sonra",
      "E) Hitap için kullanılan kelimelerden hemen sonra",
    ],
    cevap: 3,
    aciklama: "Şart ekini almış sözcüklerden sonra virgül kullanılmaz.",
  },
  {
    id: 3,
    soru: "Aşağıdaki cümlelerin hangisinde iki nokta ( : ) işareti yanlış kullanılmıştır?",
    secenekler: [
      "A) Küçük ünlü uyumuna uymayan bazı sözcükler şunlardır: televizyon, limon, horoz...",
      "B) Atatürk: \"Öğretmenler, yeni nesil sizin eseriniz olacaktır.\" demiştir.",
      "C) Sinema dağıldı: Kardeşim ortalıkta hiçbir yerde yoktu.",
      "D) Rafta sadece üç şey kalmıştı: un, şeker ve tuz.",
      "E) Gümrükteki memur başını yavaşça kaldırdı: — Adınız?",
    ],
    cevap: 2,
    aciklama: "C seçeneğinde iki noktadan sonra gelen kısım örnek veya doğrudan açıklama/konuşma değildir; iki cümle sıralı/bağlı ilişki içindedir ve buraya noktalı virgül veya nokta uygundur.",
  },
  {
    id: 4,
    soru: "Aşağıdaki cümlelerin hangisinde kesme işaretinin ( ' ) kullanımıyla ilgili bir noktalama yanlışı yapılmıştır?",
    secenekler: [
      "A) Türkiye Büyük Millet Meclisine sunulan yeni kanun teklifi kabul edildi.",
      "B) Ankara Üniversitesi Hukuk Fakültesi'ne bu yıl kayıt yaptırdı.",
      "C) Avrupa Birliği'ne üye ülkelerin temsilcileri Brüksel'de toplandı.",
      "D) Ayşe Hanım'dan gelen son evrakları masanın üzerine bıraktı.",
      "E) Geçen yıl Boğaz Köprümüzün güzelliğini seyretmeye doyamadık.",
    ],
    cevap: 1,
    aciklama: "Kurum, kuruluş ve kurul adlarına gelen ekler kesme işaretiyle ayrılmaz. \"Hukuk Fakültesine\" şeklinde yazılmalıdır. (Avrupa Birliği istisnadır ve kesmeyle ayrılır, bu yüzden C doğrudur.)",
  },
  {
    id: 5,
    soru: "\"Balıkçı ( ) orfinozu ( ) şimdiye dek tuttuklarına hiç benzemeyen bu balığı ( ) heyecanla ( ) özlemle beklemiş ( ) emeğinin karşılığını sonunda alabilmişti ( )\" Bu parçada boş bırakılan yerlere sırasıyla hangi noktalama işaretleri getirilmelidir?",
    secenekler: ["A) ( , ) ( - ) ( - ) ( , ) ( ; ) ( . )", "B) ( ; ) ( , ) ( , ) ( ; ) ( ; ) ( . )", "C) ( , ) ( , ) ( , ) ( , ) ( ; ) ( . )", "D) ( ; ) ( - ) ( - ) ( , ) ( ; ) ( ... )", "E) ( , ) ( - ) ( - ) ( , ) ( , ) ( . )"],
    cevap: 0,
    aciklama: "\"Balıkçı\" öznesinden sonra virgül gelir. Ara söz kısa çizgiyle ayrılır. \"heyecanla, özlemle\" eş görevlidir, virgülle ayrılır. İki sıralı cümleyi ayırmak için (ilk cümlede zaten virgül kullanıldığından) araya noktalı virgül (;) gelir.",
  },
  {
    id: 6,
    soru: "Bir sözcüğün kökü bulunurken, sözcüğün tamamı ile kökü arasında mutlaka anlam bağı olması gerekir. Buna göre aşağıdaki altı çizili sözcüklerden hangisinin kökü \"tür\" yönüyle (isim/fiil) diğerlerinden farklıdır?",
    secenekler: [
      "A) Saçları son aylarda iyice sararmış görünüyordu.",
      "B) Kazı çalışmalarında bulunan eserler koruma altına alındı.",
      "C) Bu oyunun inceliklerini tam olarak fark edememiş.",
      "D) Bahçedeki çiçekleri suladıktan sonra içeriye geçti.",
      "E) Havalar ısınınca çocukların hepsi sokağa döküldü.",
    ],
    cevap: 0,
    aciklama: "\"sararmış\" sözcüğünün kökü \"sarı\" ismidir (isim kökü). Diğer şıklardaki \"bulunan\" (bul-), \"suladıktan\" (su+la-), \"döküldü\" (dök-) gibi köklerin çoğu fiil kökenlidir; kök türü bakımından A farklıdır.",
  },
  {
    id: 7,
    soru: "Eklendiği sözcüğün anlamını, yapısını ve türünü değiştiren eklere yapım eki denir. Yapım eki almış sözcüklere ise gövde adı verilir. Aşağıdaki altı çizili sözcüklerden hangisi birden fazla yapım eki alarak \"gövdeden türemiş\" bir sözcüktür?",
    secenekler: [
      "A) Bazı saatçilerin vitrinleri son derece renkliydi.",
      "B) Sıkıntı dolu günlerimi güzelliklerle doldurmaya çalıştım.",
      "C) Bu çalışmalar daha sonra zevkli bir uğraş hâline geldi.",
      "D) Odadaki masanın üzerinde kalınca bir kitaplık duruyordu.",
      "E) Çocukların gözleri ışıl ışıl bakıyordu etrafa.",
    ],
    cevap: 1,
    aciklama: "\"doldurmaya\" sözcüğü dol-dur-ma-y-a şeklinde çözümlenir: \"dol-\" köküne önce \"-dur\" (ettirgenlik, yapım eki), sonra \"-ma\" (isim-fiil, yapım eki) eklenmiştir — iki yapım eki barındırdığı için gövdeden türemiştir. \"saatçilerin\" (saat-çi) ise sadece bir yapım eki alır.",
  },
  {
    id: 8,
    soru: "Aşağıdaki cümlelerin hangisinde \"-ma / -me\" eki diğerlerinden farklı bir işlevde (görevde) kullanılmıştır?",
    secenekler: [
      "A) Görme engelliler için hazırlanan bu projeyi gönülden destekledi.",
      "B) Dokunma duyusu gelişmiş olan insanlar nesneleri daha iyi tanır.",
      "C) Varma görgüsüz kapısına, canın bir kuru ekmeğe bağlı olsa da.",
      "D) Okuma salonunda sessizce oturup saatlerce kitap inceledi.",
      "E) Oturma izni almak için aylardır resmi dairelere başvuruyor.",
    ],
    cevap: 2,
    aciklama: "C seçeneğindeki \"Varma\" sözcüğündeki \"-ma\" eki olumsuzluk (emir kipi olumsuzu) ekidir. Diğer seçeneklerdeki \"-ma\" ekleri (görme, dokunma, okuma, oturma) isim-fiil (eylemsi), yani fiilden isim yapım ekidir.",
  },
  {
    id: 9,
    soru: "Aşağıdaki cümlelerin hangisinde altı çizili sözcük hem yapım hem de çekim eki almıştır?",
    secenekler: [
      "A) Uzun zamandır kendimi çok kötü hissediyorum.",
      "B) Yarışmacılardan biri salona diğerlerinden geç geldi.",
      "C) Gözlerin bir hayal âlemine dalıp gidiyor o anda.",
      "D) Başka diyarlara gideceğim gerçekleştirdiğim düşlerimle.",
      "E) Kitabın kilidini nihayet değiştirmeye karar verdiler.",
    ],
    cevap: 4,
    aciklama: "\"değiştirmeye\" sözcüğü değiş-tir-me-y-e şeklinde çözümlenir: hem yapım ekleri (-tir, -me) hem de çekim eki (yönelme hâli -e) almıştır.",
  },
  {
    id: 10,
    soru: "Aşağıdaki cümlelerin hangisinde \"-lık (-lik, -luk, -lük)\" ekiyle türetilmiş sözcük doğrudan bir \"yer adı\" bildirmektedir?",
    secenekler: [
      "A) Kışlık yiyeceklerimizi şimdiden hazırlayıp depoya kaldırdık.",
      "B) Yarın sabah çamlığa doğru keyifli bir yürüyüşe çıkacağız.",
      "C) Aylık kazancının büyük bir kısmını kitaplara harcıyordu.",
      "D) Çocukluğunda buralara pek çok kez geldiğini anlattı.",
      "E) Çevremizi kuşatan tüm çirkinliklerden rahatsız olmuştuk.",
    ],
    cevap: 1,
    aciklama: "\"çamlık\" sözcüğü gür çam ağaçlarının bulunduğu \"yer\" anlamını karşıladığı için yer bildirmektedir.",
  },
  {
    id: 11,
    soru: "Aşağıdaki cümlelerin hangisinde altı çizili ekin işlevi diğerlerinden farklıdır?",
    secenekler: ["A) Ben bu okulun tek öğretmeniyim.", "B) Ben onun sılasıyım kendimin gurbeti.", "C) Ben bir şarkı, hüzünlü bir türküyüm.", "D) Ben senin yanağında küçük bir tüyüm.", "E) Cici ayaklarım iplikle sıkıca bağlı."],
    cevap: 4,
    aciklama: "A, B, C ve D seçeneklerindeki ekler ek-fiilin şahıs ekidir ve yüklem yapmıştır. E seçeneğindeki \"ayaklarım\" sözcüğündeki \"-ım\" eki ise iyelik (aitlik) çekim ekidir.",
  },
  {
    id: 12,
    soru: "Aşağıdaki altı çizili sözcüklerin hangisinde, türetilirken (yapım eki alırken) ünlü düşmesi gerçekleşmemiştir?",
    secenekler: [
      "A) Bu yanlış karardan bir an önce dönülmesi gerekiyor.",
      "B) Hayatta her zaman yalnız kalmaktan korktuğunu söylerdi.",
      "C) Aynaya bakınca yüzünün iyice benzediğini fark etti.",
      "D) Akşam aldığımız çiçekler susuzluktan iyice sararmış.",
      "E) Sınavı kazanacağı zihnime ve gönlüme doğmuştu artık.",
    ],
    cevap: 4,
    aciklama: "\"gönlüme\" sözcüğünün kökü \"gönül\"dür. Ünlüyle başlayan çekim eki alırken ünlü düşmesine uğramıştır, yani türetilirken değil çekimlenirken düşmüştür. Diğerleri (yanlış<yanıl-, yalnız<yalın-, benzediğini<beniz, sararmış<sarı) yapım eki alırken düşmüştür.",
  },
  {
    id: 13,
    soru: "Aşağıdaki cümlelerin hangisinde altı çizili sözcük \"basit yapılı\" bir sözcüktür?",
    secenekler: [
      "A) Ankara'nın yeni yeni bahara uyandığı serin bir nisan ikindisiydi.",
      "B) Okşar gibi çiseleyip geçen yağmur havayı tamamen temizledi.",
      "C) Havada asılı duran tozu toprağı alıp uzaklara götürmüştü.",
      "D) Önceden buluşma yeri olarak saptadığım pastaneye doğru yürüdüm.",
      "E) Hızlı hızlı yürürken birden onunla karşı karşıya geldim.",
    ],
    cevap: 0,
    aciklama: "\"ikindisiydi\" sözcüğü ikindi (kök) + -si (iyelik) + -ydi (ek-fiil) şeklinde sadece çekim eki almıştır, basit yapılıdır. Diğerleri (yağmur<yağ-, saptadığım<sap-ta-) türemiştir.",
  },
  {
    id: 14,
    soru: "Aşağıdaki altı çizili sözcüklerin hangisinde ünsüz düşmesi gerçekleşmiştir?",
    secenekler: [
      "A) Masanın örtüsü el işçiliği ile titizlikle işlenmiş.",
      "B) Rüzgâr kesilince uçurtmamız gökyüzünde alçalmaya başladı.",
      "C) Bu kitap yazarın gençlik yıllarını en iyi anlatan eserdir.",
      "D) Gün doğmadan neler doğar, sabretmesini bilmelisin.",
      "E) Uykusuzluğu her hâlinden ve bakışından belli oluyordu.",
    ],
    cevap: 1,
    aciklama: "\"alçalmaya\" sözcüğünün kökü \"alçak\"tır. \"-l\" yapım ekini alarak fiil olurken sondaki \"k\" ünsüzü düşmüştür (alçak-l-a > alçal-).",
  },
  {
    id: 15,
    soru: "Aşağıdaki cümlelerin hangisinde yer alan birleşik isim \"sıfat tamlaması\" biçiminde oluşmuştur?",
    secenekler: [
      "A) Buzdolabının kapağını açık bıraktığı için yiyecekler bozulmuş.",
      "B) Bahçedeki aslanağzı çiçekleri baharla birlikte rengârenk açtı.",
      "C) Sivrisinekler yüzünden yaz gecelerinde uyumak imkânsız hâle geliyor.",
      "D) Akşam yemeği için imambayıldı yapmaya karar verdi.",
      "E) Çeyiz sandığına koymak için yeni bir dantel sipariş etti.",
    ],
    cevap: 2,
    aciklama: "\"Sivrisinek\" birleşik ismi \"sivri\" (sıfat) ve \"sinek\" (isim) birleşmesiyle oluşan bir sıfat tamlaması formudur. Diğerleri (buzdolabı, aslanağzı, imambayıldı) belirsiz isim tamlaması veya cümle formundadır.",
  },
];
