import { DenemeSorusu } from './deneme1';

export const deneme5Baslik = "Osmanlı Devleti Islahatları ve Demokratikleşme Hareketleri";

export const deneme5: DenemeSorusu[] = [
  {
    id: 1,
    soru: "Aşağıdakilerden hangisi XVII. yüzyıl ıslahatçılarından biri olup, Osmanlı tarihinde ilk kez modern anlamda \"bütçe\" hazırlayan devlet adamıdır?",
    secenekler: ["A) Köprülü Mehmet Paşa", "B) Tarhuncu Ahmed Paşa", "C) Kuyucu Murat Paşa", "D) Kemankeş Kara Mustafa Paşa", "E) Merzifonlu Kara Mustafa Paşa"],
    cevap: 1,
    aciklama: "XVII. yüzyıl sadrazamlarından Tarhuncu Ahmed Paşa, devletin gelir-gider dengesini sağlamak amacıyla Osmanlı tarihindeki ilk modern, denk bütçeyi hazırlamıştır. Ancak çıkarları zedelenen çevrelerin saraya baskısı sonucu idam edilmiştir.",
  },
  {
    id: 2,
    soru: "XVIII. yüzyılda batıdan getirilen ilk askeri uzman olan ve orduda \"Humbaracı Ocağı\"nı ıslah ederek \"Humbaracı Ahmet Paşa\" adını alan Fransız kökenli uzman aşağıdakilerden hangisidir?",
    secenekler: ["A) Baron de Tott", "B) Kont de Bonneval", "C) Helmuth von Moltke", "D) Colmar von der Goltz", "E) Layard"],
    cevap: 1,
    aciklama: "I. Mahmut döneminde batıdan getirilen ilk askeri uzman olan Fransız Kont de Bonneval, Müslüman olup Humbaracı Ahmet Paşa adını almış ve havan topu döken Humbaracı Ocağı'nı batı tarzında ıslah etmiştir.",
  },
  {
    id: 3,
    soru: "Osmanlı Devleti'nde ilk kez geçici ve sürekli elçiliklerin açıldığı dönemler aşağıdakilerin hangisinde sırasıyla doğru olarak verilmiştir?",
    secenekler: ["A) Lale Devri - III. Selim Dönemi", "B) III. Selim Dönemi - II. Mahmut Dönemi", "C) Lale Devri - II. Mahmut Dönemi", "D) I. Mahmut Dönemi - III. Selim Dönemi", "E) Lale Devri - Abdülmecid Dönemi"],
    cevap: 0,
    aciklama: "Osmanlı'da batıyı tanımak amacıyla ilk geçici elçilikler Lale Devri'nde (Yirmisekiz Mehmet Çelebi - Paris) açılmış; ilk sürekli (daimi) elçilikler ise III. Selim döneminde (Yusuf Agah Efendi - Londra) kurulmuştur.",
  },
  {
    id: 4,
    soru: "Osmanlı Devleti'nde batılılaşma hareketlerinin ilk dönemi olan Lale Devri'ni (1718-1730) sona erdiren ve padişah III. Ahmet'in tahttan indirilip yerine I. Mahmut'un geçmesine neden olan halk ayaklanması aşağıdakilerden hangisidir?",
    secenekler: ["A) Kabakçı Mustafa İsyanı", "B) Patrona Halil İsyanı", "C) Şeyh Bedrettin İsyanı", "D) 31 Mart Vakası", "E) Kuleli Vakası"],
    cevap: 1,
    aciklama: "Lale Devri'ndeki lüks, israf ve İran savaşlarındaki başarısızlıklara tepki olarak çıkan Patrona Halil İsyanı (1730), Lale Devri'ni sonlandırmış ve padişah III. Ahmet'i tahttan indirmiştir.",
  },
  {
    id: 5,
    soru: "Osmanlı Devleti'nde tıp, tarım ve idari alanlarda ilk karantina uygulamasını getirerek modernleşme adımı atan padişah aşağıdakilerden hangisidir?",
    secenekler: ["A) III. Selim", "B) II. Mahmut", "C) Abdülmecid", "D) Abdülaziz", "E) II. Abdülhamid"],
    cevap: 1,
    aciklama: "II. Mahmut, salgın hastalıkların yayılmasını önlemek amacıyla Osmanlı tarihinde ilk kez karantina (usul-i tahaffuz) uygulamasını başlatmıştır.",
  },
  {
    id: 6,
    soru: "Aşağıdakilerden hangisi II. Mahmut Dönemi'nde gerçekleştirilen ıslahatlardan biri değildir?",
    secenekler: [
      "A) Yeniçeri Ocağı'nın kaldırılarak yerine \"Asakir-i Mansure-i Muhammediye\" ordusunun kurulması",
      "B) Divanıhümayun'un kaldırılarak yerine Nazırlıkların (Bakanlıkların) kurulması",
      "C) Memurlara pantolon, ceket ve fes giyme zorunluluğunun getirilmesi",
      "D) Osmanlı tarihindeki ilk resmi gazete olan \"Takvim-i Vekayi\"nin çıkarılması",
      "E) İlk Osmanlı anayasası olan \"Kanun-i Esasi\"nin ilan edilmesi",
    ],
    cevap: 4,
    aciklama: "Kanun-i Esasi'nin ilanı (1876) ve anayasal düzene geçiş II. Mahmut döneminde değil, II. Abdülhamid döneminde gerçekleşmiştir. Diğer şıklar II. Mahmut dönemi gelişmeleridir.",
  },
  {
    id: 7,
    soru: "Osmanlı Devleti'nde Tanzimat Fermanı (1839) ve Islahat Fermanı'nı (1856) yayımlayan, her iki ferman döneminde de tahtta bulunan padişah aşağıdakilerden hangisidir?",
    secenekler: ["A) II. Mahmut", "B) Abdülmecid", "C) Abdülaziz", "D) V. Murat", "E) II. Abdülhamid"],
    cevap: 1,
    aciklama: "Hem 1839 Tanzimat Fermanı'nı hem de 1856 Islahat Fermanı'nı ilan eden padişah Sultan Abdülmecid'dir.",
  },
  {
    id: 8,
    soru: "Tanzimat Fermanı'nın ilan edilmesinde Osmanlı Devleti'nin temel amacı aşağıdakilerden hangisidir?",
    secenekler: [
      "A) Avrupalı devletlerin iç işlerimize karışmasını önlemek ve Mısır Sorunu'nda Avrupa'nın desteğini almak",
      "B) Meşruti yönetime geçerek halkı yönetime katmak",
      "C) Yeniçeri Ocağı'nın isyanlarını tamamen sonlandırmak",
      "D) Azınlıklara ilk kez kendi okullarını açma hakkı tanımak",
      "E) Kapitülasyonların olumsuz ekonomik etkilerini ortadan kaldırmak",
    ],
    cevap: 0,
    aciklama: "Tanzimat Fermanı'nın ilan edilmesindeki en temel dış etken; Mısır (Mehmet Ali Paşa) Sorunu ve Boğazlar Meselesi'nde Avrupalı devletlerin desteğini almak, ayrıca iç işlerimize karışılmasını önlemektir.",
  },
  {
    id: 9,
    soru: "Osmanlı tarihinde padişahın yetkilerini kendi rızasıyla sınırlandırdığı ilk belge olan \"Sened-i İttifak\" (1808), padişah II. Mahmut ile aşağıdaki gruplardan hangisi arasında imzalanmıştır?",
    secenekler: ["A) Yeniçeriler", "B) Genç Osmanlılar", "C) Ayanlar", "D) Jön Türkler", "E) Azınlık temsilcileri"],
    cevap: 2,
    aciklama: "II. Mahmut, tahta çıkmasında büyük rol oynayan taşradaki toprak sahibi nüfuzlu kişiler olan Ayanlar ile Sened-i İttifak'ı imzalamış ve onların varlığını hukuken tanımıştır.",
  },
  {
    id: 10,
    soru: "Osmanlı tarihinde ilk kez \"hukukun üstünlüğü\" ilkesinin kabul edildiği ve padişahın dahi bu kurallara uyacağına söz verdiği demokratikleşme belgesi aşağıdakilerden hangisidir?",
    secenekler: ["A) Sened-i İttifak", "B) Tanzimat Fermanı", "C) Islahat Fermanı", "D) Kanun-i Esasi", "E) Halepa Fermanı"],
    cevap: 1,
    aciklama: "Tanzimat Fermanı ile padişah, ferman hükümlerine bizzat kendisinin de uyacağını belirterek Osmanlı tarihinde ilk kez kanun gücünün ve hukukun üstünlüğü ilkesini kabul etmiştir.",
  },
  {
    id: 11,
    soru: "Avrupa seyahatine çıkan ilk Osmanlı padişahı olan ve kendi heykelini yaptıran ilk padişah olma özelliğini taşıyan Osmanlı hükümdarı kimdir?",
    secenekler: ["A) Abdülmecid", "B) Abdülaziz", "C) II. Abdülhamid", "D) V. Murat", "E) Mehmet Reşat"],
    cevap: 1,
    aciklama: "Padişah Abdülaziz, dış borçlanmanın da etkisiyle prestij ve ittifak arayışı için Avrupa seyahatine çıkan ilk padişah olmuş, ayrıca kendi heykelini yaptıran ilk Osmanlı padişahıdır.",
  },
  {
    id: 12,
    soru: "Osmanlı Devleti'nde Abdülaziz'i tahttan indirip yerine V. Murat'ı tahta çıkarmayı hedefleyen ancak başarısızlıkla sonuçlanan darbe girişimi aşağıdakilerden hangisidir?",
    secenekler: ["A) Kuleli Vakası", "B) Çırağan Baskını", "C) 31 Mart Vakası", "D) Babıali Baskını", "E) Edirne Olayı"],
    cevap: 1,
    aciklama: "Sadrazam Mithat Paşa önderliğindeki cuntanın Abdülaziz'i tahttan indirmesinin ardından, daha sonra onun yerine geçen V. Murat'ı indirip Abdülaziz'i geri getirmeyi hedefleyen askeri girişim Çırağan Baskını (Ali Suavi olayı) olarak bilinir ancak başarısız olmuştur.",
  },
  {
    id: 13,
    soru: "Osmanlı Devleti'nde eğitim alanındaki hizmetleri ve açtığı çok sayıda okul nedeniyle \"Maarifperver\" (Eğitimsever) olarak bilinen padişah aşağıdakilerden hangisidir?",
    secenekler: ["A) II. Mahmut", "B) Abdülmecid", "C) II. Abdülhamid", "D) Abdülaziz", "E) III. Selim"],
    cevap: 2,
    aciklama: "Saltanatı boyunca rüştiyeler, idadiler, Darülfünun (üniversite) ve çok sayıda meslek okulu açtığı için II. Abdülhamid tarih literatüründe \"Maarifperver\" olarak anılır.",
  },
  {
    id: 14,
    soru: "Osmanlı Devleti'nde I. Meşrutiyet'i (1876) ve II. Meşrutiyet'i (1908) ilan ettiren siyasi/aydın gruplar aşağıdakilerin hangisinde sırasıyla doğru olarak verilmiştir?",
    secenekler: ["A) Genç Osmanlılar (Jön Türkler) - İttihat ve Terakki Cemiyeti", "B) İttihat ve Terakki Cemiyeti - Genç Osmanlılar", "C) Ayanlar - Felah-ı Vatan Grubu", "D) Yeniçeriler - Genç Osmanlılar", "E) Hürriyet ve İtilaf Fırkası - İttihat ve Terakki Cemiyeti"],
    cevap: 0,
    aciklama: "I. Meşrutiyet'i (1876) ilan ettiren aydın kadro Genç Osmanlılar (Jön Türkler); II. Meşrutiyet'i (1908) ilan ettiren kadro ise İttihat ve Terakki Cemiyeti'dir.",
  },
  {
    id: 15,
    soru: "Osmanlı Devleti'nde mevcut rejimi (Meşrutiyeti) yıkıp eski düzeni geri getirmek amacıyla çıkarılan \"rejime karşı ilk isyan\" aşağıdakilerden hangisidir?",
    secenekler: ["A) Patrona Halil İsyanı", "B) Kabakçı Mustafa İsyanı", "C) 31 Mart İsyanı", "D) Babıali Baskını", "E) Kuleli Vakası"],
    cevap: 2,
    aciklama: "13 Nisan 1909 (Rumi takvimle 31 Mart 1325) tarihinde çıkan 31 Mart İsyanı, meşrutiyet rejimini yıkıp monarşiyi geri getirmeyi hedefleyen, Osmanlı tarihinde rejime karşı çıkan ilk isyandır.",
  },
  {
    id: 16,
    soru: "31 Mart İsyanı'nı bastırmak amacıyla Selanik'ten yola çıkan Hareket Ordusu'nda Kurmay Başkan olarak görev alan ve bu sayede tarih sahnesine ilk kez çıkan askeri figür kimdir?",
    secenekler: ["A) Enver Paşa", "B) Mustafa Kemal", "C) Mahmut Şevket Paşa", "D) Kazım Karabekir", "E) Cemal Paşa"],
    cevap: 1,
    aciklama: "31 Mart İsyanı'nı bastıran Hareket Ordusu'nun kurmay başkanı olan Mustafa Kemal, bu görevle birlikte tarih sahnesine ilk kez çıkmıştır.",
  },
  {
    id: 17,
    soru: "Osmanlı tarihinde \"Meclis kararıyla\" tahttan indirilen ilk ve ikinci padişahlar aşağıdakilerin hangisinde sırasıyla doğru olarak verilmiştir?",
    secenekler: ["A) III. Selim - II. Mahmut", "B) II. Abdülhamid - Vahdettin", "C) Abdülaziz - V. Murat", "D) II. Osman - Sultan Reşat", "E) II. Abdülhamid - III. Ahmet"],
    cevap: 1,
    aciklama: "Osmanlı tarihinde ilk kez meclis kararıyla tahttan indirilen padişah II. Abdülhamid (31 Mart Vakası sonrası), ikincisi ise Vahdettin (Saltanatın kaldırılması sonrası) olmuştur.",
  },
  {
    id: 18,
    soru: "Mustafa Kemal Atatürk'ün \"Milletin Sarayı\" olarak nitelendirdiği ve Cumhuriyet döneminde de aktif olarak kullanılan tarihi Osmanlı sarayı aşağıdakilerden hangisidir?",
    secenekler: ["A) Topkapı Sarayı", "B) Dolmabahçe Sarayı", "C) Yıldız Sarayı", "D) Çırağan Sarayı", "E) Beylerbeyi Sarayı"],
    cevap: 1,
    aciklama: "Mustafa Kemal Atatürk'ün \"Milletin Sarayı\" olarak adlandırdığı ve ömrünün son dönemini geçirip vefat ettiği saray Dolmabahçe Sarayı'dır.",
  },
  {
    id: 19,
    soru: "1859 yılında padişah Abdülmecid'i tahttan indirip yerine Abdülaziz'i tahta çıkarmayı hedefleyen, ancak önceden haber alınarak engellenen \"Osmanlı tarihindeki ilk demokratik darbe / suikast girişimi\" aşağıdakilerden hangisidir?",
    secenekler: ["A) Kuleli Vakası", "B) Çırağan Baskını", "C) Babıali Baskını", "D) 31 Mart Vakası", "E) Edirne Olayı"],
    cevap: 0,
    aciklama: "1859'da bir grup aydın ve askerin Abdülmecid'i devirip Abdülaziz'i tahta geçirmek için planladığı ancak başlamadan deşifre edilen girişim Kuleli Vakası'dır. Bu olay ilk modern darbe girişimi kabul edilir.",
  },
  {
    id: 20,
    soru: "II. Abdülhamid'i tahttan indirip yerine eski padişah V. Murat'ı tekrar tahta çıkarmayı hedefleyen ancak Ali Suavi'nin öldürülmesiyle başarısız olan darbe girişimi aşağıdakilerden hangisidir?",
    secenekler: ["A) Çırağan Baskını", "B) Kuleli Vakası", "C) Babıali Baskını", "D) 31 Mart Vakası", "E) Edirne Olayı"],
    cevap: 0,
    aciklama: "\"Sarıklı İhtilalci\" olarak bilinen Ali Suavi'nin, II. Abdülhamid'i devirip Çırağan Sarayı'nda gözetim altında tutulan V. Murat'ı tekrar tahta çıkarmak için yaptığı başarısız eylem Çırağan Baskını'dır.",
  },
];
