import { DenemeSorusu } from './deneme1';

export const denemeGB5Baslik = "Güncel Bilgiler - Deneme 5";

export const denemeGB5: DenemeSorusu[] = [
  {
    id: 1,
    soru: "Avrupa Birliği (AB) ve Kuzey Atlantik Antlaşması Örgütü (NATO) genel merkezleri ortak olarak aşağıdaki şehirlerin hangisinde yer almaktadır?",
    secenekler: ["A) Paris", "B) Brüksel", "C) Cenevre", "D) Lahey", "E) Viyana"],
    cevap: 1,
    aciklama: "Hem AB hem de NATO'nun genel merkezleri Belçika'nın Brüksel şehrindedir.",
  },
  {
    id: 2,
    soru: "2026 yılında \"Asya Oyunları\" aşağıdaki ülkelerin hangisinde gerçekleştirilecektir?",
    secenekler: ["A) Kırgızistan", "B) Japonya (Aichi - Nagoya)", "C) Güney Kore", "D) Çin", "E) Hindistan"],
    cevap: 1,
    aciklama: "2026 Asya Oyunları Japonya'nın Aichi-Nagoya bölgelerinde gerçekleştirilecektir.",
  },
  {
    id: 3,
    soru: "Şanghay İşbirliği Örgütü (ŞİÖ) genel merkezi aşağıdaki şehirlerin hangisinde bulunmaktadır?",
    secenekler: ["A) Pekin", "B) Şanghay", "C) Moskova", "D) Taşkent", "E) Tahran"],
    cevap: 0,
    aciklama: "Şanghay İşbirliği Örgütü (ŞİÖ) genel merkezi Çin'in Pekin şehrindedir.",
  },
  {
    id: 4,
    soru: "Tarihte ilk elektrikli \"ampulü\" bularak geceleri aydınlatan ve teknoloji devrimine katkıda bulunan mucit kimdir?",
    secenekler: ["A) Thomas Edison", "B) Graham Bell", "C) Nikola Tesla", "D) Samuel Morse", "E) Albert Einstein"],
    cevap: 0,
    aciklama: "Elektrikli ampulün mucidi Thomas Edison'dur.",
  },
  {
    id: 5,
    soru: "2026 yılı Oscar Ödülleri'nde \"En İyi Kadın Oyuncu\" ödülünü kazanan isim aşağıdakilerden hangisidir?",
    secenekler: ["A) Jessie Buckley", "B) Mikey Madison", "C) Emma Stone", "D) Michelle Yeoh", "E) Jessica Chastain"],
    cevap: 0,
    aciklama: "2026 yılı Oscar En İyi Kadın Oyuncu ödülünü Jessie Buckley (Hamnet filmiyle) kazanmıştır.",
  },
  {
    id: 6,
    soru: "Dünya Sağlık Örgütü (WHO), Dünya Ticaret Örgütü (WTO) ve Uluslararası Çalışma Örgütü (ILO) gibi dev yapıların tamamının merkezi olan şehir aşağıdakilerden hangisidir?",
    secenekler: ["A) Paris", "B) Brüksel", "C) Cenevre", "D) Viyana", "E) New York"],
    cevap: 2,
    aciklama: "WHO, WTO ve ILO gibi BM bağlantılı büyük örgütlerin merkezi İsviçre'nin Cenevre kentindedir.",
  },
  {
    id: 7,
    soru: "Afrika Birliği örgütünün genel merkezi aşağıdaki ülkelerin hangisinde, hangi şehirde bulunmaktadır?",
    secenekler: ["A) Etiyopya - Addis Ababa", "B) Mısır - Kahire", "C) Güney Afrika - Pretoria", "D) Nijerya - Abuja", "E) Kenya - Nairobi"],
    cevap: 0,
    aciklama: "Afrika Birliği genel merkezi Etiyopya'nın başkenti Addis Ababa'dadır.",
  },
  {
    id: 8,
    soru: "Tarihte \"İzafiyet Teorisi\"ni (Görelilik Kuramı) ortaya koyarak fizik biliminde yeni bir dönem başlatan dahi fizikçi kimdir?",
    secenekler: ["A) Albert Einstein", "B) Galileo", "C) Thomas Edison", "D) Alexander Fleming", "E) Charles Richter"],
    cevap: 0,
    aciklama: "İzafiyet Teorisinin kurucusu Albert Einstein'dır.",
  },
  {
    id: 9,
    soru: "UNESCO Yaratıcı Şehirler Ağı'na \"Gastronomi\" alanında 2019 yılında kabul edilen şehrimiz aşağıdakilerden hangisidir?",
    secenekler: ["A) Gaziantep", "B) Hatay", "C) Afyonkarahisar", "D) Adana", "E) Şanlıurfa"],
    cevap: 2,
    aciklama: "2019 yılında Gastronomi alanında ağa kabul edilen şehrimiz Afyonkarahisar'dır.",
  },
  {
    id: 10,
    soru: "2023 yılı Oscar Ödülleri'nde \"En İyi Film\" ve \"En İyi Yönetmen\" ödüllerini toplayan yapım aşağıdakilerden hangisidir?",
    secenekler: ["A) Oppenheimer", "B) Everything Everywhere All At Once", "C) CODA", "D) Nomadland", "E) Parasite"],
    cevap: 1,
    aciklama: "2023 yılında Oscar En İyi Film ödülünü \"Everything Everywhere All At Once\" kazanmıştır.",
  },
  {
    id: 11,
    soru: "Tarihte \"İlk Bilgisayar\" olarak kabul edilen ve ABD ordusu tarafından geliştirilen teknolojik cihazın adı nedir?",
    secenekler: ["A) ENIAC", "B) Altair", "C) Apple I", "D) IBM PC", "E) Colossus"],
    cevap: 0,
    aciklama: "Dünyanın ilk bilgisayarı ENIAC olarak kabul edilir.",
  },
  {
    id: 12,
    soru: "Türkiye Cumhuriyeti'nde kurulan Gelişen 8 Ülke Örgütü (D-8) ve Türk Devletleri Teşkilatı'nın (TDT) sekreterya merkezleri ortak olarak aşağıdaki şehirlerimizin hangisinde yer alır?",
    secenekler: ["A) Ankara", "B) İstanbul", "C) İzmir", "D) Bursa", "E) Antalya"],
    cevap: 1,
    aciklama: "TDT ve D-8 örgütlerinin sekreterya merkezleri İstanbul'da yer almaktadır.",
  },
  {
    id: 13,
    soru: "Tarihte ilk \"telefonu\" icat ederek ses dalgalarını kablo üzerinden iletmeyi başaran mucit kimdir?",
    secenekler: ["A) Graham Bell", "B) Martin Cooper", "C) Samuel Morse", "D) John Logie Baird", "E) Thomas Edison"],
    cevap: 0,
    aciklama: "İlk telefonun mucidi Alexander Graham Bell'dir.",
  },
  {
    id: 14,
    soru: "UNESCO Yaratıcı Şehirler Ağı'na \"Zanaat ve Halk Sanatları\" kategorisinde 2021 yılında katılan şehrimiz hangisidir?",
    secenekler: ["A) Kütahya", "B) Bursa", "C) Şanlıurfa", "D) Gaziantep", "E) İstanbul"],
    cevap: 1,
    aciklama: "2021 yılında Zanaat ve Halk Sanatları kategorisinde ağa katılan şehrimiz Bursa'dır.",
  },
  {
    id: 15,
    soru: "International Monetary Fund (IMF) ve Dünya Bankası genel merkezleri ortak olarak ABD'nin hangi şehrinde yer almaktadır?",
    secenekler: ["A) New York", "B) Washington", "C) Miami", "D) Los Angeles", "E) Chicago"],
    cevap: 1,
    aciklama: "IMF ve Dünya Bankası merkezleri ABD'nin başkenti Washington'dadır.",
  },
  {
    id: 16,
    soru: "Petrol İhraç Eden Ülkeler Örgütü (OPEC) genel merkezi aşağıdaki şehirlerin hangisinde yer almaktadır?",
    secenekler: ["A) Cidde", "B) Tahran", "C) Viyana", "D) Kuveyt", "E) Riyad"],
    cevap: 2,
    aciklama: "OPEC genel merkezi Avusturya'nın Viyana kentindedir.",
  },
  {
    id: 17,
    soru: "2023 yılı Oscar Ödülleri'nde \"En İyi Erkek Oyuncu\" ödülünü (The Whale filmindeki performansıyla) alan aktör kimdir?",
    secenekler: ["A) Brendan Fraser", "B) Adrien Brody", "C) Cillian Murphy", "D) Will Smith", "E) Joaquin Phoenix"],
    cevap: 0,
    aciklama: "2023 yılı Oscar En İyi Erkek Oyuncu ödülünü Brendan Fraser kazanmıştır.",
  },
  {
    id: 18,
    soru: "Türkiye Yüzyılı Maarif Modeli kapsamında \"Ermeni Meselesi\" ve \"Pontus Meselesi\" ifadelerinin başına aşağıdaki kelimelerden hangisi getirilerek müfredat güncellenmiştir?",
    secenekler: ["A) Tarihi", "B) Bölgesel", "C) Asılsız", "D) Küresel", "E) Siyasi"],
    cevap: 2,
    aciklama: "Yeni müfredatta her iki meselenin başına \"Asılsız\" ibaresi (Asılsız Ermeni İddiaları, Asılsız Pontus İddiaları) eklenmiştir.",
  },
  {
    id: 19,
    soru: "2021 yılı Oscar Ödülleri'nde \"En İyi Yönetmen\" ödülünü (Nomadland filmiyle) kazanarak adını tarihe yazdıran kadın yönetmen kimdir?",
    secenekler: ["A) Jane Campion", "B) Chloé Zhao", "C) Emerald Fennell", "D) Greta Gerwig", "E) Sofia Coppola"],
    cevap: 1,
    aciklama: "2021 Oscar En İyi Yönetmen ödülünü alan kadın yönetmen Chloé Zhao'dur.",
  },
  {
    id: 20,
    soru: "UNESCO Yaratıcı Şehirler Ağı'na \"Gastronomi\" alanında 2017 yılında kabul edilen ikinci şehrimiz hangisidir?",
    secenekler: ["A) Gaziantep", "B) Hatay", "C) Afyonkarahisar", "D) Adana", "E) Şanlıurfa"],
    cevap: 1,
    aciklama: "Gastronomi alanında 2017 yılında ağa dahil edilen ikinci şehrimiz Hatay'dır.",
  },
];
