import { DenemeSorusu } from './deneme1';

export const denemeGB1Baslik = "Güncel Bilgiler - Deneme 1";

export const denemeGB1: DenemeSorusu[] = [
  {
    id: 1,
    soru: "Milli Eğitim Bakanlığı'nın yayımladığı \"Türkiye Yüzyılı Maarif Modeli\" kapsamındaki güncellemelerde, \"Kurtuluş Savaşı\" kavramı yerine aşağıdaki kavramlardan hangisi kullanılmaya başlanmıştır?",
    secenekler: ["A) Mavi Vatan", "B) Yeşil Vatan", "C) Gök Vatan", "D) Milli Mücadele", "E) Adalar Denizi"],
    cevap: 3,
    aciklama: "Türkiye Yüzyılı Maarif Modeli kapsamında \"Kurtuluş Savaşı\" yerine \"Milli Mücadele\" kavramı getirilmiştir.",
  },
  {
    id: 2,
    soru: "2026 yılında düzenlenecek olan \"NATO Zirvesi\" aşağıdaki ülkelerin ve şehirlerin hangisinde gerçekleştirilecektir?",
    secenekler: ["A) Fransa - Evian-les-Bains", "B) ABD - Miami", "C) Türkiye - Ankara", "D) İtalya - Taranto", "E) Avusturya - Viyana"],
    cevap: 2,
    aciklama: "2026 NATO Zirvesi Türkiye'nin başkenti Ankara'da yapılacaktır.",
  },
  {
    id: 3,
    soru: "Gelişmiş ekonomileri bir araya getiren \"G7\" zirvesi 2026 yılında aşağıdaki ülkelerin hangisinde gerçekleştirilecektir?",
    secenekler: ["A) İtalya", "B) Kanada", "C) Fransa", "D) Almanya", "E) Japonya"],
    cevap: 2,
    aciklama: "2026 G7 Zirvesi Fransa'nın Evian-les-Bains kasabasında yapılacaktır.",
  },
  {
    id: 4,
    soru: "Birleşmiş Milletler Eğitim, Bilim ve Kültür Örgütü (UNESCO) Yaratıcı Şehirler Ağı'na Türkiye'den \"Gastronomi\" alanında katılan ilk şehir aşağıdakilerden hangisidir?",
    secenekler: ["A) Hatay", "B) Gaziantep", "C) Afyonkarahisar", "D) Adana", "E) Şanlıurfa"],
    cevap: 1,
    aciklama: "Türkiye'den gastronomi alanında ağa kabul edilen ilk şehir 2015 yılında Gaziantep olmuştur.",
  },
  {
    id: 5,
    soru: "Önemli küresel kuruluşlardan biri olan \"Birleşmiş Milletler (BM)\" genel merkezi aşağıdaki şehirlerin hangisinde yer almaktadır?",
    secenekler: ["A) Cenevre", "B) New York", "C) Washington", "D) Paris", "E) Brüksel"],
    cevap: 1,
    aciklama: "Birleşmiş Milletler (BM) genel merkezi ABD'nin New York şehrindedir.",
  },
  {
    id: 6,
    soru: "Tarihte ilk kez \"mors alfabesini\" geliştiren ve telgraf iletişimini pratik bir sisteme kavuşturan mucit aşağıdakilerden hangisidir?",
    secenekler: ["A) Samuel Morse", "B) Graham Bell", "C) Thomas Edison", "D) Guglielmo Marconi", "E) Martin Cooper"],
    cevap: 0,
    aciklama: "Mors alfabesinin mucidi Samuel Morse'tur.",
  },
  {
    id: 7,
    soru: "2026 yılı Oscar Ödülleri'nde \"En İyi Film\" ödülünü kazanan yapım aşağıdakilerden hangisidir?",
    secenekler: ["A) Oppenheimer", "B) Anora", "C) One Battle After Another", "D) CODA", "E) Nomadland"],
    cevap: 2,
    aciklama: "2026 yılı En İyi Film Oscar ödülünü \"One Battle After Another\" kazanmıştır.",
  },
  {
    id: 8,
    soru: "Türkiye'nin ilk milli insansız savaş uçağının adı aşağıdakilerden hangisidir?",
    secenekler: ["A) Kızılelma", "B) Göktürk-UV", "C) Alper", "D) ANKA", "E) Hürjet"],
    cevap: 0,
    aciklama: "Türkiye'nin ilk milli insansız savaş uçağı Kızılelma'dır.",
  },
  {
    id: 9,
    soru: "2024 yılında düzenlenen Paris Olimpiyatları'nda Türkiye toplam kaç madalya kazanmıştır?",
    secenekler: ["A) 3", "B) 5", "C) 8", "D) 10", "E) 12"],
    cevap: 2,
    aciklama: "2024 Paris Olimpiyatları'nda Türkiye toplam 8 madalya kazanmıştır (altın madalya kazanılmamıştır).",
  },
  {
    id: 10,
    soru: "Milli Eğitim Bakanlığı müfredatında yapılan güncellemeyle, Türkiye'nin \"deniz yetki alanını\" tanımlamak üzere kullanılan kavram aşağıdakilerden hangisi olmuştur?",
    secenekler: ["A) Yeşil Vatan", "B) Mavi Vatan", "C) Gök Vatan", "D) Doğu Roma", "E) Adalar Denizi"],
    cevap: 1,
    aciklama: "Deniz yetki alanlarımız yeni müfredatta \"Mavi Vatan\" olarak tanımlanmıştır.",
  },
  {
    id: 11,
    soru: "2026 yılında düzenlenecek olan Havacılık, Uzay ve Teknoloji Festivali (TEKNOFEST) aşağıdaki şehirlerimizin hangisinde gerçekleştirilecektir?",
    secenekler: ["A) İstanbul", "B) Ankara", "C) Şanlıurfa", "D) İzmir", "E) Adana"],
    cevap: 2,
    aciklama: "2026 TEKNOFEST Şanlıurfa'da düzenlenecektir.",
  },
  {
    id: 12,
    soru: "Tarihte \"Richter Ölçeği\"ni geliştirerek depremlerin büyüklüğünü ölçmeyi sağlayan bilim insanı aşağıdakilerden hangisidir?",
    secenekler: ["A) Wilhelm Condrad Röntgen", "B) Charles Frances Richter", "C) Albert Einstein", "D) Galileo", "E) Jonas Salk"],
    cevap: 1,
    aciklama: "Richter ölçeğinin mucidi deprem bilimci Charles Frances Richter'dir.",
  },
  {
    id: 13,
    soru: "Uluslararası Adalet Divanı (UAD) aşağıdaki ülkelerin hangisinde, hangi şehirde faaliyet göstermektedir?",
    secenekler: ["A) İsviçre - Cenevre", "B) Fransa - Paris", "C) Hollanda - Lahey", "D) Belçika - Brüksel", "E) İtalya - Roma"],
    cevap: 2,
    aciklama: "Uluslararası Adalet Divanı (UAD) Hollanda'nın Lahey kentindedir.",
  },
  {
    id: 14,
    soru: "2026 yılı \"Eurovision Şarkı Yarışması\" aşağıdaki ülkelerin hangisinde düzenlenecektir?",
    secenekler: ["A) Türkiye", "B) Avusturya", "C) İtalya", "D) Fransa", "E) Macaristan"],
    cevap: 1,
    aciklama: "2026 Eurovision şarkı yarışması Avusturya'nın Viyana kentinde yapılacaktır.",
  },
  {
    id: 15,
    soru: "Tarihteki \"ilk dünya haritasını\" çizen ünlü Türk denizcisi ve coğrafyacısı aşağıdakilerden hangisidir?",
    secenekler: ["A) Piri Reis", "B) Ali Kuşçu", "C) Seydi Ali Reis", "D) Katip Çelebi", "E) Evliya Çelebi"],
    cevap: 0,
    aciklama: "İlk dünya haritasını çizen denizcimiz Piri Reis'tir.",
  },
  {
    id: 16,
    soru: "Milli Eğitim Bakanlığı'nın yeni müfredatında, \"Coğrafi Keşifler\" kavramı yerine aşağıdaki ifadelerden hangisi getirilmiştir?",
    secenekler: ["A) Doğu Roma", "B) Sömürgeciliğin Başlangıcı", "C) Sevk ve İskan Kanunu", "D) Asılsız Ermeni İddiaları", "E) Türkistan"],
    cevap: 1,
    aciklama: "Yeni müfredatta \"Coğrafi Keşifler\" yerine \"Sömürgeciliğin Başlangıcı\" kavramı kabul edilmiştir.",
  },
  {
    id: 17,
    soru: "UNESCO Yaratıcı Şehirler Ağı'na 2025 yılında \"Edebiyat\" alanında dahil edilen Türkiye şehri aşağıdakilerden hangisidir?",
    secenekler: ["A) Kırşehir", "B) Şanlıurfa", "C) Kahramanmaraş", "D) Bursa", "E) Adana"],
    cevap: 2,
    aciklama: "2025 yılında Edebiyat kategorisinde ağa giren şehrimiz Kahramanmaraş'tır.",
  },
];
