import { DenemeSorusu } from './deneme1';

export const denemeTurkce1Baslik = "Ses Bilgisi ve Yazım Kuralları";

export const denemeTurkce1: DenemeSorusu[] = [
  {
    id: 1,
    soru: "\"Sonsuz gurbete doğru gönlümü alır akşam, / Yalnızlığın içinde kaybolurum o anda.\" Bu dizelerde aşağıdaki ses olaylarından hangisi birden fazla örneklenmiştir?",
    secenekler: ["A) Ünsüz yumuşaması", "B) Ünlü düşmesi", "C) Ünsüz benzeşmesi", "D) Ünsüz türemesi", "E) Ünlü daralması"],
    cevap: 1,
    aciklama: "Dizelerde \"gönlümü\" (gönül-ü) ve \"yalnızlığın\" (yalın-ız-lık) sözcüklerinde ünlü düşmesi gerçekleşmiştir. İki adet ünlü düşmesi olduğu için doğru cevap B'dir.",
  },
  {
    id: 2,
    soru: "Aşağıdaki atasözlerinin hangisinde, ünsüz yumuşaması (değişmesi) ve ünsüz benzeşmesinin (sertleşmesinin) bir arada görüldüğü türemiş bir sözcük vardır?",
    secenekler: ["A) Attan düşen ölmez, eşekten düşen ölür.", "B) Ateş düştüğü yeri yakar.", "C) Dost dostun ayıbını yüzüne söyler.", "D) Büyük başın derdi büyük olur.", "E) Akıllı düşman, akılsız dosttan hayırlıdır."],
    cevap: 1,
    aciklama: "\"Düştüğü\" sözcüğünün kökü \"düş-\" fiilidir. Sert ünsüzle bittiği için gelen \"-dük\" eki \"-tük\"e dönüşmüştür (benzeşme). Sözcük ünlüyle başlayan \"-ü\" ekini alınca \"-k\" sesi \"-ğ\"ye dönüşmüştür (yumuşama).",
  },
  {
    id: 3,
    soru: "Türkçede \"y\" kaynaştırma ünsüzü \"de-\", \"ye-\" fiillerinde ve \"ne\" sözcüğünde darlaşmaya sebep olur. Bu sözcükler dışında darlaştırma yaparsa yazım yanlışı ortaya çıkar. Buna göre aşağıdaki cümlelerin hangisinde bir yazım yanlışı yapılmıştır?",
    secenekler: [
      "A) Soruları hiç çekinmeden yanıtlayan öğrenciyi tebrik etti.",
      "B) Bizimle geziye gelmeyeceğini dün akşam bize de söyledi.",
      "C) Yıllardır görmediği arkadaşını karşısında görünce ağlamaya başladı.",
      "D) Sınav sonuçlarının haftaya açıklanacağını bekliyeceğini söyledi.",
      "E) Herkesin duruma kendince bir yorum getirmesini anlayamıyorum.",
    ],
    cevap: 3,
    aciklama: "\"y\" kaynaştırma ünsüzü \"de-\" ve \"ye-\" fiilleri dışında darlaşma yaparsa yazım yanlışı olur. \"bekliyeceğini\" sözcüğünün doğrusu \"bekleyeceğini\" olmalıdır.",
  },
  {
    id: 4,
    soru: "Aşağıdaki cümlelerin hangisinde yansımadan türemiş bir sözcükte ses olayı gerçekleşmiştir?",
    secenekler: [
      "A) Sitenin istinat duvarları bir anda büyük bir gürültüyle çatladı.",
      "B) Sınavı kazandığını duyunca gözündeki parıltıyı görmeniz gerekiyordu.",
      "C) Kamyonun ön lastiği Zigana Tüneli'nde ansızın patlıyor.",
      "D) Camı tıkla bakalım içeridekiler hâlâ uyuyorlar mı bir bak.",
      "E) Ofladı, pufladı ama bir türlü babasını yeni telefon için ikna edemedi.",
    ],
    cevap: 2,
    aciklama: "\"patlıyor\" sözcüğünün kökü yansıma bir ses olan \"pat\"tır. \"-la\" yapım ekini alarak \"patla-\" fiili olmuştur. \"-yor\" eki gelince \"patlıyor\" şeklinde ünlü daralmasına uğramıştır.",
  },
  {
    id: 5,
    soru: "\"b\" ünsüzünün kendinden önce gelen \"n\" ünsüzünü \"m\"ye dönüştürmesine n-m değişmesi denir. Özel isim ve birleşik sözcüklerde bu değişim gerçekleşmez. Aşağıdakilerin hangisinde bu kurala uymamaktan kaynaklanan bir yazım yanlışı vardır?",
    secenekler: [
      "A) Safranbolu evlerini görmek için bu yaz bir gezi planlıyoruz.",
      "B) İstanbul'un bitmek bilmeyen trafiği insanları canından bezdiriyor.",
      "C) Sonbaharın o hüzünlü havası şairlerin ilham kaynağı olmuştur.",
      "D) Gerçekleri bildiği hâlde canbaz gibi oynamaya devam ediyordu.",
      "E) Binbaşı rütbesine yükselen amcamı tebrik etmek için aradım.",
    ],
    cevap: 3,
    aciklama: "\"Canbaz\" sözcüğünün doğru yazımı n-m değişmesi kuralı gereğince \"cambaz\" olmalıdır. Safranbolu ve binbaşı sözcükleri birleşik/özel isim olduğu için istisnadır ve yazımları doğrudur.",
  },
  {
    id: 6,
    soru: "Aşağıdaki cümlelerin hangisinde büyük harflerin kullanımıyla ilgili bir yazım yanlışı yapılmıştır?",
    secenekler: [
      "A) Çocukken gittiğim Uzungöl beldesi, unutamadığım yerlerdendir.",
      "B) Osmanlı Devleti'nde Batılılaşma hamlesi Tanzimat Fermanı ile başlamıştır.",
      "C) Antep Fıstığı, bölge ekonomisine ciddi bir katkı sağlamaktadır.",
      "D) Eski Yunan tanrıları, Homeros'un eşsiz eserlerinde ana kahramanlardır.",
      "E) Uzak Doğu'dan gelen heyeti Vali Bey dün makamında kabul etti.",
    ],
    cevap: 2,
    aciklama: "Yer, millet ve kişi adlarıyla kurulan birleşik kelimelerde sadece özel adlar büyük harfle başlar. \"Antep fıstığı\" şeklinde yazılmalıdır; fıstığın \"f\"si küçük olmalıdır.",
  },
  {
    id: 7,
    soru: "Aşağıdaki cümlelerin hangisinde \"de\" bağlacının veya \"-de\" ekinin yazımıyla ilgili bir yanlışlık yapılmıştır?",
    secenekler: [
      "A) Ayşe de bizimle birlikte sinemaya gelmek istiyormuş.",
      "B) Durumu oğluna da bildirdi ama henüz bir cevap alamadı.",
      "C) Bu yaştan sonra da her gün düzenli spor yapmak zor geliyor.",
      "D) Gidip te gelmemek var, gelip de görmemek var şu dünyada.",
      "E) Dosyaları göstererek \"Onları da bana ver.\" dedi usulca.",
    ],
    cevap: 3,
    aciklama: "Ayrı yazılan \"de\" bağlacı hiçbir zaman \"ta / te\" biçiminde yazılamaz. \"Gidip de gelmemek\" şeklinde olmalıdır.",
  },
  {
    id: 8,
    soru: "Aşağıdaki cümlelerin hangisinde \"ki\" bağlacının veya \"-ki\" ekinin yazımıyla ilgili bir yanlışlık yapılmıştır?",
    secenekler: [
      "A) Kitaptaki her söz belli ki sıkı bir düşünce eleğinden geçirilmiş.",
      "B) Duydum ki bizi bırakıp çok uzaklara gidecekmişsin.",
      "C) Evdeki kitapların hepsini kütüphaneye bağışlamaya karar verdi.",
      "D) Öyle bir genç ki taşı sıksa suyunu çıkarır, herkes bilir.",
      "E) Madem ki gelmeyecektin, neden bize daha önceden haber vermedin?",
    ],
    cevap: 4,
    aciklama: "Kalıplaşmış olarak bitişik yazılan \"ki\" bağlaçları arasında \"mademki\" de vardır; bu sözcük bitişik yazılmalıdır.",
  },
  {
    id: 9,
    soru: "Aşağıdaki cümlelerin hangisinde kısaltmaların yazımı veya kısaltmalara gelen eklerin yazılışıyla ilgili bir yanlışlık yapılmıştır?",
    secenekler: [
      "A) Bu konuda TDK'nın sözlüğü en temel başvuru kaynağımız olmalıdır.",
      "B) ABD'nin Türkiye ile olan ilişkilerinde yeni bir döneme girildi.",
      "C) Kâğıdı 10 cm'lik bölümlere ayırarak titizlikle çalıştı.",
      "D) BM'nin son yaptığı toplantıda küresel iklim krizi ele alındı.",
      "E) ASELSAN'da çalışan mühendislerin başarısı göğsümüzü kabarttı.",
    ],
    cevap: 0,
    aciklama: "Büyük harflerle yapılan kısaltmalara getirilen eklerde kısaltmanın son harfinin okunuşu esas alınır. \"TDK'nin\" şeklinde olmalıdır (\"ka\" ince ünlülü okunduğu için).",
  },
  {
    id: 10,
    soru: "Aşağıdaki cümlelerin hangisinde sayıların yazımı ile ilgili bir yanlışlık yapılmıştır?",
    secenekler: [
      "A) Sınava hazırlanırken her gün en az 150 soru çözmeye çalışıyordu.",
      "B) Bayram harçlığı olarak çocukların hepsine 20'şer lira verdik.",
      "C) Bankadan yüz otuz bin lira kredi çekerek iş yeri açtı.",
      "D) Organizasyona katılan davetliler salona üçerli gruplar hâlinde alındı.",
      "E) Kitabın 8'inci maddesinde yer alan kuralları dikkatlice okudu.",
    ],
    cevap: 1,
    aciklama: "Üleştirme sayıları rakamla değil daima yazıyla belirtilir. \"20'şer\" değil \"yirmişer\" şeklinde yazılmalıdır.",
  },
  {
    id: 11,
    soru: "Aşağıdaki sözcüklerin hangisinde büyük ünlü uyumuna uymayan bir ek kullanılmamıştır?",
    secenekler: [
      "A) Akşamleyin erkenden odasına çekilip uyudu.",
      "B) Yarın Kübra bizimle geziye gelemiyormuş.",
      "C) Kuruyan yapraklar yeşilimtırak bir renk aldı.",
      "D) Çocukluğundan beri bu köyde sakin bir hayat sürüyor.",
      "E) Meslektaşları ile akşamki toplantı için buluştu.",
    ],
    cevap: 3,
    aciklama: "\"-leyin\", \"-yor\", \"-ımtrak\", \"-taş\" ekleri büyük ünlü uyumunu bozan eklerdendir. D seçeneğindeki \"çocukluğundan\" sözcüğündeki tüm ekler uyuma uyumludur.",
  },
  {
    id: 12,
    soru: "Aşağıdaki cümlelerin hangisinde altı çizili sözcüğün yazımı doğrudur?",
    secenekler: [
      "A) Karşıma birdenbire çıkınca ne söyleyeceğimi unuttum.",
      "B) Bu işten vaz geçmek onun için hiç de kolay olmayacak.",
      "C) Velilerle yüzyüze iletişime geçmek her zaman daha etkilidir.",
      "D) Her hangi bir şeye ihtiyacın olursa beni aramaktan çekinme.",
      "E) Yazları Avrupa' lı arkadaşlarıyla Akdeniz'de buluşuyor.",
    ],
    cevap: 0,
    aciklama: "\"birdenbire\" bitişik yazılır (A doğru). \"vazgeçmek\" bitişik, \"yüz yüze\" ayrı, \"herhangi bir\" bitişik yazılmalı, \"Avrupalı\" kesme işareti almadan yazılmalıdır.",
  },
  {
    id: 13,
    soru: "Aşağıdaki cümlelerin hangisinde ünsüz benzeşmesi (sertleşmesi) kuralına uyulmamasından kaynaklanan bir yazım yanlışı vardır?",
    secenekler: [
      "A) Sınavda heyecanlandığı için bildiği soruları bile yapamadı.",
      "B) Dün sabahdan beri aralıksız yağan yağmur hayatı olumsuz etkiledi.",
      "C) Yolculuk esnasında kimseyle konuşmamayı tercih etti.",
      "D) Sınıftan çıkan öğrencilerin birçoğu kütüphaneye gitti.",
      "E) 1925'te doğan dedem, köyün en saygın insanlarından biriydi.",
    ],
    cevap: 1,
    aciklama: "Sert ünsüzle (h) biten \"sabah\" sözcüğüne gelen \"-dan\" eki sertleşerek \"sabahtan\" olmalıdır.",
  },
  {
    id: 14,
    soru: "Aşağıdaki cümlelerin hangisinde satır sonunda kelimelerin bölünmesiyle ilgili bir yanlışlık yapılmıştır?",
    secenekler: ["A) ...il-kokulda...", "B) ...ba-şöğretmen...", "C) ...Ankara'daki...", "D) ...a-rabasıyla...", "E) ...il-çesindeki..."],
    cevap: 3,
    aciklama: "Kelimeler satır sonunda ve başında bir tek harf kalacak şekilde bölünemez. \"a-rabasıyla\" bölünmesi yanlıştır; doğrusu \"ara-basıyla\" olmalıdır.",
  },
  {
    id: 15,
    soru: "Aşağıdaki cümlelerin hangisinde bir yazım yanlışı yoktur?",
    secenekler: [
      "A) Bu binanın projesini Avusturyalı bir mimarla çizmişler.",
      "B) Buraya en kısa zamanda yeni bir yaya geçiti yapılacak.",
      "C) Şenliklerin bu yıl Mayıs ayında başlayacağı duyuruldu.",
      "D) Kitabın önsözünü dikkatlice okumadan içeriğe geçmeyin.",
      "E) Pazardan ikişer kilo domates molap aldık.",
    ],
    cevap: 0,
    aciklama: "A seçeneği tamamen doğrudur. B'de \"geçidi\" olmalı (yumuşama), C'de \"mayıs\" küçük harfle yazılmalı, D'de \"ön sözü\" ayrı yazılmalı, E'de \"domates molates\" gibi bir ikileme kastediliyorsa ayrı yazılmalıdır.",
  },
];
