import { DenemeSorusu } from './deneme1';

export const deneme7Baslik = "Milli Mücadele Hazırlık Dönemi ve Cemiyetler";

export const deneme7: DenemeSorusu[] = [
  {
    id: 1,
    soru: "Mondros Mütarekesi'nden sonra İzmir'in işgalinin haksız olduğunu, Türklerin çoğunlukta olduğunu ve katliamların arkasında Yunanların bulunduğunu uluslararası alanda belirten \"ilk uluslararası rapor\" aşağıdakilerden hangisidir?",
    secenekler: ["A) Amiral Bristol Raporu", "B) General Harbourd Raporu", "C) Milne Raporu", "D) Dr. Esat Işık Raporu", "E) Samsun Raporu"],
    cevap: 0,
    aciklama: "Amiral Bristol Raporu, İzmir'in işgalinin ardından bölgeye gönderilen heyetin hazırladığı, Türk tezlerinin doğruluğunu ve Yunan işgalinin haksız olduğunu dünyaya duyuran ilk uluslararası rapordur.",
  },
  {
    id: 2,
    soru: "Milli Mücadele döneminde kurulan \"ilk yararlı cemiyet\" aşağıdakilerden hangisidir?",
    secenekler: ["A) Trakya-Paşaeli Müdafaa-i Hukuk Cemiyeti", "B) Kars İslam Şurası", "C) Doğu Anadolu Müdafaa-i Hukuk Cemiyeti", "D) Kilikyalılar Cemiyeti", "E) Anadolu Kadınları Müdafaa-i Vatan Cemiyeti"],
    cevap: 1,
    aciklama: "Mondros Mütarekesi'nden sonra Ermeni ve Gürcü tehdidine karşı kurulan Kars İslam Şurası, Milli Mücadele döneminde kurulan ilk yararlı cemiyettir.",
  },
  {
    id: 3,
    soru: "Milli Mücadele'de silahlı direniş unsurlarını tanımlayan \"Kuvayımilliye\" teriminin ilk kez geçtiği tarihi belge veya rapor aşağıdakilerden hangisidir?",
    secenekler: ["A) Amiral Bristol Raporu", "B) Dr. Esat Işık Raporu", "C) Amasya Genelgesi", "D) Havza Genelgesi", "E) Erzurum Kongresi Tüzüğü"],
    cevap: 1,
    aciklama: "Yararlı cemiyetlerden olan Milli Kongre Cemiyeti'nin kurucusu Dr. Esat Işık, hazırladığı raporda milli direniş güçlerini tanımlamak için \"Kuvayımilliye\" terimini ilk kez kullanan isim olmuştur.",
  },
  {
    id: 4,
    soru: "Milli Mücadele döneminde kurulan zararlı cemiyetlerden hangisi, diğerlerinden farklı olarak Türk ve Müslümanlar tarafından kurulmayıp azınlıklar (Yahudiler) tarafından kendi çıkarlarını korumak amacıyla kurulmuş ve amacına ulaşmıştır?",
    secenekler: ["A) Mavri Mira", "B) Pontus Rum", "C) Alyans İsrailit - Maccabi", "D) Hınçak ve Taşnak", "E) İngiliz Muhipleri Cemiyeti"],
    cevap: 2,
    aciklama: "Alyans İsrailit ve Maccabi cemiyetleri, azınlık olan Yahudiler tarafından kurulmuştur. Diğer azınlık cemiyetleri toprak kazanmayı hedeflerken, bu cemiyet ticari ve ekonomik ayrıcalıklarını korumayı hedeflemiş ve amacına ulaşmıştır.",
  },
  {
    id: 5,
    soru: "Mustafa Kemal'in İstanbul hükümetinin işgallere karşı tepkisiz kalması üzerine, yakın arkadaşı Fethi Okyar ile birlikte İstanbul'da çıkardığı ve Milli Mücadele fikirlerini yaymaya çalıştığı gazete aşağıdakilerden hangisidir?",
    secenekler: ["A) Minber", "B) İrade-i Milliye", "C) Hakimiyet-i Milliye", "D) Tasvir-i Efkar", "E) Tercüman-ı Hakikat"],
    cevap: 0,
    aciklama: "Mustafa Kemal, Mondros sonrasında İstanbul'da bulunduğu dönemde Fethi Okyar ile birlikte milli davanın sesini duyurmak için Minber gazetesini çıkarmıştır.",
  },
  {
    id: 6,
    soru: "Milli Mücadele'nin \"gerekçesi, amacı ve yöntemi\" ilk kez aşağıdaki belgelerin hangisinde hukuki ve siyasi bir dille belirtilmiştir?",
    secenekler: ["A) Amasya Genelgesi", "B) Erzurum Kongresi", "C) Havza Genelgesi", "D) Misakımilli Beyannamesi", "E) Amasya Protokolü"],
    cevap: 0,
    aciklama: "22 Haziran 1919 tarihli Amasya Genelgesi; gerekçesi, amacı ve yöntemi ile ihtilal bildirisi niteliğindedir.",
  },
  {
    id: 7,
    soru: "Türk tarihinde \"milli egemenlikten\" ve \"milli bağımsızlıktan\" \"ilk kez birlikte bahseden\" tarihi vesika aşağıdakilerden hangisidir?",
    secenekler: ["A) Sivas Kongresi Kararları", "B) Erzurum Kongresi Kararları", "C) Amasya Genelgesi", "D) Havza Genelgesi", "E) Teşkilat-ı Esasiye Kanunu"],
    cevap: 2,
    aciklama: "Amasya Genelgesi'ndeki \"Milletin bağımsızlığını yine milletin azim ve kararı kurtaracaktır\" maddesi, her iki kavramın ilk kez yan yana geçtiği maddedir.",
  },
  {
    id: 8,
    soru: "Amasya Genelgesi'nde yer alan \"Vatanın bütünlüğü ve milletin bağımsızlığı tehlikededir\" maddesi Milli Mücadele'nin hangi unsurunu ortaya koymaktadır?",
    secenekler: ["A) Amacını", "B) Yöntemini", "C) Gerekçesini", "D) Kadrosunu", "E) Mali kaynağını"],
    cevap: 2,
    aciklama: "Vatanın ve milletin tehlikede olması, bu savaşın neden yapılması gerektiğini açıklayan en temel gerekçedir.",
  },
  {
    id: 9,
    soru: "Milli Mücadele döneminde \"Milli sınırlardan (Vatan bir bütündür, bölünemez)\" ilk kez nerede bahsedilmiştir?",
    secenekler: ["A) Amasya Genelgesi", "B) Erzurum Kongresi", "C) Sivas Kongresi", "D) Misakımilli", "E) Havza Genelgesi"],
    cevap: 1,
    aciklama: "Milli sınırlardan (vatan sınırlarından) ilk kez bölgesel toplanan ancak ulusal kararlar alan Erzurum Kongresi'nde bahsedilmiştir.",
  },
  {
    id: 10,
    soru: "Temsil Heyeti'nin \"kurulma fikri\", \"bölgesel olarak kurulması\" ve \"tüm yurdu temsil edecek şekilde sayısının artırılması\" gelişmeleri sırasıyla aşağıdakilerin hangisinde doğru verilmiştir?",
    secenekler: ["A) Amasya Genelgesi - Erzurum Kongresi - Sivas Kongresi", "B) Erzurum Kongresi - Sivas Kongresi - Amasya Protokolü", "C) Amasya Genelgesi - Sivas Kongresi - Erzurum Kongresi", "D) Erzurum Kongresi - Amasya Genelgesi - Sivas Kongresi", "E) Havza Genelgesi - Erzurum Kongresi - Amasya Protokolü"],
    cevap: 0,
    aciklama: "Temsil Heyeti'nin; kurulma fikri Amasya Genelgesi'nde ortaya atılmış, bölgesel olarak kurulması Erzurum Kongresi'nde gerçekleşmiş, tüm yurdu temsil edecek hale gelmesi ise Sivas Kongresi'nde sağlanmıştır.",
  },
  {
    id: 11,
    soru: "Milli Mücadele'de \"Manda ve himaye\" fikri ilk kez nerede reddedilmiş ve kesin olarak nerede tamamen gündemden çıkarılmıştır?",
    secenekler: ["A) Sivas Kongresi - Erzurum Kongresi", "B) Erzurum Kongresi - Sivas Kongresi", "C) Amasya Genelgesi - Erzurum Kongresi", "D) Erzurum Kongresi - Misakımilli", "E) Havza Genelgesi - Sivas Kongresi"],
    cevap: 1,
    aciklama: "Manda ve himaye fikri ilk kez Erzurum Kongresi'nde reddedilmiş; Sivas Kongresi'nde ise kesin ve nihai olarak tamamen gündemden çıkarılmıştır.",
  },
  {
    id: 12,
    soru: "Sivas Kongresi'nde Temsil Heyeti'nin yürütme yetkisini ilk kez kullanarak \"Batı Cephesi Komutanlığı'na\" atadığı askeri ve siyasi figür aşağıdakilerden hangisidir?",
    secenekler: ["A) Ali Fuat Cebesoy", "B) İsmet İnönü", "C) Kazım Karabekir", "D) Fevzi Çakmak", "E) Refet Bele"],
    cevap: 0,
    aciklama: "Sivas Kongresi'nde Temsil Heyeti, Ali Fuat Cebesoy'u Batı Cephesi Kuvayımilliye Komutanlığı'na atayarak adeta bir hükümet gibi çalışıp yürütme yetkisini ilk kez kullanmıştır.",
  },
  {
    id: 13,
    soru: "Sivas Kongresi'nin başarıyla tamamlanmasının ardından, istifa etmek zorunda kalan Damat Ferit Paşa'nın yerine göreve getirilen yeni sadrazam kimdir?",
    secenekler: ["A) Ali Rıza Paşa", "B) Salih Paşa", "C) Tevfik Paşa", "D) Ahmet İzzet Paşa", "E) Kamil Paşa"],
    cevap: 0,
    aciklama: "Temsil Heyeti'nin Sivas Kongresi'ndeki başarısı üzerine baskılara dayanamayan Damat Ferit Paşa istifa etmiş, yerine Milli Mücadele'ye daha ılımlı bakan Ali Rıza Paşa hükümeti kurulmuştur.",
  },
  {
    id: 14,
    soru: "İstanbul Hükümeti'nin, Anadolu'daki Milli Mücadele hareketini ve \"Temsil Heyeti'nin varlığını resmen ve hukuken tanıdığı\" ilk gelişme aşağıdakilerden hangisidir?",
    secenekler: ["A) Amasya Görüşmeleri (Protokolü)", "B) Bilecik Mülakatı", "C) Erzurum Kongresi", "D) Son Osmanlı Mebusan Meclisi'nin açılması", "E) Mudanya Mütarekesi"],
    cevap: 0,
    aciklama: "Temsil Heyeti ile İstanbul Hükümeti arasında yapılan Amasya Görüşmeleri (Protokolü) ile İstanbul hükümeti, Temsil Heyeti'ni ve Anadolu hareketini resmen ve hukuken tanımıştır.",
  },
  {
    id: 15,
    soru: "12 Ocak 1920'de toplanan \"Son Osmanlı Mebusan Meclisi'nde\" kabul edilen ve Milli Mücadele'nin siyasi bağımsızlık programını oluşturan tarihi karar aşağıdakilerden hangisidir?",
    secenekler: ["A) Teşkilat-ı Esasiye", "B) Misakımilli", "C) Sened-i İttifak", "D) Kanun-i Esasi", "E) Takrir-i Sükun"],
    cevap: 1,
    aciklama: "Son Osmanlı Mebusan Meclisi'nde Felah-ı Vatan grubunun da desteğiyle kabul edilen Misakımilli (Milli Ant), sınırlarımızı ve bağımsızlık şartlarımızı dünyaya duyuran tarihi karardır.",
  },
  {
    id: 16,
    soru: "Misakımilli kararlarının Osmanlı Mebusan Meclisi'nde kabul edilmesinin ardından, İtilaf Devletleri'nin bu kararlara tepki olarak 16 Mart 1920'de resmen işgal ettiği şehir aşağıdakilerden hangisidir?",
    secenekler: ["A) İzmir", "B) İstanbul", "C) Ankara", "D) Samsun", "E) Adana"],
    cevap: 1,
    aciklama: "Mebusan Meclisi'nin Misakımilli'yi ilan etmesi üzerine İtilaf Devletleri, 16 Mart 1920'de Osmanlı'nın başkenti İstanbul'u resmen işgal etmiş ve meclisi dağıtmıştır.",
  },
  {
    id: 17,
    soru: "Mondros Mütarekesi'nden sonra Anadolu'da başlayan işgallere karşı Ankara'da açılan I. TBMM'ye karşı çıkan isyanların genel ve ortak amacı aşağıdakilerden hangisidir?",
    secenekler: ["A) Saltanatı tamamen ortadan kaldırmak", "B) TBMM'yi ve milli mücadeleyi ortadan kaldırmak", "C) Azınlıkların kendi devletlerini kurmalarını sağlamak", "D) İtilaf Devletleri ile yeni bir mütareke imzalamak", "E) Halifelik makamını Ankara'ya taşımak"],
    cevap: 1,
    aciklama: "Gerek azınlıkların gerekse İstanbul hükümeti ve İtilaf Devletleri'nin çıkardığı tüm isyanların ortak amacı; Anadolu'da yeni kurulan TBMM'yi ve milli egemenliğe dayalı kurtuluş hareketini ortadan kaldırmaktır.",
  },
  {
    id: 18,
    soru: "Aşağıdakilerden hangisi TBMM'ye karşı doğrudan İstanbul Hükümeti tarafından kurulan askeri güçtür?",
    secenekler: ["A) Kuvayıinzibatiye (Hilafet Ordusu)", "B) Kuvayımilliye", "C) Merkez Ordusu", "D) Yeşil Ordu", "E) Asakir-i Mansure"],
    cevap: 0,
    aciklama: "Doğrudan İstanbul Hükümeti tarafından TBMM'ye karşı kurulan askeri gücün adı Kuvayıinzibatiye (Hilafet Ordusu) olarak bilinir.",
  },
  {
    id: 19,
    soru: "TBMM'ye karşı çıkan isyanlar içerisinde \"en uzun süreli isyan\" ile \"en geniş kapsamlı isyan\" sırasıyla aşağıdakilerin hangisinde doğru verilmiştir?",
    secenekler: ["A) Çerkez Ethem İsyanı - Koçgiri İsyanı", "B) Demirci Mehmet Efe İsyanı - Anzavur İsyanı", "C) Koçgiri İsyanı - Çerkez Ethem İsyanı", "D) Pontus Rum İsyanı - Koçgiri İsyanı", "E) Anzavur İsyanı - Pontus Rum İsyanı"],
    cevap: 3,
    aciklama: "TBMM'ye karşı çıkan isyanlar içinde en uzun süreli olanı Pontus Rum İsyanı; en geniş kapsamlı isyan ise Koçgiri İsyanıdır.",
  },
  {
    id: 20,
    soru: "Yararlı cemiyetlerin tek bir çatı altında birleştirilerek \"Anadolu ve Rumeli Müdafaa-i Hukuk Cemiyeti\" adını alması aşağıdaki gelişmelerin hangisinde gerçekleşmiştir?",
    secenekler: ["A) Amasya Genelgesi", "B) Erzurum Kongresi", "C) Sivas Kongresi", "D) Amasya Görüşmeleri", "E) TBMM'nin Açılışı"],
    cevap: 2,
    aciklama: "Bölgesel kurtuluş çareleri arayan tüm yararlı cemiyetler, Sivas Kongresi'nde tek bir merkezden yönetilmek üzere \"Anadolu ve Rumeli Müdafaa-i Hukuk Cemiyeti\" adı altında birleştirilmiştir.",
  },
];
