import { DenemeSorusu } from './deneme1';

export const deneme4Baslik = "Osmanlı Duraklama, Gerileme ve Dağılma Dönemi Siyasi Tarihi";

export const deneme4: DenemeSorusu[] = [
  {
    id: 1,
    soru: "Osmanlı Devleti'nde \"Yeniçeri Ocağı'nı kaldırma fikrini\" ilk kez ortaya atan ancak bu fikri hayatıyla ödeyen padişah ve bu fikrin doğmasına yol açan kuşatma aşağıdakilerin hangisinde doğru verilmiştir?",
    secenekler: ["A) II. Osman (Genç Osman) - Hotin Kuşatması", "B) IV. Murat - Bağdat Kuşatması", "C) II. Mustafa - II. Viyana Kuşatması", "D) III. Selim - Akka Kuşatması", "E) I. Ahmet - Tebriz Seferi"],
    cevap: 0,
    aciklama: "II. Osman (Genç Osman), Hotin Kuşatması (1621) sırasında yeniçerilerin isteksizliğini bizzat görerek Yeniçeri Ocağı'nı kaldırma kararı almıştır. Ancak bu gizli planı öğrenen yeniçeriler isyan ederek Genç Osman'ı tahttan indirip Yedikule Zindanları'nda şehit etmişlerdir.",
  },
  {
    id: 2,
    soru: "Osmanlı Devleti ile Safevi Devleti (İran) arasında imzalanan ve günümüz Türkiye-İran sınırını büyük ölçüde çizen antlaşma aşağıdakilerden hangisidir?",
    secenekler: ["A) Amasya Antlaşması", "B) Ferhat Paşa Antlaşması", "C) Nasuh Paşa Antlaşması", "D) Serav Antlaşması", "E) Kasr-ı Şirin Antlaşması"],
    cevap: 4,
    aciklama: "IV. Murat'ın Bağdat Seferi sonrasında 1639 yılında imzalanan Kasr-ı Şirin Antlaşması, Türk-İran sınırını büyük ölçüde belirlemiş ve günümüzde de hala geçerliliğini koruyan sınır hattını çizmiştir.",
  },
  {
    id: 3,
    soru: "Osmanlı Devleti'nin batıda ulaştığı en geniş sınırları belirleyen ve Lehistan ile imzalanan antlaşma aşağıdakilerden hangisidir?",
    secenekler: ["A) Karlofça Antlaşması", "B) Bucaş Antlaşması", "C) Pasarofça Antlaşması", "D) Belgrad Antlaşması", "E) Yaş Antlaşması"],
    cevap: 1,
    aciklama: "Osmanlı Devleti, 1672 yılında Lehistan ile imzaladığı Bucaş Antlaşması ile Podolya'yı sınırlarına katmış ve batıda en geniş sınırlarına ulaşmıştır.",
  },
  {
    id: 4,
    soru: "Osmanlı Devleti'nin batıda büyük çapta toprak kaybına uğradığı \"ilk antlaşma\" aşağıdakilerden hangisidir?",
    secenekler: ["A) Karlofça Antlaşması", "B) Pasarofça Antlaşması", "C) Küçük Kaynarca Antlaşması", "D) Yaş Antlaşması", "E) Edirne Antlaşması"],
    cevap: 0,
    aciklama: "II. Viyana Kuşatması'ndaki başarısızlığın ardından imzalanan 1699 Karlofça Antlaşması, Osmanlı Devleti'nin batıda çok büyük miktarda toprak kaybettiği ilk antlaşmadır ve Duraklama Dönemi'ni bitirip Gerileme Dönemi'ni başlatmıştır.",
  },
  {
    id: 5,
    soru: "Osmanlı Devleti'ne karşı XVII. yüzyıl sonlarında kurulan ve Karlofça Antlaşması'na giden süreci hazırlayan \"Kutsal İttifak\" içerisinde aşağıdaki devletlerden hangisi yer almaz?",
    secenekler: ["A) Avusturya", "B) Rusya", "C) Lehistan", "D) Fransa", "E) Venedik"],
    cevap: 3,
    aciklama: "Karlofça öncesinde Osmanlı'ya karşı kurulan Kutsal İttifak devletleri Venedik, Avusturya, Rusya, Lehistan ve Malta'dır. Fransa bu ittifakta yer almamış, aksine Osmanlı ile ilişkilerini korumaya çalışmıştır.",
  },
  {
    id: 6,
    soru: "1711 yılında Rusya karşısında Prut Savaşı'nı kazanan Osmanlı Devleti'nin, kaybettiği toprakları geri alma ümidini yeşerten antlaşma aşağıdakilerden hangisidir?",
    secenekler: ["A) Pasarofça Antlaşması", "B) Prut Antlaşması", "C) Belgrad Antlaşması", "D) İstanbul Antlaşması", "E) Küçük Kaynarca Antlaşması"],
    cevap: 1,
    aciklama: "Osmanlı, Baltacı Mehmet Paşa komutasında Rusları Prut nehrinde sıkıştırmış ve 1711 Prut Antlaşması'nı imzalayarak Azak Kalesi'ni geri almıştır. Bu zafer, Karlofça ile kaybedilen toprakların geri alınabileceği ümidini doğurmuştur.",
  },
  {
    id: 7,
    soru: "Osmanlı Devleti'nin kaybettiği toprakları geri alma ümidini tamamen kaybederek savunma politikasına geçtiği ve Lale Devri'nin başlamasına neden olan antlaşma aşağıdakilerden hangisidir?",
    secenekler: ["A) Karlofça Antlaşması", "B) Pasarofça Antlaşması", "C) Küçük Kaynarca Antlaşması", "D) Edirne Antlaşması", "E) Aynalıkavak Tenkihnamesi"],
    cevap: 1,
    aciklama: "1718 yılında imzalanan Pasarofça Antlaşması ile Osmanlı batıdaki toprakları geri alamayacağını anlamış, Avrupa'nın üstünlüğünü kabul ederek savunmaya çekilmiş ve barış/yenilik dönemi olan Lale Devri'ne girmiştir.",
  },
  {
    id: 8,
    soru: "Osmanlı Devleti'nin XVIII. yüzyılda imzaladığı \"en kazançlı\" son antlaşma aşağıdakilerden hangisidir?",
    secenekler: ["A) Belgrad Antlaşması", "B) Prut Antlaşması", "C) Küçük Kaynarca Antlaşması", "D) Yaş Antlaşması", "E) Ziştovi Antlaşması"],
    cevap: 0,
    aciklama: "Osmanlı Devleti'nin XVIII. yüzyılda kazandığı son parlak askeri zaferlerin ardından imzalanan 1739 Belgrad Antlaşması, bu yüzyıldaki en kazançlı son antlaşmadır.",
  },
  {
    id: 9,
    soru: "1739 Belgrad Antlaşması'nın imzalanmasında Osmanlı Devleti lehine arabuluculuk rolü üstlenen ve bu hizmeti karşılığında kapitülasyonların sürekli hale getirilmesi hakkını kazanan devlet aşağıdakilerden hangisidir?",
    secenekler: ["A) İngiltere", "B) Rusya", "C) Fransa", "D) Avusturya", "E) Prusya"],
    cevap: 2,
    aciklama: "1739 Belgrad Antlaşması'nın imzalanmasında arabuluculuk yapan Fransa, bu hizmetinin karşılığı olarak 1740 yılında I. Mahmut'tan kapitülasyonların \"sürekli hale getirilmesi\" hakkını elde etmiştir.",
  },
  {
    id: 10,
    soru: "Osmanlı Devleti'nin uluslararası siyasette \"Denge Siyasetini\" ilk defa uyguladığı tarihi gelişme aşağıdakilerden hangisidir?",
    secenekler: ["A) Napolyon'un Mısır'ı işgali", "B) Kırım Savaşı'nın çıkması", "C) Boğazlar Meselesi'nin başlaması", "D) Mehmet Ali Paşa İsyanı", "E) Navarin'de Osmanlı donanmasının yakılması"],
    cevap: 0,
    aciklama: "1798 yılında Napolyon'un Mısır'ı işgal etmesi üzerine Osmanlı Devleti, Fransa'ya karşı İngiltere ve Rusya'nın desteğini alarak tarihinin ilk Denge Siyasetini uygulamıştır.",
  },
  {
    id: 11,
    soru: "Mısır'ı işgal eden Napolyon Bonapart'ı Akka Kalesi önlerinde durdurarak büyük bir askeri başarı elde eden Osmanlı komutanı kimdir?",
    secenekler: ["A) Gazi Osman Paşa", "B) Cezzar Ahmet Paşa", "C) Merzifonlu Kara Mustafa Paşa", "D) Koca Ragıp Paşa", "E) Tarhuncu Ahmed Paşa"],
    cevap: 1,
    aciklama: "80'li yaşlarındaki ihtiyar delikanlı Cezzar Ahmet Paşa, Akka Kalesi önlerinde Napolyon'un ordusunu durdurmuş ve Fransızları geri çekilmeye zorlamıştır.",
  },
  {
    id: 12,
    soru: "Osmanlı Devleti'ne karşı milliyetçilik akımının etkisiyle ayaklanan \"ilk topluluk\" ve Osmanlı'dan bağımsızlığını kazanarak ayrılan \"ilk topluluk\" sırasıyla aşağıdakilerin hangisinde doğru verilmiştir?",
    secenekler: ["A) Sırplar - Rumlar (Yunanlılar)", "B) Rumlar - Sırplar", "C) Bulgarlar - Sırplar", "D) Sırplar - Karadağlılar", "E) Karadağlılar - Rumlar"],
    cevap: 0,
    aciklama: "Fransız İhtilali'nin yaydığı milliyetçilik akımıyla Osmanlı'ya karşı ilk isyan eden topluluk Sırplar (1804); ancak isyanı başarıya ulaşıp Osmanlı'dan ilk bağımsızlığını kazanan topluluk Rumlar (Yunanistan - 1829 Edirne Antlaşması) olmuştur.",
  },
  {
    id: 13,
    soru: "Osmanlı Devleti'nin Kuzey Afrika'daki \"ilk toprak kaybı\" aşağıdakilerden hangisidir?",
    secenekler: ["A) Trablusgarp", "B) Tunus", "C) Cezayir", "D) Mısır", "E) Fas"],
    cevap: 2,
    aciklama: "Fransa, 1830 yılında Cezayir'i işgal etmiştir. Bu işgal, Osmanlı Devleti'nin Kuzey Afrika coğrafyasındaki ilk toprak kaybıdır.",
  },
  {
    id: 14,
    soru: "Osmanlı Devleti'nde uluslararası bir sorun haline gelen \"Boğazlar Meselesi'nin\" başlamasına neden olan antlaşma aşağıdakilerden hangisidir?",
    secenekler: ["A) Hünkar İskelesi Antlaşması", "B) Londra Boğazlar Sözleşmesi", "C) Kütahya Antlaşması", "D) Paris Antlaşması", "E) Balta Limanı Antlaşması"],
    cevap: 0,
    aciklama: "Mısır Valisi isyan edince çaresiz kalan II. Mahmut, Rusya ile 1833'te Hünkar İskelesi Antlaşması'nı imzalamıştır. Rusya'ya Boğazlar üzerinde haklar veren bu antlaşma, Boğazlar Meselesi'ni resmen başlatmıştır.",
  },
  {
    id: 15,
    soru: "Mısır Valisi Mehmet Ali Paşa'nın isyan etmesi üzerine, Osmanlı Devleti'nin İngiltere'nin desteğini alabilmek amacıyla imzaladığı ve Osmanlı'yı adeta İngiltere'nin yarı sömürgesi haline getiren antlaşma hangisidir?",
    secenekler: ["A) Hünkar İskelesi Antlaşması", "B) Balta Limanı Ticaret Antlaşması", "C) Paris Antlaşması", "D) Kütahya Antlaşması", "E) Edirne Antlaşması"],
    cevap: 1,
    aciklama: "Kendi valisine karşı dış destek arayan Osmanlı, 1838 yılında İngiltere ile Balta Limanı Ticaret Antlaşması'nı imzalamış, iç ve dış gümrük vergilerini neredeyse sıfırlayarak Osmanlı pazarını İngiliz açık pazarı haline getirmiştir.",
  },
  {
    id: 16,
    soru: "Osmanlı Devleti, Kırım Savaşı (1853-1856) sırasında tarihinin ilk dış borcunu aşağıdaki devletlerin hangisinden almıştır?",
    secenekler: ["A) Fransa", "B) İngiltere", "C) Rusya", "D) Avusturya", "E) Prusya"],
    cevap: 1,
    aciklama: "Osmanlı Devleti, Kırım Savaşı'nın getirdiği mali yükü karşılayabilmek amacıyla 1854 yılında İngiltere'den ilk kez dış borç (istikraz) almıştır.",
  },
  {
    id: 17,
    soru: "Tarihte Osmanlı donanmasının yabancı devletler tarafından yakıldığı yerler kronolojik olarak aşağıdakilerden hangisinde doğru verilmiştir?",
    secenekler: ["A) İnebahtı - Çeşme - Navarin - Sinop", "B) Çeşme - İnebahtı - Sinop - Navarin", "C) Sinop - Navarin - Çeşme - İnebahtı", "D) İnebahtı - Navarin - Çeşme - Sinop", "E) Çeşme - Navarin - İnebahtı - Sinop"],
    cevap: 0,
    aciklama: "Osmanlı donanması sırasıyla: 1571 İnebahtı (Haçlılar), 1770 Çeşme (Ruslar), 1827 Navarin (İngiliz-Fransız-Rus ortak) ve 1853 Sinop (Ruslar) baskınlarında yakılmıştır.",
  },
  {
    id: 18,
    soru: "1856 Paris Antlaşması'nın aşağıdaki maddelerinden hangisi Osmanlı Devleti'nin savaşı kazanmasına rağmen \"yenik devlet\" muamelesi gördüğünün en açık kanıtıdır?",
    secenekler: [
      "A) Osmanlı Devleti'nin bir Avrupa devleti sayılması",
      "B) Karadeniz'in tarafsız hale getirilmesi, Osmanlı ve Rusya'nın burada donanma bulunduramayacak olması",
      "C) Osmanlı toprak bütünlüğünün Avrupa devletlerinin garantisi altında olması",
      "D) Boğazların 1841 Londra Sözleşmesi'ne göre yönetilmesi",
      "E) Eflak ve Boğdan'a muhtariyet verilmesi",
    ],
    cevap: 1,
    aciklama: "1856 Paris Antlaşması'ndaki \"Karadeniz'in tarafsız olması, Osmanlı ve Rusya'nın burada donanma bulunduramayacak olması\" maddesi, savaşı kazanan müttefikler safındaki Osmanlı'yı kendi denizinde silahsızlandırarak yenik devlet konumuna düşürmüştür.",
  },
  {
    id: 19,
    soru: "Kırım Savaşı sırasında döşenen ve Osmanlı tarihindeki ilk iletişim teknolojisi adımı olarak kabul edilen gelişme aşağıdakilerden hangisidir?",
    secenekler: ["A) Telgraf hattının kurulması", "B) İlk demir yolunun yapılması", "C) Posta teşkilatının kurulması", "D) İlk gazetenin çıkarılması", "E) Telsiz sistemine geçilmesi"],
    cevap: 0,
    aciklama: "Kırım Savaşı (1853-1856) sırasında cephedeki askeri gelişmeleri müttefiklere hızlı aktarabilmek amacıyla Osmanlı topraklarında ilk telgraf hattı (Varna-Kırım-Edirne hattı) döşenmiştir.",
  },
  {
    id: 20,
    soru: "93 Harbi'nde gösterdikleri kahramanlıklarla tarihe geçen Doğu Cephesi'ndeki \"kadın kahramanımız\" ile Batı Cephesi'ndeki \"Plevne Kahramanımız\" sırasıyla kimlerdir?",
    secenekler: ["A) Kara Fatma - Gazi Osman Paşa", "B) Nene Hatun - Gazi Osman Paşa", "C) Şerife Bacı - Cezzar Ahmet Paşa", "D) Nene Hatun - Halil Kut Paşa", "E) Halime Çavuş - Fahreddin Paşa"],
    cevap: 1,
    aciklama: "93 Harbi'nde Erzurum Aziziye Tabyaları'nda Ruslara karşı efsanevi bir direniş gösteren kadın kahramanımız Nene Hatun, Bulgaristan cephesindeki meşhur Plevne savunmasıyla Rus ordularını aylarca durduran kahramanımız ise Gazi Osman Paşa'dır.",
  },
];
