import { DenemeSorusu } from './deneme1';

export const denemeTurkce3Baslik = "Sözcük Türleri (İsim, Sıfat, Zamir, Zarf, Edat-Bağlaç-Ünlem, Fiiller ve Ek Fiil)";

export const denemeTurkce3: DenemeSorusu[] = [
  {
    id: 1,
    soru: "\"Biz millet olarak her zaman yalnızı korumak isteriz; ancak yalnız insanlar paylaşmayı bilmezler, bu yüzden hayatı yalnız yaşarlar.\" Bu cümledeki \"yalnız\" sözcüklerinin türleri sırasıyla aşağıdakilerin hangisinde doğru verilmiştir?",
    secenekler: ["A) İsim - Sıfat - Zarf", "B) Sıfat - İsim - Zarf", "C) Zamir - Sıfat - Edat", "D) İsim - Zarf - Bağlaç", "E) Zamir - Zarf - İsim"],
    cevap: 0,
    aciklama: "\"yalnızı\" ismi karşılar (İsim), \"yalnız insanlar\" ismi niteler (Sıfat), \"yalnız yaşarlar\" fiili niteler (Zarf).",
  },
  {
    id: 2,
    soru: "\"Bir\" sözcüğü \"tek\" anlamına geldiğinde asıl sayı sıfatı, \"herhangi bir\" anlamındaysa belgisiz sıfat olur. Buna göre \"bir\" sözcüğü aşağıdaki cümlelerin hangisinde \"belgisiz sıfat\" görevinde kullanılmıştır?",
    secenekler: [
      "A) Sınavın başlamasına sadece bir gün kaldı, heyecan dorukta.",
      "B) Bir gün sen de beni çok iyi anlayacaksın ama iş işten geçmiş olacak.",
      "C) Pazardan sadece bir kilo elma alıp eve geri döndü.",
      "D) Toplantıya katılanlardan sadece bir kişi kanun teklifine itiraz etti.",
      "E) Bu apartmanın birinci katında tam bir yıl boyunca oturduk.",
    ],
    cevap: 1,
    aciklama: "\"Bir gün\" ifadesi herhangi bir gün anlamı taşıdığı için belgisiz sıfattır. Diğerlerinde \"tek\" anlamı taşıdığı için sayı sıfatıdır.",
  },
  {
    id: 3,
    soru: "Aşağıdaki cümlelerin hangisinde \"o\" sözcüğü kişi adılı (şahıs zamiri) olarak kullanılmıştır?",
    secenekler: [
      "A) Çocuklar bahçedeki o ağacı sulamak için su taşıyorlardı.",
      "B) Kitaplıktan o kitabı alıp salondaki masaya bıraktı.",
      "C) Ben bu evi değil, sahil kenarındaki onu çok beğendim.",
      "D) Annesi onu, biraz önce kontrol için hastaneye götürdü.",
      "E) Masadaki dosyayı işaret ederek \"Onu bana ver.\" dedi.",
    ],
    cevap: 3,
    aciklama: "\"onu\" sözcüğü bir insan/şahıs yerine (annesinin çocuğu) kullanıldığı için kişi zamiridir. Diğer şıklarda işaret sıfatı veya insan dışı varlık (ev, dosya) yerine kullanıldığı için işaret zamiridir.",
  },
  {
    id: 4,
    soru: "Aşağıdaki cümlelerin hangisinde soru anlamı bir \"zamirle\" sağlanmıştır?",
    secenekler: [
      "A) Bunca sıkıntıya ve zorluğa neden katlandınız?",
      "B) Bu romanı benden sonra kim okumak ister?",
      "C) Bu güzel çiçeklere toplam kaç para verdiniz?",
      "D) Kaçıncı katta oturduğunu size de söyledi mi?",
      "E) Toplantıda bana gizlice ne söylediğini biliyor musunuz?",
    ],
    cevap: 1,
    aciklama: "\"kim\" sorusunun cevabı bir isim veya zamirdir (Ahmet okumak ister / o ister), bu yüzden soru zamiridir.",
  },
  {
    id: 5,
    soru: "Yer-yön belirten \"içeri, dışarı, yukarı, aşağı, ileri, geri\" gibi sözcükler isim çekim eki aldıklarında adlaşarak \"isim\" olurlar. Buna göre aşağıdaki cümlelerin hangisinde altı çizili sözcük \"yer-yön zarfı\" görevindedir?",
    secenekler: [
      "A) Ahmet, işlerini bitirdikten sonra yavaşça aşağıya indi.",
      "B) İçeriyi net göremediğim için pencereleri sonuna kadar açtım.",
      "C) Kardeşi, sokakta arkadaşlarıyla oynamak için az önce dışarı çıktı.",
      "D) Arkadakilerin rahatça sığması için arabayı biraz daha ileriye almalısın.",
      "E) Aşağı mahallede oturan akrabalarımızı ziyarete gittik.",
    ],
    cevap: 2,
    aciklama: "\"dışarı\" sözcüğü ek almadan yalın hâlde fiilin yönünü belirttiği için yer-yön zarfıdır. A ve D'de ek aldığı için isimleşmiştir. E'de ismi belirttiği için işaret sıfatıdır.",
  },
  {
    id: 6,
    soru: "Aşağıdaki cümlelerin hangisinde \"ile\" sözcüğü \"bağlaç\" olarak kullanılmıştır?",
    secenekler: [
      "A) Akşamüstü ağır bir parfüm kokusuyla salona girdi.",
      "B) Sesiyle okuldaki herkesi kendine hayran bırakmıştı.",
      "C) Doğru ve etkili sözlerle kaleyi içten fethetti usta yazar.",
      "D) Hayat, her zaman doğrularla yanlışlar arasında gider gelir.",
      "E) Yeni aldığımız araba ile Ankara'ya gitmeye karar verdik.",
    ],
    cevap: 3,
    aciklama: "\"ile\" yerine \"ve\" getirilebiliyorsa bağlaçtır. \"doğrular ve yanlışlar\" denebildiği için bağlaçtır. Diğerlerinde araç/durum anlamında edattır.",
  },
  {
    id: 7,
    soru: "\"Yalnız\" ve \"ancak\" sözcükleri \"sadece\" anlamına geliyorsa edat; \"ama, fakat\" anlamına geliyorsa bağlaç olur. Buna göre aşağıdaki cümlelerin hangisinde \"yalnız\" veya \"ancak\" sözcüğü \"bağlaç\" görevinde kullanılmıştır?",
    secenekler: [
      "A) Şu koca dünyada beni yalnız sen anladın, gerisi yalan.",
      "B) Bu zor uyuşmazlık problemini ancak sen çözebilirsin Enes Hoca.",
      "C) Seninle her yere gelmeyi çok isterdim yalnız evde bir yığın iş var.",
      "D) Sınavı kazanmak için yalnız bu kaynak kitapları bitirmelisin.",
      "E) Oraya tek başına gitmiş hâlbuki trenle gitmek ancak mantıklıydı.",
    ],
    cevap: 2,
    aciklama: "\"yalnız\" sözü \"ama, fakat\" anlamında kullanıldığı için bağlaçtır. A, B ve D'de \"sadece\" anlamında edattır.",
  },
  {
    id: 8,
    soru: "Aşağıdaki cümlelerin hangisinde yer alan fiil, anlattığı hareketin niteliğine göre \"oluş fiili\"dir?",
    secenekler: [
      "A) \"Sefiller\" romanını bu yıl en az dört kez okumuşumdur.",
      "B) Basketbol oynamaya başladıktan sonra oğlumun boyu iyice uzadı.",
      "C) Uçak, teknik bir arıza nedeniyle az önce alandan ayrıldı.",
      "D) Misafirler gelmeden önce odasındaki yatağına uzanıp uzandı.",
      "E) Sınıftaki tahtaya yazılan bütün notları defterine dikkatlice yazdı.",
    ],
    cevap: 1,
    aciklama: "Zamana bağlı olarak kendiliğinden gerçekleşen fiziksel değişimler (uzamak, sararmak, yaşlanmak) oluş fiilidir.",
  },
  {
    id: 9,
    soru: "Aşağıdaki cümlelerin hangisinde \"-yor\" eki, diğerlerinden farklı bir zaman/kip anlamı (kip kayması) katmıştır?",
    secenekler: [
      "A) Canı sıkılınca veya morali bozulunca her şey için sürekli beni arıyor.",
      "B) Ünlü haritacılık tarihi uzmanı, bir derginin konuğu olarak haftaya İstanbul'a geliyor.",
      "C) Genetik ve çevresel faktörler etkileşerek otizmin ortaya çıkmasında rol oynuyor.",
      "D) Bataklık yakınlarında yaşayan hoatzin kuşu, yiyeceklerini fermente ederek sindiriyor.",
      "E) Her defasında suya dalıyor ve gördüklerim karşısında büyülenmiş olarak çıkıyorum.",
    ],
    cevap: 1,
    aciklama: "B seçeneğinde \"-yor\" eki \"haftaya\" zarfıyla birlikte gelecek zaman anlamında kullanılmıştır (kip kayması). Diğer şıklarda her zaman yapılan işleri (geniş zaman) karşılar.",
  },
  {
    id: 10,
    soru: "Aşağıdaki cümlelerin hangisinde bir \"birleşik zamanlı (çekimli) fiil\" kullanılmıştır?",
    secenekler: [
      "A) Eşyalar yerleştirilince otobüse tüm yolcular da bindi.",
      "B) Şoför, zaman kaybetmeden hemen kontağı açtı.",
      "C) O sırada otobüs yazıhanesinden genç biri fırladı.",
      "D) Önümüzdeki tek boş koltuğa geçip oturdu sessizce.",
      "E) Çevresindekileri selamladı, otobüsteki herkesi tanıyordu anlaşılan.",
    ],
    cevap: 4,
    aciklama: "\"tanıyordu\" fiili tanımak eyleminin şimdiki zamanının hikâyesi (-yor-du) biçiminde iki kip eki almıştır, yani birleşik zamanlıdır. Diğerleri basit zamanlıdır.",
  },
  {
    id: 11,
    soru: "Aşağıdaki cümlelerin hangisinin yüklemi, \"ek eylem almış bir sıfattır\"?",
    secenekler: [
      "A) Bu bahçedeki elmalar henüz tam anlamıyla tatlanmamış.",
      "B) Çocukluğumuzun geçtiği o eski evimiz de bu kadar genişti.",
      "C) Şu anda yaşanan olayın gerçek nedenini bilen hiç kimse yok.",
      "D) Söylediklerine göre bu sınıfın en çalışkan öğrencisi sensin.",
      "E) Yarın hava tüm yurtta yoğun yağmurlu olacakmış.",
    ],
    cevap: 1,
    aciklama: "\"genişti\" yükleminin kökü \"geniş\" sıfatıdır, \"-ti\" ek-fiilini alarak yüklem olmuştur.",
  },
  {
    id: 12,
    soru: "Ek fiilin geniş zaman eki olan \"-dir\" bazen düşebilir veya cümleye kesinlik/olasılık anlamı katabilir ancak birleşik zamanlı fiil yapmaz. Aşağıdaki cümlelerin hangisinde ek fiil cümleye \"tahmin (olasılık)\" anlamı katmıştır?",
    secenekler: [
      "A) Biraz önce okul zili çaldı, bugünkü ders tamamen bitmiştir.",
      "B) Amcamlar, bağdaki olgunlaşan üzümleri çoktan toplamıştır.",
      "C) Sınav salonuna telefonla girmek kesinlikle yasaktır.",
      "D) Bizimle gelmeyeceğini daha önceden bize bildirmişti.",
      "E) Herkes çalışmalarını tamamlasın, teslim süresi dolmuştur.",
    ],
    cevap: 1,
    aciklama: "\"toplamıştır\" ifadesi eylemin gerçekleşmiş olabileceğine dair bir tahmin/olasılık anlamı taşır. A ve E şıklarında kesinlik bildirir.",
  },
  {
    id: 13,
    soru: "Aşağıdaki atasözlerinin hangisinde \"isim tamlaması\" niteleme göreviyle (sıfat olarak) kullanılmıştır?",
    secenekler: [
      "A) Çoban salatasının lezzeti yerindeydi.",
      "B) Onun herkesi büyüleyen deniz mavisi gözleri vardı.",
      "C) Portakal suyunun vitamin değeri çok yüksektir.",
      "D) Yolun sonundaki eski tahta köprüden geçtik.",
      "E) Sıcacık tarhana çorbasıyla güne başlamayı severdi.",
    ],
    cevap: 1,
    aciklama: "\"deniz mavisi\" belirtisiz isim tamlamasıdır. \"deniz mavisi gözler\" tamlaması ismi nitelediği için sıfat (adlaşmış/öbekleşmiş tamlama) görevindedir.",
  },
  {
    id: 14,
    soru: "Aşağıdaki cümlelerin hangisinde soru anlamı bir \"zarfla\" sağlanmıştır?",
    secenekler: [
      "A) Nasıl geçti habersiz o güzelim gençlik yılları?",
      "B) Bu taze patatesleri hangi manavdan aldın?",
      "C) Soruyu doğru çözdüğünü nereden bileceksiniz?",
      "D) Ne zaman Ordu'ya gideceğini size de söyledi mi?",
      "E) Bu sınav salonunda toplam kaç kişi bulunuyor?",
    ],
    cevap: 0,
    aciklama: "\"Nasıl geçti\" cümlesinde \"nasıl\" sorusu fiile (geçti) yöneltildiği için soru zarfıdır.",
  },
  {
    id: 15,
    soru: "\"Kendi kendine konuşan bu adamın tavırları hepimizi şaşırttı.\" Bu cümledeki \"kendi kendine\" ikilemesinin türü aşağıdakilerden hangisidir?",
    secenekler: ["A) Zamir", "B) İsim", "C) Sıfat", "D) Zarf", "E) Edat"],
    cevap: 3,
    aciklama: "\"kendi kendine\" sözü konuşmak fiilimsisini durum yönünden belirttiği için zamir kökenli bir durum zarfıdır.",
  },
];
