import { DenemeSorusu } from './deneme1';

export const deneme2Baslik = "İlk Türk-İslam Devletleri ve Beylikler";

export const deneme2: DenemeSorusu[] = [
  {
    id: 1,
    soru: "Türk-İslam tarihini başlatan ve Abbasiler ile Çinliler arasında yapılan savaş aşağıdakilerden hangisidir?",
    secenekler: ["A) Dandanakan Savaşı", "B) Katvan Savaşı", "C) Talas Savaşı", "D) Pasinler Savaşı", "E) Kösedağ Savaşı"],
    cevap: 2,
    aciklama: "751 Talas Savaşı, Çinliler ile Abbasiler arasında yapılmıştır. Bu savaşta Türk boyu Karluklar, Abbasileri desteklemiştir. Savaşın ardından Türkler kitleler halinde İslamiyet'i kabul etmeye başlamış ve Türk-İslam tarihi başlamıştır.",
  },
  {
    id: 2,
    soru: "İlk Türk-İslam medrese, kervansaray (ribat) ve posta teşkilatı örneklerini vererek Türk-İslam kültürünün temellerini atan devlet aşağıdakilerden hangisidir?",
    secenekler: ["A) Gazneliler", "B) Karahanlılar", "C) Tolunoğulları", "D) Büyük Selçuklu Devleti", "E) Eyyubiler"],
    cevap: 1,
    aciklama: "Karahanlılar, Orta Asya'da kurulan ilk Müslüman Türk devletidir. Ulusal kimliklerini koruyarak ilk Türk-İslam medreselerini (Semerkand), \"ribat\" adı verilen kervansarayları ve düzenli posta teşkilatını kurmuşlardır.",
  },
  {
    id: 3,
    soru: "Gazneli Mahmut döneminde sarayda yaşayan, hakanın \"Sarayımın en değerli hazinesidir\" diyerek onurlandırdığı ve dönemin ünlü yapıtlarına imza atan astronomi ve matematik bilgini kimdir?",
    secenekler: ["A) Biruni", "B) Ali Kuşçu", "C) Farabi", "D) İbn-i Sina", "E) Gazali"],
    cevap: 0,
    aciklama: "Gazneli Mahmut, ünlü bilim insanı El-Biruni'yi himaye etmiş ve onun için \"Sarayımın en değerli hazinesidir\" demiştir. Biruni, coğrafya, matematik ve astronomi alanında çığır açan eserler yazmıştır.",
  },
  {
    id: 4,
    soru: "Büyük Selçuklu Devleti'nin resmen kurulmasını sağlayan ve Gaznelilerin yıkılış sürecine girmesine yol açan 1040 tarihli savaş aşağıdakilerden hangisidir?",
    secenekler: ["A) Pasinler Savaşı", "B) Dandanakan Savaşı", "C) Katvan Savaşı", "D) Malazgirt Savaşı", "E) Kösedağ Savaş"],
    cevap: 1,
    aciklama: "1040 Dandanakan Savaşı, Tuğrul ve Çağrı Bey komutasındaki Selçuklular ile Gazneliler arasında yapılmıştır. Savaşı kazanan Selçuklular resmen kurulurken, Gazneliler yıkılış sürecine girmiştir.",
  },
  {
    id: 5,
    soru: "Abbasi halifesini Şii Büveyhoğulları baskısından kurtardığı için halife tarafından kendisine \"Doğu'nun ve Batı'nın Sultanı\" unvanı verilen Büyük Selçuklu hükümdarı aşağıdakilerden hangisidir?",
    secenekler: ["A) Alparslan", "B) Melikşah", "C) Tuğrul Bey", "D) Sultan Sencer", "E) Kutalmışoğlu Süleyman Şah"],
    cevap: 2,
    aciklama: "Tuğrul Bey, 1055 yılında Bağdat Seferi'ni düzenleyerek Abbasi halifesini Şii Büveyhoğulları esaretinden kurtarmıştır. Halife de ona siyasi gücün Selçuklularda olduğunu simgeleyen \"Doğu'nun ve Batı'nın Sultanı\" unvanını vermiştir.",
  },
  {
    id: 6,
    soru: "Anadolu'da kurulan ilk Türk beyliklerinden \"ilk kurulanı\" ve \"en güçlü olanı\" sırasıyla aşağıdakilerin hangisinde doğru verilmiştir?",
    secenekler: [
      "A) Saltuklular - Danişmentliler",
      "B) Mengücekliler - Artuklular",
      "C) Çaka Beyliği - Saltuklular",
      "D) Danişmentliler - Saltuklular",
      "E) Artuklular - Mengücekliler",
    ],
    cevap: 0,
    aciklama: "Malazgirt Savaşı'ndan (1071) sonra Anadolu'da kurulan ilk beylik Saltuklular (Erzurum çevresi); bu beylikler arasında en güçlü olanı ise Danişmentlilerdir (Sivas, Tokat, Kayseri çevresi).",
  },
  {
    id: 7,
    soru: "Kudüs'ü 1187 yılında Hıttin Savaşı ile Haçlılardan geri alarak İslam dünyasında büyük bir saygınlık kazanan Türk devleti aşağıdakilerden hangisidir?",
    secenekler: ["A) Memlükler", "B) Tolunoğulları", "C) Karahanlılar", "D) Eyyubiler", "E) İhşidiler"],
    cevap: 3,
    aciklama: "Selahaddin Eyyubi önderliğindeki Eyyubi Devleti, 1187 Hıttin Savaşı ile Kudüs'ü Haçlılardan geri almıştır. Bu zafer III. Haçlı Seferi'nin başlamasına neden olmuştur.",
  },
  {
    id: 8,
    soru: "Mısır'da kurulan \"ilk Türk devleti\" ve \"Maristan\" adı verilen gelişmiş hastaneleri kuran devlet aşağıdakilerden hangisidir?",
    secenekler: ["A) İhşidiler (Akşitler)", "B) Tolunoğulları", "C) Eyyubiler", "D) Memlükler", "E) Fatimiler"],
    cevap: 1,
    aciklama: "Mısır'da kurulan ilk Türk devleti Tolunoğullarıdır (868-905). Tolunoğulları sosyal devlet anlayışıyla hareket ederek \"Maristan\" adı verilen ücretsiz ve din ayrımı gözetmeyen hastaneler kurmuşlardır.",
  },
  {
    id: 9,
    soru: "Anadolu Selçuklu Devleti'nin Harzemşahlar ile yaptığı ve bu devletin yıkılmasına yol açarak Anadolu'yu Moğol istilasına açık hale getiren savaş aşağıdakilerden hangisidir?",
    secenekler: ["A) Kösedağ Savaşı", "B) Yassıçemen Savaşı", "C) Katvan Savaşı", "D) Miryokefalon Savaşı", "E) Malazgirt Savaşı"],
    cevap: 1,
    aciklama: "1230 Yassıçemen Savaşı'nda Anadolu Selçuklu Devleti, Harzemşahlar'ı yenerek yıkılış sürecine sokmuştur. Bu durum, Anadolu ile Moğollar arasındaki tampon bölgeyi ortadan kaldırmış ve Moğol istilasını kolaylaştırmıştır.",
  },
  {
    id: 10,
    soru: "Anadolu Selçuklu Devleti'nde dini ve sosyal nitelikli olarak çıkan, devletin gücünü sarsıp zayıflamasına neden olan \"ilk dini içerikli isyan\" aşağıdakilerden hangisidir?",
    secenekler: ["A) Şeyh Bedrettin İsyanı", "B) Baba İshak İsyanı", "C) Patrona Halil İsyanı", "D) Babailer Ayaklanması", "E) Buçuktepe İsyanı"],
    cevap: 1,
    aciklama: "1240 yılında yaşanan Baba İshak (Babailer) İsyanı, Anadolu Selçuklu Devleti'nde çıkan ilk büyük dini ve sosyal içerikli halk ayaklanmasıdır. Devlet bu isyanı zorlukla bastırabilmiş, bu da zayıflığını Moğollara kanıtlamıştır. Not: D şıkkı (Babailer Ayaklanması) B şıkkıyla (Baba İshak İsyanı) aynı olayı ifade eder; doğru cevap B olarak işaretlenmiştir.",
  },
  {
    id: 11,
    soru: "I. Karahanlılar\nII. Gazneliler\nIII. Büyük Selçuklu Devleti\nYukarıdaki devletlerden hangileri egemenlikleri altındaki bölgelerde bilimsel çalışmaları desteklemek amacıyla \"Bimaristan\" veya \"Maristan\" adı verilen hastane/sağlık kurumları inşa etmişlerdir?",
    secenekler: ["A) Yalnız I", "B) Yalnız II", "C) I ve II", "D) I ve III", "E) II ve III"],
    cevap: 0,
    aciklama: "Karahanlılar, hastanelerine Bimaristan (veya Maristan) adını vermişlerdir. Gazneliler ve Selçuklular da benzer kurumlar açsa da bu terminolojiyi Türk-İslam sentezinde ilk sistemleştiren Karahanlılardır.",
  },
  {
    id: 12,
    soru: "Büyük Selçuklu Devleti'nin ve Anadolu Selçuklu Devleti'nin en parlak dönemini yaşatan hükümdarlar sırasıyla aşağıdakilerin hangisinde doğru eşleştirilmiştir?",
    secenekler: [
      "A) Tuğrul Bey - I. Kılıç Arslan",
      "B) Alparslan - I. Gıyaseddin Keyhüsrev",
      "C) Melikşah - I. Alaaddin Keykubat",
      "D) Sultan Sencer - II. Gıyaseddin Keyhüsrev",
      "E) Melikşah - II. Kılıç Arslan",
    ],
    cevap: 2,
    aciklama: "Büyük Selçuklu Devleti'nin en parlak dönemi Melikşah dönemi; Anadolu Selçuklu Devleti'nin en parlak, en zengin ve ticari olarak en zirve dönemi ise I. Alaaddin Keykubat dönemidir.",
  },
  {
    id: 13,
    soru: "Malazgirt ve Kösedağ savaşlarının \"ortak sonucu\" olarak aşağıdakilerden hangisi gösterilebilir?",
    secenekler: [
      "A) Anadolu'da Türk beyliklerinin kurulmasına yol açmaları",
      "B) Anadolu'nun kesin olarak Türk yurdu haline gelmesi",
      "C) Anadolu Selçuklu Devleti'nin yıkılış sürecine girmesi",
      "D) Bizans'ın Anadolu'daki savunma gücünün tamamen kırılması",
      "E) Türk-İslam dünyasındaki halifelik makamının Türklere geçmesi",
    ],
    cevap: 0,
    aciklama: "Her iki savaş da Anadolu'da Türk beyliklerinin kurulma sürecini başlatmıştır: 1071 Malazgirt Savaşı'ndan sonra 1. Dönem Türk Beylikleri, 1243 Kösedağ Savaşı ile Anadolu Selçuklu otoritesinin çökmesinden sonra ise 2. Dönem Türk Beylikleri kurulmuştur.",
  },
  {
    id: 14,
    soru: "Tarihte ilk kez denizcilikle uğraşan ve ilk Türk donanmasını kuran beylik aşağıdakilerden hangisidir?",
    secenekler: ["A) Karesioğulları", "B) Çaka Beyliği", "C) Aydınoğulları", "D) Saruhanoğulları", "E) Candaroğulları"],
    cevap: 1,
    aciklama: "İzmir ve çevresinde kurulan Çaka Beyliği (1081), tarihteki ilk Türk denizci beyliğidir. Kurucusu Çaka Bey ise ilk Türk amiralidir.",
  },
  {
    id: 15,
    soru: "Büyük Selçuklu Devleti'nin yıkılmasını hızlandıran Karahitaylar ile yapılan savaş aşağıdakilerden hangisidir?",
    secenekler: ["A) Katvan Savaşı", "B) Kösedağ Savaşı", "C) Pasinler Savaşı", "D) Dandanakan Savaşı", "E) Yassıçemen Savaşı"],
    cevap: 0,
    aciklama: "Büyük Selçuklu Devleti, Moğol kökenli Karahitaylar ile 1141 yılında yaptığı Katvan Savaşı'nı kaybederek fiilen yıkılış ve dağılma sürecine girmiştir.",
  },
  {
    id: 16,
    soru: "Büyük Selçuklu Devleti'nin son hükümdarı olarak kabul edilen ve Selçuklu Devleti'nin dağılmasını önlemeye çalışan siyasi lider kimdir?",
    secenekler: ["A) Tuğrul Bey", "B) Sultan Sencer", "C) Melikşah", "D) Alp Arslan", "E) Berkyaruk"],
    cevap: 1,
    aciklama: "Büyük Selçuklu Devleti'nin son büyük hükümdarı Sultan Sencer'dir. Sencer'in ölümüyle (1157) imparatorluk tamamen parçalanmış ve halef devletler ortaya çıkmıştır.",
  },
  {
    id: 17,
    soru: "Semerkand ve Herat gibi şehirlerde gökbilim çalışmaları yapmış, hem Timur hem Akkoyunlu devletlerinde görev aldıktan sonra Osmanlı Devleti'nde el üstünde tutulmuş ünlü astronomi ve matematik bilgini kimdir?",
    secenekler: ["A) Biruni", "B) Ali Kuşçu", "C) İbn-i Rüşd", "D) Ömer Hayyam", "E) Uluğ Bey"],
    cevap: 1,
    aciklama: "Fatih Sultan Mehmet döneminde İstanbul'a davet edilen ve Ayasofya Medresesi'nin müderrisliğini yapan ünlü matematikçi ve astronom Ali Kuşçu'dur.",
  },
  {
    id: 18,
    soru: "Resmi dili Türkçe olan ve Karahanlılar döneminde yazılan ilk Türk-İslam yazılı eseri (Kutadgu Bilig) kaleme alan yazar aşağıdakilerden hangisidir?",
    secenekler: ["A) Edip Ahmet Yükneki", "B) Yusuf Has Hacib", "C) Kaşgarlı Mahmut", "D) Hoca Ahmet Yesevi", "E) Ali Şir Nevai"],
    cevap: 1,
    aciklama: "Karahanlılar döneminde Yusuf Has Hacib tarafından yazılan Kutadgu Bilig (Mutluluk Veren Bilgi), ilk Türk-İslam siyasetnamesidir ve hakanlara devlet yönetimi hakkında öğütler verir.",
  },
  {
    id: 19,
    soru: "Anadolu Selçuklu Devleti'nde ticareti geliştirmek amacıyla inşa edilen, tüccarların konaklaması, güvenliği ve mallarının sigortalanması gibi hizmetleri sunan mimari yapılara ne ad verilir?",
    secenekler: ["A) Bedesten", "B) Kapan Hanı", "C) Ribat / Kervansaray", "D) Külliye", "E) İmaret"],
    cevap: 2,
    aciklama: "İlk örnekleri Karahanlılar tarafından \"Ribat\" adıyla kurulan, Anadolu Selçuklu döneminde ise anıtsal yapılara dönüşen Kervansaraylar, uluslararası ticareti korumak ve geliştirmek için inşa edilmiştir.",
  },
  {
    id: 20,
    soru: "UNESCO Dünya Miras Listesi'ne giren ilk Türk mimari varlığı olan ve Anadolu Selçuklu / Mengücekliler dönemine ait eşsiz taş işçiliğiyle bilinen yapı aşağıdakilerden hangisidir?",
    secenekler: ["A) Divriği Ulu Camii ve Darüşşifası", "B) Bursa Ulu Camii", "C) Diyarbakır Ulu Camii", "D) Konya Karatay Medresesi", "E) Sivas Gök Medrese"],
    cevap: 0,
    aciklama: "Sivas sınırlarında bulunan ve Mengücekliler döneminde inşa edilen Divriği Ulu Camii ve Darüşşifası, taş işçiliğindeki muazzam detayları sayesinde 1985 yılında UNESCO Dünya Miras Listesi'ne giren ilk Türk varlığı olmuştur.",
  },
];
