import { DenemeSorusu } from './deneme1';

export const denemeTurkce5Baslik = "Anlatım Bozuklukları ve Paragrafta Anlam Soru Tipleri";

export const denemeTurkce5: DenemeSorusu[] = [
  {
    id: 1,
    soru: "\"Elbette onunla birlikte gitmiş olabilirler şu koca şehirde.\" Bu cümledeki anlatım bozukluğunun nedeni aşağıdakilerden hangisidir?",
    secenekler: ["A) Öge eksikliği bulunması", "B) Özne-yüklem uyuşmazlığı", "C) Sözcüğün yanlış yerde kullanılması", "D) Aynı anlama gelen sözcüklerin birlikte kullanılması", "E) Anlamca çelişen ifadelerin (sözcüklerin) bir arada kullanılması"],
    cevap: 4,
    aciklama: "\"Elbette\" kesinlik bildirirken \"olabilirler\" olasılık bildirir. Birbiriyle çelişen ifadelerin bir arada kullanılması anlatım bozukluğuna yol açmıştır.",
  },
  {
    id: 2,
    soru: "Aşağıdaki cümlelerin hangisinde bir anlatım bozukluğu vardır?",
    secenekler: [
      "A) Sanayide gelişmiş batı ülkelerinde bu tür sorunlar hızla çözülüyor.",
      "B) Düzenlenen toplantı ve törenlerde bütün okul öğrencileri görev alıyor.",
      "C) Bu konuda yapılan açıklamaların anlaşılmayacak hiçbir yanı bulunmuyor.",
      "D) Kurumda çalışanların başarısının, bu adil koşullara bağlı olduğu düşünülüyor.",
      "E) Teknoloji ne kadar artarsa da el emeğinin ve işçiliğin önemi azalmıyor.",
    ],
    cevap: 4,
    aciklama: "\"artarsa\" sözcüğü teknoloji için yanlış anlamda kullanılmıştır. Teknolojinin artması değil, \"ilerlemesi veya gelişmesi\" denmelidir.",
  },
  {
    id: 3,
    soru: "Aşağıdakilerin hangisinde, \"anlam belirsizliğini gidermek\" amacıyla cümlenin başına bir şahıs zamiri (senin/onun) getirmek gerekir?",
    secenekler: [
      "A) Adana'ya yerleştiklerini dün akşam nihayet duydum.",
      "B) Yeni aldığın o güzel elbiseyi törende çok beğendim.",
      "C) Sınavda tam olarak birinci olduğuna hepimiz çok sevindik.",
      "D) Önerdiğin o sürükleyici romanı henüz okuyamadım.",
      "E) Sınava İstanbul'da sakin bir okulda girmek istiyorum.",
    ],
    cevap: 2,
    aciklama: "\"birinci olduğuna\" ifadesi hem \"senin birinci olduğuna\" hem de \"onun birinci olduğuna\" anlamına geldiği için anlam belirsizliği vardır. Başına şahıs zamiri gelmelidir.",
  },
  {
    id: 4,
    soru: "Aşağıdaki cümlelerin hangisinde \"özne-yüklem uyuşmazlığından\" kaynaklanan bir anlatım bozukluğu vardır?",
    secenekler: [
      "A) Bütün gözlerin onlara çevrildiği genç çift, salona heyecanla girdiler.",
      "B) Cansız varlıkların ya da soyut kavramların çoğulları özne olduğunda yüklem tekil olur.",
      "C) Bu olumsuz düşünceler, geçerliliğini bizim toplumda çoktan yitirdi.",
      "D) Yaşanan bu ani ve derin duygular, gözlerimi her zaman yaşartırlar.",
      "E) Köylüler, sabah erkenden meydanda toplanıp yüksek sesle bağrıştılar.",
    ],
    cevap: 3,
    aciklama: "İnsan dışı varlıkların (duygular) çoğul olduğu durumlarda yüklem tekil olmak zorundadır. \"yaşartırlar\" değil \"yaşartır\" olmalıdır.",
  },
  {
    id: 5,
    soru: "(I) Konutlar, insanların sosyokültürel ve coğrafi değerlerini dışa vuran bir özelliğe sahiptir. (II) Örneğin kendisine has özellikleri bulunan Midyat evleri, en büyük özelliklerinden olan sevginin, barışın ve duyguların taşlara işlendiği özgün evlerdir. (III) Evlerin mimari yapıları, sosyal yaşam tarzlarına özgü yapım şekilleri, figürleri, mekânların kullanılış biçimleri ile Midyat'a has ceviz ağacından yapılan divan takımları ve özellikleri vardır. (IV) Midyat evlerinde kullanılan malzeme taştır ancak kullanılan bu taş normal taştan farklıdır, kalker taşı olarak adlandırılan açık renkli, sarımsı bir yapıdadır. (V) Bu taşların en büyük özelliği çok kolay kesilebilmesinden dolayı rahat bir şekilde işlenebilmesidir. Bu parçada numaralanmış cümlelerden hangisi parçanın \"ana düşüncesi\" niteliğindedir?",
    secenekler: ["A) I", "B) II", "C) III", "D) IV", "E) V"],
    cevap: 0,
    aciklama: "Paragrafın ilk cümlesi (I) nesnel/genel bir yargıyla konuyu ve ana düşünceyi ortaya koymaktadır, diğerleri bunu örneklendirir.",
  },
  {
    id: 6,
    soru: "\"Kültürü gelecek kuşaklara aktaran ve öğreten, dildir. Diğer bir deyişle dil olmasaydı kültür ve uygarlık da olmazdı. Demek ki bugünkü kültür ve uygarlığın varlığı, dil ile doğrudan ilintilidir. Medeniyet, insanlığın bilim ve teknolojideki ilerlemeyle ulaştığı ortak nokta olarak tanımlanabilir. Öyleyse kültür toplumların kendi öz malı, uygarlık ise insanlığın ortak hazinesidir. Dil olmasaydı uygarlık da olamazdı. Hayvanlarla aramızdaki temel fark burada görülüyor. Düşünsenize hayvanlar da bir kültür ve bilgi birikimine sahip olsalardı insanın durumu ne kadar acı olurdu.\" Bu parçada aşağıdakilerden hangisine değinilmemiştir?",
    secenekler: [
      "A) Dilin öğretici ve aktarıcı yönünün bulunduğuna",
      "B) Kültürün ulusal (öz mal), uygarlığın ise evrensel olduğuna",
      "C) Kültür ve uygarlığın dille doğrudan ve sıkı bir ilişkisinin olduğuna",
      "D) Dilin, toplumsal mirası geleceğe taşıyan en önemli araç olduğuna",
      "E) İnsanlığın bilim ve teknoloji sayesinde kendi kültürünü sürekli geliştirebileceğine",
    ],
    cevap: 4,
    aciklama: "Paragrafta bilim ve teknolojinin kültür geliştirmedeki rolüne dair bir ifade veya vurgu yer almamaktadır. Diğer şıkların hepsi metinden çıkarılabilir.",
  },
  {
    id: 7,
    soru: "(I) Uluslararası çapta bakıldığında günümüzün en önemli sağlık sorunlarından biri obezite. (II) Toplumda daha çok kanser ve kalp hastalıklarından çekinilse de bu sorun da ciddi bir problem olarak karşımıza çıkıyor. (III) Çünkü başlı başına bir risk faktörü olan obezite, sağlığı önemli şekilde etkiliyor. (IV) Diyabete, yüksek tansiyona, lipid bozukluğa, uyku apnesine, kalp ve akciğer hastalıklarına, depresyon ve anksiyete gibi psikolojik bozukluklara yol açıyor. (V) Ülkemizde obez oranı son 20 yılda hızla artış göstermektedir. Bu parçadaki numaralanmış cümlelerden hangisi \"düşüncenin akışını\" bozmaktadır?",
    secenekler: ["A) I", "B) II", "C) III", "D) IV", "E) V"],
    cevap: 4,
    aciklama: "V numaralı cümle paragrafın genelindeki obezitenin yol açtığı \"sağlık/hastalık\" boyutundan sapan istatistiksel bir bilgi içerir, akışı bozmaktadır.",
  },
  {
    id: 8,
    soru: "I. Asırlık çınarların gölgelediği caddeler, eski konsolosluk binalarıyla doludur. II. Cetine, Karadağ'da tarihî dokusuyla dikkat çeken bir kenttir. III. Çünkü Cetine, 15. yy.dan 1946'ya kadar başkentlik yapmıştır. IV. Yugoslavya dönemiyle birlikte bu unvanını Podgorica'ya kaptırmıştı. V. Sakin kentin geniş caddelerinde yer alan eski binalar geçmişin izlerini hâlâ taşımaktadır. Numaralanmış cümlelerle anlamlı bir paragraf oluşturulmak istense doğru sıralama nasıl olur?",
    secenekler: ["A) II - V - I - III - IV", "B) I - III - II - IV - V", "C) II - I - III - V - IV", "D) I - III - V - II - IV", "E) V - II - IV - III - I"],
    cevap: 0,
    aciklama: "Giriş cümlesi II'dir. Mantıksal akış sırasıyla II - V - I - III - IV şeklinde kurulmalıdır.",
  },
  {
    id: 9,
    soru: "\"Artvin'in Borçka ve Şavşat ilçelerinin sınırları içinde yer alan Maçaheli; buzul gölleri, zirveleri, dereleriyle ülkemizin 122 önemli bitki alanından biridir. Bölgedeki egemen ağaç türleri, kayın ve ladindir. ---- Böyle bir bitki örtüsüne sahip olması ve nüfusun fazla olmaması, yaban yaşamını olumlu etkilemiştir. Bölge, hayvan türleri açısından da zengindir. Bozayı, çakal, su samuru, çengel boynuzlu dağ keçisi bölgede yaygın olarak gözlemlenmektedir.\" Bu parçada boş bırakılan yere düşüncenin akışına göre aşağıdakilerden hangisi getirilebilir?",
    secenekler: [
      "A) Bölgenin bitki zenginliği bununla da sınırlı değildir elbette.",
      "B) Bölgedeki ağaç türlerinin korunması için önemli çalışmalar yapıldı.",
      "C) Bu ağaç türleri birçok bölgedekinden farklı özellikleri olan ağaçlardır.",
      "D) Ağaç ve diğer bitki türleri için oldukça elverişli bir iklimi vardır.",
      "E) Bu iki ağacın dışında kestane, gürgen, ıhlamur ağaçları da çok yaygındır.",
    ],
    cevap: 4,
    aciklama: "Boşluktan önceki cümlede kayın ve ladin ağaçlarından bahsedilmiştir. Boşluğa \"Bu iki ağacın dışında...\" diye başlayan E seçeneği tam olarak uymaktadır.",
  },
  {
    id: 10,
    soru: "\"Edebiyat, dille iletişim kuran bir sanatsal etkinlik alanıdır. (I) Bu sanat dalı, ortak dil üzerine temellendirilir. (II) Ancak her edebiyatçı farklı bir söylem geliştirir. (III) Bu da gündelik dilden çok farklıdır. (IV) Günlük yaşamın gerçekliği ile sanatsal gerçeklik apayrıdır. (V) Sanatsal gerçeklik, her ne kadar günlük yaşam gerçekliğinden yola çıksa da özellikler ona benzese de kurmaca gerçekliktir, günlük yaşamın gerçekliğiyle bire bir örtüşmez.\" Bu parça iki paragrafa ayrılmak istense ikinci paragraf hangi cümleden sonra başlar?",
    secenekler: ["A) I", "B) II", "C) III", "D) IV", "E) V"],
    cevap: 2,
    aciklama: "III. cümleye kadar ortak dilden bahsedilirken, IV. cümleden itibaren sanatsal gerçeklik konusuna geçilmiştir, paragraf buradan (III'ten sonra) bölünmelidir.",
  },
  {
    id: 11,
    soru: "Aşağıdakilerden hangisi bir paragrafın \"giriş cümlesi\" olmaya en uygundur?",
    secenekler: [
      "A) Bu başarıların altında zamanı doğru ve planlı yönetmek yatıyor.",
      "B) Zamanı doğru kullanmak da artık belli eğitimlerle insanlara öğretiliyor.",
      "C) Günümüzde zaman, her sektör ve her insan için çok çok önemlidir.",
      "D) Öyleyse bir değerin, ürünün kalitesi kadar zamanında üretim de önemlidir.",
      "E) Bir bu kadar önemli olan zamanı verimli kullanmanın yollarını aradık.",
    ],
    cevap: 2,
    aciklama: "A, B, D ve E seçenekleri kendinden önce bir cümlenin varlığına işaret eden bağlayıcı unsurlar içerir. C cümlesi bağımsız bir giriş cümlesidir.",
  },
  {
    id: 12,
    soru: "Aşağıdaki cümlelerin hangisinde \"gereksiz sözcük kullanımından\" kaynaklanan bir anlatım bozukluğu vardır?",
    secenekler: [
      "A) Toplantıda herkes fikirlerini açıkça söyledi, kimse çekinmedi.",
      "B) Bu tedaviden sonra hastanın durumu gün geçtikçe iyiye gitti.",
      "C) Kursu bitiren kursiyerlerin hepsi mecburen yürümek zorunda kaldı.",
      "D) Yol kenarındaki büyük kestane ağaçlarının altında saatlerce oturduk.",
      "E) Şirketin sunduğu cazip teklifi kabul edince hayatı aniden değişti.",
    ],
    cevap: 2,
    aciklama: "\"mecburen\" ve \"zorunda kaldı\" sözleri aynı anlama gelir, birlikte kullanılması gereksiz sözcük kullanımı hatasıdır.",
  },
  {
    id: 13,
    soru: "Aşağıdaki cümlelerin hangisinde \"sözcüğün yanlış yerde kullanılmasından\" kaynaklanan bir anlatım bozukluğu vardır?",
    secenekler: [
      "A) Yeni sınıfa girmiştim ki telefonum acı acı çalmaya başladı.",
      "B) Cumhurbaşkanı otoyolu hizmete açarak bölge halkını sevindirdi.",
      "C) Her gün günaşırı bu ağır ilaçları içmek zorunda kalıyorum.",
      "D) Etrafındaki meraklı kalabalığa yüksek sesle ve sinirle bağırıyordu.",
      "E) Üzülmesinin tek nedeni bizim ona haber vermeyişimizdendir.",
    ],
    cevap: 0,
    aciklama: "\"Yeni sınıfa\" değil \"Sınıfa yeni girmiştim ki...\" şeklinde olmalıdır. \"Yeni\" kelimesi yanlış yerde kullanılmıştır.",
  },
  {
    id: 14,
    soru: "Aşağıdaki cümlelerin hangisinde \"çatı uyuşmazlığından\" kaynaklanan bir anlatım bozukluğu vardır?",
    secenekler: [
      "A) Sabah erkenden yola çıkıp akşama doğru şirin köye ulaştık.",
      "B) Bütün ödevler dikkatlice kontrol edilerek hatasız şekilde bitirildi.",
      "C) Sınıftaki herkes sessizce oturmuş öğretmenin gelmesini bekliyordu.",
      "D) Hep beraber sohbet ederek akşam saatlerinde çaylar içildi.",
      "E) Kitabın kontrolleri tamamlanıp en kısa sürede baskıya gönderildi.",
    ],
    cevap: 3,
    aciklama: "\"sohbet ederek\" etken bir eylemsiyken, \"çaylar içildi\" edilgendir. Doğrusu \"sohbet edilerek çaylar içildi\" olmalıdır (çatı uyuşmazlığı).",
  },
  {
    id: 15,
    soru: "Aşağıdaki cümlelerin hangisinde \"tamlama yanlışlığından\" kaynaklanan bir anlatım bozukluğu vardır?",
    secenekler: [
      "A) Bu yasadan özel ve kamu kuruluşlarında çalışan herkes yararlanacak.",
      "B) Askerî ve fen liseleri sınav sonuçları yarın internette açıklanacak.",
      "C) Çocukluğumuz bu büyük konakta ve önündeki bahçede geçti.",
      "D) Bu zor işe ne senin gücün ne de benim gücüm yeter, bırakalım.",
      "E) Yıllarca İstanbul'da yaşadım ama trafiğine bir türlü alışamadım.",
    ],
    cevap: 1,
    aciklama: "\"Askerî liseleri ve fen liseleri\" şeklinde kurulmalıdır. \"Askerî\" sıfatı ortak tamlanana bağlandığında \"Askerî liseleri\" şeklinde uyuşmazlık (tamlama yanlışı) yaratır.",
  },
];
