import { DenemeSorusu } from './deneme1';

export const deneme10Baslik = "Çağdaş Türk ve Dünya Tarihi & Güncel Gelişmeler";

export const deneme10: DenemeSorusu[] = [
  {
    id: 1,
    soru: "II. Dünya Savaşı yıllarında (1939-1945) savaşa fiilen girmediği halde Türkiye Cumhuriyeti'nde \"Cumhurbaşkanlığı\" makamında bulunan devlet adamı aşağıdakilerden hangisidir?",
    secenekler: ["A) Celal Bayar", "B) İsmet İnönü", "C) Adnan Menderes", "D) Fevzi Çakmak", "E) Refik Saydam"],
    cevap: 1,
    aciklama: "II. Dünya Savaşı yıllarında (1939-1945) Türkiye Cumhuriyeti'nin Cumhurbaşkanı İsmet İnönü'dür. Uyguladığı başarılı denge politikasıyla Türkiye'yi savaşın yıkımından uzak tutmayı başarmıştır.",
  },
  {
    id: 2,
    soru: "Türkiye Cumhuriyeti'nin II. Dünya Savaşı'na fiilen katılmadığı halde, savaşın sonlarına doğru (23 Şubat 1945) mihver devletlere kağıt üzerinde savaş ilan etmesinin \"temel nedeni\" aşağıdakilerden hangisidir?",
    secenekler: ["A) Birleşmiş Milletler'in kurucu üyeleri arasında yer alabilmek", "B) NATO'ya üye kabul edilmek", "C) Balkan Antantı'nı yeniden canlandırmak", "D) Marshall Yardımları'ndan daha fazla pay alabilmek", "E) Sadabat Paktı sınırlarını koruma altına almak"],
    cevap: 0,
    aciklama: "Türkiye, Yalta Konferansı kararları doğrultusunda, yeni kurulacak olan Birleşmiş Milletler (BM) teşkilatının kurucu üyeleri arasında yer alabilmek için savaşın bitmesine aylar kala Almanya ve Japonya'ya kağıt üzerinde savaş ilan etmiştir.",
  },
  {
    id: 3,
    soru: "II. Dünya Savaşı'nın ardından 1945 yılında kurulan ve dünya barışını korumayı amaçlayan \"Birleşmiş Milletler\" örgütünün kurucu antlaşmasının adı aşağıdakilerden hangisidir?",
    secenekler: ["A) Roma Antlaşması", "B) BM Şartı (San Francisco Konferansı)", "C) Paris Antlaşması", "D) Washington Antlaşması", "E) Maastricht Antlaşması"],
    cevap: 1,
    aciklama: "Birleşmiş Milletler'in kurucu belgesi olan antlaşma San Francisco Konferansı'nda kabul edilen BM Şartı'dır.",
  },
  {
    id: 4,
    soru: "Türkiye'nin Kuzey Atlantik Antlaşması Örgütü'ne (NATO) üye olmasında ve batı blokuyla entegrasyonunda doğrudan etkili olan askeri gelişme aşağıdakilerden hangisidir?",
    secenekler: ["A) Kore Savaşı'na asker gönderilmesi", "B) Kıbrıs Barış Harekatı'nın yapılması", "C) II. Dünya Savaşı'nda müttefiklere destek verilmesi", "D) Körfez Savaşı'nda koalisyona katılınması", "E) Balkan Paktı'nın kurulması"],
    cevap: 0,
    aciklama: "Türkiye, Batı ittifakına ve savunma paktı olan NATO'ya kabul edilmek amacıyla 1950 yılında Kore Savaşı'na asker göndermiştir. Türk tugayının buradaki üstün başarısı sonrası Türkiye 1952'de NATO'ya üye yapılmıştır.",
  },
  {
    id: 5,
    soru: "Türkiye'de çok partili hayata geçildikten sonra yapılan seçimlerde (1950) iktidara gelen ilk parti aşağıdakilerden hangisidir?",
    secenekler: ["A) Terakkiperver Cumhuriyet Fırkası", "B) Serbest Cumhuriyet Fırkası", "C) Demokrat Parti", "D) Millet Partisi", "E) Cumhuriyet Halk Partisi"],
    cevap: 2,
    aciklama: "14 Mayıs 1950 seçimleriyle CHP'nin 27 yıllık tek parti iktidarı son bulmuş ve Celal Bayar ile Adnan Menderes liderliğindeki Demokrat Parti tek başına iktidara gelmiştir.",
  },
  {
    id: 6,
    soru: "Türkiye Cumhuriyeti'nin \"ilk kadın başbakanı\" olarak tarihe geçen siyasetçi aşağıdakilerden hangisidir?",
    secenekler: ["A) Tansu Çiller", "B) Türkan Akyol", "C) Meral Akşener", "D) Behice Boran", "E) Filiz Dinçmen"],
    cevap: 0,
    aciklama: "Türkiye Cumhuriyeti tarihinin ilk ve tek kadın başbakanı 1993-1996 yılları arasında görev yapan Tansu Çiller'dir.",
  },
  {
    id: 7,
    soru: "Avrupa Birliği'nin (AB) temeli sayılan ve üye ülkeler arasındaki ekonomik entegrasyonu başlatan antlaşma aşağıdakilerden hangisidir?",
    secenekler: ["A) Maastricht Antlaşması", "B) Roma Antlaşması", "C) Paris Antlaşması", "D) Schengen Antlaşması", "E) Londra Antlaşması"],
    cevap: 1,
    aciklama: "1957 yılında imzalanan Roma Antlaşması ile Avrupa Ekonomik Topluluğu (AET) kurulmuş ve bu topluluk bugünkü Avrupa Birliği'nin temeli sayılmıştır.",
  },
  {
    id: 8,
    soru: "Türkiye'nin Avrupa Birliği'ne (AB) \"aday ülke\" olarak resmen ilan edildiği tarihi zirve aşağıdakilerden hangisidir?",
    secenekler: ["A) Kopenhag Zirvesi", "B) Helsinki Zirvesi (1999)", "C) Maastricht Zirvesi", "D) Nice Zirvesi", "E) Roma Zirvesi"],
    cevap: 1,
    aciklama: "Türkiye'nin Avrupa Birliği'ne tam üyeliğe giden yolda \"Aday Ülke\" statüsü kazandığı zirve 1999 Helsinki Zirvesi'dir.",
  },
  {
    id: 9,
    soru: "Bosna Savaşı sırasında halkına liderlik eden, bağımsızlık mücadelesinin sembolü olan ve \"Bilge Kral\" olarak bilinen tarihi şahsiyet kimdir?",
    secenekler: ["A) Aliya İzzetbegoviç", "B) Cengiz Aytmatov", "C) Dudayev", "D) Sadık Ahmet", "E) Rauf Denktaş"],
    cevap: 0,
    aciklama: "Bosna-Hersek'in ilk cumhurbaşkanı olan Aliya İzzetbegoviç, tüm dünyada \"Bilge Kral\" olarak anılmaktadır.",
  },
  {
    id: 10,
    soru: "Kıbrıs'ta Rumların Türk halkına yönelik baskı ve katliamlarına son vermek amacıyla Türkiye'nin 1974 yılında gerçekleştirdiği askeri harekatın adı aşağıdakilerden hangisidir?",
    secenekler: ["A) Atilla Harekatı (Kıbrıs Barış Harekatı)", "B) Pençe Harekatı", "C) Fırat Kalkanı Harekatı", "D) Zeytin Dalı Harekatı", "E) Kıbrıs Yıldızı Operasyonu"],
    cevap: 0,
    aciklama: "1974 yılında Türk Silahlı Kuvvetleri tarafından Kıbrıs'ta gerçekleştirilen harekatın askeri kod adı Atilla Harekatı'dır (kamuoyunda Kıbrıs Barış Harekatı olarak bilinir).",
  },
  {
    id: 11,
    soru: "Kıbrıslı Rumların Ada'yı Yunanistan'a bağlamak (Enosis) amacıyla kurduğu terör örgütü ile buna karşı Türklerin savunma amaçlı kurduğu örgüt sırasıyla hangisinde doğru verilmiştir?",
    secenekler: ["A) EOKA - Türk Mukavemet Teşkilatı (TMT)", "B) TMT - EOKA", "C) Asala - EOKA", "D) Taşnak - Türk Mukavemet Teşkilatı", "E) Mavri Mira - Pontus"],
    cevap: 0,
    aciklama: "Kıbrıslı Rumların kurduğu terör örgütü EOKA iken; buna karşı Türk halkının can ve mal güvenliğini savunmak amacıyla kurulan örgüt Türk Mukavemet Teşkilatı (TMT)'dır.",
  },
  {
    id: 12,
    soru: "Soğuk Savaş döneminin sembolü olan ve \"Utanç Duvarı\" olarak da bilinen Berlin Duvarı hangi yıl yıkılmıştır?",
    secenekler: ["A) 1989", "B) 1991", "C) 1995", "D) 1980", "E) 2001"],
    cevap: 0,
    aciklama: "Doğu ve Batı dünyasının bölünmüşlüğünün simgesi olan Berlin Duvarı, 1989 yılında halk tarafından yıkılmış ve Almanya birleşme sürecine girmiştir.",
  },
  {
    id: 13,
    soru: "Sovyet Sosyalist Cumhuriyetler Birliği (SSCB) hangi yıl resmen dağılmış ve Soğuk Savaş dönemi tamamen sona ermiştir?",
    secenekler: ["A) 1989", "B) 1991", "C) 1993", "D) 1995", "E) 1999"],
    cevap: 1,
    aciklama: "Mihail Gorbaçov'un reform süreçlerinin (Glasnost ve Perestroyka) ardından 1991 yılında SSCB resmen dağılmış ve Soğuk Savaş dönemi sona ermiştir.",
  },
  {
    id: 14,
    soru: "Türk dünyası entegrasyonunun en önemli kurumsal adımı olan ve sekretaryası İstanbul'da bulunan örgütün günümüzdeki adı aşağıdakilerden hangisidir?",
    secenekler: ["A) Türk Konseyi", "B) Türk Devletleri Teşkilatı", "C) TÜRKSOY", "D) Türk Akademisi", "E) Türk Dünyası Vakfı"],
    cevap: 1,
    aciklama: "Eski adı Türk Konseyi olan ve üye ülkeler arasındaki entegrasyonu en üst düzeye çıkaran uluslararası örgütün günümüzdeki adı Türk Devletleri Teşkilatı'dır. Sekretaryası İstanbul'dadır.",
  },
  {
    id: 15,
    soru: "Nobel Kimya Ödülü'nü kazanarak Türkiye'ye bilim alanında bu gururu yaşatan ilk bilim insanımız aşağıdakilerden hangisidir?",
    secenekler: ["A) Gazi Yaşargil", "B) Aziz Sancar", "C) Oktay Sinanoğlu", "D) Celal Şengör", "E) Canan Dağdeviren"],
    cevap: 1,
    aciklama: "DNA onarımı mekanizmaları üzerindeki çığır açan çalışmalarıyla Aziz Sancar, 2015 yılında Nobel Kimya Ödülü'nü kazanarak bu alanda ödül alan ilk Türk bilim insanı olmuştur.",
  },
  {
    id: 16,
    soru: "Nobel Edebiyat Ödülü'nü alan ilk Türk yazar aşağıdakilerden hangisidir?",
    secenekler: ["A) Yaşar Kemal", "B) Orhan Pamuk", "C) Cengiz Aytmatov", "D) Necip Fazıl Kısakürek", "E) Ahmet Hamdi Tanpınar"],
    cevap: 1,
    aciklama: "Ünlü yazar Orhan Pamuk, 2006 yılında Nobel Edebiyat Ödülü'nü kazanarak Türkiye'ye bu daldaki ilk ödülü getiren isim olmuştur.",
  },
  {
    id: 17,
    soru: "Halk arasında \"Toprak Dede\" olarak bilinen, TEMA Vakfı'nın kurucularından olan tarihi şahsiyet kimdir?",
    secenekler: ["A) Hayrettin Karaca", "B) Gazi Yaşargil", "C) Oktay Sinanoğlu", "D) Ali Kuşçu", "E) Naim Süleymanoğlu"],
    cevap: 0,
    aciklama: "TEMA Vakfı'nın kurucularından olan, ömrünü erozyonla mücadeleye adayan milli kahramanımız Hayrettin Karaca, \"Toprak Dede\" olarak anılmaktadır.",
  },
  {
    id: 18,
    soru: "Türkiye'nin ilk astronotu olarak uzay misyonunu başarıyla tamamlayan ve uzaya çıkan ilk Türk olarak tarihe geçen kişi aşağıdakilerden hangisidir?",
    secenekler: ["A) Alper Gezeravcı", "B) Tuva Cihangir Atasever", "C) Bandırma Roket Kulübü Temsilcisi", "D) Selçuk Bayraktar", "E) Vecihi Hürkuş"],
    cevap: 0,
    aciklama: "Alper Gezeravcı, Ax-3 misyonu kapsamında uzay istasyonuna giderek uzaya çıkan ilk Türk astronot olarak tarihe geçmiştir.",
  },
  {
    id: 19,
    soru: "Osman Hamdi Bey tarafından 1880 yılında yapılan ve 2019 yılında Londra'daki bir müzayedede 6 milyon sterlinin üzerinde rekor bir fiyata satılan ünlü tablo aşağıdakilerden hangisidir?",
    secenekler: ["A) Kaplumbağa Terbiyecisi", "B) Kur'an Okuyan Kız", "C) Beyaz Vazoda Çiçekler", "D) İki Genç Kızın Türbe Ziyareti", "E) İstanbul Kadını"],
    cevap: 1,
    aciklama: "Osman Hamdi Bey'in \"Kur'an Okuyan Kız\" tablosu, 2019 yılında Londra'daki Bonhams müzayedesinde 6.3 milyon sterline satılarak en pahalı Türk sanat eserlerinden biri olmuştur.",
  },
  {
    id: 20,
    soru: "Dünya üzerinde petrol ihraç eden ülkelerin fiyat ve üretim politikalarını belirlemek amacıyla kurduğu uluslararası kartel/örgüt aşağıdakilerden hangisidir?",
    secenekler: ["A) OPEC", "B) OECD", "C) IMF", "D) WTO", "E) NATO"],
    cevap: 0,
    aciklama: "Petrol İhraç Eden Ülkeler Örgütü olarak bilinen OPEC, küresel petrol piyasasında fiyat istikrarı ve üretim kotalarını belirlemek amacıyla kurulan uluslararası kartel yapısıdır.",
  },
];
