import { DenemeSorusu } from './deneme1';

export const denemeGB4Baslik = "Güncel Bilgiler - Deneme 4";

export const denemeGB4: DenemeSorusu[] = [
  {
    id: 1,
    soru: "Milli Eğitim müfredatında \"Tehcir Kanunu\" ifadesi yerine aşağıdaki kavramlardan hangisi getirilmiştir?",
    secenekler: ["A) Milli Mücadele Kanunu", "B) Sevk ve İskan Kanunu", "C) Asılsız Ermeni İddiaları", "D) Gök Vatan Kanunu", "E) Sömürgecilik Yasası"],
    cevap: 1,
    aciklama: "MEB müfredatında \"Tehcir Kanunu\" ifadesi \"Sevk ve İskan Kanunu\" olarak değiştirilmiştir.",
  },
  {
    id: 2,
    soru: "2026 yılında \"Dünya Ekonomik Forumu\" aşağıdaki ülkelerin hangisinde gerçekleştirilecektir?",
    secenekler: ["A) İsviçre", "B) Fransa", "C) İtalya", "D) Avusturya", "E) Türkiye"],
    cevap: 0,
    aciklama: "2026 Dünya Ekonomik Forumu İsviçre'de (Davos'ta) yapılacaktır.",
  },
  {
    id: 3,
    soru: "İslam İşbirliği Teşkilatı (İİT) genel merkezi aşağıdaki şehirlerin hangisinde yer almaktadır?",
    secenekler: ["A) Tahran", "B) Cidde", "C) Kahire", "D) Addis Ababa", "E) İstanbul"],
    cevap: 1,
    aciklama: "İslam İşbirliği Teşkilatı (İİT) genel merkezi Suudi Arabistan'ın Cidde kentindedir.",
  },
  {
    id: 4,
    soru: "Teleskobu gökyüzü gözlemlerinde ilk defa kullanarak modern astronominin temellerini atan bilim insanı kimdir?",
    secenekler: ["A) Galileo", "B) Thomas Edison", "C) Albert Einstein", "D) Samuel Morse", "E) Piri Reis"],
    cevap: 0,
    aciklama: "Gökyüzünü gözlemlemek amacıyla teleskobu ilk kullanan mucit Galileo'dur.",
  },
  {
    id: 5,
    soru: "2026 yılı Oscar Ödülleri'nde \"En İyi Erkek Oyuncu\" ödülünü kazanan isim aşağıdakilerden hangisidir?",
    secenekler: ["A) Michael B. Jordan", "B) Brendan Fraser", "C) Joaquin Phoenix", "D) Cillian Murphy", "E) Will Smith"],
    cevap: 0,
    aciklama: "2026 Oscar En İyi Erkek Oyuncu ödülünü Michael B. Jordan (Sinners filmiyle) almıştır.",
  },
  {
    id: 6,
    soru: "UNESCO Yaratıcı Şehirler Ağı'na \"Müzik\" alanında 2023 yılında katılan son şehrimiz aşağıdakilerden hangisidir?",
    secenekler: ["A) Şanlıurfa", "B) Kırşehir", "C) Adana", "D) Kahramanmaraş", "E) Gaziantep"],
    cevap: 0,
    aciklama: "2023 yılında Müzik alanında ağa giren şehrimiz Şanlıurfa'dır.",
  },
  {
    id: 7,
    soru: "2024 Nobel Fizik Ödülü aşağıdaki çalışma alanlarından hangisinde çalışan bilim insanlarına verilmiştir?",
    secenekler: ["A) Kuantum bilgisayar teknolojileri", "B) Kara delik keşifleri", "C) Yapay zekâ sinir ağları", "D) Küresel ısınma modellemeleri", "E) Higgs Bozonu tespiti"],
    cevap: 2,
    aciklama: "2024 Nobel Fizik Ödülü, yapay sinir ağlarının temellerini atan çalışmalarıyla John Hopfield ve Geoffrey Hinton'a verilmiştir.",
  },
  {
    id: 8,
    soru: "2026 yılında \"Akdeniz Oyunları\" aşağıdaki ülkelerin hangisinde, hangi şehirde düzenlenecektir?",
    secenekler: ["A) İtalya - Taranto", "B) Fransa - Nice", "C) Türkiye - İzmir", "D) İspanya - Barselona", "E) Yunanistan - Atina"],
    cevap: 0,
    aciklama: "2026 Akdeniz Oyunları İtalya'nın Taranto şehrinde düzenlenecektir.",
  },
  {
    id: 9,
    soru: "Ekonomik İşbirliği Teşkilatı (EİT) genel merkezi aşağıdaki şehirlerin hangisindedir?",
    secenekler: ["A) İstanbul", "B) Tahran", "C) Cidde", "D) Pekin", "E) Kahire"],
    cevap: 1,
    aciklama: "Ekonomik İşbirliği Teşkilatı (EİT) genel merkezi İran'ın Tahran kentindedir.",
  },
  {
    id: 10,
    soru: "Milli Eğitim müfredatında \"Pontus Meselesi\" yerine aşağıdaki kullanımlardan hangisi getirilmiştir?",
    secenekler: ["A) Asılsız Ermeni iddiaları", "B) Asılsız Pontus iddiaları", "C) Sömürgeciliğin Başlangıcı", "D) Sevk ve İskan Kanunu", "E) Doğu Roma İstilaları"],
    cevap: 1,
    aciklama: "Pontus Meselesi yerine \"Asılsız Pontus iddiaları\" kavramı getirilmiştir.",
  },
  {
    id: 11,
    soru: "Tarihte ilk kez \"X-ray (Röntgen)\" cihazını bularak tıp dünyasında çığır açan bilim insanı kimdir?",
    secenekler: ["A) Wilhelm Condrad Röntgen", "B) Charles Frances Richter", "C) Galileo", "D) Albert Einstein", "E) Alexander Fleming"],
    cevap: 0,
    aciklama: "Röntgen ışınlarını bulan ve cihaza adını veren bilim insanı Wilhelm Condrad Röntgen'dir.",
  },
  {
    id: 12,
    soru: "Birleşmiş Milletler Eğitim, Bilim ve Kültür Örgütü (UNESCO) genel merkezi aşağıdaki şehirlerin hangisindedir?",
    secenekler: ["A) Brüksel", "B) Cenevre", "C) Paris", "D) Lyon", "E) New York"],
    cevap: 2,
    aciklama: "UNESCO genel merkezi Fransa'nın Paris şehrindedir.",
  },
  {
    id: 13,
    soru: "2025 yılında \"En İyi Film\" Oscar ödülünü kazanan sinema yapımı aşağıdakilerden hangisidir?",
    secenekler: ["A) Anora", "B) Oppenheimer", "C) Nomadland", "D) Parasite", "E) CODA"],
    cevap: 0,
    aciklama: "2025 yılı Oscar En İyi Film ödülünü \"Anora\" kazanmıştır.",
  },
  {
    id: 14,
    soru: "Dünyanın en büyük uluslararası kriminal polis teşkilatı olan \"INTERPOL\" genel merkezi Fransa'nın hangi şehrindedir?",
    secenekler: ["A) Paris", "B) Lyon", "C) Marsilya", "D) Nice", "E) Strazburg"],
    cevap: 1,
    aciklama: "INTERPOL genel merkezi Fransa'nın Lyon şehrindedir.",
  },
  {
    id: 15,
    soru: "UNESCO Yaratıcı Şehirler Ağı'na \"Gastronomi\" alanında 2023 yılında kabul edilen son Türk şehri hangisidir?",
    secenekler: ["A) Gaziantep", "B) Hatay", "C) Afyonkarahisar", "D) Adana", "E) Şanlıurfa"],
    cevap: 3,
    aciklama: "2023 yılında Gastronomi kategorisinde en son eklenen şehrimiz Adana'dır.",
  },
  {
    id: 16,
    soru: "Milli Eğitim Müfredatında \"Ormanlarımız\" kavramı yerine aşağıdaki kullanımlardan hangisi getirilmiştir?",
    secenekler: ["A) Mavi Vatan", "B) Yeşil Vatan", "C) Gök Vatan", "D) Doğu Roma", "E) Adalar Denizi"],
    cevap: 1,
    aciklama: "Yeni müfredatta \"Ormanlarımız\" kavramı \"Yeşil Vatan\" olarak tanımlanmıştır.",
  },
  {
    id: 17,
    soru: "Radyo dalgalarını bularak kablosuz iletişimin (radyo) temelini atan mucit aşağıdakilerden hangisidir?",
    secenekler: ["A) Guglielmo Marconi", "B) Graham Bell", "C) Samuel Morse", "D) Martin Cooper", "E) Thomas Edison"],
    cevap: 0,
    aciklama: "Radyonun mucidi Guglielmo Marconi'dir.",
  },
  {
    id: 18,
    soru: "2025 yılı Şampiyonlar Ligi Finali aşağıdaki şehirlerin hangisinde oynanmıştır?",
    secenekler: ["A) Budapeşte", "B) Münih", "C) İstanbul", "D) Paris", "E) Londra"],
    cevap: 1,
    aciklama: "2025 Şampiyonlar Ligi Finali Almanya'nın Münih kentinde oynanmıştır.",
  },
];
