import { DenemeSorusu } from './deneme1';

export const denemeTurkce4Baslik = "Fiilimsi, Fiilde Çatı, Cümle Ögeleri ve Cümle Türleri";

export const denemeTurkce4: DenemeSorusu[] = [
  {
    id: 1,
    soru: "\"Evin bahçesine dikilecek çamların üzerine konmuş bir serçe, durmadan cik cik edip şarkısını söylüyordu. Evin tekir kedisi eşiğe uzanmış, bir yandan örselenmiş tüylerini düzeltmek için yalarken bir yandan da az ilerideki çöplükte sallana sallana gezinen kargaya bakıyordu.\" Bu parçada altı çizili sözcüklerle ilgili (dikilecek, konmuş, durmadan, örselenmiş, gezinen) yapılan incelemede hangisi \"zarf-fiil\" görevindedir?",
    secenekler: ["A) dikilecek", "B) konmuş", "C) durmadan", "D) örselenmiş", "E) gezinen"],
    cevap: 2,
    aciklama: "\"durmadan\" sözcüğündeki \"-madan / -meden\" eki zarf-fiil (ulaç) ekidir. Diğerleri (dikilecek, konmuş, örselenmiş, gezinen) sıfat-fiil (ortaç) ekleridir.",
  },
  {
    id: 2,
    soru: "Aşağıdaki cümlelerin hangisinde yer alan eylemsi (fiilimsi) \"ulaç (bağ-fiil)\" görevinde kullanılmamıştır?",
    secenekler: [
      "A) Düşüncelerini toplantıda hiç çekinmeden açıkça söylerdi.",
      "B) Soruları bütün yönleriyle derinlemesine düşünerek yanıtlıyordu.",
      "C) Sınavdan hemen sonra arkadaşlarıyla güle oynaya evine gitti.",
      "D) Gezilecek yerlerin listesini akşamdan hazırlayıp bize verdi.",
      "E) İşi zamanında yetiştirmek için ölesiye çabalayıp duruyordu.",
    ],
    cevap: 3,
    aciklama: "D seçeneğindeki \"Gezilecek yerler\" tamlamasındaki \"gezilecek\" sıfat-fiildir (ortaç). Diğer şıklardaki ekler (-meden, -erek, -a -a, -esiye) zarf-fiildir.",
  },
  {
    id: 3,
    soru: "Sıfat-fiil eklerini alan bazı sözcükler, bir varlığın ya da kavramın karşılığı olarak kullanılarak kalıcı isim olur, sıfat-fiil olma özelliğini kaybederler. Aşağıdaki cümlelerin hangisinde bu duruma örnek bir \"kalıcı isim\" kullanılmıştır?",
    secenekler: [
      "A) Yolun sağına doğru hızla dönen arabayı takip edin.",
      "B) Kış için yakacak odunları bahçedeki depoya bıraktı.",
      "C) Onun tavsiye ettiği soruları mutlaka çözmelisin.",
      "D) Dolmuş durağına kadar hiç durmadan yürümeye karar verdiler.",
      "E) Dolapta giyecek hiçbir elbisesinin kalmadığını söyledi.",
    ],
    cevap: 3,
    aciklama: "\"Dolmuş\" sözcüğü sıfat-fiil ekini alarak kalıplaşmış ve bir ulaşım aracının (somut varlık) adı olmuştur.",
  },
  {
    id: 4,
    soru: "Aşağıdaki cümlelerden hangisinin yüklemi, \"nesne-yüklem ilişkisine göre\" geçişsiz bir fiildir?",
    secenekler: [
      "A) Paranın mutluluk için yeterli olmadığını her zaman bilmelisin.",
      "B) Hayatının her anını dolu dolu ve anlamlı yaşamalısın.",
      "C) Piknik alanındaki yemyeşil çimenlerin üzerine saatlerce uzandık.",
      "D) Onun el yazısını ve notlarını bir türlü okuyamıyorum.",
      "E) Yarınki zor ödevi nasıl yapacağımızı uzun uzun düşündük.",
    ],
    cevap: 2,
    aciklama: "\"uzandık\" eylemi nesne alamayan, \"onu uzandık\" şeklinde okunamayan geçişsiz bir fiildir. Diğerleri nesne alabildiği için geçişlidir.",
  },
  {
    id: 5,
    soru: "Aşağıdaki cümlelerden hangisinin yüklemi, \"özne-yüklem ilişkisine göre\" edilgen çatılı bir eylemdir?",
    secenekler: [
      "A) Düzenli olarak haftada üç gün sahilde yürüyüş yapıyorum.",
      "B) Okuldaki sınav tarihleri ve salonları bir ay önce açıklandı.",
      "C) Küçükken akşama kadar mahalledeki sokaklarda oynardık.",
      "D) Bugün yaşanan güzel olayları birer anı olarak hatırlayacağım.",
      "E) Bahçedeki meyve ağaçları ilkbaharla birlikte mis gibi kokar.",
    ],
    cevap: 1,
    aciklama: "\"açıklandı\" eylemi \"-n\" edilgenlik ekini almıştır ve sınav tarihlerinin kimin tarafından açıklandığı belli değildir (Sözde Özne: sınav tarihleri).",
  },
  {
    id: 6,
    soru: "Aşağıdaki dizelerin hangisinde \"fiilde çatı\" özelliği aranmaz?",
    secenekler: [
      "A) Duyuluyor zamanın tahtayı kemirdiği tavan aralarında.",
      "B) Atıyor sızıların çıplak duvarda nabzı çivi yaralarında.",
      "C) Bir merhamettir yanan, daracık odaların isli lambalarında.",
      "D) Bir sırrı sürüklüyor terlikler tıpır tıpır izbe sofralarında.",
      "E) Ağlayın, aşinasız, sessiz can verenlere otel odalarında.",
    ],
    cevap: 2,
    aciklama: "\"Bir merhamettir yanan\" cümlesinde yüklem \"merhamettir\" ismidir. İsim cümlelerinde fiilde çatı özelliği aranmaz.",
  },
  {
    id: 7,
    soru: "Aşağıdaki cümlelerden hangisinin yüklemi \"ettirgen çatılı\" bir eylemdir?",
    secenekler: [
      "A) Evdeki etrafı çarçabuk toparlayıp akşam sofrasını kurdurduk.",
      "B) Gölün kenarında küçük beyaz kuzular neşeyle otluyordu.",
      "C) Semtimize giden son akşam otobüsüne kıl payı yetiştim.",
      "D) Ayaklarımı denize doğru uzatıp keyifle çay içiyorum.",
      "E) Yolculuğun bu denli uzaması sınıftaki herkesi endişelendiriyor.",
    ],
    cevap: 0,
    aciklama: "\"kurdurduk\" eylemi kurmak (geçişli) fiiline \"-dur\" eki getirilerek geçişlilik derecesi artırılmış ettirgen bir fiildir.",
  },
  {
    id: 8,
    soru: "Aşağıdaki cümlelerin hangisinde yüklem \"işteş çatılı\" bir fiildir?",
    secenekler: [
      "A) Bekleyen kalabalık polisleri görünce bir anda etrafa kaçıştı.",
      "B) Bir anlık dikkatsizlik ve tedbirsizlik yüzünden kaza oluyordu.",
      "C) Her geçen yıl teknoloji ve yapay zekâ biraz daha gelişiyor.",
      "D) Biraz geç de olsa bana önerdiğin o güzel filmi izledim.",
      "E) Artık amcamın yaptığı bu kötü esprilere iyice alıştım.",
    ],
    cevap: 0,
    aciklama: "\"kaçıştı\" eylemi kaçmak fiiline \"-ış\" eki getirilerek işin birden fazla kişi tarafından birlikte yapıldığını bildiren işteş bir fiildir.",
  },
  {
    id: 9,
    soru: "\"Modern şehir hayatının gün içerisinde onlarca kişiyle iletişime geçmeyi zorunlu kılan ve kişileri binlerce mesaja maruz bırakan yapısı, insana daha önce deneyimlemediği bir uyum sürecini dayatıyor.\" Bu cümlenin öge dizilişi aşağıdakilerin hangisinde sırasıyla doğru verilmiştir?",
    secenekler: [
      "A) Özne - Belirtili Nesne - Yüklem",
      "B) Özne - Dolaylı Tümleç - Belirtili Nesne - Yüklem",
      "C) Zarf Tümleci - Özne - Dolaylı Tümleç - Yüklem",
      "D) Özne - Zarf Tümleci - Dolaylı Tümleç - Yüklem",
      "E) Belirtisiz Nesne - Özne - Zarf Tümleci - Yüklem",
    ],
    cevap: 1,
    aciklama: "Ögeler: \"...yapısı\" (Özne), \"insana\" (Dolaylı Tümleç), \"daha önce deneyimlemediği bir uyum sürecini\" (Belirtili Nesne), \"dayatıyor\" (Yüklem).",
  },
  {
    id: 10,
    soru: "Aşağıdaki cümlelerin hangisinde \"dolaylı tümleç (yer tamlayıcısı)\" vurgulanmıştır?",
    secenekler: [
      "A) Sınavdaki zor soruları felsefi bir bakış açısıyla çözdü.",
      "B) O sonsuz masmavi deniz ufkunu dün yeniden gördüm.",
      "C) Gençliğimin en güzel ve unutulmaz yılları o şirin köyde geçti.",
      "D) Binlerce kuş bir anda gürültüyle gökyüzüne havalandı.",
      "E) Ertesi gün bizimle tekrar geleceğini çok iyi biliyordum.",
    ],
    cevap: 2,
    aciklama: "Yükleme en yakın olan öge vurgulanır. \"köyde\" (Dolaylı Tümleç) \"geçti\" yükleminin hemen önünde yer aldığı için vurgulanmıştır.",
  },
  {
    id: 11,
    soru: "Aşağıdaki cümlelerin hangisi \"temel ögelerden\" (Özne ve Yüklem) oluşmuştur?",
    secenekler: [
      "A) Kurbağa, gökyüzünü sadece oturduğu kuyunun ağzı kadar sanır.",
      "B) Yaşamımız yaşadıklarımızla değil, geleceğe dair beklentilerimizle şekillenir.",
      "C) Felsefi olarak düşünmek, ruhun kendi kendisiyle derin konuşmasıdır.",
      "D) İnsanoğlunun bu hayatta yapacakları, hayal ettikleriyle sınırlıdır.",
      "E) Belirli bir hedefi olmayanlar çalışmaktan hiçbir zaman zevk almazlar.",
    ],
    cevap: 2,
    aciklama: "\"Felsefi olarak düşünmek\" öznedir, \"ruhun kendi kendisiyle derin konuşmasıdır\" yüklemdir. Cümle sadece temel ögelerden oluşmuştur.",
  },
  {
    id: 12,
    soru: "Aşağıdaki cümlelerden hangisi \"yükleminin türüne göre\" diğerlerinden farklıdır?",
    secenekler: [
      "A) Kızıl havaları büyük bir hayranlıkla seyret ki akşam olmakta.",
      "B) Hepsinin çekmektedir dayanılmaz derdini bir bir gönlüm.",
      "C) Biz düşüncelerimizi çoğu zaman omuzlarımızda gururla taşırız.",
      "D) Kendisini aldatan kişi, başkalarını hiç düşünmeden aldatır.",
      "E) Şu fani dünyada mezardan bile yükselen gizli bir ses vardır.",
    ],
    cevap: 4,
    aciklama: "\"vardır\" yüklemi isim soyludur (İsim Cümlesi). Diğer şıkların yüklemleri (seyret, çekmektedir, taşırız, aldatır) çekimli fiillerden oluşur (Fiil Cümlesi).",
  },
  {
    id: 13,
    soru: "Aşağıdaki cümlelerin hangisi yapısı bakımından \"girişik birleşik\" bir cümledir?",
    secenekler: [
      "A) Demre'yi geçer geçmez doğanın ve iklimin tamamen değiştiğini görürsünüz.",
      "B) Nefis bir dağ havası sarar o anda geziye çıkan sizi.",
      "C) Kasabada olağanüstü ve derin bir sessizlik başlar akşamları.",
      "D) Arada bir dağların ardından keçi sesleri duyulur sessizce.",
      "E) Sizi aradım fakat telefonlarınız akşama kadar kapalıydı.",
    ],
    cevap: 0,
    aciklama: "İçinde tek yüklem ve fiilimsi (geçer geçmez, değiştiğini) barındıran cümleler girişik birleşik cümlelerdir.",
  },
  {
    id: 14,
    soru: "Aşağıdaki sıralı veya bağlı cümlelerin hangisinde herhangi bir \"öge ortaklığı\" yoktur (bağımsız sıralı/bağlı)?",
    secenekler: [
      "A) Kara tren gecikir, yoğun kardan dolayı belki hiç gelmez.",
      "B) Bozuk bir saattir kalbim ve yüreğim, her zaman sende durur.",
      "C) Horoz erken ölür, ancak gözü her zaman çöplükte kalır.",
      "D) Ata dost gibi sevgiyle bakmalı, düşman gibi hırsla binmeli.",
      "E) Dışarıda lapa lapa kar yağıyordu, sokakta hiç kimsecikler yoktu.",
    ],
    cevap: 4,
    aciklama: "E seçeneğindeki \"yağıyordu\" yükleminin öznesi \"lapa lapa kar\", \"yoktu\" yükleminin öznesi ise \"hiç kimsecikler\"dir. Hiçbir öge ortaklığı bulunmayan bağımsız sıralı cümledir.",
  },
  {
    id: 15,
    soru: "Aşağıdaki cümlelerin hangisinde yan cümle \"belirtili nesne\" görevindedir?",
    secenekler: [
      "A) Bu yıl bir deneme sınavı daha yapmayı kararlaştırdık.",
      "B) Burada gürültülü oynamanıza hiç kimse karışmaz.",
      "C) Çıkmadık candan hiçbir zaman umut kesilmez, sabret.",
      "D) Doğru söyleyen insanı dokuz köyden kovarlar.",
      "E) Derdini zamanında söylemeyen derman bulamaz.",
    ],
    cevap: 0,
    aciklama: "\"bir deneme sınavı daha yapmayı\" grubu \"kararlaştırdık\" yükleminin belirtili nesnesidir (Neyi kararlaştırdık?) ve içinde isim-fiil barındırır.",
  },
];
