import { DenemeSorusu } from './deneme1';

export const denemeGB2Baslik = "Güncel Bilgiler - Deneme 2";

export const denemeGB2: DenemeSorusu[] = [
  {
    id: 1,
    soru: "Milli Eğitim Bakanlığı müfredat güncellemelerinde \"Türkiye'nin hava sahası\" aşağıdaki kavramlardan hangisiyle yeniden tanımlanmıştır?",
    secenekler: ["A) Mavi Vatan", "B) Gök Vatan", "C) Yeşil Vatan", "D) Doğu Roma", "E) Adalar Denizi"],
    cevap: 1,
    aciklama: "Türkiye'nin hava sahası yeni müfredatta \"Gök Vatan\" olarak tanımlanmıştır.",
  },
  {
    id: 2,
    soru: "2026 yılında \"G20 Zirvesi\" aşağıdaki ülkelerin ve şehirlerin hangisinde gerçekleştirilecektir?",
    secenekler: ["A) ABD - Miami", "B) Fransa - Paris", "C) Türkiye - İstanbul", "D) İsviçre - Cenevre", "E) İtalya - Roma"],
    cevap: 0,
    aciklama: "2026 G20 Zirvesi ABD'nin Miami kentinde gerçekleştirilecektir.",
  },
  {
    id: 3,
    soru: "Karadeniz Ekonomik İşbirliği (KEİ) örgütünün genel merkezi aşağıdaki şehirlerin hangisinde yer almaktadır?",
    secenekler: ["A) Pekin", "B) Cidde", "C) Tahran", "D) İstanbul", "E) Kahire"],
    cevap: 3,
    aciklama: "Karadeniz Ekonomik İşbirliği (KEİ) merkezi İstanbul'dadır.",
  },
  {
    id: 4,
    soru: "2026 yılı \"Avrupa Ligi Finali\" aşağıdaki şehirlerimizin hangisinde oynanacaktır?",
    secenekler: ["A) Ankara", "B) İzmir", "C) İstanbul", "D) Şanlıurfa", "E) Antalya"],
    cevap: 2,
    aciklama: "2026 UEFA Avrupa Ligi Finali İstanbul'da oynanacaktır.",
  },
  {
    id: 5,
    soru: "İnsanlık tarihinin en önemli buluşlarından biri olan \"matbaayı\" (hareketli parçalarla) geliştirerek modern kitap basımını başlatan mucit kimdir?",
    secenekler: ["A) John Logie Baird", "B) Johann Gutenberg", "C) Martin Cooper", "D) Thomas Edison", "E) Alexander Fleming"],
    cevap: 1,
    aciklama: "Modern matbaanın mucidi Johann Gutenberg'tir.",
  },
  {
    id: 6,
    soru: "2026 yılı Oscar Ödülleri'nde \"En İyi Yönetmen\" ödülünü kazanan isim aşağıdakilerden hangisidir?",
    secenekler: ["A) Paul Thomas Anderson", "B) Sean Baker", "C) Christopher Nolan", "D) Daniel Kwan", "E) Jane Campion"],
    cevap: 0,
    aciklama: "2026 Oscar En İyi Yönetmen ödülünü Paul Thomas Anderson kazanmıştır.",
  },
  {
    id: 7,
    soru: "NASA'nın Artemis II misyonu kapsamında Ay'a gidecek olan \"ilk kadın astronot\" aşağıdakilerden hangisidir?",
    secenekler: ["A) Christina Koch", "B) Valentina Tereshkova", "C) Sally Ride", "D) Mikey Madison", "E) Jessie Buckley"],
    cevap: 0,
    aciklama: "Artemis II ile Ay'a gidecek ilk kadın astronot Christina Koch'tur.",
  },
  {
    id: 8,
    soru: "UNESCO Yaratıcı Şehirler Ağı'na \"Müzik\" alanında 2019 yılında Türkiye'den ilk katılan şehir hangisidir?",
    secenekler: ["A) Kırşehir", "B) Şanlıurfa", "C) Gaziantep", "D) İstanbul", "E) Kütahya"],
    cevap: 0,
    aciklama: "2019 yılında Müzik alanında ağa giren ilk şehrimiz Kırşehir'dir.",
  },
  {
    id: 9,
    soru: "Ekonomik İşbirliği ve Kalkınma Örgütü (OECD) merkez ofisi aşağıdaki şehirlerin hangisindedir?",
    secenekler: ["A) Brüksel", "B) Paris", "C) Cenevre", "D) New York", "E) Viyana"],
    cevap: 1,
    aciklama: "OECD genel merkezi Fransa'nın Paris kentindedir.",
  },
  {
    id: 10,
    soru: "Milli Eğitim Müfredatında \"Ermeni Meselesi\" yerine kullanılan yeni kavram aşağıdakilerden hangisidir?",
    secenekler: ["A) Sevk ve İskan Kanunu", "B) Asılsız Ermeni iddiaları", "C) Haçlı Saldırıları", "D) Sömürgeciliğin Başlangıcı", "E) Asılsız Pontus iddiaları"],
    cevap: 1,
    aciklama: "Ermeni Meselesi kavramı \"Asılsız Ermeni iddiaları\" olarak güncellenmiştir.",
  },
  {
    id: 11,
    soru: "2026 yılı \"Şampiyonlar Ligi Finali\" aşağıdaki ülkelerin hangisinde, hangi şehirde oynanacaktır?",
    secenekler: ["A) Macaristan - Budapeşte", "B) Almanya - Münih", "C) İtalya - Milano", "D) Fransa - Paris", "E) Türkiye - İstanbul"],
    cevap: 0,
    aciklama: "2026 Şampiyonlar Ligi finali Macaristan'ın Budapeşte kentinde yapılacaktır.",
  },
  {
    id: 12,
    soru: "Tıp dünyasında devrim yaratan, \"ilk antibiyotik ve penisilini\" keşfeden bilim insanı aşağıdakilerden hangisidir?",
    secenekler: ["A) Alexander Fleming", "B) Jonas Salk", "C) Wilhelm Röntgen", "D) Galileo", "E) Thomas Edison"],
    cevap: 0,
    aciklama: "Penisilin ve ilk antibiyotiğin mucidi Alexander Fleming'dir.",
  },
  {
    id: 13,
    soru: "Uluslararası Atom Enerjisi Ajansı (IAEA) genel merkezi aşağıdaki şehirlerin hangisindedir?",
    secenekler: ["A) Lyon", "B) Roma", "C) Brüksel", "D) Cenevre", "E) Viyana"],
    cevap: 4,
    aciklama: "Uluslararası Atom Enerjisi Ajansı (IAEA) Avusturya'nın Viyana kentindedir.",
  },
  {
    id: 14,
    soru: "2025 yılı Oscar Ödülleri'nde \"En İyi Kadın Oyuncu\" ödülünü kazanan isim aşağıdakilerden hangisidir?",
    secenekler: ["A) Mikey Madison", "B) Jessie Buckley", "C) Emma Stone", "D) Michelle Yeoh", "E) Jessica Chastain"],
    cevap: 0,
    aciklama: "2025 yılı Oscar En İyi Kadın Oyuncu ödülünü Mikey Madison (Anora filmiyle) almıştır.",
  },
  {
    id: 15,
    soru: "UNESCO Yaratıcı Şehirler Ağı'na \"Zanaat ve Halk Sanatları\" kategorisinde 2017 yılında kabul edilen ilk şehrimiz hangisidir?",
    secenekler: ["A) Bursa", "B) Kütahya", "C) İstanbul", "D) Hatay", "E) Gaziantep"],
    cevap: 1,
    aciklama: "2017'de Zanaat ve Halk Sanatları kategorisinde ilk giren şehrimiz Kütahya'dır.",
  },
  {
    id: 16,
    soru: "Milli Eğitim müfredatında \"Orta Asya\" ifadesi yerine aşağıdaki kavramlardan hangisi getirilmiştir?",
    secenekler: ["A) Doğu Roma", "B) Türkistan", "C) Adalar Denizi", "D) Gök Vatan", "E) Milli Mücadele"],
    cevap: 1,
    aciklama: "Orta Asya kavramı yerine müfredatta \"Türkistan\" kavramı getirilmiştir.",
  },
  {
    id: 17,
    soru: "İlk denizaltıyı (Tahtelbahir) inşa ederek Türk denizcilik ve teknoloji tarihine adını yazdıran mucit kimdir?",
    secenekler: ["A) Piri Reis", "B) İbrahim Efendi", "C) Ali Kuşçu", "D) Takiyüddin", "E) Hezarfen Ahmet Çelebi"],
    cevap: 1,
    aciklama: "İlk denizaltıyı (Tahtelbahir) geliştiren kişi İbrahim Efendi'dir.",
  },
];
