export const SORULAR_2016 = [
  // GENEL YETENEK - TÜRKÇE
  {
    id: 2016001, yil: 2016, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Bir metinde yazar, okuyucunun anlayabileceği bir dil kullanarak karmaşık kavramları yalın biçimde aktarır. Böylece okuyucuyla güçlü bir iletişim kurar. Bu düşünceyle aşağıdaki atasözlerinden hangisi anlamca örtüşmektedir?',
    secenekler: ['A) Söz gümüşse sükût altındır.', 'B) Yere bak yürü, söze bak gülüş.', 'C) Söyleyen bilmez, bilen söylemez.', 'D) Sözün doğrusunu söyle, düşmanını dost et.', 'E) İyi söz yüz etmez, kötü söz dost eder.'],
    cevap: 3, aciklama: 'Dürüst ve anlaşılır iletişim karşılıklı güveni güçlendirir. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2016002, yil: 2016, ders: 'Türkçe', seviye: 'Lisans',
    soru: '"Gerçek sanatçı, sıradan malzemeyi işleyerek ona olağanüstü bir değer kazandırır." cümlesindeki altı çizili ifadeyle anlatılmak istenen aşağıdakilerden hangisidir?',
    secenekler: ['A) Özgün bir üslup geliştirmek', 'B) Sıradan unsurları dönüştürerek sanatsal değer yaratmak', 'C) Teknik beceriyi ön plana çıkarmak', 'D) Geleneksel yöntemleri terk etmek', 'E) İzleyiciyi şaşırtacak eserler üretmek'],
    cevap: 1, aciklama: 'Sanatçı sıradan olanı dönüştürerek değer yaratır. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2016003, yil: 2016, ders: 'Türkçe', seviye: 'Lisans',
    soru: '(I) Edebiyatta akımlar toplumsal dönüşümlerle ortaya çıkar. (II) Sanayi Devrimi yeni bir okuyucu kitlesini doğurdu. (III) Bu kitle günlük yaşamı konu alan eserleri tercih etti. (IV) Yazarlar da bu talebi karşılamak için eserlerini yeniden biçimlendirdi. (V) Böylece gerçekçi edebiyat geniş kitlelere ulaştı.\n\nBu cümlelerden hangisinde neden-sonuç ilişkisi yoktur?',
    secenekler: ['A) I', 'B) II', 'C) III', 'D) IV', 'E) V'],
    cevap: 2, aciklama: 'III. cümlede bir tercih belirtilmekte, neden-sonuç ilişkisi kurulmamaktadır. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2016004, yil: 2016, ders: 'Türkçe', seviye: 'Lisans',
    soru: '(I) Modern roman 19. yüzyılın ikinci yarısında ortaya çıktı. (II) Yazarlar kahramanlarının iç dünyasını doğrudan aktarmaya başladı. (III) Okuyucular bu yaklaşımı büyük ilgiyle karşıladı. (IV) Bu teknik giderek roman yazımının vazgeçilmezi oldu. (V) Farklı kültürlerde de benzer gelişmeler yaşandı.\n\n"Bu yenilik, geleneksel anlatı yapısını kökten değiştirmiştir." cümlesi numaralanmış cümlelerin hangisinden sonra getirilebilir?',
    secenekler: ['A) I', 'B) II', 'C) III', 'D) IV', 'E) V'],
    cevap: 1, aciklama: 'II. cümleden sonra bu etki aktarılabilir. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2016005, yil: 2016, ders: 'Türkçe', seviye: 'Lisans',
    soru: '(I) Dil, kültürün taşıyıcısıdır. (II) Toplumun değerleri ve tarihi dil aracılığıyla aktarılır. (III) Bu nedenle dil koruma büyük önem taşır. (IV) Türkçe son yüzyılda pek çok yabancı sözcük almıştır. (V) Nesli tükenen dillerin kaybolması o kültürün yok olması anlamına gelir.\n\nBu parçada düşüncenin akışını bozan cümle hangisidir?',
    secenekler: ['A) I', 'B) II', 'C) III', 'D) IV', 'E) V'],
    cevap: 3, aciklama: 'IV. cümle ana konudan saparak farklı bir alana geçmektedir. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2016006, yil: 2016, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'I. Bu süreç insan zihninin dili nasıl işlediğini anlamamıza yardımcı olur.\nII. Dil edinimi doğumdan itibaren başlayan karmaşık bir süreçtir.\nIII. Çocuklar önce sesleri sonra sözcükleri ardından cümleleri öğrenir.\nIV. Araştırmacılar bu aşamaları yıllarca incelemiştir.\nV. Sonuç olarak dil öğrenimi hem doğuştan gelen hem de çevresel faktörlere bağlıdır.\n\nAnlamlı bir bütün oluşturulduğunda baştan üçüncü olan cümle hangisidir?',
    secenekler: ['A) I', 'B) II', 'C) III', 'D) IV', 'E) V'],
    cevap: 3, aciklama: 'Doğru sıralama II-III-IV-I-V; üçüncü sırada IV bulunur. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2016007, yil: 2016, ders: 'Türkçe', seviye: 'Lisans',
    soru: '"Güneş batarken gökyüzü kızarır, rüzgâr hafifler, deniz sakinleşir; doğa bir an için nefesini tutar."\n\nBu cümledeki numaralanmış virgüllerden hangisinin işlevi diğerlerinden farklıdır?\nI. kızarır,\nII. hafifler,\nIII. sakinleşir;',
    secenekler: ['A) I', 'B) II', 'C) III', 'D) IV', 'E) V'],
    cevap: 0, aciklama: 'I numaralı virgül farklı bir işlev taşımaktadır. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016008, yil: 2016, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Aşağıdaki cümlelerin hangisinde yazım yanlışı yoktur?',
    secenekler: ['A) Herkesin hakkını teslim etmek lazımdır.', 'B) Onunla biraraya gelmek zor oldu.', 'C) Birçok kişi bu konuyu farklı değerlendiriyor.', 'D) Altıncı katta oturan komşuyla hiç tanışamadık.', 'E) Dün sabah sekizbuçukta yola çıktık.'],
    cevap: 0, aciklama: 'A şıkkında yazım yanlışı yoktur. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016009, yil: 2016, ders: 'Türkçe', seviye: 'Lisans',
    soru: '"Ağaçların dallarında sallanan yapraklar sabah ışığında parlıyordu; kuşlar şakıdıkça orman canlanıyordu." cümlesinde sözcük yapısıyla ilgili aşağıdakilerden hangisi söylenemez?',
    secenekler: ['A) "sallanan" sözcüğünde fiilden sıfat yapan ek kullanılmıştır.', 'B) "ağaçların" sözcüğünde tamlayan eki vardır.', 'C) "parlıyordu" sözcüğünde yapım ve çekim eki bir arada kullanılmıştır.', 'D) "canlanıyordu" sözcüğünde isimden fiil yapım eki kullanılmıştır.', 'E) "kuşlar" sözcüğünde yapım eki bulunmamaktadır.'],
    cevap: 4, aciklama: '"Kuşlar" sözcüğünde yapım eki yoktur; bu önerme doğrudur, söylenemez değildir. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2016010, yil: 2016, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Aşağıdaki cümlelerin hangisinde ünlü düşmesi yoktur?',
    secenekler: ['A) Kitapları raftaki yerlerine kaldırdı.', 'B) Sanatçı eserini tamamlayınca derin bir huzur duydu.', 'C) Ağaçların yapraklarını sonbaharda dökmesi doğaldır.', 'D) Öğrenciler sınava girmeden iyice hazırlanmalıdır.', 'E) Burnu kalkık insanlarla anlaşmak çok güçtür.'],
    cevap: 0, aciklama: 'A şıkkında ünlü düşmesi yoktur. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016011, yil: 2016, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Aşağıdaki cümlelerin hangisinde "açık" sözcüğü diğerlerinden farklı bir tür görevi üstlenmiştir?',
    secenekler: ['A) Bugün hava çok açık, güneş parlıyor.', 'B) Açık söylemek gerekirse bu karar yanlış.', 'C) Kapıyı açık bırakmak alışkanlık haline gelmişti.', 'D) Bu mesele henüz açık değil, araştırılmalı.', 'E) Açık fikirli biriydi, yeniliklere hep kapıyı araladı.'],
    cevap: 1, aciklama: 'B şıkkında "açık" zarf; diğerlerinde sıfat olarak kullanılmıştır. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2016012, yil: 2016, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Aşağıdakilerin hangisinde isim tamlamasının unsurlarından biri cümle biçimindedir?',
    secenekler: ['A) Sabahın erken saatlerinde kalkmak zordu.', 'B) Yıllar önce yaşadığı acının izi hâlâ silinmemişti.', 'C) Güneşin batışını seyretmek en sevdiği uğraştı.', 'D) Trenin rötar yaptığı haberi yolcuları şaşırttı.', 'E) Dağların ardında kaybolan bulutlar görkemli bir manzara oluşturuyordu.'],
    cevap: 3, aciklama: 'D şıkkında "trenin rötar yaptığı" cümlesi tamlayanı oluşturmaktadır. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2016013, yil: 2016, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Aşağıdaki cümlelerin hangisinde ayrılma durumu eki diğerlerinden farklı bir işlevde kullanılmıştır?',
    secenekler: ['A) Şehirden uzaklaşınca rahatladığını fark etti.', 'B) Yorgunluktan ayakta duracak hali kalmamıştı.', 'C) Ormandan gelen sesler onu tedirgin etti.', 'D) Bu adam hep bildiğimiz türden biri, güvenilmez.', 'E) Soğuktan elleri uyuştu, kalemi bıraktı.'],
    cevap: 3, aciklama: 'D şıkkında ayrılma eki "ait olma" anlamı taşır. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2016014, yil: 2016, ders: 'Türkçe', seviye: 'Lisans',
    soru: '(I) Çocuklar parka koştu. (II) Sarı çiçekler güneşte parıldıyordu. (III) Onların gülüşleri her şeyi unutturdu. (IV) Bütün yorgunlukları anında geçti. (V) Öğretmenleri de onlara eşlik etti.\n\nBu cümlelerin hangisinde iyelik eki çıkarılsa anlam bozulmaz?',
    secenekler: ['A) I', 'B) II', 'C) III', 'D) IV', 'E) V'],
    cevap: 0, aciklama: 'I. cümlede iyelik eki yoktur, anlam bozulmaz. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016015, yil: 2016, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Eski haritaları incelemenin tarih araştırmalarına katkısını anlatan metne göre aşağıdakilerden hangisi söylenemez?',
    secenekler: ['A) Geçmişteki ticaret yolları hakkında bilgi verir.', 'B) Araştırmacının yazı üslubunu geliştirir.', 'C) Sınırların tarihsel değişimini gösterir.', 'D) Yerleşim alanlarının dağılımını ortaya koyar.', 'E) Dönemin coğrafi anlayışını yansıtır.'],
    cevap: 1, aciklama: 'Harita incelemenin yazı üslubunu geliştirdiğine dair bilgi yoktur. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2016016, yil: 2016, ders: 'Türkçe', seviye: 'Lisans',
    soru: '"Doğada yürümek insanı günlük koşuşturmadan uzaklaştırır. Zihin dinginleşir, beyin daha verimli çalışır. Araştırmalar doğada geçirilen zamanın stres hormonlarını belirgin biçimde düşürdüğünü ortaya koymuştur. ----"\n\nParçanın sonuna en uygun cümle hangisidir?',
    secenekler: ['A) Yürüyüş güzergahları dikkatli seçilmelidir.', 'B) Bu nedenle düzenli yürüyüş alışkanlığı kazanmak büyük önem taşır.', 'C) Şehir parkları da benzer bir etki yaratabilir.', 'D) Doğa fotoğrafçılığı son yıllarda popüler olmuştur.', 'E) Yürüyüş ekipmanı seçimi önemli bir adımdır.'],
    cevap: 1, aciklama: 'Parçanın akışına en uygun sonuç cümlesi B şıkkıdır. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2016017, yil: 2016, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Şiirde ses ve anlam ilişkisini ele alan metne göre şiirle ilgili yanlış anlayış hangisidir?',
    secenekler: ['A) Şiirde ses ve anlam birbirinden ayrılmaz.', 'B) Şiirin özü yalnızca aktarılan düşüncede aranmalıdır.', 'C) Günlük sözcükler şiirde farklı işlevler kazanabilir.', 'D) Biçim ve içerik şiirde iç içe geçmiştir.', 'E) Şiirin dili düzyazıdan farklı bir işlev üstlenir.'],
    cevap: 1, aciklama: 'Şiiri yalnızca düşüncede aramak yanlıştır. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2016018, yil: 2016, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Geleneksel müzikten yararlanan bir müzisyeni anlatan metne göre müzisyenin müzik tarihindeki önemini belirten seçenek hangisidir?',
    secenekler: ['A) Eserlerinin konser salonlarında çalınması', 'B) Yerel müziği evrensel bir dille buluşturması', 'C) Ülkesinde çok sayıda hayranı olması', 'D) Halk ezgilerini birebir kullanması', 'E) Müziği akademik çerçevede ele alması'],
    cevap: 1, aciklama: 'Yerel müziği evrensel dille buluşturması önemini belirler. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2016019, yil: 2016, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Halk müziğinden yararlanmanın asıl ölçütü nedir?',
    secenekler: ['A) Halkın beğendiği ezgileri kullanmak', 'B) Geleneksel unsurları tanıtmak', 'C) Sanatçının kişisel yorumuyla özgün eser ortaya koymak', 'D) Geçmiş ile günümüzü birleştirmek', 'E) Dinleyiciyi geleneksel müzikle tanıştırmak'],
    cevap: 2, aciklama: 'Sanatçının kişisel yorumuyla özgün eser ortaya koyması temel ölçüttür. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2016020, yil: 2016, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Beyin ve bilinç ilişkisini ele alan metin aşağıdaki sorulardan hangisine yanıt olarak söylenmiş olabilir?',
    secenekler: ['A) Nörobilim çalışmalarının bugün geldiği nokta nedir?', 'B) İnsan beyninin kapasitesi ne kadardır?', 'C) Bilinç kavramının felsefi boyutu nedir?', 'D) İnsanlar birbirini nasıl anlayabilir?', 'E) Beyin araştırmalarından hangi alanlarda yararlanılır?'],
    cevap: 0, aciklama: 'Metin nörobilim çalışmalarının mevcut durumunu anlatmaktadır. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016021, yil: 2016, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Beyin ve bilinç metnindeki cümlelerle ilgili aşağıdakilerden hangisi yanlıştır?',
    secenekler: ['A) I. cümlede bir kavramın tanımı yapılmıştır.', 'B) II. cümlede yazar öznel bir görüş bildirmiştir.', 'C) IV. cümlede III. cümleyle ilgili yorum yapılmıştır.', 'D) VI. cümlede bir iddia gerekçesiyle birlikte sunulmuştur.', 'E) VII. cümlede somut bir öneri yapılmıştır.'],
    cevap: 3, aciklama: 'VI. cümlede iddia ve gerekçe bir arada verilmemiştir. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2016022, yil: 2016, ders: 'Türkçe', seviye: 'Lisans',
    soru: '"Tarihin seyrini değiştiren anlarda bireylerin kararları belirleyici olmuştur. Bu, onların tarih karşısındaki sorumluluğunu gösterir." cümlesinde altı çizili "bu" sözcüğü neye gönderme yapmaktadır?',
    secenekler: ['A) Tarihin seyrinin değişmesine', 'B) Bireylerin kararlarına', 'C) Tarihî anlarda kararların belirleyici olmasına', 'D) Tarihî sorumluluğa', 'E) Belirleyici olmaya'],
    cevap: 2, aciklama: '"Bu" sözcüğü bireylerin kararlarının belirleyici olmasına gönderme yapar. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2016023, yil: 2016, ders: 'Türkçe', seviye: 'Lisans',
    soru: '"Tarihte kaçırılan fırsatlar geri gelmez; bu anları değerlendiremeyenler uzun süre bedelini öder." Bu cümleden kesin olarak hangi çıkarım yapılabilir?',
    secenekler: ['A) Tarihte en önemli şey geleceği planlamaktır.', 'B) Fırsatları kaçıranlar ödüllendirilir.', 'C) Geçmişteki hatalar telafi edilemez.', 'D) Tarihî fırsatları kaçırmanın uzun vadeli olumsuz sonuçları vardır.', 'E) Tarihte erken davranmak geç kalmaktan iyidir.'],
    cevap: 3, aciklama: 'Uzun vadeli olumsuz sonuçlar kesin olarak çıkarılabilir. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2016024, yil: 2016, ders: 'Türkçe', seviye: 'Lisans',
    soru: '"Kültürel miras, toplumun geçmişten geleceğe taşıdığı değerler bütünüdür." ifadesinden hareketle aşağıdakilerden hangisi söylenemez?',
    secenekler: ['A) Kültürel miras kuşaklar arası köprü işlevi görür.', 'B) Her toplumun kendine özgü mirası vardır.', 'C) Miras yalnızca somut nesnelerden oluşur.', 'D) Kültürel değerler zaman içinde aktarılır.', 'E) Geçmiş geleceği biçimlendiren bir unsurdur.'],
    cevap: 2, aciklama: 'Mirasın yalnızca somut nesnelerden oluştuğu söylenemez. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2016025, yil: 2016, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Bilim insanlarının topluma katkısını anlatan bir metinden aşağıdaki çıkarımlardan hangisi kesin olarak yapılabilir?',
    secenekler: ['A) Bilim insanları her zaman toplumun desteğini alır.', 'B) Bilimsel çalışmalar kısa sürede sonuç verir.', 'C) Toplumun gelişmesi için bilimsel araştırmalar zorunludur.', 'D) Bilim insanları çalışmalarını kamuoyuyla paylaşmalıdır.', 'E) Bilimsel bilgi zaman içinde değişmez.'],
    cevap: 2, aciklama: 'Toplumsal gelişme için bilimsel araştırmaların gerekliliği çıkarılabilir. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2016026, yil: 2016, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Teknoloji ve insan ilişkisini ele alan bir metne göre aşağıdakilerden hangisi söylenemez?',
    secenekler: ['A) Teknoloji insan yaşamını köklü biçimde dönüştürmüştür.', 'B) İnsanlar teknolojiyle giderek daha bağımlı ilişki kurmaktadır.', 'C) Teknoloji tüm toplumsal sorunları çözme kapasitesine sahiptir.', 'D) Dijital araçlar iletişim biçimlerini değiştirmiştir.', 'E) Teknolojinin yaygınlaşması yeni alışkanlıklar doğurmuştur.'],
    cevap: 2, aciklama: 'Teknolojinin tüm sorunları çözeceğine dair bilgi metinde yer almaz. Doğru cevap C şıkkıdır.',
  },

  // MATEMATİK
  {
    id: 2016027, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Bir okulda A, B, C, D, E, F ve G dersleri iki öğretmen tarafından verilmektedir. Nil 3, Orhan 4 ders vermektedir. Koşullar: Bir öğretmenin bir günde tek sınavı var. Orhan\'ın sınavları art arda günlerde. B Salı. Çarşamba yalnız F. A ve D aynı gün. Cuma\'daki iki sınavdan biri C. E günü Orhan sınavı yok.\n\nI. A, II. B, III. C derslerinden hangileri Nil tarafından verilebilir?',
    secenekler: ['A) Yalnız I', 'B) Yalnız II', 'C) I ve II', 'D) I ve III', 'E) II ve III'],
    cevap: 3, aciklama: 'Koşullar analiz edildiğinde A ve C Nil tarafından verilebilir. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2016028, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Yukarıdaki sınav programı probleminde hangi dersler kesinlikle aynı öğretmen tarafından verilmektedir?',
    secenekler: ['A) A ile G', 'B) B ile F', 'C) C ile F', 'D) D ile E', 'E) E ile G'],
    cevap: 1, aciklama: 'B ile F kesinlikle aynı öğretmen tarafından verilir. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2016029, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Sınav programı probleminde aşağıdakilerden hangisi yanlıştır?',
    secenekler: ['A) A sınavı G\'den önce olacaktır.', 'B) B sınavı E\'den önce olacaktır.', 'C) D sınavı F\'den sonra olacaktır.', 'D) E sınavı G\'den önce olacaktır.', 'E) F sınavı B\'den sonra olacaktır.'],
    cevap: 1, aciklama: 'B\'nin E\'den önce olması zorunlu değildir. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2016030, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: 'B ve C aynı öğretmen tarafından verildiği biliniyorsa aşağıdakilerden hangisi kesin doğrudur?',
    secenekler: ['A) A dersi Orhan\'a ait, sınavı Pazartesi.', 'B) D dersi Orhan\'a ait, sınavı Perşembe.', 'C) E dersi Nil\'e ait, sınavı Salı.', 'D) F dersi Nil\'e ait, sınavı Çarşamba.', 'E) G dersi Nil\'e ait, sınavı Cuma.'],
    cevap: 4, aciklama: 'G dersi Nil\'e aittir ve Cuma günüdür. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2016031, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Bir dükkânda her gün 3 farklı müşteri hizmet almaktadır. İki haftada toplam kaç müşteri hizmet alır?',
    secenekler: ['A) 38', 'B) 40', 'C) 42', 'D) 44', 'E) 46'],
    cevap: 2, aciklama: '3 × 14 = 42. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2016032, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Bir sayının 3 katından 7 çıkarıldığında 8 elde ediliyor. Bu sayı kaçtır?',
    secenekler: ['A) 3', 'B) 5', 'C) 6', 'D) 7', 'E) 9'],
    cevap: 1, aciklama: '3x - 7 = 8 → x = 5. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2016033, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: 'x + y = 4 ve x - y = 6 ise x · y kaçtır?',
    secenekler: ['A) -5', 'B) -1', 'C) 0', 'D) 2', 'E) 4'],
    cevap: 0, aciklama: 'x = 5, y = -1 → x·y = -5. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016034, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: '3/10 oranı ondalık olarak kaçtır?',
    secenekler: ['A) 0,2', 'B) 0,25', 'C) 0,3', 'D) 0,35', 'E) 0,4'],
    cevap: 2, aciklama: '3/10 = 0,3. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2016035, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: 'A, B ve C tek basamaklı rakamlar olup A + B + C = 14 ve A × B = 12 koşullarını sağlıyorsa toplam kaçtır?',
    secenekler: ['A) 12', 'B) 13', 'C) 14', 'D) 15', 'E) 16'],
    cevap: 2, aciklama: 'Verilen koşullar altında toplam 14\'tür. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2016036, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: '2a + 3 = 13 ise a kaçtır?',
    secenekler: ['A) 2', 'B) 3', 'C) 4', 'D) 5', 'E) 6'],
    cevap: 3, aciklama: '2a = 10 → a = 5. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2016037, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: 'a + b = 5 ve a · b = 6 ise (a - b)² kaçtır?',
    secenekler: ['A) 1', 'B) 2', 'C) 3', 'D) 4', 'E) 5'],
    cevap: 0, aciklama: '(a-b)² = (a+b)² - 4ab = 25 - 24 = 1. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016038, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: 'x² - 5x + 6 = 0 denkleminin köklerinin toplamı kaçtır?',
    secenekler: ['A) 1', 'B) 2', 'C) 3', 'D) 4', 'E) 5'],
    cevap: 4, aciklama: 'Vieta formülüne göre kökler toplamı 5\'tir. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2016039, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: '1/4 + 1/4 işleminin sonucu kaçtır?',
    secenekler: ['A) 1/4', 'B) 1/3', 'C) 1/2', 'D) 2/3', 'E) 3/4'],
    cevap: 2, aciklama: '1/4 + 1/4 = 1/2. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2016040, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: 'a > 0 ve b > 0 koşulları altında I. a + b > 0, II. a · b > 0, III. a - b > 0 ifadelerinden hangileri her zaman doğrudur?',
    secenekler: ['A) Yalnız I', 'B) Yalnız II', 'C) Yalnız III', 'D) I ve II', 'E) II ve III'],
    cevap: 3, aciklama: 'I ve II her zaman doğrudur; III her zaman doğru değildir. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2016041, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: 'f(x) = 2x + 1 fonksiyonu için f(a) = 9 ise a kaçtır?',
    secenekler: ['A) 2', 'B) 3', 'C) 4', 'D) 5', 'E) 6'],
    cevap: 2, aciklama: '2a + 1 = 9 → a = 4. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2016042, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: 'g(x) = x² - 3 fonksiyonu için g(a) = 1 ise a kaçtır? (a > 0)',
    secenekler: ['A) -3', 'B) -1', 'C) 2', 'D) 3', 'E) 5'],
    cevap: 2, aciklama: 'a² - 3 = 1 → a = 2. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2016043, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: 'a, b pozitif tam sayılar ve a + b çift sayı olduğunda I. a - b, II. 2a + b, III. a · b ifadelerinden hangileri kesinlikle çift sayıdır?',
    secenekler: ['A) Yalnız I', 'B) Yalnız II', 'C) I ve II', 'D) I ve III', 'E) I, II ve III'],
    cevap: 0, aciklama: 'Yalnız I her zaman çift sayıdır. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016044, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Ardışık beş pozitif tam sayının toplamı olabilen sayılara "beşli sayı" deniliyor. İki basamaklı kaç tane beşli sayı vardır?',
    secenekler: ['A) 13', 'B) 15', 'C) 17', 'D) 19', 'E) 21'],
    cevap: 2, aciklama: 'İki basamaklı 17 beşli sayı vardır. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2016045, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: '29 kişilik grup A ve B araçlarına bölünüyor; A\'nın yaş ortalaması 40, B\'nin 50. Yer değişimi sonrası A\'nın ortalaması 41, B\'nin 48 oluyor. Başlangıçta A\'ya kaç kişi binmiştir?',
    secenekler: ['A) 13', 'B) 14', 'C) 15', 'D) 16', 'E) 17'],
    cevap: 4, aciklama: 'Denklemler çözüldüğünde A\'ya 17 kişi binmiştir. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2016046, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Yolun 2/5\'ini 10 dk\'da yürüyen biri kalan yolu ilk hızının 3/4\'üyle yürüyor. Yavaş yürüdüğü mesafe hızlı yürüdüğünden 480 m fazlaysa yavaş yürüme hızı dakikada kaç metredir?',
    secenekler: ['A) 72', 'B) 76', 'C) 80', 'D) 84', 'E) 88'],
    cevap: 0, aciklama: 'Yavaş yürüme hızı dakikada 72 metredir. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016047, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Satıcı 50 kg ürünü %20, 10 kg ürünü %50 kârla satıp her ikisinden eşit kâr etti. Birinci ürünün kg satış fiyatının ikinciye oranı kaçtır?',
    secenekler: ['A) 1/4', 'B) 1/3', 'C) 1/2', 'D) 2/3', 'E) 3/4'],
    cevap: 3, aciklama: 'Oran 2/3 olarak bulunur. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2016048, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: 'A aracı 12 ton, B 16 ton taşıyor; A\'nın toplam taşıdığı B\'nin 2 katı ve toplam 44 sefer yapılıyor. A\'nın sefer sayısı B\'den kaç fazladır?',
    secenekler: ['A) 12', 'B) 14', 'C) 16', 'D) 18', 'E) 20'],
    cevap: 4, aciklama: 'Fark 20\'dir. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2016049, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Kutudaki kırmızı top sayısı mavinin 3/7\'si. 1 mavi 3 kırmızı eklenince kırmızılar tüm topların 2/7\'si oluyor. Başlangıçta kutuda kaç top vardı?',
    secenekler: ['A) 14', 'B) 35', 'C) 56', 'D) 77', 'E) 98'],
    cevap: 1, aciklama: 'Başlangıçta 35 top vardı. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2016050, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Ali\'nin yaşı Mehmet\'in 2 katı ve Ayşe\'nin 3 katı. Ali Ayşe\'nin 2 katı olduğunda Mehmet 15 yaşında olacak. Ayşe\'nin bugünkü yaşı kaçtır?',
    secenekler: ['A) 3', 'B) 4', 'C) 5', 'D) 6', 'E) 8'],
    cevap: 3, aciklama: 'Ayşe\'nin yaşı 6\'dır. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2016051, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: '24 öğrencili sınıfta keman çalanlar yalnızca gitar çalanların 2 katı. Piyano çalıp keman çalamayan 9 kişi var. Keman çalabilen kaç kişidir?',
    secenekler: ['A) 9', 'B) 10', 'C) 11', 'D) 12', 'E) 13'],
    cevap: 1, aciklama: '10 öğrenci keman çalabilmektedir. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2016052, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: '{1,2,3,4,5} kümesinden rakamları birbirinden farklı 3 basamaklı kaç doğal sayı 3\'e tam bölünür?',
    secenekler: ['A) 12', 'B) 18', 'C) 24', 'D) 30', 'E) 36'],
    cevap: 2, aciklama: '24 sayı 3\'e tam bölünür. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2016053, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: '1\'den 15\'e kadar sayılar; her grupta bir sayı diğerlerine tam bölünen kurala göre gruplara ayrılıyor. Bir grupta en fazla kaç sayı bulunabilir?',
    secenekler: ['A) 4', 'B) 5', 'C) 6', 'D) 7', 'E) 8'],
    cevap: 2, aciklama: 'En fazla 6 sayı bulunabilir. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2016054, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Sayılar en fazla ikişerli 8 gruba ayrıldığında 2 sayısıyla aynı grupta hangi sayı bulunur?',
    secenekler: ['A) 4', 'B) 6', 'C) 8', 'D) 10', 'E) 12'],
    cevap: 3, aciklama: '2 ile aynı grupta 10 bulunur. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2016055, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Şirketin 192 aracı A:%25, B:%40, C:%35 oranında dağılmış. B marka araçlar A markadan kaç fazladır?',
    secenekler: ['A) 32', 'B) 36', 'C) 40', 'D) 42', 'E) 48'],
    cevap: 0, aciklama: 'B (77) - A (48) ≈ 32. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016056, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Şirket 7 B marka araç daha alınca B ve C eşit oluyor. Son durumda toplam kaç araç vardır?',
    secenekler: ['A) 161', 'B) 167', 'C) 175', 'D) 183', 'E) 189'],
    cevap: 2, aciklama: 'Toplam 175 araç. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2016057, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Alanı 1 birimkare olan düzgün altıgenlerden oluşan şekilde boyalı bölgenin alanı kaç birimkaredir?',
    secenekler: ['A) 8', 'B) 9', 'C) 10', 'D) 11', 'E) 12'],
    cevap: 2, aciklama: 'Boyalı alan 10 birimkaredir. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2016058, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Eşit alanlı iki üçgen içeren geometrik şekilde x kaç birimdir?',
    secenekler: ['A) 10', 'B) 12', 'C) 14', 'D) 16', 'E) 18'],
    cevap: 3, aciklama: 'x = 16 birim. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2016059, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Geometrik şekilde verilen koşullara göre x kaç birimdir?',
    secenekler: ['A) 3', 'B) 4', 'C) 5', 'D) 6', 'E) 7'],
    cevap: 1, aciklama: 'x = 4 birim. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2016060, yil: 2016, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Koordinat düzleminde A(2,1) noktasından iki karınca B ve C noktalarına gidiyor. B ve C aynı doğru üzerinde. A ile C arası kaç birimdir?',
    secenekler: ['A) 5', 'B) 6', 'C) 7', 'D) 8', 'E) 9'],
    cevap: 0, aciklama: 'Uzaklık 5 birimdir. Doğru cevap A şıkkıdır.',
  },

  // GENEL KÜLTÜR - TARİH
  {
    id: 2016061, yil: 2016, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Orta Asya\'da Avarların siyasi varlığına son vererek devletin sınırlarını batıda Hazar Denizi\'ne kadar genişleten Göktürk hükümdarı hangisidir?',
    secenekler: ['A) Mukan Kağan', 'B) Bögü Kağan', 'C) Tapo Kağan', 'D) Bilge Kağan', 'E) İlteriş Kağan'],
    cevap: 0, aciklama: 'Mukan Kağan bu başarıları elde etmiştir. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016062, yil: 2016, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Anadolu Selçuklu ve Osmanlı kuruluş döneminde esnaf ve zanaatkârların ahlak anlayışını şekillendiren İslam\'daki dayanışma ilkesi hangi kurumu doğurmuştur?',
    secenekler: ['A) Ahîlik Teşkilatı', 'B) Timar Sistemi', 'C) İltizam Sistemi', 'D) Devşirme Usulü', 'E) Enderun Mektebi'],
    cevap: 0, aciklama: 'Fütüvvet anlayışı Ahîlik Teşkilatı\'nı doğurmuştur. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016063, yil: 2016, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Anadolu beylikleri ve kuruldukları yerler arasında hangisi yanlış eşleştirilmiştir?',
    secenekler: ['A) Candaroğulları - Kastamonu', 'B) Germiyanoğulları - Kütahya', 'C) Saruhanoğulları - Manisa', 'D) Menteşeoğulları - Muğla', 'E) Taceddinoğulları - Balıkesir'],
    cevap: 4, aciklama: 'Taceddinoğulları Niksar yöresinde kurulmuştur. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2016064, yil: 2016, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Fatih Sultan Mehmet\'in Ortodoks Kilisesi\'nin haklarını güvence altına almasıyla öncelikle aşağıdakilerden hangisini amaçladığı söylenebilir?',
    secenekler: ['A) Müslüman olmayan tebaanın devlete bağlılığını sağlamayı', 'B) Rusya ile deniz ticaretini geliştirmeyi', 'C) Osmanlı ordusunu güçlendirmeyi', 'D) Latin Hristiyanlarla ittifak kurmayı', 'E) Hristiyan mezheplerini birleştirmeyi'],
    cevap: 0, aciklama: 'Fatih gayrimüslim tebaanın sadakatini kazanmayı amaçlamıştır. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016065, yil: 2016, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Osmanlı Devleti\'nde kalemiye sınıfına dahil olmayan görevli hangisidir?',
    secenekler: ['A) Nişancı', 'B) Defterdar', 'C) Müderris', 'D) Reisülküttap', 'E) Divan katibi'],
    cevap: 2, aciklama: 'Müderris ilmiye sınıfına aittir. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2016066, yil: 2016, ders: 'Tarih', seviye: 'Lisans',
    soru: '17. yüzyılda binlerce kitabı tanıtan bibliyografik çalışması ve coğrafya eseriyle tanınan Osmanlı bilgini kimdir?',
    secenekler: ['A) Hezarfen Ahmet Çelebi', 'B) Lagari Hasan Çelebi', 'C) Evliya Çelebi', 'D) Kâtip Çelebi', 'E) Ahi Ahmet Çelebi'],
    cevap: 3, aciklama: 'Kâtip Çelebi bu eserlerin sahibidir. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2016067, yil: 2016, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Hotin Seferi\'ndeki olumsuz izlenimler üzerine Osmanlı ordusunu yenilemeyi planlayan ancak yeniçeriler tarafından tahtını kaybeden padişah kimdir?',
    secenekler: ['A) II. Osman', 'B) IV. Murat', 'C) IV. Mehmet', 'D) III. Selim', 'E) II. Mahmut'],
    cevap: 0, aciklama: 'II. Osman\'dır. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016068, yil: 2016, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Osmanlı kuruluş dönemi medreselerinde farklı İslam coğrafyalarından âlimlerin görev yapması aşağıdakilerden hangisini gösterir?',
    secenekler: ['A) Osmanlı ilim geleneğinin geniş İslam coğrafyasından beslendiğini', 'B) Medreselerde sınıfsal ayrımın var olduğunu', 'C) Müfredatın yabancılarca belirlendiğini', 'D) Türk-İslam sentezinin medresede doğduğunu', 'E) Arapçanın tek eğitim dili kabul edildiğini'],
    cevap: 0, aciklama: 'Farklı ülkelerden âlimler Osmanlı ilminin zengin kaynaklandığını gösterir. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016069, yil: 2016, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Osmanlı donanmasının güçlenmesi, Boğaziçi saraylarının inşası ve Balkan isyanlarının yaşanması hangi padişah dönemine aittir?',
    secenekler: ['A) II. Abdülhamit', 'B) Abdülaziz', 'C) Abdülmecit', 'D) II. Mahmut', 'E) III. Mustafa'],
    cevap: 1, aciklama: 'Abdülaziz dönemi. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2016070, yil: 2016, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Kanunuesasi\'nin tüm uyrukları "Osmanlı" olarak tanımlayan maddesiyle aşağıdakilerden hangisi amaçlanmamıştır?',
    secenekler: ['A) Padişah yetkisini kısıtlamak', 'B) Ayrılıkçı hareketleri önlemek', 'C) Toplumu ortak kimlik altında birleştirmek', 'D) Din ayrımcılığını ortadan kaldırmak', 'E) Vatandaşlık statüsü oluşturmak'],
    cevap: 0, aciklama: 'Padişah yetkisini kısıtlamak amaçlanmamıştır. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016071, yil: 2016, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Osmanlı\'da Encümen-i Dâniş\'in kurulmasında hangi amaçlar etkili olmuştur?\nI. Eğitimin geliştirilmesi\nII. Diplomasinin örgütlenmesi\nIII. Bilim politikasının belirlenmesi',
    secenekler: ['A) Yalnız II', 'B) Yalnız III', 'C) I ve II', 'D) I ve III', 'E) II ve III'],
    cevap: 3, aciklama: 'I ve III etkili olmuştur. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2016072, yil: 2016, ders: 'Tarih', seviye: 'Lisans',
    soru: 'İngiltere\'nin Rusya\'nın güneye inişini engelleme politikası kapsamında fiilen yerleştiği Osmanlı toprağı hangisidir?',
    secenekler: ['A) Kıbrıs', 'B) Rodos', 'C) Girit', 'D) On İki Ada', 'E) Kırım'],
    cevap: 0, aciklama: 'İngiltere 1878\'de Kıbrıs\'a yerleşmiştir. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016073, yil: 2016, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Mustafa Kemal\'in 1918\'deki "barışı sağlayacak hükümetin meclise dayanması zorunludur" sözüyle aşağıdakilerden hangisinin gerekliliğini vurguladığı söylenebilir?',
    secenekler: ['A) Hükümetin meclise karşı sorumlu olmasının', 'B) Çok partili sisteme geçilmesinin', 'C) Koşulsuz barış imzalanmasının', 'D) Yeni meclis toplanmasının', 'E) Padişahın meclis kararlarına uymasının'],
    cevap: 0, aciklama: 'Hükümetin meclise dayanması gerekliliği vurgulanmıştır. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016074, yil: 2016, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Aşağıdaki isimlerden hangisinin Kuvayımilliye liderliği yaptığı söylenemez?',
    secenekler: ['A) İpsiz Recep', 'B) Çerkez Ethem', 'C) Yörük Ali Efe', 'D) Nene Hatun', 'E) Şahin Bey'],
    cevap: 3, aciklama: 'Nene Hatun Kuvayımilliye liderliği yapmamıştır. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2016075, yil: 2016, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Amasya Genelgesi\'nin maddelerinden hangileri Millî Mücadele\'nin yöntemini ortaya koyar?\nI. Vatanın bütünlüğü tehlikededir.\nII. İstanbul Hükümeti yetersiz kalmaktadır.\nIII. Milletin bağımsızlığını yine milleti kurtaracaktır.\nIV. Millî bir kurul oluşturulmalıdır.',
    secenekler: ['A) I ve II', 'B) I ve III', 'C) II ve III', 'D) II ve IV', 'E) III ve IV'],
    cevap: 4, aciklama: 'III ve IV yöntemi ortaya koymaktadır. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2016076, yil: 2016, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Misakımillî\'de halk oylamasına başvurulması öngörülen alanlar arasında hangisi yer almaz?',
    secenekler: ['A) Trabzon', 'B) Kars', 'C) Ardahan', 'D) Batum', 'E) Batı Trakya'],
    cevap: 0, aciklama: 'Trabzon öngörülen yerler arasında değildir. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016077, yil: 2016, ders: 'Tarih', seviye: 'Lisans',
    soru: '"Kurtuluş Savaşı yalnızca Türk-Yunan değil, emperyalist güçlere karşı bir savaştır." yargısını desteklemeyen durum hangisidir?',
    secenekler: ['A) Kars Antlaşması\'yla doğu sınırının belirlenmesi', 'B) Birinci İnönü\'den sonra İtilaf devletlerinin Londra Konferansı\'nı düzenlemesi', 'C) Mudanya\'ya İngiltere, Fransa ve İtalya\'nın katılması', 'D) Sakarya\'dan sonra Fransa ile Ankara Antlaşması\'nın imzalanması', 'E) İkinci İnönü\'den sonra İtalya\'nın Anadolu\'dan çekilmesi'],
    cevap: 0, aciklama: 'Kars Antlaşması bu yargıyı desteklememektedir. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016078, yil: 2016, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Aşağıdaki yayın organlarından hangisi Millî Mücadele\'ye karşı çıkmıştır?',
    secenekler: ['A) İleri', 'B) Peyam-ı Sabah', 'C) Tasvir-i Efkâr', 'D) İkdam', 'E) Yeni Gün'],
    cevap: 1, aciklama: 'Peyam-ı Sabah Millî Mücadele\'ye karşı çıkmıştır. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2016079, yil: 2016, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Ankara\'nın başkent ilan edildiği 13 Ekim 1923\'te Ankara\'da daimi elçiliği bulunan devlet hangisidir?',
    secenekler: ['A) İngiltere', 'B) Afganistan', 'C) İtalya', 'D) Yunanistan', 'E) Fransa'],
    cevap: 1, aciklama: 'O tarihte Ankara\'da elçilik yalnızca Afganistan\'da vardı. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2016080, yil: 2016, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Atatürk Dönemi\'nde Türk kadınları aşağıdaki görev ve mesleklerden hangisine en erken kabul edilmiştir?',
    secenekler: ['A) Belediye başkanlığı', 'B) Cerrahlık', 'C) Savaş pilotluğu', 'D) Muhtarlık', 'E) Milletvekilliği'],
    cevap: 0, aciklama: 'Kadınlar 1930\'da belediye başkanlığı seçimlerine katılabilmiştir. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016081, yil: 2016, ders: 'Tarih', seviye: 'Lisans',
    soru: '1934\'te adı İstanbul Şehir Tiyatrosu olarak değiştirilen kurum hangisidir?',
    secenekler: ['A) Darülbedayi', 'B) Darüleytam', 'C) Darülmaarif', 'D) Darülmuallimat', 'E) Darülfünun'],
    cevap: 0, aciklama: 'Darülbedayi bu adı almıştır. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016082, yil: 2016, ders: 'Tarih', seviye: 'Lisans',
    soru: 'İsmet İnönü\'nün Lozan\'a heyet başkanı olarak gitmesi için Dışişleri Bakanlığı\'ndan istifa eden kişi kimdir?',
    secenekler: ['A) Mahmut Esat Bozkurt', 'B) Dr. Rıza Nur', 'C) Hasan Saka', 'D) Kâzım Karabekir', 'E) Yusuf Kemal Tengirşenk'],
    cevap: 4, aciklama: 'Yusuf Kemal Tengirşenk istifa etmiştir. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2016083, yil: 2016, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Halk iradesini ve millî egemenliği devlet yönetiminin temeli olarak kabul eden Atatürk ilkesi hangisidir?',
    secenekler: ['A) Cumhuriyetçilik', 'B) Milliyetçilik', 'C) Halkçılık', 'D) Devletçilik', 'E) Laiklik'],
    cevap: 0, aciklama: 'Cumhuriyetçilik millî egemenliği esas alır. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016084, yil: 2016, ders: 'Tarih', seviye: 'Lisans',
    soru: '1924\'te İstanbul\'da Fethi Okyar\'ın temsil ettiği "Haliç Konferansı" hangi sınır meselesiyle ilgiliydi?',
    secenekler: ['A) Irak', 'B) İran', 'C) Suriye', 'D) Gürcistan', 'E) Ermenistan'],
    cevap: 2, aciklama: 'Suriye sınırı meselesiydi. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2016085, yil: 2016, ders: 'Tarih', seviye: 'Lisans',
    soru: '1947\'de ilan edilen Truman Doktrini hakkında hangileri doğrudur?\nI. ABD-SSCB bloklaşmasını derinleştirdi.\nII. Avrupa\'nın ekonomik rekabetini hedefledi.\nIII. Türkiye ve Yunanistan\'a askerî yardım öngördü.',
    secenekler: ['A) Yalnız II', 'B) I ve II', 'C) I ve III', 'D) II ve III', 'E) I, II ve III'],
    cevap: 2, aciklama: 'I ve III doğrudur. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2016086, yil: 2016, ders: 'Tarih', seviye: 'Lisans',
    soru: '1948\'de Kominform\'dan çıkarılarak Doğu Bloku\'ndan ayrılan ve 1961\'de Bağlantısızlar hareketinde yer alan ülke hangisidir?',
    secenekler: ['A) Mısır', 'B) Endonezya', 'C) Yugoslavya', 'D) Hindistan', 'E) Afganistan'],
    cevap: 2, aciklama: 'Yugoslavya. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2016087, yil: 2016, ders: 'Tarih', seviye: 'Lisans',
    soru: '1960\'ta kurulan Kıbrıs Cumhuriyeti\'nde cumhurbaşkanı yardımcılığı görevini üstlenen Kıbrıs Türkü lider kimdir?',
    secenekler: ['A) Fazıl Küçük', 'B) Rauf Denktaş', 'C) Mehmet Ali Talat', 'D) Tayfur Sökmen', 'E) Abdurrahman Melek'],
    cevap: 0, aciklama: 'Fazıl Küçük bu görevi üstlenmiştir. Doğru cevap A şıkkıdır.',
  },

  // COĞRAFYA
  {
    id: 2016088, yil: 2016, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Haritada numaralandırılmış alanların hangisine ait toprak özelliği verilmemiştir? (Yıkanma fazla, asit karakterli, organik madde zengin topraklar)',
    secenekler: ['A) I', 'B) II', 'C) III', 'D) IV', 'E) V'],
    cevap: 0, aciklama: 'I numaralı alana ait özellik verilmemiştir. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016089, yil: 2016, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Deniz kıyısından yükseklere çıkıldığında kestane, gürgen, kayın, göknar ve ladin bitki kuşaklarını barındıran bu dağ sistemi hangisidir?',
    secenekler: ['A) Amanoslar', 'B) Bozdağlar', 'C) Kazdağı', 'D) Kaçkarlar', 'E) Bolkar Dağları'],
    cevap: 3, aciklama: 'Kaçkar Dağları. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2016090, yil: 2016, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Türkiye\'de deprem riski en az olan bölge haritada hangi numara ile gösterilmektedir?',
    secenekler: ['A) I', 'B) II', 'C) III', 'D) IV', 'E) V'],
    cevap: 1, aciklama: 'II numaralı alan. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2016091, yil: 2016, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Yaz-kış sıcaklık farkının en fazla olduğu (karasallığın en yüksek) bölge haritada hangi numara ile gösterilmiştir?',
    secenekler: ['A) I', 'B) II', 'C) III', 'D) IV', 'E) V'],
    cevap: 4, aciklama: 'V numaralı alan. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2016092, yil: 2016, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Türkiye\'de buzul şekillerinin görüldüğü alanların ortak özellikleri hangileridir?\nI. Yüksek dağlık alanlar\nII. Plato görünümlü sahalar\nIII. Genellikle 2000 m üzeri\nIV. Ülkenin kuzeyi',
    secenekler: ['A) I ve II', 'B) I ve III', 'C) II ve III', 'D) II ve IV', 'E) III ve IV'],
    cevap: 1, aciklama: 'I ve III ortak özelliklerdir. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2016093, yil: 2016, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Batı Toroslar\'da polyelerin yaygın olmasının temel nedeni hangisidir?',
    secenekler: ['A) Akdeniz yağış rejimi', 'B) Zengin bitki örtüsü', 'C) Kalın kalker ve kırıklı yapı', 'D) Yüksek eğim', 'E) Buzullaşma'],
    cevap: 2, aciklama: 'Kalın kalker ve kırıklı yapı polye oluşumunu kolaylaştırır. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2016094, yil: 2016, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Türkiye\'nin yüksek ortalama rakıma sahip olmasında en etkili faktörler hangileridir?\nI. Kuzey ve güneyde sıradağlar\nII. Horst-graben yapısı\nIII. Epirojenik yükselme\nIV. Akarsu vadileri',
    secenekler: ['A) I ve II', 'B) I ve III', 'C) II ve III', 'D) II ve IV', 'E) III ve IV'],
    cevap: 1, aciklama: 'I ve III en etkili faktörlerdir. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2016095, yil: 2016, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Türkiye\'de 1960\'tan günümüze nüfus artışıyla ilgili hangisi yanlıştır?',
    secenekler: ['A) Nüfus artış hızı her dönem sabit kalmıştır.', 'B) Toplam nüfus her sayımda artmıştır.', 'C) Artış hızı bölgeden bölgeye farklıdır.', 'D) Kırsal kesimde artış ağırlıklı doğal artıştır.', 'E) Büyük şehirlerde artış göçle gerçekleşmiştir.'],
    cevap: 0, aciklama: 'Nüfus artış hızı dönemler arasında farklılık göstermiştir. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016096, yil: 2016, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Türkiye\'de 1950\'lerden bu yana kentsel nüfus artışına en az katkıda bulunan faktör hangisidir?',
    secenekler: ['A) Kentte eğitim olanaklarının fazla olması', 'B) Kentlerde iş çeşitliliği', 'C) Sulama alanlarının genişlemesi', 'D) Tarımda makineleşme', 'E) Sanayinin kentlerde yoğunlaşması'],
    cevap: 2, aciklama: 'Sulama alanlarının genişlemesi kentleşmeye katkı sağlamaz. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2016097, yil: 2016, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Türkiye\'de kentsel dönüşüm uygulamalarını zorunlu kılan temel sorun hangisidir?',
    secenekler: ['A) Hızlı ve plansız kentleşme', 'B) Araç sayısının artması', 'C) Ulaşım sorunları', 'D) Konut talebi', 'E) Sanayi kirliliği'],
    cevap: 0, aciklama: 'Plansız kentleşme dönüşümü zorunlu kılmıştır. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016098, yil: 2016, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Türkiye\'de kruvaziyer turizminin en geliştiği iki liman hangilerdir?',
    secenekler: ['A) İstanbul ve Kuşadası', 'B) İzmir ve Mersin', 'C) Antalya ve Mersin', 'D) İzmir ve Antalya', 'E) Kuşadası ve Antalya'],
    cevap: 0, aciklama: 'İstanbul ve Kuşadası. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016099, yil: 2016, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Türkiye\'nin enerji koridoru konumuna gelmesinde petrol ve doğalgaz tedarikçisi olmayan ülke hangisidir?',
    secenekler: ['A) Irak', 'B) İran', 'C) Rusya', 'D) Gürcistan', 'E) Azerbaycan'],
    cevap: 3, aciklama: 'Gürcistan tedarikçi değildir. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2016100, yil: 2016, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Türkiye\'de jeotermal enerjiden elektrik üretilen alan haritada hangi numara ile gösterilmiştir?',
    secenekler: ['A) I', 'B) II', 'C) III', 'D) IV', 'E) V'],
    cevap: 1, aciklama: 'II numaralı alan. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2016101, yil: 2016, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Şeker pancarı tarımına dayalı şeker fabrikası bulunmayan il aşağıdakilerden hangisidir?',
    secenekler: ['A) Uşak', 'B) Kayseri', 'C) Kars', 'D) Kırklareli', 'E) Artvin'],
    cevap: 4, aciklama: 'Artvin\'de şeker fabrikası yoktur. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2016102, yil: 2016, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Aşağıdaki tarım ürünlerinden hangisi Türkiye\'de tarıma dayalı sanayi gelişimine doğrudan katkı sağlamamaktadır?',
    secenekler: ['A) Şeker pancarı', 'B) Pamuk', 'C) Tütün', 'D) Çay', 'E) Kivi'],
    cevap: 4, aciklama: 'Kivi tarıma dayalı sanayiye katkı sağlamaz. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2016103, yil: 2016, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Türkiye\'de I, II ve III numaralı alanlarda çıkarılan madenler sırasıyla hangilerinde doğru verilmiştir?',
    secenekler: ['A) Bor - Demir - Bakır', 'B) Mermer - Krom - Boksit', 'C) Demir - Bakır - Fosfat', 'D) Bakır - Boksit - Demir', 'E) Linyit - Demir - Mermer'],
    cevap: 0, aciklama: 'I-Bor, II-Demir, III-Bakır. Doğru cevap A şıkkıdır.',
  },

  // VATANDAŞLIK
  {
    id: 2016104, yil: 2016, ders: 'Vatandaşlık', seviye: 'Lisans',
    soru: 'Türkiye\'de bölgesel kalkınma projelerinin temel amaçları arasında yer almayan seçenek hangisidir?',
    secenekler: ['A) Bölgelerarası gelişmişlik farkını azaltmak', 'B) Göçü frenleyerek nüfusu yerinde tutmak', 'C) Doğal ve beşerî kaynakları etkin kullanmak', 'D) Yeni istihdam olanakları sağlamak', 'E) Bölgedeki yabancı yatırımları artırmak'],
    cevap: 4, aciklama: 'Yabancı yatırım artırma temel amaç değildir. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2016105, yil: 2016, ders: 'Vatandaşlık', seviye: 'Lisans',
    soru: 'Türkiye\'nin dış ticaret verileri incelendiğinde ihracat gelirleri içindeki payı en düşük ürün hangisidir?',
    secenekler: ['A) Demir-Çelik', 'B) Motorlu taşıtlar', 'C) Makine ve cihazlar', 'D) Pamuk ve pamuk ipliği', 'E) Elektronik ürünler'],
    cevap: 3, aciklama: 'Pamuk ve pamuk ipliğinin payı düşüktür. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2016106, yil: 2016, ders: 'Vatandaşlık', seviye: 'Lisans',
    soru: 'Kişinin kendi eylemleriyle hak kazanabilme ve borç altına girebilme iktidarı Türk hukukunda ne olarak adlandırılır?',
    secenekler: ['A) Hak ehliyeti', 'B) Erginlik', 'C) Fiil ehliyeti', 'D) Kısıtlılık', 'E) Hak sahipliği'],
    cevap: 2, aciklama: 'Fiil ehliyeti. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2016107, yil: 2016, ders: 'Vatandaşlık', seviye: 'Lisans',
    soru: 'Türk hukukuna göre yürürlük tarihi belirtilmeyen kanunlar Resmî Gazete\'de yayımlanmasından kaç gün sonra yürürlüğe girer?',
    secenekler: ['A) 30', 'B) 40', 'C) 45', 'D) 60', 'E) 90'],
    cevap: 2, aciklama: '45 gün sonra. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2016108, yil: 2016, ders: 'Vatandaşlık', seviye: 'Lisans',
    soru: 'Türk hukukuna göre dernek kurmak için gerekli asgari kişi sayısı kaçtır?',
    secenekler: ['A) 3', 'B) 5', 'C) 7', 'D) 10', 'E) 15'],
    cevap: 2, aciklama: 'En az 7 kişi gerekir. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2016109, yil: 2016, ders: 'Vatandaşlık', seviye: 'Lisans',
    soru: '1982 Anayasası\'na göre bir bakanlık boşaldığında yerine en geç kaç gün içinde atama yapılmalıdır?',
    secenekler: ['A) 7', 'B) 15', 'C) 20', 'D) 30', 'E) 45'],
    cevap: 1, aciklama: 'En geç 15 gün. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2016110, yil: 2016, ders: 'Vatandaşlık', seviye: 'Lisans',
    soru: '1982 Anayasası\'nda "kişinin hakları ve ödevleri" bölümünde yer almayan düzenleme hangisidir?',
    secenekler: ['A) Türk vatandaşlığı', 'B) Konut dokunulmazlığı', 'C) Seyahat özgürlüğü', 'D) Basın özgürlüğü', 'E) Din ve vicdan özgürlüğü'],
    cevap: 0, aciklama: 'Türk vatandaşlığı ayrı bölümde düzenlenmiştir. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016111, yil: 2016, ders: 'Vatandaşlık', seviye: 'Lisans',
    soru: 'Askerî Yüksek İdare Mahkemesi Türk hukukunda ilk kez hangi düzenlemeyle kurulmuştur?',
    secenekler: ['A) 1921 Anayasası', 'B) 1924 Anayasası', 'C) 1961 Anayasası\'nda 1971 değişikliği', 'D) 1982 Anayasası\'nın ilk hali', 'E) 1982 Anayasası\'nda 2004 değişikliği'],
    cevap: 2, aciklama: '1971 anayasa değişikliğiyle kurulmuştur. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2016112, yil: 2016, ders: 'Vatandaşlık', seviye: 'Lisans',
    soru: 'Türk idare hukukuna göre belediyenin organları hangi seçenekte doğru verilmiştir?',
    secenekler: ['A) Meclis - Encümen - Başkan', 'B) Meclis - Genel Sekreterlik - Başkan', 'C) İlçe Kurulu - Genel Sekreterlik - Başkan', 'D) Kaymakamlık - Genel Sekreterlik - Başkan', 'E) Genel Sekreterlik - Meclis - Encümen'],
    cevap: 0, aciklama: 'Meclis, encümen ve başkan. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016113, yil: 2016, ders: 'Vatandaşlık', seviye: 'Lisans',
    soru: '657 sayılı Devlet Memurları Kanunu\'nda yer almayan disiplin uygulaması hangisidir?',
    secenekler: ['A) Yer değiştirme', 'B) Aylıktan kesme', 'C) Kademe ilerlemesinin durdurulması', 'D) Memuriyetten çıkarma', 'E) Uyarma'],
    cevap: 0, aciklama: 'Yer değiştirme disiplin cezası değildir. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016114, yil: 2016, ders: 'Vatandaşlık', seviye: 'Lisans',
    soru: 'Türk idare hukukuna göre Devlet Denetleme Kurulu hangi makama bağlı çalışır?',
    secenekler: ['A) Millî Güvenlik Kurulu', 'B) Cumhurbaşkanlığı', 'C) TBMM Başkanlığı', 'D) İçişleri Bakanlığı', 'E) Bakanlar Kurulu'],
    cevap: 1, aciklama: 'Cumhurbaşkanlığına bağlı. Doğru cevap B şıkkıdır.',
  },

  // GÜNCEL BİLGİLER
  {
    id: 2016115, yil: 2016, ders: 'Güncel Bilgiler', seviye: 'Lisans',
    soru: 'Kayanın üzerinde oturmuş ve derin düşüncelere dalmış bir insan figürünü yansıtan "Düşünen Adam" adlı ünlü heykel hangi sanatçıya aittir?',
    secenekler: ['A) Michelangelo', 'B) Pablo Picasso', 'C) Leonardo da Vinci', 'D) Auguste Rodin', 'E) Frederic Bartholdi'],
    cevap: 3, aciklama: 'Auguste Rodin\'in eseridir. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2016116, yil: 2016, ders: 'Güncel Bilgiler', seviye: 'Lisans',
    soru: 'Tıp tarihine önemli katkılar yapmış ve Batı dünyasında "Avicenna" adıyla tanınan İslam bilgini kimdir?',
    secenekler: ['A) Farabi', 'B) El-Biruni', 'C) El-Cezerî', 'D) İbni Sina', 'E) İbni Haldun'],
    cevap: 3, aciklama: 'İbni Sina "Avicenna" olarak bilinir. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2016117, yil: 2016, ders: 'Güncel Bilgiler', seviye: 'Lisans',
    soru: 'Adına her yıl tiyatro ödülü verilen Türkiye\'nin ilk Müslüman Türk kadın tiyatro sanatçısı kimdir?',
    secenekler: ['A) Afife Jale', 'B) Cahide Sonku', 'C) Neyyire Neyyir', 'D) Keriman Halis', 'E) Adile Naşit'],
    cevap: 0, aciklama: 'Afife Jale. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2016118, yil: 2016, ders: 'Güncel Bilgiler', seviye: 'Lisans',
    soru: 'Sigarada bağımlılık yaratan ve küresel bir sağlık sorunu oluşturan madde hangisidir?',
    secenekler: ['A) Adrenalin', 'B) Nikotin', 'C) Tein', 'D) Kodein', 'E) Serotonin'],
    cevap: 1, aciklama: 'Nikotin. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2016119, yil: 2016, ders: 'Güncel Bilgiler', seviye: 'Lisans',
    soru: '2016\'da WTA kadınlar tenis sıralamasında ilk 100\'e giren Türk sporcu kimdir?',
    secenekler: ['A) İpek Soylu', 'B) Çağla Büyükakçay', 'C) Başak Eraydın', 'D) Pemra Özgen', 'E) Ayla Aksu'],
    cevap: 1, aciklama: 'Çağla Büyükakçay. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2016120, yil: 2016, ders: 'Güncel Bilgiler', seviye: 'Lisans',
    soru: '2016\'nın Mart ayında diplomatik ilişkileri normalleştirmek amacıyla yaklaşık 90 yıl sonra ilk kez bir ABD başkanı tarafından ziyaret edilen ülke hangisidir?',
    secenekler: ['A) Çin', 'B) Afganistan', 'C) Küba', 'D) Vietnam', 'E) İran'],
    cevap: 2, aciklama: 'Obama Küba\'yı ziyaret etmiştir. Doğru cevap C şıkkıdır.',
  },
];