export const SORULAR_2017 = [
  // GENEL YETENEK - TÜRKÇE
  {
    id: 2017001, yil: 2017, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'İnsanlar başkalarının hatalarını kolayca fark edip eleştirirken aynı hataları kendilerinde göremezler. Oysa kişi önce kendini sorgulamalıdır. Bu düşünceyle aşağıdaki atasözlerinden hangisi anlamca örtüşmektedir?',
    secenekler: ['A) El için kuyu kazan kendisi düşer.', 'B) Elin ağzı torba değil ki büzesin.', 'C) Komşunun tavuğu komşuya kaz görünür.', 'D) Damdan düşen damdan düşenin halini bilir.', 'E) Sırça köşkte oturan komşusuna taş atmamalı.'],
    cevap: 4, aciklama: 'Başkalarını eleştirmeden önce kendini sorgulamak gerekir. E şıkkı bu düşünceyle örtüşür.',
  },
  {
    id: 2017002, yil: 2017, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Bir yazarın klasik eserini çağdaş dile uyarlaması akademik çevrelerde büyük tartışma yarattı. Eleştirmenler uyarlamanın özgün eseri gölgeleyeceğini öne sürdü. Nitekim zamanla okuyucuların özgün esere olan ilgisinin azaldığı görüldü. Bu durumda uyarlamanın "özgün esere ihanet" sayılmasının dayanağı nedir?',
    secenekler: ['A) Uyarlama ile özgün eser arasında benzerlik olmadığına', 'B) Uyarlamanın özgün eserin dünya edebiyatındaki değerine zarar vermesine', 'C) Özgün eserdeki bazı bölümlerin uyarlamada yer almamasına', 'D) Uyarlamanın özgün eseri unutturacak olmasına', 'E) Uyarlamada konunun köklü biçimde değiştirilmesine'],
    cevap: 3, aciklama: 'Uyarlamanın özgün eseri unutturacak olması gerekçesi öne çıkmaktadır. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2017003, yil: 2017, ders: 'Türkçe', seviye: 'Lisans',
    soru: '(I) Fotoğrafın yaygınlaşmadan önceki dönemde ressamlar şehirleri ve nesneleri kendi izlenimlerine dayanarak çizerdi. (II) 18. yüzyılda Anadolu\'lu sanatçılar en çok İstanbul\'u ve deniz araçlarını konu aldı. (III) İstanbul o dönemde de güzelliğiyle bir çekim merkezi olmayı sürdürüyordu. (IV) Deniz ve gemiler kıyıdan uzakta yaşayan halk için her zaman ilgi çekici konular arasındaydı. (V) Ancak sanatçıların ilgi alanı bununla sınırlı kalmadı; yel değirmenleri ve antik kentler de tablolara girdi.\n\nBu cümlelerle ilgili aşağıdakilerden hangisi yanlıştır?',
    secenekler: ['A) I. cümlede sanatçıların beslendiği kaynaklardan söz edilmiştir.', 'B) II. cümlede ağırlıklı olarak işlenen konular belirtilmiştir.', 'C) III. cümlede sanatçıların konu tercihinin nedenine değinilmiştir.', 'D) IV. cümlede Anadolu coğrafyasının resimlere etkisi açıklanmıştır.', 'E) V. cümlede konu çeşitlenmesi üzerinde durulmuştur.'],
    cevap: 3, aciklama: 'IV. cümlede coğrafyanın etkisi değil halkın ilgisi anlatılmaktadır. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2017004, yil: 2017, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Kültürel kimlik ve miras konusundaki bir yazıda altı cümle yer almaktadır. Hangi cümlede I. cümlede dile getirilen durumun nedeni belirtilmemiştir?\n(I) Türkiye\'de Türk-İslam dönemi mirası toplumca daha kolay benimsenmektedir. (II) Bir mekân ya da gelenekle özdeşleşmek kültürel kimliğin şekillenmesinde belirleyicidir. (III) Toplum kendi kimliğiyle örtüşen mirası daha çabuk sahiplenir. (IV) Kimlikle bağdaşmayan dönemlerin kavranması ise güçtür. (V) Geçmişin mevcut kimlikle uzak düşen evreleri bireyler için anlam taşımaz. (VI) Bu tür durumlarda toplum söz konusu mirasa haksız biçimde değer vermeyebilir.',
    secenekler: ['A) II', 'B) III', 'C) IV', 'D) V', 'E) VI'],
    cevap: 0, aciklama: 'II. cümlede I. cümledeki durumun nedeni belirtilmemiştir. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2017005, yil: 2017, ders: 'Türkçe', seviye: 'Lisans',
    soru: '(I) Cam sanatının özgün tekniklerinden biri olan çeşmibülbül saydam cam içinde dönen helezonlarıyla dikkat çeker. (II) Osmanlı Türkçesinde "bülbülün gözü" anlamına gelen bu sözcük bülbülün gözündeki çizgilerden ilham almış olabilir. (III) Bu teknik 16. yüzyılda Venedik\'te geliştirilmiş, 19. yüzyıl başlarında Osmanlı topraklarına gelmiştir. (IV) Çeşmibülbülün yapımı ilk hazırlıktan son biçimine kadar tam bir sanatçı duyarlılığı gerektirir. (V) Bir süre unutulan teknik 1960\'larda yeniden canlanmıştır.\n\nDüşüncenin akışını bozan cümle hangisidir?',
    secenekler: ['A) I', 'B) II', 'C) III', 'D) IV', 'E) V'],
    cevap: 3, aciklama: 'IV. cümle tarihsel akıştan koparak yapım sürecine geçmektedir. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2017006, yil: 2017, ders: 'Türkçe', seviye: 'Lisans',
    soru: '(I) Teknolojinin gelişmesiyle yeni askerî keşif yöntemleri ortaya çıktı. (II) Günümüzde keşif görevleri farklı araçlarla yürütülmektedir. (III) Mikro hava araçlarıyla keşif görevlerini daha güvenli kılmak hedefleniyor. (IV) Uydular, yüksek irtifaya çıkabilen uçaklar ve insansız hava araçları bu amaçla kullanılıyor. (V) Tek bir askerin sırt çantasında taşıyabileceği bu araçlarla bilgi daha ucuz ve güvenli biçimde elde edilebiliyor.\n\nAnlamlı bir bütün oluşturmak için hangi cümleler yer değiştirmelidir?',
    secenekler: ['A) I ile II', 'B) II ile III', 'C) II ile V', 'D) III ile IV', 'E) IV ile V'],
    cevap: 3, aciklama: 'III ve IV yer değiştirmelidir. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2017007, yil: 2017, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'I. İçimden geldiğince her şeyi deneyerek öğrendim.\nII. Yaşlandıkça doğayı varılacak bir hedef gibi görmeye başladım.\nIII. Doğa çocukluğumda benim için bir keşif alanıydı.\nIV. Aynı zamanda o yıllarda büyük bir coşku içindeydim.\nV. Ama bir yanım hep çocuk kaldı ve bunu doğaya borçluyum.\n\nBu cümleler anlamlı sıralanınca sonuncu hangisi olur?',
    secenekler: ['A) I', 'B) II', 'C) III', 'D) IV', 'E) V'],
    cevap: 4, aciklama: 'Doğru sıralama III-I-IV-II-V; son cümle V\'tir. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2017008, yil: 2017, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Bir roman kahramanının çevresiyle ilişkisini anlatan parçada aşağıdakilerden hangisi yoktur?',
    secenekler: ['A) Betimleme', 'B) Öyküleme', 'C) Karşılaştırma', 'D) Örneklendirme', 'E) Tanımlama'],
    cevap: 4, aciklama: 'Parçada tanımlama yapılmamıştır. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2017009, yil: 2017, ders: 'Türkçe', seviye: 'Lisans',
    soru: '"Arkeologlar insanlığın yalnızca temel ihtiyaçlarını karşılamak için değil süs ve estetik kaygılarla da hareket ettiğini ortaya koydu. Kazılarda kemik ve boynuzdan yapılmış pek çok aksesuar bulunması bunun en önemli kanıtıydı. Bulunan figürlerin bir kısmı yaklaşık 30.000 yıl önce oyulmuş hayvan ve insan tasvirleriydi."\n\nAşağıdaki sözcüklerden hangisinin yazımı yanlıştır?\nI. arkeologlar\nII. temel\nIII. aksesuar\nIV. figürlerin\nV. tasvirleriydi',
    secenekler: ['A) I', 'B) II', 'C) III', 'D) IV', 'E) V'],
    cevap: 2, aciklama: '"Aksesuar" doğru yazımıdır; "aksesuvar" yanlıştır. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2017010, yil: 2017, ders: 'Türkçe', seviye: 'Lisans',
    soru: '"Düşüncelerimiz ve dolayısıyla kavramlarımız sürekli değişiyor. Bir yüzyıldan öbürüne şair kavramının da dönüştüğünü söyleyebiliriz. Dünün o duygulu şairi geçti; yerine tam anlamıyla bir insan araştırmacısı olan çağdaş şair geldi."\n\nAltı çizili sözcüklerin türleri sırasıyla verilmiştir. Hangi seçenek doğrudur?\nI. düşüncelerimiz\nII. bir yüzyıldan öbürüne\nIII. o\nIV. çağdaş',
    secenekler: ['A) İsim - zarf - sıfat - sıfat', 'B) İsim - zarf - zamir - sıfat', 'C) İsim - edat - zamir - zarf', 'D) Edat - zarf - isim - zarf', 'E) Edat - zarf - sıfat - isim'],
    cevap: 0, aciklama: 'Sözcüklerin türleri sırasıyla isim, zarf, sıfat, sıfat\'tır. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2017011, yil: 2017, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Bir filozofun düşüncelerini aktaran parçada aşağıdaki ses olaylarından hangisi yoktur?',
    secenekler: ['A) Ünlü düşmesi', 'B) Ünlü daralması', 'C) Ünsüz yumuşaması', 'D) Ünsüz düşmesi', 'E) Ünsüz benzeşmesi'],
    cevap: 4, aciklama: 'Parçada ünsüz benzeşmesi örneği bulunmamaktadır. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2017012, yil: 2017, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Aşağıdaki cümlelerin hangisinin öznesi sıfat tamlamasından oluşmuştur?',
    secenekler: ['A) Bireyin benliğini saran duygular yaşamın her alanında belirleyicidir.', 'B) Duygular mı düşüncelere yön verir sorusu zihni zorlayan bir sorudur.', 'C) Toplumun düşünce dünyasını sorgulamak insanları zorlamıştır.', 'D) Buzulların erimesi okyanus sularının yükselmesine yol açacaktır.', 'E) Yazma eylemi boş vakit değil duygu dünyasına bağlanma isteğidir.'],
    cevap: 0, aciklama: '"Bireyin benliğini saran duygular" sıfat tamlamasından oluşan öznedir. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2017013, yil: 2017, ders: 'Türkçe', seviye: 'Lisans',
    soru: '"ALS hastalığının yanlış katlanmış proteinlerle ilişkisi biliniyordu. Yeni bir araştırmada bu sürecin bağırsak bakterilerindeki proteinlerle başlayabileceği üzerinde duruldu. Bağırsak bakterilerinin ürettiği amiloid proteinin yapısal olarak beyindeki sorunlu proteinlere benzediği fark edildi."\n\nAltı çizili sözcüklerin hangileri niteleme görevinde kullanılmamıştır?\nI. yanlış\nII. kümelenip\nIII. üretilen\nIV. amiloid\nV. sorunlu',
    secenekler: ['A) I ve II', 'B) I ve III', 'C) II ve V', 'D) III ve IV', 'E) IV ve V'],
    cevap: 0, aciklama: 'I ve II niteleme görevinde kullanılmamıştır. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2017014, yil: 2017, ders: 'Türkçe', seviye: 'Lisans',
    soru: '"Normal insanlar hayatlarında bir kez gençlik sancısı çekerler." diyen bir düşünüre göre sanatçılar bu sancıyı birçok kez yaşar ve her defasında yeniden canlanır.\n\nParçadaki numaralanmış sözcüklerden hangisi yapısı bakımından diğerlerinden farklıdır?\nI. insanlar\nII. ardından\nIII. Fakat\nIV. sanatçılar\nV. gençleşirler',
    secenekler: ['A) I', 'B) II', 'C) III', 'D) IV', 'E) V'],
    cevap: 1, aciklama: '"Ardından" sözcüğü yapı bakımından diğerlerinden farklıdır. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2017015, yil: 2017, ders: 'Türkçe', seviye: 'Lisans',
    soru: '"Nobel" sözcüğünün kökenine ilişkin parçaya göre aşağıdakilerin hangisine ulaşılabilir?\n(Antik Yunan\'da yarışmalarda kazananlara onur nişanesi verilir, bu nişane mitolojide bir tanrının taşıdığı tacı temsil ederdi. Nobel ödülündeki "laureate" sözcüğü de buradan gelmektedir.)',
    secenekler: ['A) Eski Yunan mitolojisinin Nobel ödülünü doğrudan biçimlendirdiğine', 'B) Farklı dönem ve kültürlerde başarılı kişilere unvan verildiğine', 'C) Tarihsel süreçte ödül verilen alanların benzer olduğuna', 'D) Sanat alanındaki kişilerin hatırlanmak istediğine', 'E) Eski dönem sözcüklerinin günümüzde işlevini yitirdiğine'],
    cevap: 1, aciklama: 'Farklı dönem ve kültürlerde başarıya unvan verildiği çıkarılabilir. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2017016, yil: 2017, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Bir editörün bir yazara verdiği dönütte yazarın anlatımının "düzensizliği" vurgulanmaktadır. Editör dosyayı iade ederken gelişime inandığını da belirtmektedir. Bu roman yazarıyla ilgili aşağıdakilerden hangisi söylenemez?',
    secenekler: ['A) Anlatımında sıra dışı özellikler sergilediği', 'B) Güçlü yanlarının bulunduğu', 'C) Derli toplu bir anlatımdan uzak olduğu', 'D) Romancılıkta kendini geliştirmesi gerektiği', 'E) Modern sanat anlayışına uygun davrandığı'],
    cevap: 4, aciklama: 'Modern sanat anlayışına uygunluğu parçada belirtilmemektedir. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2017017, yil: 2017, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Cumhuriyet\'in ilk döneminde yayımlanan bir sinema dergisiyle ilgili parçada aşağıdakilerin hangisine değinilmemiştir?\n(Dergi 1923\'te Hikmet Nazım yönetiminde çıkmaya başladı. Türkçe ve Fransızca yayımlandı. Başyazarlığını Vedat Örfi yaptı. Okuyucuyu dünya sinemasından haberdar etmeyi amaçladı. Kendi döneminin sinema dergilerini etkiledi.)',
    secenekler: ['A) Yayın süresine', 'B) Yönetici kadrosuna', 'C) Yayın diline', 'D) Alandaki öncülüğüne', 'E) Yayımlanma amacına'],
    cevap: 0, aciklama: 'Derginin yayın süresine değinilmemiştir. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2017018, yil: 2017, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Bir yazar yurt dışı seyahatlerinde alışveriş yaparken son parasına kadar harcadığını, valizinin taşımakta güçlük çektiğini aktarıyor. Kibar gezginlere gıpta ettiğini de belirtiyor. Yazar hakkında aşağıdakilerden hangisi söylenemez?',
    secenekler: ['A) Başkalarının davranışlarına özendiği', 'B) İmkânlarını zorlayacak biçimde eşya aldığı', 'C) Yurt dışına gittiği', 'D) Çevresindeki insanları gözlemlediği', 'E) Yeni yerleri keşfetmekten keyif aldığı'],
    cevap: 4, aciklama: 'Yeni yerleri keşfetmekten keyif aldığı parçada belirtilmemiştir. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2017019, yil: 2017, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Antropoloji bilimini tanıtan bir parçada aşağıdakilerden hangisi söylenebilir?\n(İnsanlık tarihin büyük bölümünde kimlik ve köken soruları bilimsel değil söylencesel yollarla yanıtlandı. Antropoloji bilimsel yaklaşımı kullanan bir alan olarak ortaya çıktı. Ancak araştırmacılar inceledikleri türün üyesi olduklarından nesnel bakış açısını korumakta zorlanırlar.)',
    secenekler: ['A) Antropologların gelecekte daha başarılı olacağına inanıldığına', 'B) Araştırmacıların deneyimlerinin çalışmalarını olumsuz etkilediğinden yakındığına', 'C) İnsanlık tarihini açıklamada bilimin yanı sıra anlatıların kullanıldığına dikkat çektiğine', 'D) Antropoloji ile insan üzerine çalışmaların arttığı düşüncesinde olduğuna', 'E) Homo sapiens çalışmalarının gelecek için faydalı olduğu kanısında olduğuna'],
    cevap: 2, aciklama: 'Yazar söylencelerle de insanlık tarihine yanıt arandığına dikkat çekmektedir. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2017020, yil: 2017, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Sözlü kültür ve matbaa ilişkisini ele alan parçadan aşağıdakilerin hangisine ulaşılabilir?\n(Sözlü kültür insanları birbirine bağlar. Matbaa ile birlikte okuma bireysel bir etkinliğe dönüştü; herkes kendi başına okumaya başladı. Önceki dönemlerde metinler bir kişi tarafından topluluğa seslendirilirdi.)',
    secenekler: ['A) El yazması eserleri okumak yerine dinlemeyi tercih etmişlerdir.', 'B) Sözlü kültürde hacimli kitaplardan kaçınılmıştır.', 'C) Matbaa ile okumada bireysellik ön plana çıkmıştır.', 'D) Birlikte okuma dönemlerinde daha fazla bilgi üretilmiştir.', 'E) Yazının icadı okuma alışkanlığını doğrudan geliştirmiştir.'],
    cevap: 2, aciklama: 'Matbaa ile okumada bireyselleşme ön plana çıkmıştır. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2017021, yil: 2017, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Aynı parçaya göre "okuma eylemi"nin özellikleri arasında gösterilemez?',
    secenekler: ['A) Bireysel çaba gerektirmesi', 'B) Uygun bir mekânda gerçekleşmesi', 'C) Farklı dönemlerde varlığını sürdürmesi', 'D) Sözlü kültür ürünlerini dışlaması', 'E) Matbaayla birlikte dönüşüm geçirmesi'],
    cevap: 3, aciklama: 'Okuma eylemi sözlü kültür ürünlerini dışlamamıştır. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2017022, yil: 2017, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Richard Strauss\'u anlatan parçadan hareketle onu özgün kılan özellik nedir?\n(Strauss gelenekçilik ile modernizm arasındaki konumuyla müzik tarihine damgasını vurdu. Eserleri iki farklı yüzyılı birbirine bağladı.)',
    secenekler: ['A) Farklı dönemleri harmanlayarak yeni bir sentez oluşturması', 'B) Eleştirileri dikkate alarak kendini geliştirmesi', 'C) Müzik kariyerine yeni türlerle başlaması', 'D) Çağdaşlarının işlemediği temaları kullanması', 'E) Bestelerini yaşadığı yüzyılın beğenisiyle yapması'],
    cevap: 0, aciklama: 'Farklı dönemleri harmanlayan sentezi onu özgün kılmaktadır. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2017023, yil: 2017, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Richard Strauss parçasının anlatımı hakkında hangisi söylenemez?',
    secenekler: ['A) Karşılaştırma yapılmıştır.', 'B) Örneklemeye başvurulmuştur.', 'C) Öznel yargılar içermektedir.', 'D) Benzetmeden yararlanılmıştır.', 'E) Mecaz kullanımı söz konusudur.'],
    cevap: 1, aciklama: 'Parçada örnekleme yapılmamıştır. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2017024, yil: 2017, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Tarihsel empati kavramını ele alan uzun parçada aşağıdakilerin hangisine değinilmemiştir?\n(Tarihsel empati geçmişi kendi bağlamında değerlendirmek demektir. Kavramı 19. yüzyılda Alman tarihçi Ranke temellendirdi. Sempatiyle karıştırıldı. Farklı disiplinlerden beslenir. Tartışmalara yol açtı. İngiltere\'de somut bir eğitim projesinde kullanıldı.)',
    secenekler: ['A) Temel özelliklerinin ne olduğuna', 'B) Kim tarafından ortaya atıldığına', 'C) Yer aldığı somut bir çalışmaya', 'D) Ortaya çıkardığı tartışmalara', 'E) Diğer disiplinlerdeki uygulamalarına'],
    cevap: 4, aciklama: 'Diğer disiplinlerdeki uygulamalarına değinilmemiştir. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2017025, yil: 2017, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Tarihsel empatiyi benimseyen bir araştırmacıdan aşağıdakilerden hangisi beklenmez?',
    secenekler: ['A) Araştırdığı dönemi anlamak için farklı disiplinlerden yararlanması', 'B) Dönemin kültür ve inançlarını göz önünde bulundurması', 'C) İncelediği kişiliklerin duygu ve düşünceleriyle özdeşleşmesi', 'D) Kendi döneminin değer yargılarını bir kenara bırakması', 'E) İncelediği toplumları kendi gerçeklikleri içinde kavramaya çalışması'],
    cevap: 2, aciklama: 'Tarihsel empati, sempati değildir; kişiliklerin duygusuyla özdeşleşmek beklenmez. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2017026, yil: 2017, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Tarihsel empati parçasındaki cümlelerin hangisinde mecaz anlamda kullanılmış bir ifade yoktur?',
    secenekler: ['A) I', 'B) II', 'C) III', 'D) IV', 'E) V'],
    cevap: 2, aciklama: 'III. cümlede mecaz anlam yoktur. Doğru cevap C şıkkıdır.',
  },

  // MATEMATİK
  {
    id: 2017027, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Bir istasyona gün içinde sırayla gelen A, B, C, D, E, F, G ve H araçları benzin, LPG veya mazot almıştır. Her araç tek tür yakıt almış olup:\n• E ilk sırada geldi ve mazot aldı.\n• F ile G arasında yalnızca C geldi ve mazot aldı.\n• B ile H arasında yalnızca bir araç geldi.\n• B ve H LPG aldı.\n• H\'den hemen sonra F yakıt aldı.\n• C\'den sonra yalnızca bir araç yakıt aldı.\n• Art arda aynı tür yakıt satılmadı.\n\nI. A, II. D, III. G araçlarından hangileri mazot almış olabilir?',
    secenekler: ['A) Yalnız I', 'B) Yalnız II', 'C) Yalnız III', 'D) I ve II', 'E) II ve III'],
    cevap: 3, aciklama: 'D şıkkı (I ve II) doğrudur. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2017028, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Yakıt istasyonu probleminde aşağıdakilerden hangisi kesinlikle yanlıştır?',
    secenekler: ['A) Benzin alan toplam iki araç vardır.', 'B) Mazot alan toplam dört araç vardır.', 'C) LPG alan toplam üç araç vardır.', 'D) Mazot alan toplam üç araç vardır.', 'E) Benzin alan toplam dört araç vardır.'],
    cevap: 1, aciklama: 'Mazot alan dört araç olması mümkün değildir. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2017029, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Yakıt istasyonu probleminde aşağıdakilerden hangisi kesin olarak doğrudur?',
    secenekler: ['A) İkinci sırada B geldi.', 'B) Üçüncü sırada A geldi.', 'C) Dördüncü sırada D geldi.', 'D) Beşinci sırada H geldi.', 'E) Altıncı sırada G geldi.'],
    cevap: 3, aciklama: 'Beşinci sırada H yakıt almıştır. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2017030, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: 'En az satılan yakıtın benzin olduğu biliniyorsa aşağıdakilerden hangisi kesin doğrudur?',
    secenekler: ['A) A benzin aldı.', 'B) D benzin aldı.', 'C) D mazot aldı.', 'D) G benzin aldı.', 'E) G LPG aldı.'],
    cevap: 4, aciklama: 'Bu koşul altında G LPG almıştır. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2017031, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: '(2 + 3) × 4 - 8 işleminin sonucu kaçtır?',
    secenekler: ['A) 4', 'B) 9', 'C) 12', 'D) 16', 'E) 20'],
    cevap: 2, aciklama: '5 × 4 - 8 = 20 - 8 = 12. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2017032, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: '3² + 4² - 16 işleminin sonucu kaçtır?',
    secenekler: ['A) 4', 'B) 9', 'C) 12', 'D) 16', 'E) 20'],
    cevap: 1, aciklama: '9 + 16 - 16 = 9. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2017033, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: '√4 - √1 işleminin sonucu kaçtır?',
    secenekler: ['A) 1', 'B) 2', 'C) 3', 'D) 4', 'E) 5'],
    cevap: 0, aciklama: '√4 = 2, √1 = 1; 2 - 1 = 1. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2017034, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: '3/10 ondalık gösterimi nedir?',
    secenekler: ['A) 0,1', 'B) 0,2', 'C) 0,3', 'D) 0,4', 'E) 0,5'],
    cevap: 2, aciklama: '3/10 = 0,3. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2017035, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: 'A, B, C birer rakam olmak üzere A + B + C = 10 ve A × B = 6 ise toplam kaçtır?',
    secenekler: ['A) 8', 'B) 10', 'C) 11', 'D) 13', 'E) 15'],
    cevap: 1, aciklama: 'Toplam 10\'dur. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2017036, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: '3x - 2 = 7 ise x kaçtır?',
    secenekler: ['A) 1', 'B) 2', 'C) 3', 'D) 4', 'E) 5'],
    cevap: 2, aciklama: '3x = 9 → x = 3. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2017037, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: 'a ve b farklı gerçel sayılar olmak üzere a + b = 10 ve a × b = 21 ise a² + b² kaçtır?',
    secenekler: ['A) 6', 'B) 7', 'C) 9', 'D) 12', 'E) 58'],
    cevap: 4, aciklama: 'a² + b² = (a+b)² - 2ab = 100 - 42 = 58. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2017038, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: 'a/b = 3/4 ve a + b = 7 ise a · b kaçtır?',
    secenekler: ['A) 1', 'B) 3', 'C) 4', 'D) 6', 'E) 12'],
    cevap: 3, aciklama: 'a = 3, b = 4 → a · b = 12. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2017039, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: 'x ve y tam sayılar olmak üzere x + y = 5 koşulunu sağlayan xy çarpımının alabileceği en büyük değer kaçtır?',
    secenekler: ['A) 3', 'B) 4', 'C) 6', 'D) 8', 'E) 9'],
    cevap: 2, aciklama: 'x=2, y=3 → xy=6 en büyük değerdir. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2017040, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: 'a > 2 ve b < 5 koşulları altında I. a + b > 7, II. a - b < -3, III. 2a > 4 ifadelerinden hangileri her zaman doğrudur?',
    secenekler: ['A) Yalnız I', 'B) Yalnız II', 'C) Yalnız III', 'D) I ve II', 'E) I ve III'],
    cevap: 2, aciklama: 'Yalnızca III her zaman doğrudur. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2017041, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: 'f(x) = 3x + 1 ve g(x) = x - 2 fonksiyonları için f(g(3)) kaçtır?',
    secenekler: ['A) 3', 'B) 4', 'C) 6', 'D) 9', 'E) 12'],
    cevap: 1, aciklama: 'g(3) = 1; f(1) = 3(1) + 1 = 4. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2017042, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: 'f(x) = x² - 1 fonksiyonu için f(3) kaçtır?',
    secenekler: ['A) 5', 'B) 6', 'C) 7', 'D) 8', 'E) 9'],
    cevap: 3, aciklama: 'f(3) = 9 - 1 = 8. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2017043, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: 'x, y, z tam sayılar ve x + y + z tek sayı olduğunda I. x + y çifttir, II. y tek ise z tektir, III. y çift ise z tektir ifadelerinden hangileri her zaman doğrudur?',
    secenekler: ['A) Yalnız II', 'B) Yalnız III', 'C) I ve II', 'D) I ve III', 'E) II ve III'],
    cevap: 2, aciklama: 'I ve II her zaman doğrudur. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2017044, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Bir doğal sayıda her rakam kendi sayı değeri kadar tekrar ediyorsa buna "âlim sayı" deniyor (örn. 41444). Altı basamaklı kaç farklı âlim sayı vardır?',
    secenekler: ['A) 82', 'B) 80', 'C) 78', 'D) 76', 'E) 74'],
    cevap: 0, aciklama: '82 farklı âlim sayı vardır. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2017045, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: 'A ve B araçları birbirine doğru hareket ediyor. 2 saat sabit hızla ilerledikten sonra B hızını yarıya düşürüyor, A değiştirmiyor. A aracının hızı saatte kaç km\'dir?',
    secenekler: ['A) 60', 'B) 55', 'C) 50', 'D) 45', 'E) 40'],
    cevap: 4, aciklama: 'A aracının hızı 40 km/s\'tir. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2017046, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: 'A deposu boş, B deposu dolu. Su seviyeleri eşitlenince A 9 saatte doluyor, B 4 saatte boşalıyor. A deposu toplamda kaç saatte dolmuştur?',
    secenekler: ['A) 15', 'B) 16', 'C) 17', 'D) 18', 'E) 19'],
    cevap: 0, aciklama: 'A deposu toplamda 15 saatte dolmuştur. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2017047, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Fabrikada 2. gün 1. güne göre %50 fazla, 3. gün 2. güne göre %50 fazla havlu üretildi. İlk iki günün toplamı 3. günün 2 katı olsaydı 320 fazla üretilecekti. Toplam kaç havlu üretilmiştir?',
    secenekler: ['A) 720', 'B) 740', 'C) 760', 'D) 780', 'E) 800'],
    cevap: 2, aciklama: 'Toplam 760 havlu. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2017048, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Kerem ile dedesi arasındaki yaş farkı, dedesiyle babasının yaş farkından bir fazla. Kerem 20 yaşındayken dedesi 69. Kerem ile babası arasındaki yaş farkı kaçtır?',
    secenekler: ['A) 20', 'B) 23', 'C) 25', 'D) 28', 'E) 30'],
    cevap: 2, aciklama: 'Yaş farkı 25\'tir. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2017049, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: 'İki mağaza 8. ve 10. günde teslimat yapıyor. Geç teslimatta biri %2 diğeri %5 iade ediyor. Oktay 9000 TL ödedi, 11. gün teslim alarak 500 TL iade aldı. Birinci mağazadan alınan mobilyanın fiyatı kaç TL\'dir?',
    secenekler: ['A) 4200', 'B) 4500', 'C) 4800', 'D) 5000', 'E) 5500'],
    cevap: 3, aciklama: 'Fiyat 5000 TL\'dir. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2017050, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Alper her ay 50 TL ödemeyi planladı. İlk 5 ay 40 TL, sonra 160 TL ödeyince planın yarısında bitti. Toplam borcu kaç TL\'dir?',
    secenekler: ['A) 400', 'B) 600', 'C) 800', 'D) 1000', 'E) 1200'],
    cevap: 3, aciklama: 'Toplam borç 1000 TL. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2017051, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: 'ABC üç basamaklı doğal sayısı BC iki basamaklı sayısının 26 katıdır. En büyük ABC sayısının rakamları toplamı kaçtır?',
    secenekler: ['A) 15', 'B) 18', 'C) 20', 'D) 21', 'E) 24'],
    cevap: 1, aciklama: 'Rakamlar toplamı 18\'dir. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2017052, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Aslı hafta içi bir gün hafta sonu bir gün tiyatroya gidiyor. Salı ve pazar günlerinde gitme olasılığı kaçtır?',
    secenekler: ['A) 1/10', 'B) 1/8', 'C) 1/6', 'D) 1/5', 'E) 1/4'],
    cevap: 3, aciklama: 'Olasılık 1/5\'tir. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2017053, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: 'En küçük asal çarpanı k olan sayılara "k-sel sayı" deniyor. İki basamaklı en küçük 3-sel sayı ile en büyük 5-sel sayının toplamı kaçtır?',
    secenekler: ['A) 110', 'B) 105', 'C) 100', 'D) 95', 'E) 90'],
    cevap: 0, aciklama: 'Toplam 110\'dur. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2017054, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Verilen doğal sayı 3-sel sayı olduğuna göre n\'nin alabileceği tam sayı değerlerinin toplamı kaçtır?',
    secenekler: ['A) 72', 'B) 80', 'C) 88', 'D) 92', 'E) 96'],
    cevap: 4, aciklama: 'Toplam 96\'dır. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2017055, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: '20 toplu torba oyununda Sevim ve Tuğba sırayla 1, 3 veya 6 top çekiyor. Oyun 7. adımda bitiyor. Toplam kaç kez 1 top çekilmiştir?',
    secenekler: ['A) 1', 'B) 2', 'C) 3', 'D) 4', 'E) 5'],
    cevap: 1, aciklama: '2 kez 1 top çekilmiştir. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2017056, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: 'İlk ve son adımda Sevim 6\'şar top çekmiş ve oyun bitmiş. Oyun kaç adımda bitmiştir?',
    secenekler: ['A) 5', 'B) 7', 'C) 9', 'D) 10', 'E) 11'],
    cevap: 0, aciklama: 'Oyun 5 adımda bitmiştir. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2017057, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Her ikisi eşit sayıda top çekiyor ancak farklı miktarlarda. Tuğba top çektikten sonra oyun bitiyor. Oyun kaç adımda bitmiştir?',
    secenekler: ['A) 6', 'B) 8', 'C) 10', 'D) 12', 'E) 14'],
    cevap: 2, aciklama: 'Oyun 10 adımda bitmiştir. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2017058, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: 'D, E ve F noktaları ABC üçgeninin kenarlarında. Verilen koşullara göre x kaç birimdir?',
    secenekler: ['A) 4', 'B) 5', 'C) 6', 'D) 7', 'E) 8'],
    cevap: 3, aciklama: 'x = 7 birimdir. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2017059, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: 'ABCD karesinin alanı EFD ikizkenar dik üçgeninin alanının 16 katı. ABCD\'nin alanının EFGH\'nin alanına oranı kaçtır?',
    secenekler: ['A) 2', 'B) 4', 'C) 6', 'D) 8', 'E) 10'],
    cevap: 1, aciklama: 'Oran 4\'tür. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2017060, yil: 2017, ders: 'Matematik', seviye: 'Lisans',
    soru: 'ABC eşkenar üçgeninde AB x eksenine paralel. d1 (0,12)\'den geçiyor. B\'nin apsisi 8. ABC eşkenar üçgeninin çevresi kaç birimdir?',
    secenekler: ['A) 12', 'B) 15', 'C) 16', 'D) 20', 'E) 24'],
    cevap: 4, aciklama: 'Çevre 24 birimdir. Doğru cevap E şıkkıdır.',
  },

  // GENEL KÜLTÜR - TARİH
  {
    id: 2017061, yil: 2017, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Türk töresinde hanedan erkeklerinin devlet yönetiminde ortak hak sahibi olması aşağıdakilerden hangisine yol açtığı savunulamaz?',
    secenekler: ['A) Hatunların idareye karışmasına', 'B) Dinî ayaklanmalara', 'C) Ülkenin parçalanmasına', 'D) Taht kavgalarına', 'E) Üst yöneticilerin müdahalesine'],
    cevap: 1, aciklama: 'Ortak hak sahipliği dinî değil siyasi çatışmalara yol açar. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2017062, yil: 2017, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Büyük Selçuklular döneminde Hasan Sabbah\'ın kurduğu ve önemli devlet adamlarına suikastlar düzenleyen gizli örgütün mensupları için kullanılan yaygın ifade hangisidir?',
    secenekler: ['A) Haşhaşîler', 'B) Babaîler', 'C) Kalenderîler', 'D) Selefîler', 'E) Hâricîler'],
    cevap: 0, aciklama: 'Hasan Sabbah\'ın örgütü Haşhaşîler olarak bilinir. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2017063, yil: 2017, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Gazneliler Devleti başka bir İslam devletine hizmet eden Türk komutanlar tarafından kurulmuştur. Hangi devlet bu kuruluş biçimiyle benzerlik gösterir?',
    secenekler: ['A) Büyük Selçuklu Devleti', 'B) Karahanlı Devleti', 'C) Altınordu Devleti', 'D) Tolunoğulları Devleti', 'E) Babürlüler Devleti'],
    cevap: 3, aciklama: 'Tolunoğulları Abbasi hizmetindeki Türk komutan tarafından kurulmuştur. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2017064, yil: 2017, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Osmanlı şehirlerinde ham madde ve temel ihtiyaç maddelerinin toptan satışının yapıldığı yere ne ad verilirdi?',
    secenekler: ['A) İmaret', 'B) Zaviye', 'C) Menzil', 'D) Kapan', 'E) Kervansaray'],
    cevap: 3, aciklama: 'Bu yer "kapan" olarak adlandırılırdı. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2017065, yil: 2017, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Osmanlı padişahlarının kıyafet değiştirerek halkı denetlemesinden hareketle hangisini hedeflemedikleri söylenebilir?',
    secenekler: ['A) Halk arasındaki söylentileri öğrenmeyi', 'B) Görevlilerin davranışlarını gözlemlemeyi', 'C) Ekonomik yapıyı doğrudan güçlendirmeyi', 'D) Olan bitenden haberdar oldukları algısını yaratmayı', 'E) Adil yönetim sağlamayı'],
    cevap: 2, aciklama: 'Ekonomik yapıyı güçlendirmek doğrudan amaç değildir. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2017066, yil: 2017, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Mimar Sinan\'ın ustalık eseri olarak kabul edilen yapı hangisidir?',
    secenekler: ['A) Şehzadebaşı Camii', 'B) Selimiye Camii', 'C) Süleymaniye Camii', 'D) Revan Köşkü', 'E) Topkapı Sarayı'],
    cevap: 1, aciklama: 'Selimiye Camii Mimar Sinan\'ın ustalık eseridir. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2017067, yil: 2017, ders: 'Tarih', seviye: 'Lisans',
    soru: 'XVI. yüzyıl sonlarında yaşanan nüfus artışı ve kapısız kalan sekbanların yarattığı sorunların sonuçlarıyla ilgili hangisi ileri sürülemez?',
    secenekler: ['A) Taşrada asayiş ve güvenliğin sağlandığı', 'B) Timarlı sipahilerin öneminin azaldığı', 'C) Devletin askerî alanda yenilik yapması gerektiği', 'D) Kırdan kente göçün yaşandığı', 'E) Kuvvetli beylerin önem kazandığı'],
    cevap: 0, aciklama: 'Kapısız sekbanlar taşrada güvensizlik yarattı; güvenliği sağlamadı. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2017068, yil: 2017, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Osmanlı\'da XVII. yüzyılda timar sisteminin bozulmasına bağlı olarak aşağıdaki gelişmelerden hangisi yaşanmıştır?',
    secenekler: ['A) Yeniçeri sayısının azaldığı', 'B) Ekberiyyet usulüne geçildiği', 'C) Tarımsal ürün çeşitliliğinin arttığı', 'D) Müsadere uygulamasının genişlediği', 'E) İltizam sisteminin yaygınlaştığı'],
    cevap: 4, aciklama: 'Timar sisteminin bozulması iltizam sistemini yaygınlaştırdı. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2017069, yil: 2017, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Osmanlı\'nın XVIII. yüzyıldan itibaren Avrupa başkentlerinde daimi elçilik açmasında hangileri etkili olmuştur?\nI. Avrupalı devletler karşısında yenilgiler\nII. Merkezi otoritenin bozulması ve isyanlar\nIII. Denge politikası izleme ihtiyacı',
    secenekler: ['A) Yalnız I', 'B) Yalnız II', 'C) I ve II', 'D) I ve III', 'E) II ve III'],
    cevap: 3, aciklama: 'I ve III etkili olmuştur. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2017070, yil: 2017, ders: 'Tarih', seviye: 'Lisans',
    soru: 'II. Mahmut Dönemi\'ndeki yeniliklere ilişkin verilen bilgilerden hangisine ulaşılamaz?',
    secenekler: ['A) Islahatların halkın isteğiyle gerçekleştiğine', 'B) Devlet bürokrasisinde değişikliklere gidildiğine', 'C) Islahatlar için uygun ortamın hazırlandığına', 'D) Merkezi yapının güçlendirilmesine önem verildiğine', 'E) Yeniliklerin kamuoyuna duyurulduğuna'],
    cevap: 0, aciklama: 'Islahatların halkın talebiyle yapıldığı bilgisi verilmemiştir. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2017071, yil: 2017, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Islahat Fermanı\'nın amaçlarından biri değildir?',
    secenekler: ['A) Gayrimüslimlere Müslümanlarla eşit statü vermek', 'B) Devlet dairelerinde gayrimüslimlerin çalışmasına izin vermek', 'C) Dinî gerilimleri azaltmak', 'D) Devlet düzeninde laiklik ilkelerini yerleştirmek', 'E) Toplumsal yükümlülükleri tüm kesimlere yaymak'],
    cevap: 3, aciklama: 'Islahat Fermanı laikliği yerleştirmeyi amaçlamamıştır. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2017072, yil: 2017, ders: 'Tarih', seviye: 'Lisans',
    soru: 'İngilizlerin Araplara halifeliği sahiplenmeleri yönündeki telkininin sebebi olamaz?',
    secenekler: ['A) Halifeliği kendi çıkarları doğrultusunda kullanmak', 'B) Osmanlı\'nın gücünü kırmak', 'C) Ortadoğu\'da yeni siyasi yapı oluşturmak', 'D) Arapları tek devlet altında birleştirmek', 'E) Sömürge yollarının güvenliğini sağlamak'],
    cevap: 3, aciklama: 'İngiltere Arapları birleştirmeyi değil bölmeyi hedefliyordu. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2017073, yil: 2017, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Misakımillî kararları göz önüne alındığında aşağıdakilerden hangisine ulaşılamaz?',
    secenekler: ['A) Uluslararası ilişkilerde eşitlik ilkesinin gözetildiğine', 'B) Halkın isteklerine öncelik verildiğine', 'C) Tam bağımsızlık ilkesinin kabul edildiğine', 'D) Vatanın sınırlarının çizildiğine', 'E) Boğazlar kararının Milletler Cemiyeti\'ne bırakıldığına'],
    cevap: 4, aciklama: 'Boğazlar kararının Milletler Cemiyeti\'ne bırakılmadığı çıkarılabilir. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2017074, yil: 2017, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Mustafa Kemal\'in görevden azledilip istifa etmesinden hangisine ulaşılamaz?',
    secenekler: ['A) İstanbul\'daki bazı çevrelerden farklı düşündüğüne', 'B) Mondros koşullarını hafifletmek istediğine', 'C) Anadolu merkezli direniş kurmak istediğine', 'D) Makam peşinde koşmadığına', 'E) İşgal güçlerinin beklentilerini aştığına'],
    cevap: 1, aciklama: 'Mondros koşullarını hafifletme isteği parçadan çıkarılamaz. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2017075, yil: 2017, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Vahdettin\'in Ali Rıza Paşa\'ya görevi vermesinin gerekçeleri arasında hangisi yer almaz?',
    secenekler: ['A) Temsil Heyetini İstanbul\'da etkili kılmak', 'B) Birlik ve beraberliği güçlendirmek', 'C) Düzen ve sükûneti sağlamak', 'D) Seçimleri yasal çerçevede yapmak', 'E) Millî hareket destekçileriyle iyi ilişkiler kurmak'],
    cevap: 0, aciklama: 'Temsil Heyetini güçlendirmek Vahdettin\'in amacı değildi. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2017076, yil: 2017, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Birinci TBMM\'nin olağanüstü yetkilere sahip olduğuna kanıt hangileridir?\nI. Yasama, yürütme ve yargıyı elinde tutması\nII. Yetkilerini Başkomutanlık Yasasıyla Mustafa Kemal\'e devretmesi\nIII. Çoğulcu yapıya sahip olması',
    secenekler: ['A) Yalnız I', 'B) Yalnız II', 'C) I ve II', 'D) I ve III', 'E) II ve III'],
    cevap: 2, aciklama: 'I ve II kanıt olarak gösterilebilir. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2017077, yil: 2017, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Lozan Konferansı\'na katılan devletler ve katılım konuları dikkate alındığında hangisine ulaşılamaz?',
    secenekler: ['A) Daveti Anlaşma Devletleri gönderdi.', 'B) Türkiye ve bazı Balkan devletleri tüm görüşmelere katıldı.', 'C) Avrupa dışından da devletler davet edildi.', 'D) Boğazlar konusuna çağrılacak devletlerde coğrafi konum belirleyiciydi.', 'E) Ticaret kurallarını Belçika ve Portekiz belirledi.'],
    cevap: 4, aciklama: 'Belçika ve Portekiz ticaret kurallarını belirlemek için değil sözleşmelere katılmak için davet edildi. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2017078, yil: 2017, ders: 'Tarih', seviye: 'Lisans',
    soru: '"Ordular, ilk hedefiniz Akdeniz\'dir. İleri!" emrinin verilmesinde hangileri etkili olmuştur?\nI. Güney Cephesi\'ndeki işgalleri sona erdirmek\nII. Batı Anadolu\'daki işgalleri bitirmek\nIII. Yunan ordusunun yeni savunma hattı kurmasını engellemek',
    secenekler: ['A) Yalnız I', 'B) Yalnız II', 'C) Yalnız III', 'D) I ve II', 'E) II ve III'],
    cevap: 4, aciklama: 'II ve III bu emrin verilmesinde etkili olmuştur. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2017079, yil: 2017, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Gümrü Antlaşması\'nın maddelerinden hareketle hangisine ulaşılamaz?',
    secenekler: ['A) Askerî ve siyasi konuların dışındaki hükümlere yer verildiğine', 'B) Erivan ve TBMM hükümetlerinin birbirini tanıdığına', 'C) Ermenilerin Türk topraklarındaki taleplerinden vazgeçtiğine', 'D) Türkiye\'nin doğu sınırını belirleyen son antlaşma olduğuna', 'E) Ermenistan\'daki Müslüman halkın haklarının korunduğuna'],
    cevap: 3, aciklama: 'Gümrü\'nün son antlaşma olduğu bilgisi çıkarılamaz. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2017080, yil: 2017, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Mustafa Kemal\'in imzasını değiştirmesinde etkili olan gelişme hangisidir?',
    secenekler: ['A) Latin harfli Türk alfabesinin kabulü', 'B) Laikliğin anayasaya girmesi', 'C) TBMM\'nin Gazi unvanı vermesi', 'D) Türk Dil Kurumu\'nun açılması', 'E) TBMM\'nin soyadı vermesi'],
    cevap: 4, aciklama: 'Soyadı Kanunu ve "Atatürk" soyadının alınması imzanın değişmesine yol açtı. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2017081, yil: 2017, ders: 'Tarih', seviye: 'Lisans',
    soru: '1927 seçim koşullarındaki milletvekillerinin ekonomik faaliyetlerine ilişkin maddenin amacı hangisidir?',
    secenekler: ['A) Milletvekillerinin nüfuzlarını kullanarak çıkar sağlamasını önlemek', 'B) Meclis devamını düzenlemek', 'C) Katkılarını siyasi alanla sınırlamak', 'D) Milletvekilliğinin ayrıcalığını göstermek', 'E) Maaşların yetersizliğine dikkat çekmek'],
    cevap: 0, aciklama: 'Milletvekillerinin nüfuz kullanarak çıkar sağlamasının önlenmesi amaçlanmıştır. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2017082, yil: 2017, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Atatürk Dönemi\'ndeki gelişmeler ile hangi ilke arasında ilişki kurulamaz?',
    secenekler: ['A) Halkçılık', 'B) Laiklik', 'C) Devletçilik', 'D) Cumhuriyetçilik', 'E) Milliyetçilik'],
    cevap: 2, aciklama: 'Devletçilik verilen gelişmelerle doğrudan ilişkilendirilemez. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2017083, yil: 2017, ders: 'Tarih', seviye: 'Lisans',
    soru: 'İngiltere\'nin Musul politikası için başvurmadığı yol hangisidir?',
    secenekler: ['A) Casusluk faaliyetleri', 'B) Halk oylaması sağlamak', 'C) Milletler Cemiyetini kullanmak', 'D) Etnik ve dinsel farklılıklardan yararlanmak', 'E) Türkiye\'ye askerî tehdit uygulamak'],
    cevap: 1, aciklama: 'Musul\'da halk oylaması İngiltere\'nin başvurduğu bir yol değildi. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2017084, yil: 2017, ders: 'Tarih', seviye: 'Lisans',
    soru: '1938 Türk-Sovyet Antlaşması kapsamındaki konsolosluk kapatmalarından hangisine ulaşılabilir?',
    secenekler: ['A) Karşılıklılık ilkesiyle hareket ettiklerine', 'B) Dünya gelişmelerinin dışında kaldıklarına', 'C) İlişkilerin giderek güçlendiğine', 'D) Sovyetler\'in yayılmacı politika uyguladığına', 'E) Farklı bloklarda yer aldıklarına'],
    cevap: 0, aciklama: 'Karşılıklı konsolosluk kapatmaları karşılıklılık ilkesini göstermektedir. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2017085, yil: 2017, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Yalta Konferansı bildirisinde yer almayan ilke hangisidir?',
    secenekler: ['A) Nazizm ve Faşizm kalıntılarını ortadan kaldırmak', 'B) Demokratik kurumları desteklemek', 'C) Toplumlara yönetim biçimini seçme hakkı vermek', 'D) Zorla alınan egemenlik haklarını iade etmek', 'E) Temel hakları sınırlandırma konusunda devletleri serbest bırakmak'],
    cevap: 4, aciklama: 'Temel hakları sınırlandırma Yalta ilkeleri arasında değildir. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2017086, yil: 2017, ders: 'Tarih', seviye: 'Lisans',
    soru: 'II. Dünya Savaşı sonrası Avrupa\'daki sosyal ve ekonomik gelişmelerden biri değildir?',
    secenekler: ['A) Kadınların iş hayatına daha fazla katılması', 'B) Nüfus artışı', 'C) Askerî harcamaların artması', 'D) SSCB tarafından ilk uydunun uzaya gönderilmesi', 'E) Radyonun günlük hayatta kullanılmaya başlanması'],
    cevap: 4, aciklama: 'Radyonun kullanımı savaş öncesine aittir. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2017087, yil: 2017, ders: 'Tarih', seviye: 'Lisans',
    soru: '1992-1995 Bosna Savaşı\'nda bağımsızlık mücadelesini yöneten ve "Bilge Lider" olarak anılan devlet başkanı kimdir?',
    secenekler: ['A) Ebulfeyz Elçibey', 'B) Enver Hoca', 'C) Sadık Ahmet', 'D) Aliya İzzetbegoviç', 'E) Saparmurad Niyazov'],
    cevap: 3, aciklama: 'Aliya İzzetbegoviç "Bilge Lider" olarak anılmaktadır. Doğru cevap D şıkkıdır.',
  },

  // COĞRAFYA
  {
    id: 2017088, yil: 2017, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Aşağıdakilerden hangisi Türkiye\'nin özel konumuyla ilgilidir?',
    secenekler: ['A) Dört mevsimin belirgin yaşanması', 'B) Karadeniz\'in Akdeniz\'den daha soğuk olması', 'C) Ankara\'nın Erzurum\'dan daha sıcak olması', 'D) Diyarbakır\'da güney rüzgârlarının sıcaklığı artırması', 'E) Antalya\'nın İstanbul\'dan daha sıcak olması'],
    cevap: 0, aciklama: 'Türkiye\'nin özel konumu dört mevsimin belirgin yaşanmasını sağlar. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2017089, yil: 2017, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Ağaç türleri ile yaygın görüldüğü iklim eşleştirmelerinden hangisi yanlıştır?\nI. Kızılçam - Akdeniz İklimi\nII. Sedir - Karasal İklim\nIII. Kayın - Karadeniz İklimi',
    secenekler: ['A) Yalnız I', 'B) Yalnız II', 'C) Yalnız III', 'D) I ve II', 'E) II ve III'],
    cevap: 1, aciklama: 'Sedir Akdeniz iklimine özgüdür, karasal değil. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2017090, yil: 2017, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Aşağıdakilerden hangisi Türkiye\'deki set göllerinden değildir?',
    secenekler: ['A) Büyük Çekmece Gölü', 'B) Köyceğiz Gölü', 'C) Uzungöl', 'D) Beyşehir Gölü', 'E) Tortum Gölü'],
    cevap: 3, aciklama: 'Beyşehir Gölü tektonik kökenlidir. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2017091, yil: 2017, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'İstanbul ve Çanakkale Boğazlarından Akdeniz\'e çıkış imkânı bulunmayan ülke hangisidir?',
    secenekler: ['A) Azerbaycan', 'B) Rusya', 'C) Romanya', 'D) Ukrayna', 'E) Gürcistan'],
    cevap: 0, aciklama: 'Azerbaycan\'ın Karadeniz\'e kıyısı yoktur. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2017092, yil: 2017, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Doğu Karadeniz kıyı kuşağı hakkında doğru ifadeler hangileridir?\nI. Yayvan yapraklı ormanlar geniş yer tutar.\nII. Yüksek ve engebeli araziler azdır.\nIII. Yağışlar genellikle yağmur şeklindedir.\nIV. Akarsular menderesler yaparak akar.',
    secenekler: ['A) I ve II', 'B) I ve III', 'C) II ve III', 'D) II ve IV', 'E) III ve IV'],
    cevap: 1, aciklama: 'I ve III doğrudur. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2017093, yil: 2017, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Türkiye\'deki yaşlı temel (masif) arazilerle ilgili hangisi doğrudur?',
    secenekler: ['A) Yalnızca Doğu Anadolu\'da bulunurlar.', 'B) Tümü kıvrımlı dağ kuşaklarında yer alır.', 'C) Kuzey Anadolu Dağları ve Torosların oluşmasından önce var olan eski kara kütleleridir.', 'D) Türkiye\'nin en genç jeolojik birimleridir.', 'E) Volkanik kökenlidirler.'],
    cevap: 2, aciklama: 'Yaşlı temel araziler (masifler), Alpin orojenezinden önce var olan eski kara parçalarıdır; Türkiye\'de Kırşehir, Menderes ve Bitlis masiflerinde gözlemlenir. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2017094, yil: 2017, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Türkiye\'nin nüfus özellikleriyle ilgili doğru ifade hangisidir?',
    secenekler: ['A) Nüfus ülke genelinde dengeli dağılmıştır.', 'B) Çatalca-Kocaeli yöresinde nüfus yoğunluğu azdır.', 'C) Taşeli Platosu nüfus yoğunluğunun fazla olduğu alanlardan biridir.', 'D) Nüfusun büyük bölümü kırsal kesimde yaşamaktadır.', 'E) Karadeniz\'e kıyısı olan illerde nüfus kıyı kuşağında yoğunlaşmıştır.'],
    cevap: 4, aciklama: 'Karadeniz\'de nüfus kıyı şeridinde yoğundur. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2017095, yil: 2017, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Yaylacılık faaliyetleri bakımından en az gelişmiş alan hangisidir?',
    secenekler: ['A) Orta Toros Dağları', 'B) Erzurum-Kars Platosu', 'C) Bozdağlar', 'D) Yıldız Dağları', 'E) Zigana Dağları'],
    cevap: 2, aciklama: 'Bozdağlar yaylacılık için elverişli değildir. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2017096, yil: 2017, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Nüfus artışı demir-çelik sanayisiyle gerçekleşen il hangisidir?',
    secenekler: ['A) Soma', 'B) İskenderun', 'C) Elbistan', 'D) Tunçbilek', 'E) Seydişehir'],
    cevap: 1, aciklama: 'İskenderun demir-çelik sanayisiyle nüfusu artan kenttir. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2017097, yil: 2017, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Türkiye\'nin büyük bölümünde yetişen, Isparta ve Antalya\'nın üretimde öne çıktığı ve sanayide ham madde olarak kullanılan tarım ürünü hangisidir?',
    secenekler: ['A) Armut', 'B) Üzüm', 'C) Elma', 'D) Gül', 'E) Kayısı'],
    cevap: 2, aciklama: 'Elma geniş üretim alanı ve ihracatıyla öne çıkmaktadır. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2017098, yil: 2017, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Türkiye\'nin enerji üretiminde en büyük paya sahip kaynak hangisidir?',
    secenekler: ['A) Biyokütle', 'B) Hidrolik', 'C) Kömür', 'D) Petrol', 'E) Jeotermal'],
    cevap: 2, aciklama: 'Kömür Türkiye\'nin enerji üretiminde en büyük paya sahiptir. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2017099, yil: 2017, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Jeotermal enerji potansiyeli daha düşük olan il hangisidir?',
    secenekler: ['A) Denizli', 'B) Çanakkale', 'C) Aydın', 'D) Antalya', 'E) Manisa'],
    cevap: 3, aciklama: 'Antalya jeotermal potansiyel bakımından düşük bir ildedir. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2017100, yil: 2017, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Türkiye\'de varlığı belirlenen altın madeni yatağı hangisidir?',
    secenekler: ['A) Kastamonu-Küre', 'B) Artvin-Cerattepe', 'C) Konya-Seydişehir', 'D) Elazığ-Maden', 'E) Kütahya-Emet'],
    cevap: 1, aciklama: 'Artvin-Cerattepe önemli bir altın yatağıdır. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2017101, yil: 2017, ders: 'Coğrafya', seviye: 'Lisans',
    soru: '2007\'de açılan ve 211 km\'si Türkiye\'den geçen doğal gaz boru hattı projesi hangisidir?',
    secenekler: ['A) Bakü-Tiflis-Ceyhan', 'B) Mavi Akım', 'C) Türkiye-Yunanistan-İtalya Boru Hattı', 'D) Trans Anadolu Doğalgaz', 'E) Trans Hazar'],
    cevap: 2, aciklama: 'Türkiye-Yunanistan-İtalya Boru Hattı 2007\'de açılmıştır. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2017102, yil: 2017, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Türkiye-İran sınırına ait özellikler hangileridir?\nI. En uzun kara sınırı\nII. En eski belirlenen sınır\nIII. Büyük kısmı su bölümü çizgilerinden geçer',
    secenekler: ['A) Yalnız I', 'B) Yalnız II', 'C) Yalnız III', 'D) I ve II', 'E) II ve III'],
    cevap: 4, aciklama: 'II ve III Türkiye-İran sınırına aittir. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2017103, yil: 2017, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Turistik mekân - il eşleştirmelerinden hangisi yanlıştır?',
    secenekler: ['A) Ahlat Kümbetleri - Bitlis', 'B) Balıklı Göl - Adıyaman', 'C) İnce Minare Medresesi - Konya', 'D) Selimiye Camii - Edirne', 'E) Ani Harabeleri - Kars'],
    cevap: 1, aciklama: 'Balıklı Göl Adıyaman\'da değil Şanlıurfa\'dadır. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2017104, yil: 2017, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Türkiye\'nin batı kesiminde sanayinin daha gelişmiş olması hangileriyle ilişkilidir?\nI. Ulaşım olanaklarının elverişliliği\nII. Nitelikli iş gücünün fazlalığı\nIII. Enerji üretiminin fazlalığı',
    secenekler: ['A) Yalnız I', 'B) Yalnız II', 'C) Yalnız III', 'D) I ve II', 'E) II ve III'],
    cevap: 3, aciklama: 'I ve II belirleyici faktörlerdir. Doğru cevap D şıkkıdır.',
  },

  // VATANDAŞLIK
  {
    id: 2017105, yil: 2017, ders: 'Vatandaşlık', seviye: 'Lisans',
    soru: 'Sahibine bir eşya üzerinde kullanma, yararlanma ve tasarruf yetkilerinin tamamını veren ayni hak hangisidir?',
    secenekler: ['A) Kiracılık hakkı', 'B) Mülkiyet hakkı', 'C) Rehin hakkı', 'D) Oturma hakkı', 'E) Zilyetlik'],
    cevap: 1, aciklama: 'Mülkiyet hakkı bu yetkilerin tamamını sağlar. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2017106, yil: 2017, ders: 'Vatandaşlık', seviye: 'Lisans',
    soru: 'Kanunlarla ilgili aşağıdaki ifadelerden hangisi yanlıştır?',
    secenekler: ['A) Kanunlar kural olarak TBMM\'de kabulünün ertesi günü yürürlüğe girer.', 'B) Her milletvekili kanun teklif edebilir.', 'C) Kanun görüşülmesi için üye tam sayısının en az 1/3\'ü Genel Kurula katılmalıdır.', 'D) Kabulü için toplantıya katılanların salt çoğunluğunun oyu gerekir.', 'E) Kanun koyma yetkisi TBMM\'ye aittir.'],
    cevap: 0, aciklama: 'Kanunlar Resmî Gazete\'de yayımlandıktan 45 gün sonra yürürlüğe girer. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2017107, yil: 2017, ders: 'Vatandaşlık', seviye: 'Lisans',
    soru: 'Türk hukukuna göre kanuni hâkim güvencesini ifade eden seçenek hangisidir?',
    secenekler: ['A) Kimse yürürlükteki kanunun suç saymadığı bir fiilden cezalandırılamaz.', 'B) Kimseye suç işlediği zaman öngörülenden daha ağır ceza verilemez.', 'C) Kimse kendini suçlayan beyanda bulunmaya zorlanamaz.', 'D) Hukuka aykırı elde edilen bulgular delil sayılamaz.', 'E) Kimse kanunen tabi olduğu mahkemeden başka merciye çıkarılamaz.'],
    cevap: 4, aciklama: 'Kanuni hâkim güvencesi E şıkkında tanımlanmıştır. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2017108, yil: 2017, ders: 'Vatandaşlık', seviye: 'Lisans',
    soru: '1982 Anayasası\'na göre TBMM seçimleri hangi gerekçeyle ve en fazla ne kadar süreyle ertelenebilir?',
    secenekler: ['A) Sıkıyönetim - 6 ay', 'B) Seferberlik - 3 ay', 'C) Olağanüstü hâl - 1 yıl', 'D) Savaş - 1 yıl', 'E) Yakın savaş tehdidi - 6 ay'],
    cevap: 3, aciklama: 'Savaş gerekçesiyle en fazla 1 yıl ertelenebilir. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2017109, yil: 2017, ders: 'Vatandaşlık', seviye: 'Lisans',
    soru: 'Olağanüstü hâl ilanının hukuki sonuçları arasında yer almayan seçenek hangisidir?',
    secenekler: ['A) Para, mal ve çalışma yükümlülükleri getirilebilir.', 'B) Temel hakların kullanımı durdurulabilir.', 'C) Olağanüstü hâlin gerektirdiği konularda KHK çıkarılabilir.', 'D) Genel mahkemelerin yargı yetkisi devam eder.', 'E) Kolluk yetkileri askerî makamlara geçer.'],
    cevap: 4, aciklama: 'Olağanüstü hâlde kolluk yetkileri askerî makamlara geçmez. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2017110, yil: 2017, ders: 'Vatandaşlık', seviye: 'Lisans',
    soru: '1982 Anayasası\'na göre cumhurbaşkanlığına Meclis dışından aday gösterilebilmesi için en az kaç milletvekilinin yazılı teklifi gerekir?',
    secenekler: ['A) 10', 'B) 20', 'C) 25', 'D) 30', 'E) 45'],
    cevap: 1, aciklama: 'En az 20 milletvekili. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2017111, yil: 2017, ders: 'Vatandaşlık', seviye: 'Lisans',
    soru: 'Türk idare hukukunda il özel idaresinin başı ve tüzel kişiliğinin temsilcisi kimdir?',
    secenekler: ['A) Vali', 'B) İl genel meclisi başkanı', 'C) Belediye başkanı', 'D) İl encümeni', 'E) En kıdemli kaymakam'],
    cevap: 0, aciklama: 'Vali il özel idaresinin başıdır. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2017112, yil: 2017, ders: 'Vatandaşlık', seviye: 'Lisans',
    soru: 'Danıştay incelemesinden geçirilerek kanunun uygulanmasını göstermek üzere çıkarılan hukuki metin hangisidir?',
    secenekler: ['A) Tüzük', 'B) Yönetmelik', 'C) Sirküler', 'D) Genelge', 'E) Statü'],
    cevap: 0, aciklama: 'Tüzük Danıştay\'dan geçirilerek çıkarılır. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2017113, yil: 2017, ders: 'Vatandaşlık', seviye: 'Lisans',
    soru: 'Türk hukukunda kamu başdenetçisi kimler tarafından seçilir?',
    secenekler: ['A) Bakanlar Kurulu', 'B) Cumhurbaşkanı', 'C) Halk', 'D) Anayasa Mahkemesi', 'E) TBMM'],
    cevap: 4, aciklama: 'Kamu başdenetçisi TBMM tarafından seçilir. Doğru cevap E şıkkıdır.',
  },

  // GÜNCEL BİLGİLER
  {
    id: 2017114, yil: 2017, ders: 'Güncel Bilgiler', seviye: 'Lisans',
    soru: '1986\'da yaşanan nükleer kazayla ünlenen Çernobil günümüzde hangi ülkenin sınırları içindedir?',
    secenekler: ['A) Rusya', 'B) Beyaz Rusya', 'C) Ukrayna', 'D) Romanya', 'E) Ermenistan'],
    cevap: 2, aciklama: 'Çernobil Ukrayna\'dadır. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2017115, yil: 2017, ders: 'Güncel Bilgiler', seviye: 'Lisans',
    soru: 'Aşağıdakilerden hangisi 1989\'dan önce il statüsü kazanmıştır?',
    secenekler: ['A) Nevşehir', 'B) Batman', 'C) Karabük', 'D) Iğdır', 'E) Bayburt'],
    cevap: 0, aciklama: 'Nevşehir 1954\'te il olmuştur. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2017116, yil: 2017, ders: 'Güncel Bilgiler', seviye: 'Lisans',
    soru: '20 Temmuz 1974\'teki Kıbrıs Barış Harekâtı sırasında Türkiye Cumhuriyeti Başbakanlığı görevini kim yürütüyordu?',
    secenekler: ['A) Ferit Melen', 'B) Süleyman Demirel', 'C) Nihat Erim', 'D) Bülent Ecevit', 'E) Necmettin Erbakan'],
    cevap: 3, aciklama: 'Başbakan Bülent Ecevit\'ti. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2017117, yil: 2017, ders: 'Güncel Bilgiler', seviye: 'Lisans',
    soru: '17. yüzyılda Babürlüler döneminde inşa edilen Tac Mahal hangi ülkede yer almaktadır?',
    secenekler: ['A) Pakistan', 'B) Hindistan', 'C) İran', 'D) Afganistan', 'E) Türkmenistan'],
    cevap: 1, aciklama: 'Tac Mahal Hindistan\'dadır. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2017118, yil: 2017, ders: 'Güncel Bilgiler', seviye: 'Lisans',
    soru: '15 Temmuz 2016 darbe girişimine karşı verdiği mücadele nedeniyle adına "Kahraman" ibaresi eklenen ilçenin önceki adı ve bağlı olduğu il aşağıdakilerin hangisinde doğru verilmiştir?',
    secenekler: ['A) Fatih, İstanbul', 'B) Kazan, Ankara', 'C) Marmaris, Muğla', 'D) Battalgazi, Malatya', 'E) Adapazarı, Sakarya'],
    cevap: 1, aciklama: 'Kazan (Ankara) Kahramankazan adını almıştır. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2017119, yil: 2017, ders: 'Güncel Bilgiler', seviye: 'Lisans',
    soru: '2016 yılında kamu yatırımları arasında en büyük paya sahip olan sektör hangisidir?',
    secenekler: ['A) Eğitim', 'B) Sağlık', 'C) Ulaştırma', 'D) Enerji', 'E) Tarım'],
    cevap: 2, aciklama: '2016\'da kamu yatırımlarında en büyük pay ulaştırmaya aittir. Doğru cevap C şıkkıdır.',
  },
];