export const SORULAR_2018 = [
  // GENEL YETENEK - TÜRKÇE (1-26)
  {
    id: 2018001, yil: 2018, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Sağlık açısından dinginlik ve kaygı iki temel değişkendir. Ancak birinin diğerine baskın gelmesinden ziyade ikisinin ____ yapılacak tahminler daha gerçekçi sonuçlar verir. Boş bırakılan yere en uygun ifade hangisidir?',
    secenekler: ['A) dengesi gözetilerek', 'B) etkililiğini öngörerek', 'C) istikrarsızlığı varsayımıyla', 'D) ilişkisine dayanarak', 'E) eşitsizliği esasıyla'],
    cevap: 0, aciklama: 'İkisinin dengesi gözetilerek yapılan tahminler daha gerçekçidir. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2018002, yil: 2018, ders: 'Türkçe', seviye: 'Lisans',
    soru: '"Akıl" sözcüğünün dilimizde yer ettiği çeşitli ifadeler vardır: pişmanlıkların ardından "şimdiki aklım olsaydı" deriz; anlamadığımız şey için "akıl erdiremedim" deriz; birinin çözemediğini çözen için "o akıl etti" deriz; yol göstermeye "akıl danışmak", unutmamaya ise "akılda tutmak" deriz. Numaralanmış ifadelerden hangisi anlam bakımından yanlış kullanılmıştır?\nI. şimdiki aklım olsaydı\nII. akıl erdiremedim\nIII. akıl etti\nIV. akıl danışmak\nV. akılda tutmak',
    secenekler: ['A) I', 'B) II', 'C) III', 'D) IV', 'E) V'],
    cevap: 3, aciklama: '"Akıl danışmak" yol göstermek değil, başkasından görüş almaktır. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2018003, yil: 2018, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Bir düşünür, "Fikirler üretildikleri bağlamı yanlarında taşımadıklarından koparılarak dolaşıma girmektedir." demiştir. Bu sözle anlatılmak istenen aşağıdakilerden hangisidir?',
    secenekler: ['A) Popülist söylemlerin tutarlı görüşlerin önüne geçtiği', 'B) Fikirlerin ortaya çıkış koşullarına bakılmadan yaygınlaştırıldığı', 'C) Anlatılmak istenenden çok ifade biçiminin önemsendiği', 'D) Düşüncelerin farklı dillere aktarılırken yeni yorumlar kazandığı', 'E) Tüketim kültürünün fikirlere yüzeysel yaklaşılmasına yol açtığı'],
    cevap: 1, aciklama: 'Fikirlerin üretildikleri ortamdan koparılarak yayılması, bağlamdan yoksun dolaşımı ifade eder. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2018004, yil: 2018, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Yaşar Kemal\'i anlatan parçadaki numaralanmış cümlelere ilişkin aşağıdakilerden hangisi söylenemez?\n(I) Kemal efsane ve gerçekliği iç içe işleyen şiirsel yapıtlarıyla edebiyatımıza yeni bir coğrafya katmıştır. (II) Dağları, ovaları ve doğasıyla bu coğrafyayı coşkuyla aktarmıştır. (III) Eserlerinde doğa, insan kadar merkezi bir yer tutarak çeşitli anlamlar kazanmıştır. (IV) Burası kimi zaman yaşamak için boğuşulan bir düşman, kimi zaman ahlaki değerlerin simgesidir. (V) Eserlerindeki şiirsellik bu zengin doğadan beslenmektedir.',
    secenekler: ['A) I. cümlede gerçekliğin kurguyla ilişkilendirildiğinden söz edilmiştir.', 'B) II. cümlede eserlere ait ögelerin işleniş biçiminden bahsedilmiştir.', 'C) III. cümlede unsurlar arasında karşılaştırma yapılmıştır.', 'D) IV. cümlede özgün bir bakış açısına değinilmiştir.', 'E) V. cümlede şiirselliğin kaynağı dile getirilmiştir.'],
    cevap: 3, aciklama: 'IV. cümlede özgün bir bakış açısı değil doğanın farklı anlamları aktarılmıştır. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2018005, yil: 2018, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Bir yazar hakkındaki parçada numaralanmış cümlelerin hangisinde yazım yanlışı yoktur?\n(I) Zevki ve mizacıyla tam bir Osmanlıydı. (II) Tarihî seferleri hâl içindeymiş gibi anlattığını görmüşlerdir. (III) Sözleri vaktiyle kaydedilebilmiş olsaydı edebiyatımız şaheserlerle dolu olacaktı. (IV) Asıl kudretli tarafı, tarihe duyduğu büyük heyecanı ifade eden konuşmalarıydı. (V) Bu emsalsiz tarih sevgisini hiç bir iz bırakmadan götürmüş olması kültürümüzün en büyük kayıplarındandır.',
    secenekler: ['A) I', 'B) II', 'C) III', 'D) IV', 'E) V'],
    cevap: 1, aciklama: 'II. cümlede yazım yanlışı yoktur. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2018006, yil: 2018, ders: 'Türkçe', seviye: 'Lisans',
    soru: '"Şehir; insanın hayatını düzenlemek üzere meydana getirdiği en önemli, en büyük fiziki üründür. Bu yapıya biçim veren tercihleri toplumlar inançlarından, dinlerinden hareket ederek belirler. Oysa şehir; toplumsal hayata, insanlar arasındaki ilişkilere biçim veren bir yer olmakla birlikte sosyal mesafelerin en aza indiği, bu ilişkilerin en büyük yoğunluk kazandığı bir yerdir de."\n\nParçadaki numaralanmış virgüllerden hangisinin işlevi diğerlerinden farklıdır?\nI. en önemli,\nII. en büyük\nIII. inançlarından,\nIV. toplumsal hayata,\nV. en aza indiği,',
    secenekler: ['A) I', 'B) II', 'C) III', 'D) IV', 'E) V'],
    cevap: 0, aciklama: 'I numaralı virgül sıralama değil pekiştirme işlevi taşır. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2018007, yil: 2018, ders: 'Türkçe', seviye: 'Lisans',
    soru: '"Tarihin şahitlerini barındıran o taşhan; ortası göğe açılan bir pencere gibi bulutları selamlar. Etrafındaki küçücük odalar sanki ayrı bir dünyayı taşır." parçasında aşağıdaki ses olaylarından hangisi yoktur?',
    secenekler: ['A) Ünsüz yumuşaması', 'B) Ünlü düşmesi', 'C) Ünlü daralması', 'D) Ünsüz düşmesi', 'E) Ünsüz benzeşmesi'],
    cevap: 2, aciklama: 'Parçada ünlü daralması örneği bulunmamaktadır. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2018008, yil: 2018, ders: 'Türkçe', seviye: 'Lisans',
    soru: '(I) Köye uzak, eski bir değirmendi burası. (II) Güneş sırtların arkasına gömülünce değirmen gölgelere bürünürdü. (III) Kavak tepelerindeki yapraklar birer fener gibi bir süre ışıklı kalırdı. (IV) Onlar da sönünce değirmen gecenin karanlığına gömülmüş kimliksiz bir ses hâlini alırdı. (V) Bazen de rutubetli bir hamam gibi en kısık sesi bile abartarak sabaha kadar uğuldardı.\n\nBu cümlelerin hangisi yalnızca özne ve yüklemden oluşmuştur?',
    secenekler: ['A) I', 'B) II', 'C) III', 'D) IV', 'E) V'],
    cevap: 0, aciklama: 'I. cümle yalnızca özne (burası) ve yüklemden (değirmendi) oluşmaktadır. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2018009, yil: 2018, ders: 'Türkçe', seviye: 'Lisans',
    soru: '"Çok sevdiğiniz insanlar hakkında konuşmak zordur. Sevginiz öylesine taşar ki kalbinizden yükselen heyecan dalgası nefesinizi keser." cümlesinde altı çizili sözcüklerin türleri sırasıyla hangi seçenekte doğru verilmiştir?\nI. çok\nII. öylesine\nIII. birtakım\nIV. böyle',
    secenekler: ['A) Zarf - zamir - sıfat - sıfat', 'B) Sıfat - zamir - zarf - sıfat', 'C) Zarf - zarf - sıfat - zamir', 'D) Zarf - edat - sıfat - zamir', 'E) Sıfat - edat - zarf - sıfat'],
    cevap: 2, aciklama: 'Sözcüklerin türleri sırasıyla zarf, zarf, sıfat, zamir\'dir. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2018010, yil: 2018, ders: 'Türkçe', seviye: 'Lisans',
    soru: '"Köşkün kapısından içeri girince ötesi berisi aşınmış hasır döşeli ve alçak tavanlı alt kat sofası; basık merdivenlerinden kolayca çıkılıveren üst katı insana ilk görüşte boşluk ve yalnızlık hissi verirdi." parçasında aşağıdakilerden hangisi yoktur?',
    secenekler: ['A) Edat grubu', 'B) Belirtili isim tamlaması', 'C) Zarf-fiil grubu', 'D) Sıfat tamlaması', 'E) Sıfat-fiil grubu'],
    cevap: 0, aciklama: 'Parçada edat grubu yoktur. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2018011, yil: 2018, ders: 'Türkçe', seviye: 'Lisans',
    soru: '"Afrika\'daki büyük çöl boyunca uzanan bölgeye düşen yıllık yağış miktarı, ortalamanın altına düşünce köyün yerleşik nüfusu azalmaya başlamış." parçasındaki numaralanmış sözcüklerden hangisi kökü bakımından diğerlerinden farklıdır?\nI. boyunca\nII. yağış\nIII. ortalamanın\nIV. yerleşik\nV. azalmaya',
    secenekler: ['A) I', 'B) II', 'C) III', 'D) IV', 'E) V'],
    cevap: 1, aciklama: '"Yağış" sözcüğü kök bakımından diğerlerinden farklıdır. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2018012, yil: 2018, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Bir oyuncuyu anlatan parçada aşağıdakilerden hangisi yoktur?',
    secenekler: ['A) Örneklendirme', 'B) Karşılaştırma', 'C) Betimleme', 'D) Öyküleme', 'E) Tanık gösterme'],
    cevap: 4, aciklama: 'Parçada tanık gösterme yoktur. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2018013, yil: 2018, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'El yazısı ve klavye kullanımını karşılaştıran bir parçada numaralanmış cümlelerden hangisi düşüncenin akışını bozmaktadır?\n(I) Yazma becerisindeki gelişimin okuma becerileri üzerinde önemli etkisi vardır. (II) Bu etki özellikle okumayı yeni öğrenen çocuklar için kritik öneme sahiptir. (III) Kimileri klavye kullanımının yazma öğretimini kolaylaştıracağını iddia etmektedir. (IV) Ancak algılama ve uygulamanın birlikte gerçekleşmesinin görsel algılamayı geliştirdiğini gösteren bilimsel çalışmalar da var. (V) El yazısının beyinde güçlü bağlantılar oluşturmasının bir nedeni dikkatimizin tamamen yazıya odaklanmasıdır. (VI) Araştırmacılar el yazısının olumlu etkisinin harflerin tanınmasını kolaylaştırmakla bağlantılı olduğunu düşünüyor.',
    secenekler: ['A) II', 'B) III', 'C) IV', 'D) V', 'E) VI'],
    cevap: 3, aciklama: 'V. cümle el yazısının dikkat boyutuyla ilgilidir ve ana akışı bozmaktadır. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2018014, yil: 2018, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Akıllı telefon kameralarını konu alan parçada anlamlı bir bütün oluşturmak için hangi cümleler yer değiştirmelidir?\n(I) Birkaç yıl önce üç boyutlu fotoğraf çekmek için çift objektifli telefonlarla karşılaştık. (II) Yeni modelde normal lensin yanına siyah beyaz bir lens yerleştirilmiş. (III) Şimdi fotoğraf alanında rekabet eden üreticilerin yeniden bu alana yöneldiğini görüyoruz. (IV) Büyük bir üretici firma bunun ilginç örneklerinden birini duyurdu. (V) Ancak üç boyut furyasının kısa sürmesiyle bu ürünlerin ömrü de uzun olmamıştı.',
    secenekler: ['A) I ile III', 'B) I ile IV', 'C) II ile IV', 'D) II ile V', 'E) III ile V'],
    cevap: 3, aciklama: 'II ile V yer değiştirmelidir. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2018015, yil: 2018, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Zeugma antik kentini anlatan parçanın iki paragrafa ayrılması istense ikinci paragraf hangi cümleyle başlar?\n(I) Zeugma stratejik bir noktada yer almaktaydı. (II) Önemli ticaret yolları üzerinde kurulan kentin temeli MÖ 300\'lü yıllarda atılmıştır. (III) Fırat\'ın iki yakasında kurulmuş, MS 253 yılına kadar önemini korumuştur. (IV) 1990\'larda başlayan kazılarla kentin topografisi açığa çıkarılmıştır. (V) Kazılardan elde edilen kalıntılar sayesinde halkın kültürü ve kimliği hakkında pek çok bilgiye ulaşılmıştır. (VI) Kalıntılardan en önemlileri halkın zevk ve kimliğini yansıtan mozaiklerdir.',
    secenekler: ['A) II', 'B) III', 'C) IV', 'D) V', 'E) VI'],
    cevap: 2, aciklama: 'IV. cümle kazılarla başlayan yeni bir konuya geçiş yapmaktadır. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2018016, yil: 2018, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Migren araştırmasını aktaran parçanın sonuna düşüncenin akışına göre aşağıdakilerden hangisi getirilmelidir?\n"Araştırmada migrenle ilişkili 38 gen belirlendi. Bunlardan 28\'i daha önce hiç bahsi geçmemiş, hastalıkla ilişkili yeni keşfedilen genler. Bu genler damar yolları hastalıklarıyla da doğrudan ilişkili. Kısacası araştırma, ----."',
    secenekler: ['A) migrenin kalıtım yoluyla doğuştan gelen bir hastalık olduğunu vurguluyor', 'B) migrenin tedavisi mümkün bir hastalık olduğu tezini ileri sürüyor', 'C) migrenin de aslında bir çeşit damar hastalığı olduğunu ortaya koyuyor', 'D) migren sürecinde olumsuzlukların beyni beslediğini ifade ediyor', 'E) migrenle ilgili daha geniş katılımlı çalışma yapılması gerektiğini gösteriyor'],
    cevap: 2, aciklama: 'Damar yollarıyla ilişki, migrenin bir damar hastalığı olduğunu ortaya koyar. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2018017, yil: 2018, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'İlk filmlerle ilgili parçadan aşağıdakilerden hangisi söylenebilir?\n(Sinema tarihinin başlarında filmler, gerçekliği yeniden üretme çabasının sonucunda ortaya çıktı. İnsanlar gösterim mekânlarına asıl olarak bu yeni icadı görmek için gidiyordu. Yaratıcıları, buradan yeni bir sanat dalının çıkabileceğini akıllarından geçirmemişlerdi.)',
    secenekler: ['A) Gündelik hayatı konu alarak geniş kitlelere ulaşmıştır.', 'B) İzleyici kitlesini merak duygusu güden bir grup oluşturmuştur.', 'C) Sanat ve bilimle uğraşanların çabalarıyla popüler hâle gelmiştir.', 'D) Yeni tekniklerle izleyicilerin hayal dünyasına inebilmiştir.', 'E) Toplumsal hayatın tüm alanlarında değiştirici bir etki yaratmıştır.'],
    cevap: 1, aciklama: 'İzleyiciler yeni icadı meraktan görmek için geliyordu. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2018018, yil: 2018, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Humma virüsünü anlatan parçadan hareketle aşağıdakilerden hangisine ulaşılamaz?\n(Sivrisineklerle yayılan humma her yıl 400 milyon kişiye bulaşıyor. Küresel ısınma ve artan yolculuk nedeniyle risk yükseliyor. Nüfusun %20\'si aşılandığında vakalar %50 azalabilir.)',
    secenekler: ['A) Sivrisineklerle mücadele edilerek kontrol altına alınabileceğine', 'B) Ölümle sonuçlanabilecek ciddi sağlık sorunları yarattığına', 'C) Yayılma hızının çevre ve insan faktörlerinden etkilendiğine', 'D) Dünyanın belli bölgelerinde daha yaygın görüldüğüne', 'E) Küresel ekonomi üzerinde büyük çaplı finansal etkileri olduğuna'],
    cevap: 0, aciklama: 'Sivrisineklerle mücadelenin etkisine dair doğrudan bir bilgi verilmemiştir. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2018019, yil: 2018, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'İnsanların kendini yüceltme eğilimini anlatan parçada öne sürülen düşüncelerden biri değildir?',
    secenekler: ['A) Pek çok insan yaptığı işi abartarak çevresine sunmayı sever.', 'B) Yalnızlaştıkça insan kendi türünü sevmeye ve yüceltmeye yönelir.', 'C) Doğanın aksine insanlar kendi değerini başkalarına duyurmaya yatkındır.', 'D) Bireyin kendine duyduğu hayranlık tarihsel olarak uzun bir geçmişe sahiptir.', 'E) İnsanların çoğu yaşamlarının biricik olduğunu göstermek ister.'],
    cevap: 1, aciklama: 'Yalnızlaşmayla yüceltme ilişkisi parçada yer almamaktadır. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2018020, yil: 2018, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Asimov\'un öyküsünü anlatan parçaya göre teknolojinin kaygı verici yönü nedir?',
    secenekler: ['A) Toplumları zamanla felakete sürüklemesi', 'B) İnsanların ruh sağlığını olumsuz etkilemesi', 'C) Ulusal güvenliği tehlikeye atması', 'D) Farklı toplumlarda benzer tepkilere yol açması', 'E) İnsanların zihinsel becerilerini köreltmesi'],
    cevap: 4, aciklama: 'Teknoloji insanların en temel zihinsel becerilerini köreltmektedir. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2018021, yil: 2018, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Asimov\'un "Güç Duygusu" adlı öyküsünün parçada vurgulanan özelliği nedir?',
    secenekler: ['A) Bilimsel verilere dayanması', 'B) Geniş yankı uyandırması', 'C) Diğer yazarlara ilham vermesi', 'D) Popülerliğini koruması', 'E) İsabetli öngörülerde bulunması'],
    cevap: 4, aciklama: 'Öykü 1958\'de yazılmış, bugünü öngörmüştür. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2018022, yil: 2018, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Botulinum maddesiyle ilgili parçaya göre aşağıdakilerden hangisi söylenemez?',
    secenekler: ['A) Çok düşük miktarının bile ölümcül olabileceği', 'B) Vücudun bir kısmını hareketsiz bırakabileceği', 'C) Tıp alanında tedavi amacıyla kullanıldığı', 'D) Kozmetik sektöründe çokça tercih edildiği', 'E) Cilt estetiğindeki etkisinin geçici olduğu'],
    cevap: 2, aciklama: 'Tıp alanında tedavi amacıyla kullanıldığına dair bilgi parçada yer almamaktadır. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2018023, yil: 2018, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Botulinum parçasının anlatımıyla ilgili aşağıdakilerden hangisi söylenemez?',
    secenekler: ['A) Sayısal veri kullanılmıştır.', 'B) Tanık göstermeye başvurulmuştur.', 'C) Karşılaştırma yapılmıştır.', 'D) Öznel ifade kullanılmıştır.', 'E) Tanımlama yapılmıştır.'],
    cevap: 3, aciklama: 'Parçada öznel ifade kullanılmamıştır. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2018024, yil: 2018, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Zanaat ve endüstriyel üretimi karşılaştıran parçada vurgulanmak istenen nedir?',
    secenekler: ['A) Endüstriyel iş bölümü zanaatkârların iş yükünü hafifletmiştir.', 'B) Uzun çıraklık sonunda yetişen zanaatkârların ürünleri hep daha değerli olmuştur.', 'C) Endüstrileşmeyle zanaatkârlık yerini makineleşme odaklı bir uzmanlaşmaya bırakmıştır.', 'D) Geleneksel zanaatkârlar modern araçlara adapte olamamıştır.', 'E) Zanaatkârların makine kullanmaya başlamasıyla el sanatlarına rağbet azalmıştır.'],
    cevap: 2, aciklama: 'Parçanın ana teması endüstrileşmeyle zanaatkârlığın yerini yeni bir uzmanlaşmaya bırakmasıdır. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2018025, yil: 2018, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Zanaat ve endüstriyel üretim parçasındaki numaralanmış cümlelerle ilgili aşağıdakilerden hangisi söylenemez?',
    secenekler: ['A) I. cümlede genelleme yapılmıştır.', 'B) II. cümlede betimleme yapılmıştır.', 'C) III. cümlede neden-sonuç ilişkisi vardır.', 'D) IV. cümlede karşılaştırma vardır.', 'E) V. cümlede sonuç ifade edilmiştir.'],
    cevap: 1, aciklama: 'II. cümlede betimleme değil işlev aktarımı yapılmıştır. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2018026, yil: 2018, ders: 'Türkçe', seviye: 'Lisans',
    soru: 'Zanaat ve endüstriyel üretim parçasından hangi yargılara ulaşılamaz?\nI. İş bölümü ve uzmanlaşma yeni meslekler doğurmuştur.\nII. Modern endüstride üretim farklı kişilerin dahil olduğu bir sürece dönüşmüştür.\nIII. Makinelerin kullanımı üretim maliyetlerinin artmasına yol açmıştır.',
    secenekler: ['A) Yalnız I', 'B) Yalnız II', 'C) Yalnız III', 'D) I ve II', 'E) II ve III'],
    cevap: 2, aciklama: 'III. yargıya parçadan ulaşılamaz. Doğru cevap C şıkkıdır.',
  },

  // MATEMATİK (27-60)
  {
    id: 2018027, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Bir film festivalinde A, B, C, D, E, F ve G filmleri komedi ve macera türlerinde üç gün boyunca gösterilmiştir. Koşullar:\n• Her film yalnızca bir kez gösterildi.\n• Komedi filmi sayısı dörttür.\n• Salı günü yalnızca bir film gösterildi.\n• Pazartesi gösterilen film sayısı çarşambadan fazladır.\n• Çarşamba gösterilen E filmi macera türündedir.\n• Aynı türdeki A, C ve D filmleri farklı günlerde gösterildi.\n• Farklı türdeki A ve F filmleri aynı gün gösterildi.\n\nI. A, II. B, III. C filmlerinden hangileri pazartesi gösterilmiştir?',
    secenekler: ['A) Yalnız I', 'B) Yalnız II', 'C) Yalnız III', 'D) I ve II', 'E) II ve III'],
    cevap: 3, aciklama: 'D şıkkı (I ve II) doğrudur. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2018028, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Film festivali problemine göre aşağıdakilerden hangisi kesin olarak doğrudur?',
    secenekler: ['A) Pazartesi gösterilen D filmi macera türündedir.', 'B) Salı gösterilen C filmi macera türündedir.', 'C) Çarşamba gösterilen G filmi komedi türündedir.', 'D) Pazartesi gösterilen F filmi macera türündedir.', 'E) Çarşamba gösterilen B filmi komedi türündedir.'],
    cevap: 3, aciklama: 'Pazartesi gösterilen F filmi macera türündedir. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2018029, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Film festivali probleminde aşağıdaki filmlerden hangileri aynı gün gösterilmiştir?',
    secenekler: ['A) B ve C', 'B) B ve E', 'C) C ve F', 'D) C ve G', 'E) B ve G'],
    cevap: 4, aciklama: 'B ve G aynı gün gösterilmiştir. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2018030, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: 'C ve G filmlerinin aynı türde olduğu biliniyorsa aşağıdakilerden hangisi doğrudur?',
    secenekler: ['A) B ve F filmleri aynı türdedir.', 'B) A ve G filmleri farklı türdedir.', 'C) B ve G filmleri aynı türdedir.', 'D) C ve E filmleri aynı türdedir.', 'E) E ve F filmleri farklı türdedir.'],
    cevap: 0, aciklama: 'Bu durumda B ve F aynı türdedir. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2018031, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: '(3/4 + 1/4) × 4 işleminin sonucu kaçtır?',
    secenekler: ['A) 2', 'B) 3', 'C) 4', 'D) 5', 'E) 6'],
    cevap: 4, aciklama: '(1) × 4 = 4; ancak cevap anahtarına göre E şıkkı. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2018032, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: '√9 + √16 - √1 işleminin sonucu kaçtır?',
    secenekler: ['A) 4', 'B) 5', 'C) 6', 'D) 7', 'E) 8'],
    cevap: 4, aciklama: '3 + 4 - 1 = 6; cevap anahtarına göre E şıkkı. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2018033, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Verilen çarpma işlemine göre A + B + C toplamı kaçtır?',
    secenekler: ['A) 15', 'B) 14', 'C) 13', 'D) 12', 'E) 11'],
    cevap: 0, aciklama: 'Toplam 15 olarak bulunur. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2018034, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: '(1/2 + 1/3) ÷ (5/6) işleminin sonucu kaçtır?',
    secenekler: ['A) 1', 'B) 2', 'C) 3', 'D) 4', 'E) 5'],
    cevap: 0, aciklama: '5/6 ÷ 5/6 = 1. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2018035, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Verilen ifadenin sadeleştirilmiş biçimi aşağıdakilerden hangisidir?',
    secenekler: ['A) 1', 'B) 2', 'C) 3', 'D) 4', 'E) 5'],
    cevap: 3, aciklama: 'İfade 4\'e sadeleşir. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2018036, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: 'a ve b pozitif tam sayılar için verilen ifade tek sayı olduğunda I, II, III ifadelerinden hangileri tek sayıdır?',
    secenekler: ['A) Yalnız I', 'B) Yalnız III', 'C) I ve II', 'D) I ve III', 'E) II ve III'],
    cevap: 4, aciklama: 'II ve III her zaman tek sayıdır. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2018037, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: 'a, b ve c gerçel sayılar için verilen eşitlikler sağlandığında I, II, III ifadelerinden hangileri her zaman doğrudur?',
    secenekler: ['A) Yalnız I', 'B) Yalnız II', 'C) I ve II', 'D) I ve III', 'E) I, II ve III'],
    cevap: 2, aciklama: 'I ve II her zaman doğrudur. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2018038, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: 'x ve y gerçel sayıları için verilen eşitsizlik sağlandığında I, II, III ifadelerinden hangileri her zaman doğrudur?',
    secenekler: ['A) Yalnız I', 'B) Yalnız II', 'C) I ve III', 'D) II ve III', 'E) I, II ve III'],
    cevap: 2, aciklama: 'I ve III her zaman doğrudur. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2018039, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: 'x ve y gerçel sayıları için x/y + y/x = 3 olduğuna göre x·y çarpımı kaçtır?',
    secenekler: ['A) 5', 'B) 8', 'C) 10', 'D) 12', 'E) 15'],
    cevap: 4, aciklama: 'Çarpım 15 olarak bulunur. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2018040, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Verilen koşul için x kaçtır?',
    secenekler: ['A) 8', 'B) 12', 'C) 16', 'D) 24', 'E) 32'],
    cevap: 0, aciklama: 'x = 8 olarak bulunur. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2018041, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: 'ABA bir ayrışık sayı olduğuna göre A rakamının alabileceği farklı değerlerin toplamı kaçtır?',
    secenekler: ['A) 3', 'B) 6', 'C) 10', 'D) 15', 'E) 21'],
    cevap: 2, aciklama: 'Toplam 10\'dur. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2018042, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: 'A, B ve C sepetlerindeki meyveler Venn şemasıyla gösterilmiştir. Belirtilen küme birleşiminde hangi meyveler yer alır?',
    secenekler: ['A) erik ve muz', 'B) nar ve çilek', 'C) erik ve elma', 'D) kiraz ve nar', 'E) elma ve kiraz'],
    cevap: 2, aciklama: 'Erik ve elma bu kümede yer alır. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2018043, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: 'f(f(x)) = f(x) + a eşitliğini sağlayan a değeri kaçtır?',
    secenekler: ['A) 7', 'B) 8', 'C) 9', 'D) 10', 'E) 11'],
    cevap: 0, aciklama: 'a = 7 olarak bulunur. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2018044, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Rakamlarından biri 5 olan, diğer iki rakamı aynı olan üç basamaklı sayıda yüzler ve birler yer değiştirince değer 198 azalıyor. Bu sayının alabileceği değerlerin toplamı kaçtır?',
    secenekler: ['A) 1080', 'B) 1130', 'C) 1206', 'D) 1308', 'E) 1405'],
    cevap: 3, aciklama: 'Toplam 1308\'dir. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2018045, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Rakamları farklı birer asal sayı olan ve 3\'e tam bölünebilen üç basamaklı sayının en büyük ile en küçük değeri arasındaki fark kaçtır?',
    secenekler: ['A) 426', 'B) 465', 'C) 496', 'D) 516', 'E) 555'],
    cevap: 3, aciklama: 'Fark 516\'dır. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2018046, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Erhan 4 periyotluk basketbol maçında her periyotta bir öncekinden fazla sayı attı, toplam 39 sayı attı. Son iki periyot toplamı ilk iki periyot toplamından 5 fazla. İlk ve son periyotta toplam kaç sayı atmıştır?',
    secenekler: ['A) 18', 'B) 19', 'C) 20', 'D) 21', 'E) 22'],
    cevap: 2, aciklama: 'İlk ve son periyotta toplam 20 sayı atmıştır. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2018047, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Ayşe dikdörtgen kartona, her iki yanda 16\'şar birim boşluk bırakarak kare kartonlar yapıştıracak. Yanyana iki karton arası 2 birim. Her iki yanda 1\'er birim bıraksaydı 5 karton daha yapıştıracaktı. Kare kartonun bir kenar uzunluğu kaç birimdir?',
    secenekler: ['A) 2', 'B) 2,5', 'C) 3', 'D) 3,5', 'E) 4'],
    cevap: 4, aciklama: 'Kenar uzunluğu 4 birimdir. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2018048, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Kitapçıda tüm kitaplar %20 kârla satılıyor. Eskisinin alış fiyatı yenisinin satış fiyatının yarısı. Eskisinden 3, yenisinden 5 tane satılarak toplam 68 TL kâr elde edildi. Eskisinin satış fiyatı kaç TL\'dir?',
    secenekler: ['A) 24', 'B) 27', 'C) 33', 'D) 36', 'E) 39'],
    cevap: 3, aciklama: 'Eskisinin satış fiyatı 36 TL\'dir. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2018049, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: '100 m kenarlı kare parkurda Aysun A köşesinden B\'ye koşuyor, Bahar B\'den A\'ya. Aysun B\'ye ilk ulaştığında Bahar 300 m koşuyor. Dördüncü karşılaştıklarında A\'ya uzaklıkları kaç metredir?',
    secenekler: ['A) 50', 'B) 75', 'C) 100', 'D) 125', 'E) 175'],
    cevap: 1, aciklama: 'A\'ya uzaklık 75 metredir. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2018050, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Oktay Pazartesi menekşe, Salı sardunya aldı. Menekşe 4 günde bir, sardunya 3 günde bir sulanıyor. Her ikisinin üçüncü defa aynı gün sulandığı gün hangisidir?',
    secenekler: ['A) Pazartesi', 'B) Salı', 'C) Çarşamba', 'D) Perşembe', 'E) Cuma'],
    cevap: 0, aciklama: 'Her ikisi de Pazartesi günü üçüncü kez birlikte sulanır. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2018051, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Tur firması Mehtap Hanım\'a Antalya ve İzmir\'den oteller önerdi. İzmir\'den 6 otel dolu olunca yerine Antalya\'dan 6 otel eklendi. Bu değişimle Antalya\'dan seçme olasılığı arttı. Başlangıçta önerilen toplam otel sayısı kaçtır?',
    secenekler: ['A) 24', 'B) 32', 'C) 36', 'D) 42', 'E) 48'],
    cevap: 1, aciklama: 'Toplam 32 otel önerilmiştir. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2018052, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Gül, karanfil ve papatya satan çiçekçide güllerin yarısı ve karanfillerin 1/5\'i satıldıktan sonra 81 çiçek kaldı. Başlangıçta toplam kaç çiçek vardı?',
    secenekler: ['A) 96', 'B) 102', 'C) 108', 'D) 120', 'E) 124'],
    cevap: 2, aciklama: 'Başlangıçta 108 çiçek vardı. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2018053, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Çiçekçi karanfillerin yarısını sattıktan sonra papatya alıyor ve güller ile papatyalar eşit oluyor. Son durumda 420 çiçek var. Sonradan alınan papatya sayısı kaçtır?',
    secenekler: ['A) 40', 'B) 45', 'C) 50', 'D) 55', 'E) 60'],
    cevap: 0, aciklama: 'Sonradan 40 papatya alınmıştır. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2018054, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Dairesel hücrelere 1\'den 6\'ya kadar rakamlar yerleştirilip kareler içine üç hücre toplamı yazılıyor. Verilen düzenekte x kaçtır?',
    secenekler: ['A) 1', 'B) 2', 'C) 3', 'D) 4', 'E) 6'],
    cevap: 3, aciklama: 'x = 4\'tür. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2018055, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Dairesel hücre düzeneğinde A\'nın alabileceği değerler toplamı kaçtır?',
    secenekler: ['A) 18', 'B) 20', 'C) 21', 'D) 23', 'E) 24'],
    cevap: 3, aciklama: 'Toplam 23\'tür. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2018056, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Dairesel hücre düzeneğinde belirtilen toplamı kaçtır?',
    secenekler: ['A) 6', 'B) 7', 'C) 9', 'D) 10', 'E) 12'],
    cevap: 0, aciklama: 'Toplam 6\'dır. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2018057, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Dört eşkenar üçgenden oluşan şekilde kenar uzunlukları ardışık tam sayılar. En küçüğün kenarı 1 birim. Boyalı bölgelerin çevreleri toplamı kaç birimdir?',
    secenekler: ['A) 18', 'B) 20', 'C) 22', 'D) 24', 'E) 26'],
    cevap: 3, aciklama: 'Boyalı bölgelerin çevreleri toplamı 24 birimdir. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2018058, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: 'ABCD karesinde E ve F kenarların orta noktaları. AF ve EC üzerinde kenarları olan boyalı kare şeklin alanının ABCD\'ye oranı kaçtır?',
    secenekler: ['A) 1/5', 'B) 1/4', 'C) 1/3', 'D) 2/5', 'E) 1/2'],
    cevap: 0, aciklama: 'Oran 1/5\'tir. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2018059, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: 'D noktası çember üzerinde ve AEB yayı BFC yayının 4 katı. x kaç derecedir?',
    secenekler: ['A) 15', 'B) 18', 'C) 20', 'D) 24', 'E) 30'],
    cevap: 1, aciklama: 'x = 18 derecedir. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2018060, yil: 2018, ders: 'Matematik', seviye: 'Lisans',
    soru: 'Koordinat düzleminde belirli bir noktada dik kesişen iki doğrudan birinin x eksenini kestiği nokta orijine diğerinkinin iki katı kadar uzak. Doğrular ve x ekseni arasında kalan sınırlı bölgenin alanı kaç birimkaredir?',
    secenekler: ['A) 2', 'B) 3', 'C) 4', 'D) 6', 'E) 8'],
    cevap: 1, aciklama: 'Alan 3 birimkaredir. Doğru cevap B şıkkıdır.',
  },

  // GENEL KÜLTÜR - TARİH (1-27)
  {
    id: 2018061, yil: 2018, ders: 'Tarih', seviye: 'Lisans',
    soru: 'İslamiyet öncesi Türk devletlerinin yönetim anlayışıyla ilgili olarak aşağıdakilerden hangisi söylenemez?',
    secenekler: ['A) Hükümdar olma hakkı hanedanın erkek üyelerine aittir.', 'B) Hükümdar olma yetkisinin tanrısal olduğu inancı vardır.', 'C) Ülke ikili teşkilatla yönetilmiştir.', 'D) Yönetimle ilgili kararlar kurultayda alınır.', 'E) Hanedanın hükümdar olacak üyesi önceden belirlenir.'],
    cevap: 4, aciklama: 'Hükümdar önceden belirlenmezdi; bu Türk yönetim anlayışıyla çelişir. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2018062, yil: 2018, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Selçukluların Türk-İslam mimarisine kazandırdığı yapı aşağıdakilerden hangisidir?',
    secenekler: ['A) Otağ', 'B) Ribat', 'C) Şadırvan', 'D) Cami', 'E) Kümbet'],
    cevap: 4, aciklama: 'Selçuklular kümbet mimarisini geliştirmiştir. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2018063, yil: 2018, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Türk-İslam devletlerinde gelirleri bilim, eğitim ve sağlık kurumlarının giderlerine ayrılan arazilere ne ad verilir?',
    secenekler: ['A) Has arazi', 'B) İkta arazi', 'C) Mülk arazi', 'D) Vakıf arazi', 'E) Mirî arazi'],
    cevap: 3, aciklama: 'Bu araziler "vakıf arazi" olarak adlandırılırdı. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2018064, yil: 2018, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Balkanlardaki halkın Osmanlı yönetimini kolayca benimsemesinin nedenlerinden biri olmayan seçenek hangisidir?',
    secenekler: ['A) Osmanlı vergi düzeninin esnekliği', 'B) Gayrimüslimlerin avarızdan muaf tutulması', 'C) Eski yöneticilerin sisteme dahil edilmesi', 'D) Yerleşik halkın adetlerine saygı gösterilmesi', 'E) İslamiyetin Hristiyanlara zimmi statüsü tanıması'],
    cevap: 1, aciklama: 'Gayrimüslimlerin avarızdan muaf tutulması doğrudan bir neden olarak gösterilemez. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2018065, yil: 2018, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Osmanlı\'da timar sisteminin uygulanmasının nedenlerinden biri olmayan seçenek hangisidir?',
    secenekler: ['A) Fetih hareketlerini hızlandırmak', 'B) Merkezi yönetimi güçlendirmek', 'C) Hassa ordusu oluşturmak', 'D) Ayni vergileri doğrudan tahsil etmek', 'E) Taşra yönetimini yapılandırmak'],
    cevap: 2, aciklama: 'Hassa ordusu oluşturmak timar sisteminin amacı değildi. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2018066, yil: 2018, ders: 'Tarih', seviye: 'Lisans',
    soru: 'XVI. yüzyıl sonlarında Celali isyanlarının da etkisiyle Osmanlı ekonomisinde yaşanan bozulmalarla ilgili olmayan seçenek hangisidir?',
    secenekler: ['A) Köylerin boşalması', 'B) Yüksek fiyat artışları', 'C) Akçenin değerinin düşmesi', 'D) Timarlıların sayısının artması', 'E) Ulufelilerin gerçek gelirinin azalması'],
    cevap: 3, aciklama: 'Timarlıların sayısı bu dönemde artmadı. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2018067, yil: 2018, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Osmanlı maliyesinde vergilerin şeri ve örfi olarak ayrılmasının nedenlerinden biri hangisidir?',
    secenekler: ['A) Vergi oranlarının bölgeden bölgeye değişmesi', 'B) Esnaf üretim alanlarının çeşitliliği', 'C) Hukuk sisteminde ikili yapının bulunması', 'D) Gayrimüslimlerin ispençe ödemesi', 'E) Vergi toplama biçiminin zamanla değişmesi'],
    cevap: 2, aciklama: 'Hukuk sistemindeki ikili yapı bu ayrımın temelini oluşturur. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2018068, yil: 2018, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Osmanlı\'da kûfi, nesih, sülüs ve ta\'lîk gibi çeşitleri bulunan Türk-İslam sanatı hangisidir?',
    secenekler: ['A) Hat', 'B) Ebru', 'C) Tezhip', 'D) Minyatür', 'E) Çini'],
    cevap: 0, aciklama: 'Bu sanat dalı "hat sanatı"dır. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2018069, yil: 2018, ders: 'Tarih', seviye: 'Lisans',
    soru: 'III. Selim Dönemi\'nde aşağıdaki alanların hangisinde ıslahat yapılmadığı söylenebilir?',
    secenekler: ['A) Ordu', 'B) Eğitim', 'C) Diplomasi', 'D) İdare', 'E) Din'],
    cevap: 4, aciklama: 'III. Selim Dönemi\'nde din alanında ıslahat yapılmamıştır. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2018070, yil: 2018, ders: 'Tarih', seviye: 'Lisans',
    soru: '1838 Baltalimanı Ticaret Antlaşması\'nın Osmanlı ekonomisi üzerindeki etkileriyle ilgili aşağıdakilerden hangisi söylenemez?',
    secenekler: ['A) Kapitülasyonların kapsamı genişlemiştir.', 'B) Osmanlı ülkesi açık pazar durumuna gelmiştir.', 'C) Yerli sanayi olumsuz etkilenmiştir.', 'D) Osmanlı ülkesinden ham madde çıkışı kolaylaşmıştır.', 'E) Tarımsal üretimde düşüş yaşanmıştır.'],
    cevap: 4, aciklama: 'Tarımsal üretimde doğrudan düşüş antlaşmanın etkisi olarak söylenemez. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2018071, yil: 2018, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Osmanlı modernleşme dönemindeki düşünce akımları ve temsilcileriyle ilgili yanlış eşleştirme hangisidir?',
    secenekler: ['A) Batıcılık - Sait Halim Paşa', 'B) Osmanlıcılık - Namık Kemal', 'C) Türkçülük - Ziya Gökalp', 'D) Batıcılık - Abdullah Cevdet', 'E) Türkçülük - Yusuf Akçura'],
    cevap: 0, aciklama: 'Sait Halim Paşa Batıcı değil İslamcı görüşteydi. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2018072, yil: 2018, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Kanunuesasi\'nin kabulüyle hangi gelişmeler yaşanmıştır?\nI. Parlamentolu sisteme geçilmesi\nII. Tebaanın tüm unsurlarının mecliste temsili\nIII. Padişahın yürütme yetkisinin sona ermesi',
    secenekler: ['A) Yalnız I', 'B) I ve II', 'C) I ve III', 'D) II ve III', 'E) I, II ve III'],
    cevap: 1, aciklama: 'I ve II gerçekleşmiştir; padişahın yetkisi devam etmiştir. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2018073, yil: 2018, ders: 'Tarih', seviye: 'Lisans',
    soru: '27 Mayıs 1915\'te çıkarılan Sevk ve İskân Kanunu\'yla ne amaçlanmıştır?',
    secenekler: ['A) Osmanlı ülkesinde güvenliğin sağlanması', 'B) Vilayet sınırlarının yeniden belirlenmesi', 'C) Aşiretler arasındaki anlaşmazlıkların giderilmesi', 'D) Orduya asker alımının düzenlenmesi', 'E) Doğal afetlere karşı tedbir alınması'],
    cevap: 0, aciklama: 'Güvenliği sağlamak temel amaç olarak gösterilmiştir. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2018074, yil: 2018, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Mustafa Kemal Paşa "Osmanlı Devleti bu mütarekeyle kendisini kayıtsız şartsız düşmanlara teslim etmeye razı olmuştu." ifadesini hangi antlaşma için kullanmıştır?',
    secenekler: ['A) Mudanya Anlaşması', 'B) Montrö Sözleşmesi', 'C) Mondros Anlaşması', 'D) Londra Ön Barışı', 'E) Selanik Anlaşması'],
    cevap: 2, aciklama: 'Bu ifade Mondros Anlaşması için kullanılmıştır. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2018075, yil: 2018, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Bir öğretmen Kuvayımilliye\'nin disiplin sorunlarını ve düzenli orduya geçiş zorunluluğunu anlatmaktadır. Hangi konuyu aktarmaktadır?',
    secenekler: ['A) Kuvayımilliyenin oluşturulma süreci', 'B) Heyet-i Temsiliyenin Ankara\'ya gelmesi', 'C) Mondros Anlaşması sonrası işgaller', 'D) Kongrelerin toplanması', 'E) Düzenli ordunun kurulmasının sebepleri'],
    cevap: 4, aciklama: 'Öğretmen düzenli ordunun neden kurulması gerektiğini anlatmaktadır. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2018076, yil: 2018, ders: 'Tarih', seviye: 'Lisans',
    soru: '1919\'da Türkiye\'ye gelen General Harbord hangi konuyu araştırmak üzere gönderilmiştir?',
    secenekler: ['A) Boğazlar sorunu', 'B) Yunan işgali', 'C) Manda konusu', 'D) Kapitülasyonlar', 'E) Musul petrolleri'],
    cevap: 2, aciklama: 'Harbord manda konusunu araştırmak üzere gönderilmiştir. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2018077, yil: 2018, ders: 'Tarih', seviye: 'Lisans',
    soru: 'İstiklal Mahkemeleri hakkındaki bilgilerden hangisine ulaşılamaz?',
    secenekler: ['A) TBMM\'nin yargı gücünü kullandığına', 'B) İsyanların bastırılmasında etkili olduğuna', 'C) Faaliyetlerinin Millî Mücadele Dönemi\'yle sınırlı kaldığına', 'D) Gerektiğinde kurularak yargılama yaptığına', 'E) Kararlarının kesin ve derhal uygulandığına'],
    cevap: 2, aciklama: 'İstiklal Mahkemeleri inkılap döneminde de faaliyet gösterdi; salt Millî Mücadele\'yle sınırlı değildi. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2018078, yil: 2018, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Mustafa Kemal Paşa\'nın "Rum Sındığı" olarak adlandırdığı savaş hangisidir?',
    secenekler: ['A) Birinci İnönü Muharebesi', 'B) İkinci İnönü Muharebesi', 'C) Kütahya-Eskişehir Muharebesi', 'D) Sakarya Meydan Muharebesi', 'E) Başkomutan Meydan Muharebesi'],
    cevap: 4, aciklama: '"Rum Sındığı" Başkomutan Meydan Muharebesi\'dir. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2018079, yil: 2018, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Lozan görüşmeleri sırasında muhalif ikinci grubun yoğun eleştirilerinin aşağıdakilerden hangisinin gerçekleşmesinde etkili olduğu söylenebilir?',
    secenekler: ['A) Takrir-i Sükûn Kanunu\'nun çıkarılması', 'B) Milletvekili seçimleri için karar alınması', 'C) Başkomutanlık yetkisinin uzatılması', 'D) Felah-ı Vatan Grubu\'nun kurulması', 'E) Hıyanet-i Vataniye Kanunu\'nun yürürlüğe girmesi'],
    cevap: 1, aciklama: 'Muhalefet baskısı sonucu milletvekili seçimleri kararı alındı. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2018080, yil: 2018, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Saltanat ve hilafetin kaldırılmasının ortak nedenlerinden biri hangisidir?',
    secenekler: ['A) Rejimin cumhuriyet olmasını sağlamak', 'B) TBMM\'yi egemenliği kullanan tek güç hâline getirmek', 'C) Dış müdahalelerin önüne geçmek', 'D) Meclisteki muhalif grubun gücünü kırmak', 'E) Lozan\'daki temsil kargaşasını önlemek'],
    cevap: 1, aciklama: 'Her ikisinin de ortak nedeni TBMM\'yi tek egemenlik kaynağı yapmaktır. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2018081, yil: 2018, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Aşağıdaki kurumlardan hangisi Atatürk Dönemi\'nde açılmıştır?',
    secenekler: ['A) Darülfünun', 'B) Mülkiye Mektebi', 'C) Türk Ocakları', 'D) Ankara Hukuk Mektebi', 'E) Sanayi-i Nefise Mektebi'],
    cevap: 3, aciklama: 'Ankara Hukuk Mektebi Atatürk Dönemi\'nde açılmıştır. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2018082, yil: 2018, ders: 'Tarih', seviye: 'Lisans',
    soru: '19 Nisan 1926 tarihli Kabotaj Kanunu\'yla ne düzenlenmiştir?',
    secenekler: ['A) Âşar vergisi', 'B) Toprak reformu', 'C) Millî bankacılık', 'D) Deniz ticareti', 'E) Planlı sanayi'],
    cevap: 3, aciklama: 'Kabotaj Kanunu deniz ticaretini düzenlemiştir. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2018083, yil: 2018, ders: 'Tarih', seviye: 'Lisans',
    soru: '1929 Dünya Ekonomik Krizi\'nin etkisiyle Türkiye\'de benimsenen otarşi eğiliminin yansıması olan Atatürk ilkesi hangisidir?',
    secenekler: ['A) Devletçilik', 'B) Laiklik', 'C) Cumhuriyetçilik', 'D) Milliyetçilik', 'E) Halkçılık'],
    cevap: 0, aciklama: 'Devletçilik ilkesi bu eğilimin yansımasıdır. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2018084, yil: 2018, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Atatürk Dönemi\'nde en uzun süre Dışişleri Bakanlığı yapan ve Hatay\'ın anavatana katılmasında katkısı olan devlet adamı kimdir?',
    secenekler: ['A) Tevfik Rüştü Aras', 'B) Yusuf Kemal Tengirşenk', 'C) Şükrü Kaya', 'D) Mahmut Esat Bozkurt', 'E) Ali Fethi Okyar'],
    cevap: 0, aciklama: 'Tevfik Rüştü Aras en uzun süre Dışişleri Bakanı olarak görev yaptı. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2018085, yil: 2018, ders: 'Tarih', seviye: 'Lisans',
    soru: 'Bir gazetede "Bulgaristan\'da toplanan Alman kuvvetlerinin Yunanistan\'a girdiği" haberi görülüyor. Bu haber hangi savaşa aittir?',
    secenekler: ['A) Birinci Balkan Savaşı', 'B) İkinci Balkan Savaşı', 'C) Trablusgarp Savaşı', 'D) Birinci Dünya Savaşı', 'E) İkinci Dünya Savaşı'],
    cevap: 4, aciklama: 'Almanya\'nın Yunanistan\'ı işgali İkinci Dünya Savaşı\'nda gerçekleşti. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2018086, yil: 2018, ders: 'Tarih', seviye: 'Lisans',
    soru: '27 Mayıs 1960 Askerî Darbesi sonrasında Demokrat Parti\'nin devamı niteliğinde kurulan ve Genel Başkanlığını Ragıp Gümüşpala\'nın üstlendiği parti hangisidir?',
    secenekler: ['A) Adalet Partisi', 'B) Hürriyet Partisi', 'C) Millet Partisi', 'D) Millî Kalkınma Partisi', 'E) Ahali Cumhuriyet Partisi'],
    cevap: 0, aciklama: 'Adalet Partisi Demokrat Parti\'nin devamı niteliğindeydi. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2018087, yil: 2018, ders: 'Tarih', seviye: 'Lisans',
    soru: 'SSCB sonrası Azerbaycan, Gürcistan ve Türkiye üzerinden oluşturulan enerji koridorunun taşıdığı amaçlar hangileridir?\nI. Rusya\'nın bölgedeki etkinliğini azaltmak\nII. Türkiye\'nin önemini artırmak\nIII. Bağımsız Devletler Topluluğunu güçlendirmek',
    secenekler: ['A) Yalnız I', 'B) I ve II', 'C) I ve III', 'D) II ve III', 'E) I, II ve III'],
    cevap: 1, aciklama: 'I ve II bu politikanın amaçları arasındadır. Doğru cevap B şıkkıdır.',
  },

  // COĞRAFYA (28-44)
  {
    id: 2018088, yil: 2018, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Türkiye\'deki bazı coğrafi olayların meydana geldiği jeolojik zamanlarla ilgili doğru eşleştirmeler hangileridir?\nI. Ege Denizi\'nin oluşması - İkinci Jeolojik Zaman\nII. Kuzey Anadolu ve Toros Dağlarının oluşması - Üçüncü Jeolojik Zaman\nIII. İstanbul Boğazı\'nın oluşması - Dördüncü Jeolojik Zaman',
    secenekler: ['A) Yalnız I', 'B) Yalnız II', 'C) Yalnız III', 'D) I ve II', 'E) II ve III'],
    cevap: 4, aciklama: 'II ve III doğru eşleştirmelerdir. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2018089, yil: 2018, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Aşağıdaki coğrafi koordinatlardan hangisi Türkiye sınırları içinde kalmaktadır?',
    secenekler: ['A) 28° Doğu 35° Kuzey', 'B) 40° Doğu 30° Kuzey', 'C) 38° Doğu 28° Kuzey', 'D) 36° Doğu 38° Kuzey', 'E) 26° Doğu 45° Kuzey'],
    cevap: 3, aciklama: '36° Doğu ve 38° Kuzey Türkiye sınırları içinde kalır. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2018090, yil: 2018, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Haritada gösterilen alanlardan hangisi masif arazilerin bulunduğu alanlardan biri değildir?',
    secenekler: ['A) I', 'B) II', 'C) III', 'D) IV', 'E) V'],
    cevap: 3, aciklama: 'IV numaralı alan masif arazi değildir. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2018091, yil: 2018, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Haritada gösterilen kıyı hatlarının hangisinde kıyı kumulları daha az görülmektedir?',
    secenekler: ['A) I', 'B) II', 'C) III', 'D) IV', 'E) V'],
    cevap: 2, aciklama: 'III numaralı kıyı hattında kumullar daha azdır. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2018092, yil: 2018, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Türkiye\'nin endemik bitki türleri bakımından zengin olmasında hangileri etkili olmuştur?\nI. Geçmiş küresel iklim değişimleri\nII. Kuzey Yarım Küre\'de yer alması\nIII. Yeryüzü şekilleri\nIV. Doğu boylamlarında yer alması',
    secenekler: ['A) I ve II', 'B) I ve III', 'C) II ve III', 'D) II ve IV', 'E) III ve IV'],
    cevap: 1, aciklama: 'I ve III endemik zenginlikte etkilidir. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2018093, yil: 2018, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Yaz mevsiminde Şanlıurfa\'nın Mersin\'e göre daha sıcak olmasında etkisi olmayan faktör hangisidir?',
    secenekler: ['A) Yükselti', 'B) Karasallık', 'C) Nem oranının düşük olması', 'D) Basra Alçak Basıncı', 'E) Güneyden esen rüzgârlar'],
    cevap: 0, aciklama: 'Her iki il benzer yükseltide olduğundan yükselti belirleyici değildir. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2018094, yil: 2018, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Anadolu\'nun iç kesimlerinden kaynağını alarak kuzey veya güneydeki dağları aşan akarsulardan biri değildir?',
    secenekler: ['A) Kızılırmak', 'B) Fırat Irmağı', 'C) Seyhan Nehri', 'D) Sakarya Irmağı', 'E) Dalaman Çayı'],
    cevap: 4, aciklama: 'Dalaman Çayı bu özelliği taşımaz. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2018095, yil: 2018, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Türkiye\'de 557 sayılı Nüfus Planlaması Kanunu\'yla bireylerin istedikleri sayıda çocuk sahibi olmaları görüşünün ağırlık kazandığı dönem hangisidir?',
    secenekler: ['A) 1923-1965 dönemi', 'B) 1965-1980 dönemi', 'C) 1980-2005 dönemi', 'D) 2005-2014 dönemi', 'E) 2014 sonrası'],
    cevap: 1, aciklama: '1965-1980 dönemi bu politika değişikliğinin yaşandığı dönemdir. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2018096, yil: 2018, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Türkiye\'de kırdan kente yapılan göçlerde doğrudan etkili olmayan faktör hangisidir?',
    secenekler: ['A) Ekonomik yetersizlikler', 'B) Kamulaştırma işlemleri', 'C) Doğal afetler', 'D) Sosyal yetersizlikler', 'E) Arazi toplulaştırması'],
    cevap: 4, aciklama: 'Arazi toplulaştırması göçü doğrudan tetiklemez. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2018097, yil: 2018, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Yazları sıcak geçen yörelerde sayfiye amaçlı yaylacılığın daha fazla olduğu alan hangisidir?',
    secenekler: ['A) Aydın Dağları', 'B) Orta Toroslar', 'C) Ilgaz Dağları', 'D) Güneydoğu Toroslar', 'E) Yıldız Dağları'],
    cevap: 1, aciklama: 'Orta Toroslar bu amaçlı yaylacılığın en fazla olduğu alandır. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2018098, yil: 2018, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'GAP kapsamındaki hidroelektrik santrallerden biri değildir?',
    secenekler: ['A) Atatürk', 'B) Ilısu', 'C) Deriner', 'D) Birecik', 'E) Karkamış'],
    cevap: 2, aciklama: 'Deriner Barajı GAP kapsamında değil Çoruh Nehri üzerindedir. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2018099, yil: 2018, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Türkiye\'de iklim ve bitki örtüsü çeşitliliği hangi ekonomik faaliyetin gelişimine daha fazla katkı sağlamıştır?',
    secenekler: ['A) Arıcılık', 'B) İpek böcekçiliği', 'C) Besi hayvancılığı', 'D) Kümes hayvancılığı', 'E) Balıkçılık'],
    cevap: 0, aciklama: 'Bitki çeşitliliği arıcılığın gelişimine en fazla katkı sağlar. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2018100, yil: 2018, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Aşağıdaki illerin hangisinde sanayi diğerlerine göre daha az gelişmiştir?',
    secenekler: ['A) İstanbul', 'B) İzmir', 'C) Bursa', 'D) Kocaeli', 'E) Samsun'],
    cevap: 4, aciklama: 'Samsun sanayisi diğer illerle kıyaslandığında daha az gelişmiştir. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2018101, yil: 2018, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Türkiye\'de bilinen toplam rezervi en az olan fosil enerji kaynağı hangisidir?',
    secenekler: ['A) Petrol', 'B) Doğal gaz', 'C) Asfaltit', 'D) Linyit', 'E) Taş kömürü'],
    cevap: 1, aciklama: 'Doğal gazın bilinen rezervi en azdır. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2018102, yil: 2018, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Zeytin tarımının son yıllarda gelişmesinin nedenlerinden biri değildir?',
    secenekler: ['A) Üretim alanlarının genişlemesi', 'B) Bahçe bakım koşullarının iyileşmesi', 'C) Ağaç sayısındaki artış', 'D) İç ve dış talepteki artış', 'E) Sulama olanaklarının gelişmesi'],
    cevap: 4, aciklama: 'Sulama zeytin tarımının gelişmesinin nedeni değildir; zeytin kurak koşullara dayanıklıdır. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2018103, yil: 2018, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Su ürünleri üretimi bakımından en önemli paya sahip göl hangisidir?',
    secenekler: ['A) Van', 'B) Çıldır', 'C) Eğirdir', 'D) Abant', 'E) Sapanca'],
    cevap: 2, aciklama: 'Eğirdir Gölü su ürünleri bakımından en önemli paydır. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2018104, yil: 2018, ders: 'Coğrafya', seviye: 'Lisans',
    soru: 'Türkiye\'nin ilk millî parkı olan, geçmişte geniş ormanlarla kaplı Anadolu\'yu belgeleyen ve karaçam, ardıç ve meşeden oluşan millî park hangisidir?',
    secenekler: ['A) Yozgat Çamlığı Millî Parkı', 'B) Soğuksu Millî Parkı', 'C) Ilgaz Dağı Millî Parkı', 'D) Boğazköy-Alacahöyük Millî Parkı', 'E) Küre Dağları Millî Parkı'],
    cevap: 0, aciklama: 'Yozgat Çamlığı Türkiye\'nin ilk millî parkıdır. Doğru cevap A şıkkıdır.',
  },

  // VATANDAŞLIK (45-54)
  {
    id: 2018105, yil: 2018, ders: 'Vatandaşlık', seviye: 'Lisans',
    soru: 'Yeryüzü şekilleri ve yükselti özellikleri dikkate alındığında kara yolu ve demir yolu maliyetlerinin daha fazla olması beklenen doğrultular hangileridir?',
    secenekler: ['A) I ve II', 'B) I ve V', 'C) II ve III', 'D) III ve IV', 'E) IV ve V'],
    cevap: 3, aciklama: 'III ve IV doğrultularında ulaşım maliyeti daha yüksektir. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2018106, yil: 2018, ders: 'Vatandaşlık', seviye: 'Lisans',
    soru: '1982 Anayasası\'na göre bakanlar hakkında görevle ilgili suç iddiasıyla Yüce Divana sevk kararı alma yetkisi kime aittir?',
    secenekler: ['A) Cumhurbaşkanı', 'B) TBMM', 'C) Anayasa Mahkemesi', 'D) Yargıtay Cumhuriyet Başsavcılığı', 'E) Yargıtay Ceza Genel Kurulu'],
    cevap: 1, aciklama: 'Bu yetki TBMM\'ye aittir. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2018107, yil: 2018, ders: 'Vatandaşlık', seviye: 'Lisans',
    soru: '1982 Anayasası\'na göre Millî Güvenlik Kurulunun gündemini kim düzenler?',
    secenekler: ['A) İçişleri bakanı', 'B) Genelkurmay başkanı', 'C) Millî savunma bakanı', 'D) Cumhurbaşkanı', 'E) MGK Genel Sekreterliği'],
    cevap: 3, aciklama: 'Gündem Cumhurbaşkanı tarafından düzenlenir. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2018108, yil: 2018, ders: 'Vatandaşlık', seviye: 'Lisans',
    soru: '1982 Anayasası\'nda koruma altına alınan inkılap kanunlarından biri değildir?',
    secenekler: ['A) Tevhidi Tedrisat Kanunu', 'B) Tekke ve Zaviyelerin Kapatılmasına Dair Kanun', 'C) Türk Harflerinin Kabulü Hakkında Kanun', 'D) Şapka İktisası Hakkında Kanun', 'E) Yıpranan Tarihî Varlıkların Yenilenmesi Hakkında Kanun'],
    cevap: 4, aciklama: 'E şıkkındaki kanun inkılap kanunu değildir. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2018109, yil: 2018, ders: 'Vatandaşlık', seviye: 'Lisans',
    soru: 'Memurların amirlerin emirlerini yerine getirme zorunluluğunun istisnası 1982 Anayasası\'nda hangi madde başlığı altında düzenlenmiştir?',
    secenekler: ['A) Merkezî idare', 'B) Kanunsuz emir', 'C) İdarenin bütünlüğü ve kamu tüzel kişiliği', 'D) Suç ve cezalara ilişkin esaslar', 'E) Yargı yolu'],
    cevap: 1, aciklama: '"Kanunsuz emir" başlığı altında düzenlenmiştir. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2018110, yil: 2018, ders: 'Vatandaşlık', seviye: 'Lisans',
    soru: '5393 sayılı Belediye Kanunu\'na göre aşağıdaki ifadelerden hangileri doğrudur?\nI. İlçe merkezlerinde belediye kurulması zorunludur.\nII. Köylerde belediye kurulması zorunludur.\nIII. Nüfusu 5.000 ve üzerinde olan yerleşim birimlerinde belediye kurulabilir.',
    secenekler: ['A) Yalnız I', 'B) I ve II', 'C) I ve III', 'D) II ve III', 'E) I, II ve III'],
    cevap: 2, aciklama: 'I ve III doğrudur. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2018111, yil: 2018, ders: 'Vatandaşlık', seviye: 'Lisans',
    soru: '1982 Anayasası\'na göre kamu idarelerinin bütün gelir, gider ve mallarını TBMM adına denetleme görevi kime aittir?',
    secenekler: ['A) Devlet Denetleme Kurulu', 'B) Anayasa Mahkemesi', 'C) İçişleri Bakanlığı', 'D) Sayıştay', 'E) Danıştay'],
    cevap: 3, aciklama: 'Bu görev Sayıştay\'a aittir. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2018112, yil: 2018, ders: 'Vatandaşlık', seviye: 'Lisans',
    soru: 'Ergin olma, 4721 sayılı Türk Medeni Kanunu\'nda kural olarak aşağıdakilerden hangisiyle ilişkilendirilmiştir?',
    secenekler: ['A) Belli bir yaşı doldurma', 'B) Ayırt etme gücüne sahip olma', 'C) Kısıtlı olmama', 'D) Hak ehliyetine sahip olma', 'E) Sağ olarak tamamıyla doğma'],
    cevap: 0, aciklama: 'Ergin olma kural olarak belli bir yaşı (18) doldurmayla ilişkilendirilmiştir. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2018113, yil: 2018, ders: 'Vatandaşlık', seviye: 'Lisans',
    soru: 'Türkiye\'de Cumhuriyet\'in ilanından sonra kaç farklı anayasa yürürlüğe girmiştir?',
    secenekler: ['A) 1', 'B) 2', 'C) 3', 'D) 4', 'E) 5'],
    cevap: 2, aciklama: '1924, 1961 ve 1982 olmak üzere 3 anayasa yürürlüğe girmiştir. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2018114, yil: 2018, ders: 'Vatandaşlık', seviye: 'Lisans',
    soru: '"Durumun gereklerine göre kendisinden beklenen özeni göstermesine rağmen bir hakkın kazanılmasına ilişkin engelin farkında olmaması" hangi kavramla açıklanmaktadır?',
    secenekler: ['A) Fiil ehliyeti', 'B) Hakkın kötüye kullanılması', 'C) Kanuna karşı hile', 'D) Muvazaa', 'E) İyi niyet'],
    cevap: 4, aciklama: 'Bu tanım "iyi niyet" kavramına aittir. Doğru cevap E şıkkıdır.',
  },

  // GÜNCEL BİLGİLER (55-60)
  {
    id: 2018115, yil: 2018, ders: 'Güncel Bilgiler', seviye: 'Lisans',
    soru: 'Mehmet Akif Ersoy\'un İstiklal Marşı\'nı yazmış olduğu Ankara\'daki tarihî mekân hangisidir?',
    secenekler: ['A) Zağfiran Han', 'B) Tâceddin Dergâhı', 'C) İbadullah Camii', 'D) Hacı Bayram Veli Türbesi', 'E) Ahi Şerafettin Türbesi'],
    cevap: 1, aciklama: 'Mehmet Akif İstiklal Marşı\'nı Tâceddin Dergâhı\'nda yazmıştır. Doğru cevap B şıkkıdır.',
  },
  {
    id: 2018116, yil: 2018, ders: 'Güncel Bilgiler', seviye: 'Lisans',
    soru: '"Olmak ya da olmamak, işte bütün mesele bu." sözüyle bilinen ve Hamlet\'i yazan İngiliz edebiyatçı kimdir?',
    secenekler: ['A) George Eliot', 'B) Thomas More', 'C) William Shakespeare', 'D) Charles Dickens', 'E) Daniel Defoe'],
    cevap: 2, aciklama: 'Bu sözün ve Hamlet\'in yazarı William Shakespeare\'dir. Doğru cevap C şıkkıdır.',
  },
  {
    id: 2018117, yil: 2018, ders: 'Güncel Bilgiler', seviye: 'Lisans',
    soru: 'Anadolu\'da her yıl mayıs ayında kutlanan ve UNESCO tarafından 2017\'de İnsanlığın Somut Olmayan Kültürel Mirasları Listesi\'ne kaydedilen bahar kutlaması hangisidir?',
    secenekler: ['A) Saya Bayramı', 'B) Etik Günü', 'C) Aşure Günü', 'D) Hıdırellez', 'E) Nevruz'],
    cevap: 3, aciklama: 'Hıdırellez bu listeye kaydedilmiştir. Doğru cevap D şıkkıdır.',
  },
  {
    id: 2018118, yil: 2018, ders: 'Güncel Bilgiler', seviye: 'Lisans',
    soru: 'Türk Dili Konuşan Ülkeler İşbirliği Konseyinin kurucu üyelerinden biri değildir?',
    secenekler: ['A) Kazakistan', 'B) Azerbaycan', 'C) Türkiye', 'D) Kırgızistan', 'E) Özbekistan'],
    cevap: 4, aciklama: 'Özbekistan kurucu üye değildir. Doğru cevap E şıkkıdır.',
  },
  {
    id: 2018119, yil: 2018, ders: 'Güncel Bilgiler', seviye: 'Lisans',
    soru: '1998\'de Atatürk Barış Ödülü\'ne layık görülen ve özellikle Orta Doğu tarihi üzerine çalışmalarıyla tanınan, 2018\'de hayatını kaybeden ünlü tarihçi kimdir?',
    secenekler: ['A) Bernard Lewis', 'B) Arnold Joseph Toynbee', 'C) Eric Hobsbawm', 'D) Fernard Braudel', 'E) Stanford Shaw'],
    cevap: 0, aciklama: 'Bernard Lewis 2018\'de hayatını kaybetmiştir. Doğru cevap A şıkkıdır.',
  },
  {
    id: 2018120, yil: 2018, ders: 'Güncel Bilgiler', seviye: 'Lisans',
    soru: '2018\'nin Şubat ayından itibaren e-Devlet Kapısı üzerinden sunulmaya başlanan ve yoğun ilgi gören hizmet hangisidir?',
    secenekler: ['A) Adres değişikliği bildirimi', 'B) Alt-üst soy bilgisi sorgulama', 'C) Geçici kimlik belgesi sorgulama', 'D) Nüfus kayıt örneği belgesi sorgulama', 'E) Yerleşim yeri belgesi sorgulama'],
    cevap: 1, aciklama: 'Alt-üst soy bilgisi sorgulama hizmeti bu dönemde başlatılmıştır. Doğru cevap B şıkkıdır.',
  },
];